### ISSUE TITLE
Any recommendation about migrating old sdk.Patch function

### ISSUE THREAD

**Issue by patrickshan** [operator-framework/operator-sdk#1077]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

best practices

## Question

**What did you do?**
Try to migrate operator-sdk from old v0.0.7 to v0.4.0

**What did you expect to see?**
old sdk actions are supported inside the new controller runtime client

**What did you see instead? Under which circumstances?**
The old sdk package supports [Patch action](https://github.com/operator-framework/operator-sdk/blob/v0.0.7/pkg/sdk/action.go#L67) but the new controller runtime client doesn't

**Environment**
* operator-sdk version: v0.0.7 / v0.4.0

* Kubernetes version information: v1.12.3

**Additional context**

Any recommendation for migrating the old sdk Patch action using new controller runtime client ?

**Comment by LiliC** [comment]
@patrickshan There is the `Update` action in the client.

**Comment by patrickshan** [comment]
Thanks @LiliC . I could use the `Update` function but was wondering if there is any recommended way to convert the old `Patch` since the old library has both `Patch` and `Update`.

**Comment by hasbro17** [comment]
@patrickshan I don't think the controller-runtime client will be looking to support Patch anytime soon (if ever) since it deviates from the goal of providing a clear API and not redoing client-go.
Upstream discussion:
https://github.com/kubernetes-sigs/controller-runtime/pull/95
https://github.com/kubernetes-sigs/controller-runtime/pull/235

You can get around by constructing the REST client for a particular type by using the upstream [RESTClientForGVK()](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/apiutil/apimachinery.go#L67) util for this. Although it's a little painful to use.
There's some work planned upstream to just expose the raw REST client for a type #299 

But for now since `Patch()` is just an optimization you should be able to replace it with a `Get()` followed by an `Update()`. Or just create the raw rest client to use the [Patch()](https://github.com/kubernetes-sigs/controller-runtime/blob/master/vendor/k8s.io/client-go/rest/client.go#L48) function directly.

**Comment by patrickshan** [comment]
Thanks @hasbro17 . I think I might just use the Get & Update to replace it.

**Comment by calind** [comment]
@patrickshan check `controllerutil.CreateOrUpdate` (https://godoc.org/sigs.k8s.io/controller-runtime/pkg/controller/controllerutil#CreateOrUpdate).

Also note that in 0.2.0 it will change a little bit: kubernetes-sigs/controller-runtime#319

**Comment by awprice** [comment]
You definitely need patch when updating objects that could be modified by something else, e.g. nodes and pods. A pod or node could be modified by the controller-manager (or something else) in between the Get and Update calls.

When using Get + Update to modify a field on a node, I've often had the API server reject the update request with: `Operation cannot be fulfilled on nodes \"ip-10-149-72-69.us-west-2.compute.internal\": the object has been modified; please apply your changes to the latest version and try again`

For anyone else that has found this issue, the following can be done to get a client-go Kubernetes client that will allow you to do patch calls:

```go
rawClient := kubernetes.NewForConfigOrDie(mgr.GetConfig())
```
