### ISSUE TITLE
Watch Secondary Resource 

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#1087]
## Type of question

How to implement a specific feature

## Question

Is there a way to get implement a secondary "watched" resource for a resource that was not created as part of the operator SDK.

**What did you do?**
I create new custom resource configsync ,the aim of this resource  is to mount config map to existing deployment.
The name of the configmap and deployment are defined as part of the  configsync resource

each time i am creating/updating/deletion the resource configsync the reconcile method is triggered

I would like to trigger reconcile method each time a config map even its not created as part of the operator lifecycle running.

i did the following code changes: 

`

      func add(mgr manager.Manager, r reconcile.Reconciler) error {
	...

	// primary watch
	err = c.Watch(&source.Kind{Type: &appv1beta1.ConfigSync{}},
		&handler.EnqueueRequestForObject{})
	if err != nil {
		return err
	}

	// secondary watch
	err = c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestForOwner{
		IsController: true,
		OwnerType:    &appv1beta1.ConfigSync{},
	})`

`

    func (r *ReconcileConfigBinding) Reconcile(request reconcile.Request) (reconcile.Result, error)

    //as part of the Reconcile logic find the configmap and update the reference of the configSync

    foundConfigMap := &corev1.ConfigMap{}

    err := client.Get(context.TODO(), types.NamespacedName{Name: instance.Spec.ConfigMapRef, 

     Namespace: instance.Namespace}, foundConfigMap)
     if err != nil {
		return reconcile.Result{}, err
      } else {
       controllerutil.  SetControllerReference(instance, foundConfigMap, scheme)
       }`

**What did you expect to see?**
each time config map is changed the Reconcile method will be called with the corresponding request of type configSync 

**What did you see instead? Under which circumstances?**
configmap is changed and  Reconcile is not called

**Environment**
* operator-sdk version:
latest
operator-sdk version v0.4.0

  insert release or Git SHA here

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by hasbro17** [comment]
@petro404 The [EnqueueRequestForOwner](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/handler#EnqueueRequestForOwner) event handler is used for mapping request for the owner of an object.
In your case the ConfigMap objects are not owned by your ConfigSync CR so it can't trigger the reconcile for the owner.

For objects that aren't directly owned by by your ConfigSync CR but are related to it you would use the [EnqueueRequestsFromMapFunc](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/handler#EnqueueRequestsFromMapFunc) handler. This let's you map a watch event(Create,Update,Delete) for a related resource(Configmap) to a reconcile request for your primary resource(ConfigSync).

We don't have docs on how to use that eventhandler yet #1028 but you can probably get the idea from the godoc example. If not I can give an example of how to use it. 

```Go
// secondary watch
err = c.Watch(&source.Kind{Type: &corev1.ConfigMap{}}, &handler.EnqueueRequestsFromMapFunc{
	ToRequests: handler.ToRequestsFunc(func(configMapObject handler.MapObject) []reconcile.Request {
		// TODO: Get related ConfigSync CR for configMapObject
		return []reconcile.Request{
			{NamespacedName: types.NamespacedName{
			Name:      // Name of related ConfigSync,
			Namespace: // Name of related ConfigSync,
			}}
		}
	}
})

```

The issue now is how do you figure out which ConfigMap object is related to which ConfigSync object? ConfigSync has the name of the ConfigMap and Deployment but can you go the other way around. This depends on your application logic.

And it could be targeted by multiple ConfigSync CRs, which is why you can return a map of requests that can fan out to multiple CRs.

**Comment by petro404** [comment]
Thanks a lot it worked for me

**Comment by hasbro17** [comment]
@petro404 Sounds good. I'll close the issue then.
