### ISSUE TITLE
Create/Update/Delete behavior consistency

### ISSUE THREAD

**Issue by matihost** [operator-framework/operator-sdk#1090]
Currently there is a little inconsistency in create/update/delete feedback:
* kubectl create/app  for CR  and handling is asynchronous - CR created/configured/unchanged - returns immediately and role/playbook is run asynchrously, and CR status needs to be checked for the result
* kubectl delete for CR hangs until playbook/role finishes successfuly (if play/role fails, it hangs forever)

Please make the behavior consistent for all CUD operations.

Please consider adding the following configurable options:
* allow to block kubectl create/app until the underlying play finishes successfully
* allow to fail kubectl create/app when underlying play finishes with error
* allow to make delete/finalizer logic asynchronous (CR deleted returns immediately while play/role is run asynchronously)

**Comment by shawn-hurley** [comment]
Hi @matihost 

Kubectl is behaving correctly. The deletion is not actually "hanging." You can exit the command, and the deletion still happened. You can make sure of this by checking the `metadata. DeletionTimestamp` field. 

Basically what is happening is that kubectl is waiting for the resource to be garbage collected. Because of the finalizer, you're correct that the resource will never be cleaned up due to the controller failing. This is the correct behavior; a user will need to clear the finalizer if they think it is acceptable that the resource is cleaned up. The reason for this is that the controller does not know if everything was cleaned up correctly and we need to make sure that is true before the finalizer is removed. 

Please note that kubernetes is an eventually consistent system, this means that when you create a resource, the resource is created. If for some reason we are unable to complete the actions in the cluster the correct behavior is to alert the user via the status of the resource.  There is the ability to add a Webhook for a CRD that will check if the fields are valid and can reject creation/updates. 

Lastly, changing kubectl behavior is out of the scope of this project. How this interacts with kubernetes resources is a standard thing. I am going to close this issue, and if you believe that the kubectl behavior for interacting with resources should be updated, please open a bug here: 
https://github.com/kubernetes/kubectl

**Comment by matihost** [comment]
Good explanation! Thank You!
