### ISSUE TITLE
CR reconciliation upon operator pod restart should honor reconcile period option as well

### ISSUE THREAD

**Issue by matihost** [operator-framework/operator-sdk#1127]
The Reconcile Period option  (aka https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/advanced_options.md#watches-file-options )is not taken into account when operator pod restarts. When operator pod is restarted - reconciliation is run.

Please add a  configuration option that reconciliation will not be run upon operator pod restart - unless last reconciliation happen before configure reconcile period.

**Comment by joelanford** [comment]
@matihost The state about reconciliation periods and timing is all internal to the operator process, so when the pod restarts, it has no way of knowing when the last reconciliation happened in the previous pod process.

The reason that a reconciliation happens when the operator starts is that changes may have been made to the CR while the operator was not running, so it is important for them to be reconciled as quickly as possible.

What are you trying to accomplish by tracking the reconcile period across restarts? Since operator pod restarts should be fairly infrequent, this shouldn't happen often. Do you have a use case that is sensitive to the timing between reconciliations?

**Comment by matihost** [comment]
> so when the pod restarts, it has no way of knowing when the last reconciliation happened in the previous pod process.

Technically it can - just look at status section of the CR - it is the only way to figure out whether CR is in consistent state.

It is only a problem when when the reconcile period and the operator logic is taking a lot of time - and the reconciliation period is intentionally set to big value (1h or so)

For  example if there are 100 CR each of them take a minute or more to process - so restart may lead a long "warning up" period.

Is it possible to configure ansible-runner parallelism so that many CR will be checked simultaneously?

However based on https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/information-flow-ansible-operator.md  it is WAD.

W/o it the whole cache cannot be filled – and that is critical for operator to not overload etcd with queries afterwards.

**Comment by shawn-hurley** [comment]
@matihost Does this mean that we can close this issue?
