### ISSUE TITLE
Create command "version" to match style of other k8s binaries

### ISSUE THREAD

**Issue by cwilkers** [operator-framework/operator-sdk#1165]
## Feature Request

While creating a [bug report issue](https://github.com/operator-framework/operator-sdk/issues/1164) I tried to run the `operator-sdk version` command to find it does not exist as a command, but a flag `--version`

```10:06 $ operator-sdk version
Error: unknown command "version" for "operator-sdk"
Run 'operator-sdk --help' for usage.
10:06 $ operator-sdk --version
operator-sdk version v0.5.0+git
```
I would like to see `version` added as a command rather than as a flag to match the look and feel of other Kubernetes ecosystem CLIs like `kubectl`, etc.

**Comment by hasbro17** [comment]
That's a good idea. 
I think it should be easy enough to change this by [adding a new cobra command](https://github.com/spf13/cobra#create-additional-commands) for `version` to the SDK binary instead of using the [--version](https://github.com/operator-framework/operator-sdk/blob/master/commands/operator-sdk/cmd/root.go#L27) flag.

Feel free to pick this up if you have time.

**Comment by Avni-Sharma** [comment]
Hi, Can I work on this?
