### ISSUE TITLE
"generate openapi" fails with no explanation "exit status 1"

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#1181]
## Bug Report

**What did you do?**
```
$ operator-sdk generate openapi
```

**What did you expect to see?**
The generated openapi documentation for my operator

**What did you see instead? Under which circumstances?**
```
$ operator-sdk generate openapi
INFO[0001] Running OpenAPI code-generation for Custom Resource group versions: [io:[v1alpha1], jaegertracing:[v1], ] 
Error: failed to perform openapi code-generation: exit status 1
Usage:
  operator-sdk generate openapi [flags]

Flags:
      --header-file string   Path to file containing headers for generated files.
  -h, --help                 help for openapi
```

**Environment**
* operator-sdk version: 0.5.0
* Kubernetes version information: v1.13.3
* Are you writing your operator in ~ansible~, ~helm~, or *go*?

**Additional context**
This can be reproduced with the current master from the Jaeger Operator: https://github.com/jaegertracing/jaeger-operator/commit/8d5f92c8d1392a459ce1ac84b8e6f04f3ad4d601

**Comment by hasbro17** [comment]
@jpkrohling You can get a more verbose output by setting the `GOFLAGS="-v"` env for the command.

```console
$ GOFLAGS="-v" operator-sdk generate openapi
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [io:[v1alpha1], jaegertracing:[v1], ]
2019/03/08 15:16:17 Code for OpenAPI definitions generated
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,FreeForm,json
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerAgentSpec,JaegerCommonSpec
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerAllInOneSpec,JaegerCommonSpec
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerCollectorSpec,JaegerCommonSpec
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerIngesterSpec,JaegerCommonSpec
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerIngressSpec,JaegerCommonSpec
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerQuerySpec,JaegerCommonSpec
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerSpec,JaegerCommonSpec
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerStorageSpec,SparkDependencies
API rule violation: names_match,github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1,JaegerStorageSpec,Rollover
2019/03/08 15:16:18 OpenAPI code generation error: Failed executing generator: some packages had errors:
API rule violations exist
Error: failed to perform openapi code-generation: failed to exec []string{"/Users/haseeb/work/go-space/src/github.com/jaegertracing/jaeger-operator/build/_output/bin/openapi-gen", "--input-dirs", "github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1", "--output-package", "github.com/jaegertracing/jaeger-operator/pkg/apis/jaegertracing/v1", "--output-file-base", "zz_generated.openapi", "--go-header-file", "build/_output/bin/114195333"}: exit status 1
```

Your current problem seems to be a violation of the [name_match rule](https://github.com/kubernetes/kube-openapi/blob/master/pkg/generators/rules/names_match.go#L54-L76).
kube-openapi name validation rules expect the field name in Go code and field name in json to be exactly same with (Go code requires CamelCase, json requires camelCase).

I'm not sure if it's feasible for you to change the json tags for those fields since that'll probably be a breaking change in your API at this point.
I'll have to dig around more in kube-openapi but I think there's a way to make exceptions.

@estroz Side note but I think we can probably make the output for `generate openapi` always be verbose in case there's a failure by simply using [cmd.CombinedOutput](https://golang.org/pkg/os/exec/#Cmd.CombinedOutput) to check the error and print stdout/stderr.
Having that as the default instead of passing `GOFLAGS="-v"` will probably be a better user experience.

**Comment by jpkrohling** [comment]
Thanks, I got it working based on your insights.
