### ISSUE TITLE
Watch Readiness/Liveness on Secondary Resource

### ISSUE THREAD

**Issue by marcomancuso** [operator-framework/operator-sdk#1197]
## Type of question

how to implement a specific feature

## Question

Is it possible to trigger the reconcile function on change of ready/not ready of a pod?
Do I need a specific watcher?
How would I catch this event inside the Reconcile?

**Environment**
* operator-sdk version: v0.5.0+git

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: any

**Comment by hasbro17** [comment]
@marcomancuso When you watch a resource in your controller the reconcile loop will get triggered for any kind of update for an instance of that resource type.

If you're watching pods as your primary resource with `handler.EnqueueRequestForObject` such that your reconciler receives the keys for Pod objects then you can simply observe the ContainerStatus field of the Pod object in your reconcile loop and act/ignore accordingly.

If Pods are being watched as a secondary resource with `handler.EnqueueRequestForOwner` then you can use [predicate based filtering](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/event-filtering.md) to compare the difference between the old and new pod object to decide which pod update events will trigger the reconcile function for your CR. 
So in your case you could filter out all update events where the Pod object's ContainerStatus field is unchanged, so that only pod update events with status changes will trigger the reconcile loop.

However this will ignore all other updates besides the container status change so you need to be sure that's what you want.

I can go into more details on an example if that's your use case.

**Comment by LiliC** [comment]
Closing as the question was answered. If you @marcomancuso need more information, feel free to reopen this issue or open a new one.
