### ISSUE TITLE
Ansible Operator Playbook is running twice

### ISSUE THREAD

**Issue by gbaufake** [operator-framework/operator-sdk#1201]
## Bug Report

**What did you do?**
- Created an ansible operator (https://github.com/kiali/kiali-test-mesh/pull/41) and ran it on openshift

**What did you expect to see?**
- CR playbook should only run one time (lo
[kiali-test-mesh-operator-8ddfc8fc5-pljpj-kiali-test-mesh-operator.log](https://github.com/operator-framework/operator-sdk/files/2958830/kiali-test-mesh-operator-8ddfc8fc5-pljpj-kiali-test-mesh-operator.log)

**What did you see instead? Under which circumstances?**
- My playbook was running twice

**Environment**
* operator-sdk version: 0.4.0

  Insert operator-sdk release or Git SHA here. If you have paste the Gopkg.lock operator-sdk information here. 

* Kubernetes version information: 1.12.4

  Insert output of `kubectl version` here

* Kubernetes cluster kind: openshift

* Are you writing your operator in ansible, helm, or go?
ansible

**Comment by gbaufake** [comment]
I moved to 0.5.0 and I still see this issue

**Comment by gbaufake** [comment]
cc @shawn-hurley

**Comment by shawn-hurley** [comment]
This is the expected behavior of an operator. Your reconcile loop should be idempotent and can be run more than once. There is no way to guarantee that your playbook will only be run one time. What is most likely happening is that somehow your CR is being changed and causing a reconcile. There is no expectation that your operator will only run one time because there is no way to enforce this in every situation. 

If you believe that it is causing a second reconciliation when it does not make sense (nothing changed in the CR and such) then can you update the name of the bug and re-open. I don't want to give an appearance that only running one time is a supported feature.

**Comment by gbaufake** [comment]
@shawn-hurley 
In my case, my playbooks are idempotent so is not a problem running twice.
I just want to understand what causes this behavior since there no modification of CR

**Comment by shawn-hurley** [comment]
There could be many reasons:
1. The operator pod restarts will trigger a reconcile.
2. Reconcile period (requeue after) could be set which cause this
3. I wonder if the spec is changed due to the operator code. We had some code that should be removed in 0.6.0 which might have caused this if the initial CR didn't have a spec. 
4. Something in the cluster could trigger this by changing a label or annotation of the CR.


After looking at your code, I bet it is 3. I think you might be right that in a sense this was a bug and the second reconciliation was triggered when it should not have been. But I think I fixed it in this pr: https://github.com/operator-framework/operator-sdk/pull/1192

specifically this line: https://github.com/operator-framework/operator-sdk/pull/1192/files#diff-9649888b3df1961dad649345545de4c0L112

WDYT does that makes sense to you?

**Comment by gbaufake** [comment]
Ok.
It does make sense.
Was your code incorporated on 0.6.0 release?

I can try and let you know if there any difference.

**Comment by shawn-hurley** [comment]
It should be if you use the 0.6.0 base image that should work thanks for testing!
