### ISSUE TITLE
Why declare and initialize ignored variable like Reconciler?

### ISSUE THREAD

**Issue by saamalik** [operator-framework/operator-sdk#1219]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
Yes, I think so

## Question

Hey guys - just a silly question, but I was wondering why both kubebuilder and operator-sdk generate this empty, ignored variable:

```
var _ reconcile.Reconciler = &ReconcileMemcached{}
```

It's seen in the `memcached_controller.go` but I believe I've seen it a few other places. I've commented out that line and everything still continues to work. Just curious why it's added?

Thanks!

**Environment**
* operator-sdk version: v0.6.0+git

**Comment by shawn-hurley** [comment]
This is so that the compiler can check that the `ReconcileMemcached` type still conforms to the `reconcile.Reconciler` interface. If you remove the ` Reconcile` function you can see that the compiler says that the `ReconcileMemcached` does not conform to the reconcile.Reconciler.

Going to close, and we can continue the discussion on this PR if you have more questions, or you can re-open if you think there is a bug.

**Comment by saamalik** [comment]
Ok thanks, @shawn-hurley. In this specific `Reconciler` case, the compiler also has another place to verify, e.g:

```
// newReconciler returns a new reconcile.Reconciler
func newReconciler(mgr manager.Manager) reconcile.Reconciler {
	return &ReconcileMemcached{client: mgr.GetClient(), scheme: mgr.GetScheme()}
}
```

but I guess the black hole trick is useful in other areas. Thanks!
