### ISSUE TITLE
Helm v3 support

### ISSUE THREAD

**Issue by vchande** [operator-framework/operator-sdk#1255]
I am very curious about what is the plan for helm-operator support with helm v3 coming out.
Are there any plans or active discussions about this?

Before I choose to adapt to operator SDK with helm operator I would like to understand what is the support for helm v3. this can help me in designing an operator for me

**Comment by LiliC** [comment]
@vchande 
You mention:
> helm v3 coming out soon.

I am curious when Helm 3 release is scheduled to happen? I have been hearing a lot about it, but never an actual release date for it. Do you know more about an actual release date? End of last year they still said it's in early development stages.

cc @joelanford

**Comment by vchande** [comment]
@LiliC I am following the listing messages. it's not that soon but I am looking at what are the plans from operator SDK about adapt to the changes. No plans here is making me nervous about adapting to the SDK now.

**Comment by joelanford** [comment]
@vchande It's hard to speculate since Helm 3 has not been released, but we have been tracking the [Helm 3 design proposal](https://github.com/helm/community/blob/master/helm-v3/000-helm-v3.md), and we plan on evaluating it once it's released. I'd be surprised if we aren't able to support it.

In fact, we've already begun implementing some of Helm 3's designs in the existing operator. Our [release state storage mechanism](https://github.com/operator-framework/operator-sdk/pull/1102) is now very similar to [Helm 3's storage design](https://github.com/helm/community/blob/master/helm-v3/003-state.md).

**Comment by vchande** [comment]
@joelanford  thanks this helps me a lot. I am glad this is been thought through in advance.
