### ISSUE TITLE
add option to generate the header files to all files and not only for api

### ISSUE THREAD

**Issue by cpanato** [operator-framework/operator-sdk#1270]
## Feature Request

today looks like you can add a custom header file only for the api, will be good to have an option to add to all files in the project

**Comment by LiliC** [comment]
Since we already use the `--header-file` flag in the `k8s` and `openapi` subcommands, we could be using the same whenever we generate any files to be consistent. 

cc @joelanford

**Comment by joelanford** [comment]
@cpanato When you say all files in the project, do you really mean _all_ files? For example, are you asking to have headers added to `Dockerfile`, `.gitignore`, `Gopkg.*`, YAML files, etc.? Or are we just talking `go` source files?

**Comment by LiliC** [comment]
He was thinking of something like that https://book.kubebuilder.io/beyond_basics/boilerplate.html

**Comment by cpanato** [comment]
@joelanford I'm talking about go files.

yeah, similar that the kubebuilder does.

**Comment by joelanford** [comment]
Ahh okay. Yeah that seems reasonable to me. There's a chicken and egg problem with the `operator-sdk new` command though, since it fails if the project directory exists. To get around that, we could add a `--header-file` flag to the `new` subcommand to populate `hack/boilerplate.go.txt` prior to running all of the scaffolds.

Would we remove the `--header-file` flags that we currently have for the `generate` subcommands and rely only on this file?

/cc @estroz

**Comment by estroz** [comment]
@joelanford seems reasonable. I'll make a PR.
