### ISSUE TITLE
Partial cleanup of ClusterRole and ClusterRoleBinding after running test.

### ISSUE THREAD

**Issue by Avni-Sharma** [operator-framework/operator-sdk#1287]
## Bug Report

**What did you do?**
I ran a test for an operator referring this https://github.com/operator-framework/operator-sdk/blob/master/doc/test-framework/writing-e2e-tests.md .

**What did you expect to see?**
After running the test it should ideally clean up all the resources and PASS. However, it fails because it is not deleting the ClusterRoles and the ClusterRoleBindings.

**What did you see instead? Under which circumstances?**
```
INFO[0000] Testing operator locally.                    
=== RUN   TestComponent
--- FAIL: TestComponent (0.16s)
    client.go:57: resource type ServiceAccount with namespace/name (component-1554370431/devconsole-operator) created
    require.go:794: 
        	Error Trace:	component_test.go:48
        	Error:      	Received unexpected error:
        	            	clusterroles.rbac.authorization.k8s.io "devconsole-operator" already exists
        	Test:       	TestComponent
        	Messages:   	failed to initialize cluster resources
    client.go:75: resource type ServiceAccount with namespace/name (component-1554370431/devconsole-operator) successfully deleted
FAIL
FAIL	github.com/redhat-developer/devconsole-operator/test/e2e	0.284s
Error: failed to exec []string{"go", "test", "./test/e2e//...", "-namespacedMan", "/tmp/namespaced-manifest.yaml795760087", "-globalMan", "/tmp/global-manifest.yaml162133322", "-root", "/home/avni/go/src/github.com/redhat-developer/devconsole-operator", "-v", "-parallel=1"}: exit status 1
Usage:
  operator-sdk test local <path to tests directory> [flags]

Flags:
      --debug                        Enable debug-level logging
      --global-manifest string       Path to manifest for Global resources (e.g. CRD manifests)
      --go-test-flags string         Additional flags to pass to go test
  -h, --help                         help for local
      --image string                 Use a different operator image from the one specified in the namespaced manifest
      --kubeconfig string            Kubeconfig path
      --molecule-test-flags string   Additional flags to pass to molecule test
      --namespace string             If non-empty, single namespace to run tests in
      --namespaced-manifest string   Path to manifest for per-test, namespaced resources (e.g. RBAC and Operator manifest)
      --no-setup                     Disable test resource creation
      --up-local                     Enable running operator locally with go run instead of as an image in the cluster
```

**Possible Solution**
Deleting the ClusterRoles and ClusterRoleBindings if present.

**Comment by hasbro17** [comment]
@Avni-Sharma Can you specify the exact command and flags used to run the tests and the namespaced and global manifests used? E.g `operator-sdk test local ...`

@AlexNPavel There's nothing explicit in the test framework that would cause it to ignore the cleanup a ClusterRole right?
From the manifests in question it seems that role.yaml would just have a ClusterRole instead of a Role.
So we'd have a ClusterRole as part of the namespaced manifests. 
https://github.com/redhat-developer/devconsole-operator/tree/master/deploy

**Comment by AlexNPavel** [comment]
There shouldn't be any reason that it wouldn't be deleted by the test framework. By default, all roles (regardless of cluster scoped or not) are part of the namespaced manifests. The SDK automatically deletes the resources and waits for deletion to complete. If the object is not deleted an error is given

**Comment by hasbro17** [comment]
@Avni-Sharma The SDK and test-framework version in the operator that you linked is also quite old.
https://github.com/redhat-developer/devconsole-operator/blob/master/Gopkg.toml#L46
Please update to one of the latest versions i.e `v0.6.0` or `v0.7.0` and retry. 
The test framework has had significant changes made since `v0.2.1`. If you still see the same problem please reopen this issue.
