### ISSUE TITLE
Deadlock on operator with Leader Locker with Evicted Pod Bug 1749620

### ISSUE THREAD

**Issue by gbaufake** [operator-framework/operator-sdk#1305]
## Bug Report

**What did you do?**
- Deployed an operator (on this case https://github.com/kiali/kiali/tree/master/operator)
- Went out of resources and operator pod went to evicted state
- Openshift created a new operator pod, but it didn't start the operator code because of the locker.

**What did you expect to see?**
- Ignored the locker on Evicted Operator Pod

**What did you see instead? Under which circumstances?**
- Health pod was deadlock mode waiting to become a leader when the leader was an evicted pod.

**Environment**
* operator-sdk version: 0.6.0

* go version:

* Kubernetes version information:

Openshift 3.11

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

Ansible

**Possible Solution**
- Check for some sort of liveness probe on operator leader pod?

**Additional context**
Operator Pod logs : 
[kiali-operator-854c688ff-kqv77.log](https://github.com/operator-framework/operator-sdk/files/3060154/kiali-operator-854c688ff-kqv77.log)

Evicted Pod:
![evicted-pod-operator](https://user-images.githubusercontent.com/2313749/55820237-ef064480-5afa-11e9-9ac8-9552397fee9c.png)

**Comment by joelanford** [comment]
Thanks for the report! This is an interesting case we haven't seen before. The reason this is happening is that the operator pod creates the ConfigMap lock with the pod as an owner reference. So the lock will not be garbage-collected until the evicted pod is deleted.

The workaround would be to delete the evicted pod.

The default `main.go` scaffold used to include a readiness check, but we removed it because it also caused a deadlock in certain deployment rollout cases. See #920. 

Also related is #1234, and to reiterate, we plan to work on re-implementing liveness and readiness checks in a future sprint, this time accounting for these deadlock issues.

**Comment by gbaufake** [comment]
This issue still happening on 0.8.0 and 0.9.0

**Comment by gbaufake** [comment]
![Captura de tela de 2019-08-20 11-41-09](https://user-images.githubusercontent.com/2313749/63342911-037e0780-c34d-11e9-9ebc-5399ad7717a1.png)
![Captura de tela de 2019-08-20 11-41-25](https://user-images.githubusercontent.com/2313749/63342914-037e0780-c34d-11e9-99d1-a03b38a5b92d.png)

**Comment by asmacdo** [comment]
BZ clone: https://bugzilla.redhat.com/show_bug.cgi?id=1749620

**Comment by asmacdo** [comment]
Demo of bugfix: https://www.youtube.com/watch?v=qTzdAYWPdCQ
