### ISSUE TITLE
migrate command gives access to manager

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-sdk#1306]
## Feature Request

When a user run the `migrate` command, they may want to do one of these things:
* create a go-based webhook
* create a go-based controller and run it with the same manager as the ansible or helm based controllers

 Today, the `migrate` command does not give access to the `Manager` object or anything else that's useful. It would be up to the user to copy-and-paste a bunch of existing startup code, and then modify it to their needs.

**Describe the solution you'd like**

We need a way to enable those use cases that is easier. An example would be to allow a user to create their own manager in `main.go`, do whatever they want with it, and then pass that manager into [`ansible.Run`](https://github.com/operator-framework/operator-sdk/blob/v0.7.0/pkg/ansible/run.go#L47) or [`helm.Run`](https://github.com/operator-framework/operator-sdk/blob/v0.7.0/pkg/helm/run.go#L47).

**Comment by camilamacedo86** [comment]
I am closing this one because the migrate command was deprecated in the 0.19. See the [CHANGELOG](https://github.com/operator-framework/operator-sdk/blob/182f02198ab252b3e2e8328781de1d02c3e3d60e/CHANGELOG.md#deprecations) and was removed for the 1.0 release as part of the process to integrate the project with Kubebuilder. 

> The migrate sub-command is deprecated. (#3319)

However, please, feel free to ping us if you need and raise new issues. Really thank you for you collaboration.
