### ISSUE TITLE
document how to access CRs from helm or ansible based operators in go

### ISSUE THREAD

**Issue by mhrivnak** [operator-framework/operator-sdk#1308]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When running an operator that happens to be implemented in Ansible or Helm, I may want to interact with that operator's CRs from go code. For example, I might write an admission webhook in Go for an ansible-based operator. It's not clear how I should access the CRs since there are no Go types defined.

**Describe the solution you'd like**
Documentation that explains a recommended approach.

**Comment by varshaprasad96** [comment]
Ansible operator's have reached Level V capabilities, they can perform the same actions as a Go operator does. Whereas, in Helm this feature is being solved using Hybrid Operators. It is unsure if the community would still want to perform this action.

Additionally, creating a Go type from existing CRs in a cluster, is a topic by itself which needs more work to be done. The best place to have it would probably be in controller-tools, rather than in Operator SDK. Closing this issue for now, please feel free to re-open if there are any questions.
