### ISSUE TITLE
generate openapi removes shortNames from CRD

### ISSUE THREAD

**Issue by enisoc** [operator-framework/operator-sdk#1323]
## Bug Report

**What did you do?**
1. operator-sdk add api ...
2. Edit `deploy/crds/my_crd.yaml` to add `shortNames: ["blah"]`.
3. operator-sdk generate openapi

**What did you expect to see?**
The validation section should be filled in without removing my shortNames.

**What did you see instead? Under which circumstances?**
The generator removed my shortNames.

**Environment**
* operator-sdk version: v0.7.0

* go version: 1.12.2

**Additional context**

I also tried the `+kubebuilder` annotation for setting shortNames, but it was ignored:

```
// +kubebuilder:resource:path=services,shortName=to;ty
```

**Comment by hasbro17** [comment]
Thanks for reporting this. 

This is another bug because of the way we currently try to regenerate only the validation block and preserve everything else in the existing CRD manifest.
Except it turns out we're also stomping out the `spec.names` section. 
https://github.com/operator-framework/operator-sdk/blob/master/internal/pkg/scaffold/crd.go#L138-L139

This was due to an older assumption where the controller-tools CRD generator didn't support generating Singular names. But that's been fixed now with the `+kubebuilder:singular` tag.
https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/internal/codegen/parse/crd.go#L89-L92
https://github.com/kubernetes-sigs/controller-tools/pull/142

We're planning to fix this in #1278 by regenerating the entire CRD on `operator-sdk generate openapi` so that we entirely rely on the `+kubebuilder:...` tags and not try to preserve manual edits.
