### ISSUE TITLE
Using zap.Sugared() to write log statements

### ISSUE THREAD

**Issue by jaxxstorm** [operator-framework/operator-sdk#1341]
## Question

I'm trying to use zap's Sugared logging https://godoc.org/go.uber.org/zap#hdr-Choosing_a_Logger

Which allows you to do

```
log.Infof("something %s", string)
```
But I don't seem to be able to get this working. Is there any documentation on how to do this?

**Comment by joelanford** [comment]
@jaxxstorm controller-runtime and operator-sdk use the [`logr`](https://github.com/go-logr/logr) logging interface for structured logging throughout. operator-sdk uses the [`zapr`](https://github.com/go-logr/zapr) library to convert a `*zap.Logger` into an implementation of the `logr.Logger` interface. `*zap.SugaredLogger` is not supported by `zapr`

The logr interface encourages the use of structured logging because it's more searchable and much easier to parse, index, analyze, etc.

If those benefits aren't applicable for your use case, you could convert a `zap.Logger` to a `zap.StructuredLogger`:

```go
logger, err := zap.NewProduction()
zapLogger := zapr.NewLogger(logger)
logf.SetLogger(zapLogger)
sugaredLogger := logger.Sugar()

somethingString := "foobar"
sugaredLogger.Infof("something %s", somethingString)
```

Or you could use `fmt.Sprintf()` with the `zap.Logger`:
```go
logger, err := zap.NewProduction()
zapLogger := zapr.NewLogger(logger)
logf.SetLogger(zapLogger)

somethingString := "foobar"
zapLogger.Info(fmt.Sprintf("something %s", somethingString))
```

Let me know if that helps!

**Comment by jaxxstorm** [comment]
Awesome, thanks!
