### ISSUE TITLE
Enhance the controller skaffolded in order to support additional patterns

### ISSUE THREAD

**Issue by cmoulliard** [operator-framework/operator-sdk#1349]
## Feature Request

**Is your feature request related to a problem? Please describe.**

One of the most difficult thing due to the event based architecture of k8s and async creation of the different kubernetes resources, is to figure out properly if the children resources created by the Controller when a CR is reconciled are created AND have by the example the status "Running". Such information is mandatory if we would like to report to the user responsible to create a Custom Resource if the application has been deployed sucessfully.

**Describe the solution you'd like**

I would like to suggest that the controller generated during the skaffolding process includes also the code able to fetch all the children resources populated (e.g pod, replicaSet) and update the status of the CR to by example "installed" if all the children resources status are "Running". Ideally, the children resources which are owned by the CR should be recuperated using an utility function such as `fetchAllOwnedResources`.

Question : Should we perform this logic within the reconcile function of the CR OR using another controller ?

**Comment by LiliC** [comment]
So you want the `Status` support to be added?

**Comment by cmoulliard** [comment]
> So you want the `Status` support to be added?

Yes as I think that this is key feature needed in order to report to the end use using (oc get or kubectl get) if the CR is functionally operational. A CR is a contract between a user and a kubernetes controller in order to install k8s resources and they expect to be informed if the resources have been deployed/updated/removed and if the platform is now ready (= running) in order to continue what they have to do.

**Comment by LiliC** [comment]
Yes, we have plans to add support and helpers for the `Status` field. Not sure if we have another github issue for this @joelanford?

**Comment by joelanford** [comment]
We have #1143, which is a work in progress. Its scope is only to define types and helpers to make it easier for operator developers to create/modify/remove conditions in `status.conditions`.

I'm not sure there's a straightforward way for the SDK to implement a `fetchAllOwnedResources` utility because I don't think there's an `OwnerRefSelector` option for listing resources. To get similar functionality, I think you'd have to set labels on the resources created by your CR, and then use a label selector to query for them later.
