### ISSUE TITLE
Suggestion: Close the issues/questions which has already the answer and/or are without the required info and replies for X days 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1358]
## WHAT:

**Suggestion:** Close the issues/questions which has already the answer and/or are without the required info and replies for X days 

Example:

"We are closing this issue since shows that the question raised was answered. Please, feel free to re-open it if be required."

"We are closing this issue since it is opened for more than X days without any reply with the required info.  Please, feel free to re-open it if be required."

## WHY:

* Be easier to find the questions/issues which still open
* Be easier to find the questions/issues solved
* Be easier to contribute with still needing contribution

**Comment by LiliC** [comment]
Hey, @camilamacedo86 we try to close and cleanup issues if they are open for longer than X days or if we don't get a response, as much as we can, I just did a small cleanup on Friday. :) 

But we often leave issues open if we want to include it in the docs, or if it's a feature request or sometimes we just miss some. 🤷‍♀ 

> Be easier to find the questions/issues which still open
Be easier to find the questions/issues solved
Be easier to contribute with still needing contribution

Of course, we are not perfect and we can do better, especially in adding the help wanted labels! Thanks for the suggestion but since we are already doing this as part of our weekly rotation closing the issue. :)
