### ISSUE TITLE
Failed to find exact match with ansible-operator:v0.7.0 docker image

### ISSUE THREAD

**Issue by fromanirh** [operator-framework/operator-sdk#1380]
## Bug Report

**What did you do?**
We recently rebased github.com/MarSik/kubevirt-ssp-operator on top of quay.io/operator-framework/ansible-operator:v0.7.0.
Our operator, among other things, deploys openshift templates. We get this error trying to deploy the aforementioned templates: "Failed to find exact match for template.openshift.io/v1.Template by [kind, name, singularName, shortNames]"
Using the very same role from command line works fine with 
```
ansible-playbook 2.7.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Oct 30 2018, 23:45:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
```
**What did you expect to see?**
templates deployed succesfully

**What did you see instead? Under which circumstances?**
error: "Failed to find exact match for template.openshift.io/v1.Template by [kind, name, singularName, shortNames]"

**Environment**
* operator-sdk version:
quay.io/operator-framework/ansible-operator:v0.7.0

* Kubernetes version information:
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
kubernetes v1.11.0+d4cacc0

* Kubernetes cluster kind: 
bare metal

* Are you writing your operator in ansible, helm, or go?
ansible

**Additional context**
Role here: https://github.com/MarSik/kubevirt-ssp-operator/blob/master/roles/KubevirtCommonTemplatesBundle/tasks/main.yml

**Comment by fabianvf** [comment]
This is actually due to a fix in the openshift python client, basically there are two resources in the openshift API with the GVK of `templates.openshift.io/v1 Template`, previously the client would only discover one of them (whichever one was processed first), but now the client properly reports two matching resources which unfortunately makes the `k8s` module fail. 

The hacky workaround for now is that you can put `templates` into the kind of the object rather than `Template`, which due to the fuzzy way that the `k8s` module matches the resource will find the proper one. In the long-term we probably just need to add a module specifically for dealing with Templates since they violate the otherwise valid assumption that each GVK maps to a single resource.

**Comment by fabianvf** [comment]
Closing this for now as it's not anything that the operator-sdk can fix, this would have to be fixed either in https://github.com/ansible/ansible or https://github.com/openshift/openshift-restclient-python
