### ISSUE TITLE
Automatic CRD registration

### ISSUE THREAD

**Issue by mikewied** [operator-framework/operator-sdk#139]
CRD registration can be easily performed in the SDK by generating a few extra fields in register.go in the api folder, creating the CRD in the codebase, and then pushing it to Kubernetes when the operator starts up. This is a nice usability feature because people deploying the operator no longer need to worry about pushing the CRD into Kubernetes before starting the operator.

Ideally this would be a separate API so that users who prefer manually pushing the CRD to Kubernetes are still able to get that behavior.

**Comment by ecordell** [comment]
The sdk should probably support creating the CRDs as an option, but https://github.com/operator-framework/operator-lifecycle-manager will create the CRDs on behalf of an operator, and the sdk at some point should generate manifests for OLM as well.

The advantage of doing that is that operators can run with reduced permissions - since CRD-creation is currently a cluster-level operation.

**Comment by devlounge** [comment]
I also believe one should always decouple the crd  registration from the operator deployment. 
This way, for example, the cluster admins will register the CRDs, but the operator could be deployed by anyone having the permission to deploy in a given namespace. Otherwise we need to grant to many permissions via RBAC.

**Comment by kfox1111** [comment]
I wonder if this is a good time to bring up the idea of CRD's that are namespace(/tenant), not cluster specific? CRD's that an end user in a multitenant environment could create/consume.

IE, if the operator is being deployed for all tenants, then it probably should have permissions to look at all tenants anyway.

While a user might want to deploy it themselves but would need CRD's that match and they probably should be able to create those too for themselves.
