### ISSUE TITLE
Small improvements for Memcached example

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1464]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Since it is not a good practice to make a loop be performed many times, with many checks, unnecessarily which will spend more resources without any need/reason for that I understand that the reconcile follow the same principal.

In order to clarify my idea, make the reconcile requeue always without any reason for that shows not a good practice like the following example. 

```go
while { // reconcile
	if conditional { // conditional
		// do something
		// go to begginer without any reason when it could stop here 
                 reconcile.Result{Requeue: true}, nil
	}
}
```

Because of this, I think that a small change in the example could bring a better understanding and lead a more responsible usage of it. Shows that many people believe that **requeue always after any action as creating/updating an object** is required/mandatory or indeed a good practice which is NOT my POV.

Please, let me know if I did not get it properly as well. 

**Describe the solution you'd like**

* Add impl to create a Service in the Memcached example 
* Do not use requeue true after creating this Service in order to make clear that is not mandatory requeue ALWAYS after creating/update an object/resource.

PS.: IMHO: It could be helpful to make clear not just this point but also address the requests made in other places over the example and shows better how to create/manage the objects.

I will be working on it and a PR probably will make easier understand my idea/suggestion :-)

**Comment by camilamacedo86** [comment]
I will be working on it. :-)

**Comment by grdryn** [comment]
In that Memcached example, it explicitly comments to return and requeue when things are created or updated. It does seem odd to have that explicitly commented if you're saying that it's not necessary.

https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/controller/memcached/memcached_controller.go#L116..L117

https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/controller/memcached/memcached_controller.go#L132..L133

I'm not as familiar as you are with this sdk, and I agree that if you are intimate enough with what's going on, it's probably fine to not "return and requeue".

I can think of a reasons that it might be better to just requeue always after sending something to the api server, but I'm not sure how valid or important it is:

Consider the case where you check if a `Deployment` exists, and go down a different path if it does (happy path) or not (create path). Now remember that Kubernetes will add/update information to your `Deployment` instance, as the state of the world changes, such as metadata, status, etc. By returning and requeueing once you've gotten to the end of this "create path", you now start again in the hopes of following the "happy path". This allows you to benefit from the fact that you query the state of the `Deployment` before deciding what path to follow, rather than needing to query again after creation in the cases where you rely on information that Kubernetes may have created or updated in your `Deployment` instance.

I've seen what I think is a variation of this case where we created a Route in an OpenShift environment, but didn't "return and requeue". We left it to OpenShift to decide what the value of the `spec.host` field of the `Route`, based on the configuration of the router, but because we didn't query the state back from the server, then "sometimes" it would be set when we later try to read it (actually I never saw it set properly, but others claim they did). I didn't know about the "return and requeue" pattern at the time, so I fixed it in a different way, by just querying for the new state again. Now that I think about it though, If I had just followed the example, where it does a return and requeue after create or update, I think it would have been a cleaner solution.

It would be good to get clarification if this is an intentional pattern, or if it's just unnecessary! :smiley:

**Comment by hasbro17** [comment]
@camilamacedo86 Requeuing after creating/updating resources is intentional because as @grdryn rightly pointed out, you want to ensure that your operator gets to the end of its "happy path"(or end of the reconcile loop).

While it's true that any updates to the API server will necessarily result in watch events to re-trigger your reconcile loop, you can still end up missing events, or even worse not be watching all your secondary resources which means your reconcile loop won't be re-triggered as a result of the create/update step.

So while you can probably get away with not requeing after a create/update I would not want to encourage it in the memcached-operator example.

> Since it is not a good practice to make a loop be performed many times, with many checks, unnecessarily which will spend more resources without any need/reason

This is debatable. Intentionally re-queueing to rerun your reconcile loop many times to fully reconcile the state of your application is better than potentially missing updates in order to save resources. Plus what resources are we talking about? 
If it's requests to the api server then you can reduce the chattiness of your operator by adding a delay in your requeue.

Hope I've understood your suggestion correctly, and if not please feel free to clarify. Otherwise you can close the issue.

**Comment by hasbro17** [comment]
@camilamacedo86 Closing this for now. Please reopen if you still have questions.

**Comment by shawn-hurley** [comment]
Can

**Comment by camilamacedo86** [comment]
I did the PR to example: https://github.com/operator-framework/operator-sdk-samples/pull/67
However, I am waiting for the review in order to check where more we need to reflect this change and them update them. c/c @shawn-hurley

**Comment by camilamacedo86** [comment]
Hi @hasbro17 we updated the example to make it more clear. So, I think we can close this one 👍. Please, feel free to re-open if you think it is required.
