### ISSUE TITLE
Create a command to upgrade the local version installed

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1465]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If the user would like to update the local installation needs came to be to docs and guess that re-install it again will works which is not a good experience.

**Describe the solution you'd like**

Add a new command `operator-sdk upgrade` for example which will check the SO re-install it to get the latest version. E.g For MacOS it should exec  "brew install operator-sdk" 
```shell

An SDK for building operators with ease

Usage:
  operator-sdk [command]

Available Commands:
  add         Adds a controller or resource to the project
  build       Compiles code and builds artifacts
  completion  Generators for shell completions
  generate    Invokes specific generator
  help        Help about any command
  migrate     Adds source code to an operator
  new         Creates a new operator application
  olm-catalog Invokes a olm-catalog command
  print-deps  Print Golang packages and versions required to run the operator
  run         Runs a generic operator
  scorecard   Run scorecard tests
  test        Tests the operator
  up          Launches the operator
  version     Prints the version of operator-sdk

```

**Comment by joelanford** [comment]
IMO, this would add too much complexity to `operator-sdk`.

For homebrew users, I think it's reasonable to expect them to use the `brew` CLI to upgrade their package natively, since that's how they do it for all other brew-installed packages.

For non-homebrew users, there are currently two methods:
1. Download it from our releases page. This could be scripted fairly easily (just have to pass in a version number). It could also be improved with #1398.
2. Build from source. This is pretty simple for existing users. (cd operator-sdk; git co v0.8.0; make install)

Another option could be to pursue creating a package for major OSes (maybe a .rpm and .deb)

**Comment by camilamacedo86** [comment]
It is fine. Please, feel to close if you think that add it is not the best way.

**Comment by camilamacedo86** [comment]
Hi @joelanford,

I think reinstall it again is fine. It is the same approach of Minishift and many other tools. We just need to make clear it in the docs as it is for Minishift for example.

**Comment by joelanford** [comment]
@camilamacedo86 Sounds good. I'll close this one then. If you think we need to clarify anything in the [install doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md), feel free to open an issue or PR for that!
