### ISSUE TITLE
operator-sdk event history

### ISSUE THREAD

**Issue by dragon9783** [operator-framework/operator-sdk#1478]
## Type of question

**help around the operator-sdk**

## Question

**What did you do?**
operator-sdk event only handle object's current state, how could cache event history, and compare object's old state and current state, like controller informer

**What did you expect to see?**

**What did you see instead? Under which circumstances?**

**Environment**
* operator-sdk version:
v0.7.0
  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @dragon9783,

It is really up to you. You can create variables in the Status struct of your CR to keep this information. You can use logs to track the info. You can do it in many ways. Could you describe more what need you are trying to solve? What exactly you need store and why?  Maybe with this info, will be easier to give better ideas.

**Comment by dragon9783** [comment]
Hi, @camilamacedo86 ,
sorry for reply later, like replicas controller in kubernetes,  in order to decrease to request api-server, will get oldReplicas and newReplicas from informer cache.

**Comment by hasbro17** [comment]
@dragon9783 If you are simply trying to ignore duplicate events where the event's resource version hasn't changed, or the CR's metadata.generation hasn't changed during an update then you can use event filtering via [predicates](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/predicate).
See the [guide on event filtering](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/event-filtering.md).

But other than that, I would advise against trying to store/track the history of your objects (as variables or in a cache) in your operator. Your reconciler is intentionally not passed in the object's old state and new state because your reconcile loop should be idempotent by only looking at the current state of an object in order to reconcile it.

Feel free to close this issue if that helps answer your use case for reducing api-server requests.
