### ISSUE TITLE
Horizontally scaling operators/multiple operators under the same resource group

### ISSUE THREAD

**Issue by wreed4** [operator-framework/operator-sdk#1540]
## Type of question

Best practices, how to use the image the operator-sdk produces

## Question

**What did you do?**
I have three operators, each for one CRD.  These are in different repositories and different "operator-sdk" projects.  However, they all share a resource "group".  let's call them `A.my.group.io`, `B.my.group.io`, and `C.my.group.io`.  They are all go operators.  I've structured them this way because I noticed that the operator-sdk produces a single image meant to run as a single deployment and it does not appear to be possible to horizontally scale this to manage high load.  

However, when I went to generate a clientset for one of these resources (which would be really nice if this could be incorporated into `operator-sdk generate k8s`, by the way), I noticed that he client it generates is for `my.group.io`, not for `A`.  This leads me to think keeping `B` and `C` in different repos will lead to issues when creating those clients.  It seems like they're meant to be all part of the same repo/project.  Which also makes sense why you can add multiple "controllers" under one project.  

But this operator (these operators?) I'm building are meant to manage potentially thousands of customer's resources.. all resources for the whole cluster.  There could possibly be quite a lot of traffic for these things to handle.  This is my first operator, so I'm unclear if that's just... not a concern with golang because it just won't scale too big for a single go container to handle, but that hasn't been my experience with anything else.  At some point, It always seems like things need to be scaled out horizontally.  

So my question is sort of multi-part:
1. Should an operator run in a leader-less, multi-pod deployment, with each pod handling events simultaneously or is this just not how they're supposed to be structured.. are they always supposed to be one pod?
1. If they are supposed to be one pod, at what point should I be worried that a single pod will not be able to handle events in a timely manner?
1. If I am going to exceed that level of events, how should I be splitting up these resources?  They are all related, it makes sense to me for them to be in one api group, but there's nothing preventing me technically from just creating a different api group for each.. just seems wasteful. 
1. After all that, if I have multiple repos, how is client generation supposed to work in that situation? When a golang codebase imports my clientset, would they be able to use all clients simultaneously? or would they need to import them separately?

I know there's a lot here, but I'm hoping someone can clear some of this up for me.  I feel like I'm probably thinking about the problem incorrectly at some level, but I'm not sure where that is. 

**Environment**
* operator-sdk version:
```
operator-sdk version: v0.8.0, commit: 78c472461e75e6c64589cfadf577a2004b8a26b3
```

* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

**Additional context**
This is work for my employer, so I can't divulge _toooo_ many details of what the controllers are or what they do, but at a high level, an A, B, and C resource contains information (similar to a helm chart) and the controllers use that information to provision other resources, both in the cluster, and one of them uses that information to provision a mysql database.  A, B, and C correspond to abstract concepts that a customer might buy.  Customers can update these resources (through an api) at any time, and with any frequency.  I am not anticipating these being updated multiple times a second per customer, but perhaps multiple times an hour per customer.  And the Reconcile loop may be semi-expensive.. but it is basically creating other k8s resources or provisioning mysql databases.

**Comment by joelanford** [comment]
@wreed4 I'll take a stab at this, but @shawn-hurley and @hasbro17 may have some helpful insights as well.

> Should an operator run in a leader-less, multi-pod deployment, with each pod handling events simultaneously or is this just not how they're supposed to be structured.. are they always supposed to be one pod?

Generally, no. Your operator is generally only using CPU cycles to update its caches and reconcile watched objects when they change. Do you anticipate that your operator will be watching and reconciling a large number of objects that are changing frequently?

If you do need to scale up, you have a couple of options:
1. You can use controller-runtime's [`controller.Options.MaxConcurrentReconciles`](https://github.com/kubernetes-sigs/controller-runtime/blob/056a18adfb38c7cafac2aeefdda0b63c41c0919b/pkg/controller/controller.go#L33-L34) to scale the number of goroutines handling reconciliations with a single operator process.
2. You can deploy multiple copies of your operator, each watching a specific subset of the cluster. For example, depending on your use case, you could deploy the operator into each namespace you expect your CRs to be present, and configure each operator instance to only watch and reconcile objects in its namespace.

> If they are supposed to be one pod, at what point should I be worried that a single pod will not be able to handle events in a timely manner?

This is probably extremely dependent on your cluster, what your operator is doing, and how often it is reconciling watched objects. I'd suggest keeping an eye on CPU and [controller-runtime's built-in metrics](https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html). 

> If I am going to exceed that level of events, how should I be splitting up these resources? They are all related, it makes sense to me for them to be in one api group, but there's nothing preventing me technically from just creating a different api group for each.. just seems wasteful.

Will you always be deploying A, B, and C together and is there strong coupling between them? If so, I'd suggest creating them in a single group and managing them with one operator.

On the other hand, if each object is unrelated and your customers can deploy any of them without the others, then you may want to consider different groups and different operators so that each can be updated and deployed independently.

> After all that, if I have multiple repos, how is client generation supposed to work in that situation? When a golang codebase imports my clientset, would they be able to use all clients simultaneously? or would they need to import them separately?

The SDK does not currently support clientset generation, though you could probably set it up for your project (e.g. with a `make` target) See: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/generating-clientset.md)

If you have multiple repos, each with their own APIs, you will likely need to generate at least one clientset per repo. And your clients would have to import those clientsets from whichever repos contain the clients they need.

If you have a single repo, the number of imports will depend on how you structure your APIs and clientset generation.

**Comment by shawn-hurley** [comment]
> If you have multiple repos, each with their own APIs, you will likely need to generate at least one clientset per repo. And your clients would have to import those clientsets from whichever repos contain the clients they need.

> If you have a single repo, the number of imports will depend on how you structure your APIs and clientset generation.

I would suggest in this case to have an `api` repo where the structs and clientset are defined and that your controller will vendor this repo in. This is how k8s and openshift are breaking these things up. see https://github.com/kubernetes/api

> But this operator (these operators?) I'm building are meant to manage potentially thousands of customer's resources.. all resources for the whole cluster. There could possibly be quite a lot of traffic for these things to handle.

Most kubernetes controllers use leader election and don't shard the cluster AFAIK. I think it would be safe to assume that if it works for the pod controller that it will probably be fine for your controller but you will need to increase the MaxConcurrentReconciles as @joelanford mentioned.

**Comment by wreed4** [comment]
Thank you both, your responses have been extremely helpful.  

> Do you anticipate that your operator will be watching and reconciling a large number of objects that are changing frequently?
Not necessarily per resource, but on aggregate I think so.  I anticipate thousands of objects.  Under normal usage, probably only 50% of those will be updated in a day.. so maybe not much traffic.  There are cases however where many customers might do something at the same time which means we might get a burst of several hundred or thousand events (not precisely at the same time, but maybe over the course of an hour?).  So.... potentially not really enough to worry about given some of the other input you've given.

> Will you always be deploying A, B, and C together and is there strong coupling between them? If so, I'd suggest creating them in a single group and managing them with one operator.
Yes one really doesn't make any sense without the other.  Which is why I ideally would have wanted them in one repo, but the one container thing scared me. 

>Most kubernetes controllers use leader election and don't shard the cluster AFAIK. I think it would be safe to assume that if it works for the pod controller that it will probably be fine for your controller but you will need to increase the MaxConcurrentReconciles
I think this is the most impactful thing to put it in perspective for me.  If it works for Deployments/ReplicaSets, etc.. it should definitely work for me.  Those will have much more traffic than my operators (since my operators will be manipulating these resources) so they should end up being a bottleneck before mine does ideally.  

I think at this point, I will use one repository, one container, and see how it goes.  Definitely increasing `MaxConcurrentReconciles` like you both suggested.  Thank you both!

One final question:  The nginx ingress controller does have the ability to horizontally auto-scale the controller.  Do you guys have any insight into why and how they accomplished this?

**Comment by joelanford** [comment]
@wreed4 If I understand your question about the the nginx ingress controller correctly, I don't think it is directly comparable to an operator.

In the case of an ingress controller, it is looking at every ingress resource (at least that is assigned to it via an annotation), building and applying a reverse proxy configuration, and actually running the reverse proxy all in the same pod. In this case, it makes sense for there to be multiple replicas that all watch the same set of resources because:
1. You need to scale your reverse proxies to handle incoming traffic.
2. You need each of the ingress controller replicas to have the same view of the backend services described by the ingress resources, so that a load balancer can hit any of the ingress controller replicas and get to the backend service based on the incoming request.

**Comment by kvaps** [comment]
It would be really nice to have an ability to run multiple controllers for manage same resources set, each set can be selected by labels or field-selector or just simple process every n'th resource by operator's replica number.
