### ISSUE TITLE
Allow openapi to act only on specific GKV

### ISSUE THREAD

**Issue by jpkrohling** [operator-framework/operator-sdk#1633]
## Feature Request

In the Jaeger Operator, we have a legacy CRD (`io.jaegertracing/v1alpha1`) which we deprecated some months ago. When running the `generate openapi` command, I'd like to keep the CRD `deploy/crds/io_v1alpha1_jaeger_crd.yaml` untouched, as I don't want to bring new features or bugs to it.

Currently, the mentioned command will regenerate all the CRDs that it can find. From the command documentation:

```
generate openapi generates OpenAPI validation specs in Go from tagged types
in all pkg/apis/<group>/<version> directories. Go code is generated under
pkg/apis/<group>/<version>/zz_generated.openapi.go. CRD's are generated, or
updated if they exist for a particular group + version + kind, under
deploy/crds/<group>_<version>_<kind>_crd.yaml; OpenAPI V3 validation YAML
is generated as a 'validation' object.

Example:
	$ operator-sdk generate openapi
	$ tree pkg/apis
	pkg/apis/
	└── app
		└── v1alpha1
			├── zz_generated.openapi.go
	$ tree deploy/crds
	├── deploy/crds/app_v1alpha1_appservice_cr.yaml
	├── deploy/crds/app_v1alpha1_appservice_crd.yaml

Usage:
  operator-sdk generate openapi [flags]

Flags:
  -h, --help   help for openapi

Global Flags:
      --verbose   Enable verbose logging
```

**Comment by LiliC** [comment]
We could add a flag of some sort to ignore certain APIs that are passed via that flag. cc @estroz

**Comment by estroz** [comment]
I'm thinking of a flag `-i/--ignore` for all `generate` subcommands that takes a slice of API group versions and skips generating their OpenAPI or deepcopy code. I chose a brief name because the commands are specific to API's so it should be obvious what is being ignored (with good CLI help text of course). We should not expose the ability to ignore kinds, since that will take a lot more work; the generator is run at a package level.

@LiliC @hasbro17 @joelanford @AlexNPavel @jmrodri @fabianvf WDYT

**Comment by LiliC** [comment]
@estroz that sounds good to me! 👍 

Would that solve your usecase @jpkrohling ?

**Comment by jpkrohling** [comment]
I believe so: at the moment, I don't need to ignore specific `Kind`, but entire groups.

**Comment by camilamacedo86** [comment]
To solve this one we could does as it was done for:

> Added new --skip-generation flag to the operator-sdk add api command to support skipping generation of deepcopy and OpenAPI code and OpenAPI CRD specs. (#1890)

**Comment by camilamacedo86** [comment]
HI @jpkrohling,

As described in the comment https://github.com/operator-framework/operator-sdk/pull/2054#issuecomment-542262737 was decided not to move forward with this kind of request. The reason for that is because we are looking for to design changes to give more flexibility to our users. Then, for customizations like this one, we would like to suggest the usage of [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen) directly by a Makefile. Following an example of a Makefile with targets to generate/update the CRD's in the SDK structure. 

```makefile
# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
CRD_OPTIONS ?= "crd:trivialVersions=true"

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# Generate manifests e.g. CRD, RBAC etc.
manifests: controller-gen
	$(CONTROLLER_GEN) paths=./... crd:trivialVersions=true output:crd:artifacts:config=deploy/crds

# find or download controller-gen
# download controller-gen if necessary
controller-gen:
ifeq (, $(shell which controller-gen))
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
CONTROLLER_GEN=$(GOBIN)/controller-gen
else
CONTROLLER_GEN=$(shell which controller-gen)
endif
```
Then, when the command `make manifests` be called the CRD's in the path `deploy/crds` will be created/updated. 

For further information about how to use the controller-gen options/commands see its [docs]
(https://book.kubebuilder.io/reference/controller-gen.html).

In this way, I am closing this one. However, please feel free to re-open if you feel that would be required.
