### ISSUE TITLE
Provide a Makefile instead adding of more flags in the CLI 

### ISSUE THREAD

**Issue by hasbro17** [operator-framework/operator-sdk#1655]
## Feature Request

From #1600 
> The SDK team has been talking about the fact that the built-in subcommands that wrap go, docker, and other CLI tools are falling short of the necessary flexibilities to meet all use cases.
>
> So instead of constantly fixing bugs and adding new flags for each new use case that comes up (see #1034, #1271, #1311, #1357, #1419, #1422, #1488, #1489, #1497, #1509, #1535, #1582, #1605), we think it makes more sense to recommend that users that need more flexibility start using Makefiles in their projects so that they have full control.
>
> This has a few benefits to both users and SDK maintainers:
> - Users no longer have to wait for a bug fix or new feature in the SDK to customize their operator builds.
> - Users can more easily tie dependent commands together (e.g. always run code generation before building binaries, and always rebuild binaries before building the Docker image)
> - It makes the SDK much simpler in some areas, so maintainers can spend less time dealing with the complexities of abstracting wrapped go, docker, podman, and buildah commands under one CLI. And more time on core SDK and operator-related features.
> - It aligns more with Kubebuilder, which actually scaffolds a Makefile for go compilations, image builds, code generation, etc.
>
> Going down this path, the SDK will also need to scaffold a Makefile to give users the same default experience as the existing subcommands, so I think that's an area we should start devoting effort toward.

**Comment by camilamacedo86** [comment]
HI @hasbro17, 

I think that is a great idea we add a Makefile in the scaffold project which can provide many facilities as for example to apply and delete all resources. However, IMHO the commands which are responsible for generating resources/code need still in the SDK. Following a few reasons for this.

* Regards supportability

If the user changes the impl to do it we will no longer able to help them identify what is wrong since we cannot ensure it more. I mean we are not able to support the user code. 

* Regards the complexity to address the issues that may be raised after it:

It will allow they change the commands and RFE's for we change and or improve them will no longer be raised, however, many issues as "my project is not working", "how to fix the command to gen x", "how to create a command to  gen",  "my resource N is no longer generated successfully" will start to be raised and these ones will be harder to address then the flags options. 

* Introduction of a design limitation:

Currently, we don't need to do the scaffold for all features and options. If the gen commands go to the Makefile them if think that we will need to start to do it and/or have config files which will be hard to make them be easier to be used as well. Also, because the SDK is responsible for having the gen implementations many complexities are reduced too to set up what should or not be generated. See https://github.com/kubernetes-sigs/kubebuilder/issues/1026 in order to get a better idea over my POV and what I am trying to say here. 

c/c @joelanford

**Comment by camilamacedo86** [comment]
HI @hasbro17, 

I think that is a great idea we add a Makefile in the scaffold project which can provide many facilities as for example to apply and delete all resources. However, IMHO the commands which are responsible for generating resources/code would be better still in the SDK. 

Following some questions?

- How can we support the generated code if they can be changed by the user?
- It would be great have no longer the example issues asking for flags and options in the commands, however, would not this approach allow issues as `my project is not working ...`, `how to fix the command to gen N`, `how to create a command to gen ...`,  `my resource N is no longer generated successfully ...` start to be raised?  Would not these ones harder to address then the flags options? 
- Today the developers are allowed to just generate code according to what they need, for example, for OLM CSV file. How would it work? How we can provide good usability for optional features? how to do it without the need to scaffold all possibilities as it is done in the kubebuilder?

**Comment by camilamacedo86** [comment]
After 0.19 SDK release, the new projects created with the tool will have the Makefile scaffolded by default. So, I am closing this one as solved.
