### ISSUE TITLE
Helm Operator can't install chart when using cluster scoped CR

### ISSUE THREAD

**Issue by madorn** [operator-framework/operator-sdk#1666]
## Bug Report

**What did you do?**
* Provision a new Helm Operator with `operator-sdk new my-operator --type=helm --helm-chart mychart --helm-chart-repo https://myrepo`

* Update `watches.yaml` to proper path of imported Helm chart.

* Ensure CR has values inline with `values.yaml`.

* Per [cluster-scope doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md), modify CRD from `scope: Namespaced` to `scope: Cluster`.

* Apply CRD to cluster.

* Run `operator-sdk up local --namespace "" --zap-level 10 --zap-encoder console`

* Apply cluster-scoped CR into cluster.

**What did you expect to see?**
Release Revision info written to a secret, Helm Chart applied.
 
**What did you see instead? Under which circumstances?**
No Release Revision info, Helm chart does not get deployed.

Receive the following error:
```2019-07-10T02:40:50.070-0500	ERROR	kubebuilder.controller	Reconciler error	{"controller": "f5bigipctlr-controller", "request": "/example", "error": "failed to roll back failed installation: release: \"example-f5bigipctlr-btnm92ynag54ik7c5eaxj3o1t\" not found: release example-f5bigipctlr-btnm92ynag54ik7c5eaxj3o1t failed: resource name may not be empty"}```

Upon further investigation, it appears that `tiller.InstallRelease` is failing when attempting to`PUT` a `kind: Secret` for the Release Revision info. The request does not contain a namespace in `metadata.namespace`:

```I0709 23:38:56.768639   53995 request.go:942] Request Body{"kind":"Secret","apiVersion":"v1","metadata":{"name":"example 961xz37tv2z5wyxtdph78gsho.v1","creationTimestamp":null,"labels" {"CREATED_AT":"1562733536","NAME":"example-961xz37tv2z5wyxtdph78gsho","OWNER":"TILLER","STATUS":"PENDING_INSTALL","VERSION":"1"}},"data":{"release":"<base64-encoded-binary"}}I0709 23:38:56.769132   53995 request.go:686] Error in request: resource name may not be empty```

**Environment**
`operator-sdk version: v0.8.1`
`go version go1.12.6 darwin/amd64`

* Kubernetes version information:
```Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

* Kubernetes cluster kind:
`minikube`, also tested with ocp4.1.3

**Possible Solution**
If namespace = nil, write Release Version info into `kube-system` or user designated namespace.

**Comment by LiliC** [comment]
Thanks for opening this. @joelanford should be back from PTO on the 22nd, let us know if you need this sooner for a customer or not.

**Comment by joelanford** [comment]
@madorn Thanks for reporting this. We definitely need to do something to fix or clarify support for cluster-scoped CRs with the helm-operator. Helm associates releases with namespaces, but it also supports installing cluster-scoped resources, so it's somewhat awkward. Helm 3's [proposal for state storage](https://github.com/helm/community/blob/master/helm-v3/003-state.md#namespacing-changes) specifically discusses storing the release state objects in the same namespace as the release.

There are a few options:
1. Make no code changes, but document that the helm-controller supports only namespace-scoped CRDs because of Helm's limitations.
2. Add a mechanism to enable storing a cluster-scoped CR's release secret in `kube-system` or another namespace. The default could be customized with an option to the helm-operator to apply to all cluster-scoped CRs, something found in a CR annotation to give the CR creator more control, or both.

Given Helm 3's direction, I think I'd lean toward option 1, but perhaps this is a question we should bring up with the helm maintainers.
