### ISSUE TITLE
`make dep` doesn't seems to work

### ISSUE THREAD

**Issue by chawlanikhil24** [operator-framework/operator-sdk#1722]
## Bug Report

**What did you do?**
I was trying to install the dependencies using `make dep` command, so as to build the operator.

**What did you expect to see?**
It should install the dependencies.

**What did you see instead? Under which circumstances?**

```sh
[nichawla@nikhil-wicked-machine operator-sdk]$ make dep
make: *** No rule to make target 'dep'.  Stop.
[nichawla@nikhil-wicked-machine operator-sdk]$ 
```

**Environment**
* operator-sdk version:

* go version:

```sh
[nichawla@nikhil-wicked-machine operator-sdk]$ go version
go version go1.9.7 linux/amd64
[nichawla@nikhil-wicked-machine operator-sdk]$ dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.9.4
 go compiler : gc
 platform    : linux/amd64

```

* Kubernetes version information:

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?

**Possible Solution**

**Additional context**

**Comment by hasbro17** [comment]
> using make dep command, so as to build the operator

@chawlanikhil24 The operator project scaffolded by the SDK doesn't have a makefile. Also based on your working directory I'm assuming you meant to build the SDK binary from the operator-sdk repo.

Can you specify what version of the SDK you're trying to build?
Since [v0.9.0](https://github.com/operator-framework/operator-sdk/releases/tag/v0.9.0) we've switched to using modules for the SDK so there is no `make dep` rule anymore.

You should be able to just do `make install` to build the SDK binary.
See: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md#prerequisites

**Comment by joelanford** [comment]
Closing since `make dep` has been removed since `v0.9.0`. See #1777 for doc updates.
