### ISSUE TITLE
Install / Update Charts from Github Repository

### ISSUE THREAD

**Issue by muralov** [operator-framework/operator-sdk#1727]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Currently, operator sdk supports building helm operator with helm charts built in a docker docker image. Whenever a change is made to the helm charts, the operator image must be built.

**Describe the solution you'd like**
I would like to suggest to have an option where helm operator can be configured with a Github repository containing helm charts. Charts will be downloaded and installed from the repository and also updated when the helm charts change in the repository.

**Comment by joelanford** [comment]
@muralov I've actually thought about this before, but there are a few reasons we designed the helm operator project type to build the helm chart into the container.

1. If the chart templates change between versions of a helm chart, existing CR specs that define values for the old chart templates may no longer be valid with the new chart templates. 

    In general Kubernetes solves this problem with [CRD versioning and webhooks](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/). The idea being that the new version of an operator supports the latest API version and it supports converting old CRs to the latest API version with a conversion webhook.

    CRD versioning is not currently supported by the helm operator, however. To do that, we would need to come up with a way to expose CRD conversion logic to operator developers in a way that would be approachable to helm chart authors.

2. If the operator is deployed to a cluster that has limited (or no) access to the internet, then it would not be able to download the helm chart and function correctly. By including the helm chart in the image itself, everything is self-contained.

If these are not concerns to you, I'd recommend using [git-sync](https://github.com/kubernetes/git-sync) as an init container or sidecar, which can do the heavy lifting to make sure that a volume shared with the operator container is populated with whatever git repo you define.

**Comment by muralov** [comment]
@joelanford thank you for your feedback.

1. Regarding your first point, using CRD versioning and webhooks makes sense to me if helm operator should support multiple versions of CRD. Currently, I don't see a need to support multiple versions because helm values under spec should be free to change. 

I think the values not matching helm templates is normal as they are separated each other. This happens in normal cases where people configuration and helm charts in different repositories as we currently do with our GitOps process. Changing the CR is okay in case values don't match the helm templates.

2, Regarding your second point, we can provide this as an option. Then consumer of the helm operator decides whether he want to build docker image with charts or without charts. In case the consumer decides to use the charts remotely during runtime, then it is his/her responsibility to resolve internet connection issue.

**Comment by joelanford** [comment]
@muralov Are you able to use the git-sync mechanism I suggested? If so, I'm not sure it makes sense to duplicate and maintain that functionality in the SDK.

Also separate question: if we made it easier to upgrade the chart of an existing helm-operator project, would that solve your problem? Or are you looking for a more automated/dynamic update mechanic?

To explain my first point more, take the following scenario as an example of what's possible if you aren't careful:
1. You create a helm-operator image based on `my-storage-chart-1.0.0` which is chart that provisions storage and a web app for access (think S3, perhaps). The chart hardcodes storage size to 1000 (MB) and contains a template that uses a `size` value (that defaults to 1 if `size` is not set) to populate the replicas in the web app `Deployment`
2. You build and deploy the operator, and then create a CR called `example-storage` with `spec.size: 2`. This creates a `Deployment` with 2 replicas and provisions 1000 MB of storage.
3. You update your helm chart to `my-storage-chart-2.0.0` to expose storage size and modify the template such that `size` is now used to configure the size of the storage (defaulting to 1000) and the deployment replica count value is now called `deployment.size`. You rebuild and redeploy your operator, without changing `example-app`.
4. The operator reconciles `example-app` by changing the storage size to 2 (MB) (based on the new meaning of `spec.size`) and scales your deployment down to 1 (since that's the default `spec.deployment.size`)

In this scenario, there's no way to migrate `example-app`'s values from `my-storage-1.0.0`-based values to `my-storage-2.0.0`-based values, without either using a conversion webhook. Other options will likely cause downtime or be destructive in some way.

Obviously, this is a contrived example, and there are certainly ways to avoid this issue. My point is that you can get yourself into a tough situation if you don't control the helm chart or if you aren't careful about how you handle breaking changes.

Either way, I'm tempted to close this since it seems like there's a way forward with git-sync, and it's not something we want to encourage, at least until we have a better story on CRD conversion with the helm operator.

**Comment by joelanford** [comment]
@muralov I'm going to close this issue since I'm fairly sure you can accomplish what you're asking for with git-sync. If I'm misunderstanding or would like to discuss more, we can definitely re-open it. Thanks!

**Comment by muralov** [comment]
@joelanford sorry, I have seen it today. I don't get a notification for the comments. It is okay. I will still provide you helm charts you asked. Thanks.
