### ISSUE TITLE
Improve project base and examples by using the FactoryPattern

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1740]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Developers have been facing difficulties to know how to impl their operators to find the best practices to do it.

**Describe the solution you'd like**

Examples and project base generated when we run the commands to create a new project, a new API/Object(CR/CRD) could follow a design design-pattern as [Factory Method Pattern](https://books.studygolang.com/go-patterns/creational/factory.html) to create the objects in the reconcile. See an example of this implementation in an operator [here](https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityservice/controller.go)

**Comment by camilamacedo86** [comment]
Hi, @shawn-hurley @jmrodri @hasbro17 wdyt?

**Comment by hasbro17** [comment]
Retitled to make the issue more specific to using FactoryPatterns which I believe is the main suggestion here.

So this probably has less to do with operator best practices, and more to do with encouraging users to use the FactoryPattern.

Our current base project for the app-operator and the example memcached-operator are small enough that the factory pattern wouldn't make sense.
That makes more sense for when you have a big list of objects that the operator has to check and create at the start of the reconcile loop. As in your example:
https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityservice/controller.go#L203-L229

Since the goal for a new user is to understand the basic APIs and reconcile pattern through a small example, expanding the  example reconcile code to use a FactoryPattern would probably deviate from that.

It might make more sense to document this as a way of reducing the size of a large reconciler that does a bunch of create-if-not-exists at the start. 
But adding the FactoryPattern to the default base project, or memcached-operator example might be awkward fit.

**Comment by camilamacedo86** [comment]
Hi @hasbro17,

Really tks for your engagement here and ideas. We have a doc for good practices will be definitely great and could already address this issue. I agree 100%

I really got your point and make sense, but maybe we could improve a little example and the scaffolded project in order to clarify it a little more as was done [here](https://github.com/operator-framework/operator-sdk-samples/pull/67) and discussed [here](https://github.com/operator-framework/operator-sdk/issues/1464). So, maybe after that apply something like the [example](https://github.com/aerogear/mobile-security-service-operator/blob/master/pkg/controller/mobilesecurityservice/controller.go#L203-L229) could make more sense.

**Comment by joelanford** [comment]
@hasbro17 and @camilamacedo86 

I think this is a good suggestion for larger projects, but I wonder if, rather than documenting each "good suggestion" in isolation, it would make more sense to list good examples of real-world operators that use controller-runtime (maybe in the kubebuilder book with a link from our FAQ?).

Then users would have context and could get a sense of what others are doing to make their operators easier to build and maintain, and we wouldn't have to maintain isolated examples. WDYT?

**Comment by camilamacedo86** [comment]
HI @joelanford,

IMHO: 
- I think we could do a few improvements in the base project which is generated by the tool to lead the dev to follow some design
- Also, I like the @hasbro17 suggestion about we have some doc with good practices since if we check the biggest part of operator projects available in the operatorhub.io they are violating some conceptions as for example using just one controller as install.go for many kinds of CR/CRDs created  which show that the developers have been struggling to get these points.  
- Also, I like the idea of FAQ and centralize examples as well.

**Comment by camilamacedo86** [comment]
Hi @hasbro17 and @joelanford, 

I have been working on in a personal project where I did not apply to it the FactoryPattern and actually, I think the result is better for these small scenarios as you suggested. Please, feel free to check and let me know what you think. (https://github.com/dev4devs-com/postgresql-operator)

Since I understand that improve the docs is already part of the strategy, I think we can close this one.  
Really thank you for share your thoughts and your inputs.
