### ISSUE TITLE
What is the difference between kubebuilder and operator-sdk

### ISSUE THREAD

**Issue by gyliu513** [operator-framework/operator-sdk#1758]
I can use the https://github.com/kubernetes-sigs/kubebuilder to create an operator as well for both APIs and Controllers, so what is the major difference between those two projects?

**Comment by joelanford** [comment]
@gyliu513 There's not a huge difference between the Go projects that kubebuilder and operator-sdk scaffold. Both use controller-tools and controller-runtime and both scaffold substantially similar go package structures.

Where they differ is:
- Operator SDK also has support for Ansible and Helm operators, which make it easy to write operators without having to learn Go and if you already have experience with Ansible or Helm
- Operator SDK includes integrations with the Operator Lifecycle Manager (OLM), which is a key component of the Operator Framework that is important to Day 2 cluster operations, like managing a live upgrade of your operator.
- Operator SDK includes a scorecard subcommand that helps you understand if your operator follows best practices.
- Operator SDK includes an e2e testing framework that simplifies testing your operator against an actual cluster.
- Kubebuilder includes an envtest package that allows operator developers to run simple tests with a standalone etcd and apiserver.
- Kubebuilder scaffolds a Makefile to assist users in operator tasks (build, test, run, code generation, etc.); Operator SDK is currently using built-in subcommands. Each has pros and cons. The SDK team will likely be migrating to a Makefile-based approach in the future.
- Kubebuilder uses Kustomize to build deployment manifests; Operator SDK uses static files with placeholders.
- Kubebuilder has recently improved its support for admission and CRD conversion webhooks, which has not yet made it into SDK.

The SDK and Kubebuilder teams work closely together, and we're planning to increase our efforts to help the kubebuilder team maintain controller-tools and controller-runtime so that the entire community has access to the latest features and bug fixes.

I'm closing this issue since that covers all the major things I can think of. We'll keep answering questions if you have follow-ups though! :slightly_smiling_face:

**Comment by gyliu513** [comment]
Awesome, thanks @joelanford for the detailed explanation! 

One more question: Does the  SDK and Kubebuilder team had some discussion to merge those two projects to one project for easy maintain?

**Comment by danielle-mustillo** [comment]
I believe the answer is yes @gyliu513 , it seems it is a work in progress at this time.

https://github.com/kubernetes-sigs/kubebuilder/projects/7

**Comment by Hats-Wang** [comment]
> @gyliu513 There's not a huge difference between the Go projects that kubebuilder and operator-sdk scaffold. Both use controller-tools and controller-runtime and both scaffold substantially similar go package structures.
> 
> Where they differ is:
> 
> * Operator SDK also has support for Ansible and Helm operators, which make it easy to write operators without having to learn Go and if you already have experience with Ansible or Helm
> * Operator SDK includes integrations with the Operator Lifecycle Manager (OLM), which is a key component of the Operator Framework that is important to Day 2 cluster operations, like managing a live upgrade of your operator.
> * Operator SDK includes a scorecard subcommand that helps you understand if your operator follows best practices.
> * Operator SDK includes an e2e testing framework that simplifies testing your operator against an actual cluster.
> * Kubebuilder includes an envtest package that allows operator developers to run simple tests with a standalone etcd and apiserver.
> * Kubebuilder scaffolds a Makefile to assist users in operator tasks (build, test, run, code generation, etc.); Operator SDK is currently using built-in subcommands. Each has pros and cons. The SDK team will likely be migrating to a Makefile-based approach in the future.
> * Kubebuilder uses Kustomize to build deployment manifests; Operator SDK uses static files with placeholders.
> * Kubebuilder has recently improved its support for admission and CRD conversion webhooks, which has not yet made it into SDK.
> 
> The SDK and Kubebuilder teams work closely together, and we're planning to increase our efforts to help the kubebuilder team maintain controller-tools and controller-runtime so that the entire community has access to the latest features and bug fixes.
> 
> I'm closing this issue since that covers all the major things I can think of. We'll keep answering questions if you have follow-ups though! 🙂



> @gyliu513 There's not a huge difference between the Go projects that kubebuilder and operator-sdk scaffold. Both use controller-tools and controller-runtime and both scaffold substantially similar go package structures.
> 
> Where they differ is:
> 
> * Operator SDK also has support for Ansible and Helm operators, which make it easy to write operators without having to learn Go and if you already have experience with Ansible or Helm
> * Operator SDK includes integrations with the Operator Lifecycle Manager (OLM), which is a key component of the Operator Framework that is important to Day 2 cluster operations, like managing a live upgrade of your operator.
> * Operator SDK includes a scorecard subcommand that helps you understand if your operator follows best practices.
> * Operator SDK includes an e2e testing framework that simplifies testing your operator against an actual cluster.
> * Kubebuilder includes an envtest package that allows operator developers to run simple tests with a standalone etcd and apiserver.
> * Kubebuilder scaffolds a Makefile to assist users in operator tasks (build, test, run, code generation, etc.); Operator SDK is currently using built-in subcommands. Each has pros and cons. The SDK team will likely be migrating to a Makefile-based approach in the future.
> * Kubebuilder uses Kustomize to build deployment manifests; Operator SDK uses static files with placeholders.
> * Kubebuilder has recently improved its support for admission and CRD conversion webhooks, which has not yet made it into SDK.
> 
> The SDK and Kubebuilder teams work closely together, and we're planning to increase our efforts to help the kubebuilder team maintain controller-tools and controller-runtime so that the entire community has access to the latest features and bug fixes.
> 
> I'm closing this issue since that covers all the major things I can think of. We'll keep answering questions if you have follow-ups though! 🙂

Hi. Does operator-sdk support the goalng based operator in operator-sdkv0.19.0?If it supports, why it prints " value of --type can only be `ansible`, or `helm`: unknown operator type "go""when I type the command "operator-sdk new memcached-operator  --type=go"?

**Comment by feuyeux** [comment]
https://www.openshift.com/blog/operator-sdk-reaches-v1.0
