### ISSUE TITLE
metadata.name too long error

### ISSUE THREAD

**Issue by itdove** [operator-framework/operator-sdk#1764]
## Type of question

Reuse the helm-operator manager in another operator.

## Question

**What did you do?**
I have this kind of code:

```
	o := &unstructured.Unstructured{}
	o.SetGroupVersionKind(s.GroupVersionKind())
	o.SetNamespace(s.GetNamespace())
	o.SetName(releaseName)
	uuid, err := uuid.NewV4()
	if err != nil {
		glog.Error(err, "Failed to generate a UUID.")
		return nil, err
	}
	o.SetUID(types.UID(uuid.String()))
	mgr, err := manager.New(cfg, manager.Options{
		Namespace: s.GetNamespace(),
		//		MetricsBindAddress: fmt.Sprintf("%s:%d", metricsHost, metricsPort),
	})
	if err != nil {
		glog.Error(err, "Failed to create a new manager.")
		return nil, err
	}

	f := helmrelease.NewManagerFactory(mgr, chartDir)
	helmManager, err := f.NewManager(o)
```
Then once I have my helmManager I called Sync and InstallRelease.
and get the error:

**What did you expect to see?**
A deployment done...

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).
```
       	            	failed to install release: release nginx-ingress-a8ioz44hhfymono5wb5rrsn4f failed: CronJob.batch "nginx-ingress-a8ioz44hhfymono5wb5rrsn4f-delete-registrations" is invalid: metadata.name: Invalid value: "nginx-ingress-a8ioz44hhfymono5wb5rrsn4f-delete-registrations": must be no more than 52 characters
```

**Environment**
* operator-sdk version: v0.9.0

* Kubernetes version information:

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5+icp-ee", GitCommit:"eb4df6c6fb47f5b4fd1ed8bfbfe2d0ed5ea636e1", GitTreeState:"clean", BuildDate:"2019-05-08T02:18:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

**Additional context**
seems adding the UID makes the metadata.name too long for some CR generated by k8s during the deployment.
Why the uid is added. 
I read another #1094 but I don't think any of these proposition will solve the problem I encountered above.

**Comment by joelanford** [comment]
@itdove I think [the solution I suggested in #1094](https://github.com/operator-framework/operator-sdk/issues/1094#issuecomment-513374488) will solve the problem. It will:
1. Remove the UID from the release name, such that the default release name for new CRs will be the CR name
2. Allow the CR owner to choose a custom release name at CR creation time by setting an annotation

Can you elaborate on why you think that solution will not work?

The background on how we arrived at the current solution can be found here: https://github.com/operator-framework/helm-app-operator-kit/pull/57

As a workaround, you can try decreasing the length of your CR name. And if you control your helm chart, you can shorten the template for the name of the delete-registrations cronjob.

**Comment by itdove** [comment]
Hi, thanks for the prompt reply.

I think will not work for me because I don't have a real CR.... I'm calling directly the manager.Sync and manager.InstallRelease and I think in that case the webhook will not work (not sure).

Still wondering why we need a UID the usual helm-chart that we deploy using helm don't have a UID in there name. I understand we want to avoid collisions here but this should be managed by the release-name itself (metadata.name) and not by adding AFAIK a UID to avoid a collision.

**Comment by joelanford** [comment]
> I think will not work for me because I don't have a real CR.... I'm calling directly the manager.Sync and manager.InstallRelease and I think in that case the webhook will not work (not sure).

Ahh yes. So you're using the go libraries directly, not the helm-operator base image. Unfortunately, the current design of the go libraries is more of an internal implementation for the helm-operator base image. We're planning on making two big changes, more or less simultaneously:
1. Upgrade from Helm 2 to Helm 3 (which requires a stable Helm 3 release)
2. Re-design the helm-operator go libraries to be more consumable and customizable so that use cases like yours are possible. The approach that is discussed in #1094 will likely occur as part of this.

> Still wondering why we need a UID the usual helm-chart that we deploy using helm don't have a UID in there name. I understand we want to avoid collisions here but this should be managed by the release-name itself (metadata.name) and not by adding AFAIK a UID to avoid a collision.

Ultimately, the reason that the UID is included is to guarantee that there will be no conflict with an existing release name at CR creation time. Without the UID, the following scenario would be possible:
1. Run two helm operators, one watching CRD_A and another watching CRD_B, in the same namespace.
2. Create CR A called `default`
3. The operator watching CRD_A installs a release called `default`.
4. Create CR B called `default` (this is allowed since CR A and CR B have different GVKs)
5. The operator watching CRD_B attempts an upgrade of the CR A release because it finds an existing release called `default`.

I don't remember the details, but 5) either succeeds, overwriting the release for CR A, or it fails indefinitely. If the former, it would trigger a reconciliation in the helm operator watching CR A, which performs another upgrade back to release A, which would then trigger a reconciliation in the helm operator watching CR B, and that would go back and forth indefinitely.

Ideally, the user experience is that the CR B creation itself fails, much like a `helm install` would fail if the provided release name already exists. This is where the necessity for a validating webhook comes into play.

We haven't had the time to dig very deeply into Helm 3 and think about the API design for these changes, so it's hard to say right now how the release name defaulting and validation will work.

At the end of the day, the goal is to create a more flexible and user-friendly go API for the helm operator, which will very likely include a way to override the way that a release name is derived from a CR.

I'm going to close this and reference it from #1094, so we can keep all of the discussion about release naming in one place. Thanks for the issue report! This is good use case info that we'll make sure to account for.
