### ISSUE TITLE
[ansible] meta should include api_version

### ISSUE THREAD

**Issue by jmazzitelli** [operator-framework/operator-sdk#1771]
## Feature Request

I have an issue where I need to load in the CR in my ansible playbook (see issue #1770). I can do so thanks to the `meta.name` and `meta.namespace` (I just use `k8s_facts` and load in that named CR from the given namespace).

However, I have to hardcode the api_version because `meta` does not provide that. It would be nice to be given that api_version so it need not be hardcoded in the ansible playbook.

**Describe the solution you'd like**

In addition to `name` and `namespace` being in the `meta` dict, add a new one called `api_version`.

**Comment by jmazzitelli** [comment]
Note: after further research, it turns out I do not need to load the CR. So I actually don't need this, however, I think it could still be useful. The PR #1772 is still there if you want to merge - its simple.

**Comment by joelanford** [comment]
@fabianvf Thoughts on this? If we add API version, should we also add group and kind?

**Comment by fabianvf** [comment]
I think we decided not to add the `GVK` to the `meta` parameter passed in because we couldn't think of a use-case that required it, and we worried that it could encourage some bad practices (ie, switching your tasks based on the GVK rather than using the `watches.yaml` to handle that logic). I'd totally be happy to include them if there were a use-case that required it or it was proving to be a burden to users, but since the role/playbook should be pretty specific to a GVK anyway I don't have an issue with users hardcoding it.

**Comment by jmazzitelli** [comment]
I ended up not needing this because I found that "hidden-not-hidden" variable passed to the playbook (_<group>_<kind>) and that provided what I needed for my use-case. So feel free to close this if you think there isn't a need for it.

**Comment by joelanford** [comment]
Sounds good. Closing. We can re-open if a use case emerges for this.
