### ISSUE TITLE
Query on the design of operator sdk helm

### ISSUE THREAD

**Issue by SamhooXee** [operator-framework/operator-sdk#1774]
## Type of question

Query on the design of operator sdk helm.

## Question

In current operator sdk helm implementation, I can see function call in pkgs tiller/chartutil are used. It seems to me that to use helm client/local tiller server is a straightforward option, has this option been considered? 

**Environment**
* operator-sdk version:

  operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934

* Kubernetes version information:

  Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"archive", BuildDate:"2019-04-01T10:20:14Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

**Comment by joelanford** [comment]
@SamhooXee if I understand your question, you're asking why the helm operator doesn't just use an existing Tiller instance installed in the cluster?

If that's your question, there are a few of reasons:
1. Better security: Helm is moving away from a global tiller instance because of its security model (which basically gives all authorized users cluster-admin). The helm operator embeds tiller libraries and requires RBAC privileges only for the chart(s) it manages. Additionally, all user-facing permissions are handled via RBAC on the CRs that the operator is watching.
2. Fewer dependencies: With a tiller instance built into the operator, there is no prerequisite for users of helm-based operators to install the global tiller. In fact, cluster administrators, don't even need to know that the operator is based on Helm.
3. Customization: We add some customizations to make the operator experience better. For example, we override the tiller rendering engine so that the resources include an owner reference to the CR that defines the release. We also customize the storage backend to use Secrets instead of ConfigMaps and to store them in the same namespace as the CR to allow the same release names in different namespaces. Both of these changes are coming in Helm 3, but we were able to implement them using Helm 2 libraries.

If I misunderstood your question, I apologize. We can re-open and discuss more if that's the case!
