### ISSUE TITLE
helm-release not created but only resources are

### ISSUE THREAD

**Issue by itdove** [operator-framework/operator-sdk#1779]
## Type of question

General question:

I'm reusing the `github.com/operator-framework/operator-sdk/pkg/helm/release.NewManagerFactory` and the github.com/operator-framework/operator-sdk/pkg/helm/release.NewManager()` methods from the operator-sdk version`v0.9.1-0.20190724001845-d6e1aba9fa51`

## Question
I created a new manager by providing 
```
	f := helmrelease.NewManagerFactory(mgr, chartDir)
	helmManager, err := f.NewManager(o)
```
then I call the helmManager.Sync() and a helmManager.InstallRelease()

**What did you expect to see?**
I expect to see an helm release being created. `helm list`
**What did you see instead? Under which circumstances?**
All resources get created including the deployment and the application is running but no helm release is created.

**Environment**
* operator-sdk version: v0.9.1-0.20190724001845-d6e1aba9fa51

* Kubernetes version information:

  insert output of `kubectl version` here
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5+icp-ee", GitCommit:"eb4df6c6fb47f5b4fd1ed8bfbfe2d0ed5ea636e1", GitTreeState:"clean", BuildDate:"2019-05-08T02:18:32Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

Any idea? is the helmManager.InstallRelease() not enough to create the release?
When I look at the code, it seems that the `InstallRelease` loop on all resources and do a kind of `kubectl create` instead of an `helm install` with the whole chart. That's maybe the reason why the release doesn't appear.

Thx

**Comment by joelanford** [comment]
@itdove The helm-operator library makes use of Helm and is compatible with Helm charts, but you shouldn't expect to use the operator and the Helm CLI interchangeably.

Specifically, this isn't working for because the helm operator runs its own internal tiller, scoped to just the namespace and permissions it needs to manage its built-in chart(s). The Helm CLI commands that query the cluster require Helm's actual tiller to be installed and configured, which the helm operator doesn't use. In addition, the helm operator uses a Secret backend (Helm 2's default is ConfigMap) and stores the release secret in the same namespace as the CR (Helm 2 stores it in the namespace of the global tiller, IIRC).

**Comment by itdove** [comment]
Thank you for the clarification!
