### ISSUE TITLE
Generating CRDs got noticably slower in 0.9.0

### ISSUE THREAD

**Issue by buoto** [operator-framework/operator-sdk#1787]
## Type of question

**General context and help around the operator-sdk**

## Question

Is slowdown in `operator-sdk generate openapi` call after upgrading to v0.9.0 expected? Is it caused by some new features or a possible generator bug?

**What did you do?**
I created a new project with three empty apis (`AService`, `BService`, `CService`). Then I ran:
```
operator-sdk generate openapi
```

**What did you expect to see?**
Generation process that lasts 11 seconds.
```
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [app:[v1], ] 
2019/08/06 16:16:10 Code for OpenAPI definitions generated
INFO[0011] Created deploy/crds/app_v1_aservice_crd.yaml 
INFO[0011] Created deploy/crds/app_v1_bservice_crd.yaml 
INFO[0011] Created deploy/crds/app_v1_cservice_crd.yaml 
INFO[0011] Code-generation complete.    
```

**What did you see instead? Under which circumstances?**
Generation process that lasts 25 seconds (for 3 empty CRDs).
```
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [app:[v1], ] 
INFO[0014] Created deploy/crds/app_v1_aservice_crd.yaml 
INFO[0019] Created deploy/crds/app_v1_bservice_crd.yaml 
INFO[0025] Created deploy/crds/app_v1_cservice_crd.yaml 
INFO[0025] Code-generation complete.  
```

**Environment**
* operator-sdk version:

```
operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934
```

* go version:
```
go version go1.12.7 linux/amd64
```

* Are you writing your operator in ansible, helm, or go? **Go**

**Additional context**
I used simple example to make it easier to reproduce and it may not show the full scale of problem (11s -> 25s is not that much), however in my project time got increased from 1 minute to 6 minutes without any code change.

**Comment by joelanford** [comment]
@buoto Haven't had a chance to attempt to reproduce yet, but we switched from building and running the `openapi-gen` binary as a subprocess in 0.8.x to vendoring the code from `k8s.io/kube-openapi` and running it directly in the `operator-sdk` binary in 0.9.0 .

In 0.8.2, projects were scaffolded to use this as the `kube-openapi` dependency (for both `dep` and go module-based projects)
https://github.com/operator-framework/operator-sdk/blob/28bd2b0d4fd25aa68e15d928ae09d3c18c3b51da/internal/pkg/scaffold/gopkgtoml.go#L55-L57
https://github.com/operator-framework/operator-sdk/blob/28bd2b0d4fd25aa68e15d928ae09d3c18c3b51da/internal/pkg/scaffold/go_mod.go#L89

And in 0.9.0, we're using the same version:
https://github.com/operator-framework/operator-sdk/blob/560208dc998de497bbf59fea1b63426aec430934/go.mod#L123

We also made a few minor changes that I wouldn't expect to drastically change generation time since v0.9.0, so it might be worth a shot to rebuild from the latest `master` and see if you're still seeing the same runtime discrepancy.

**Comment by buoto** [comment]
Thanks for a quick response! I'm sorry I missed that `v0.8.2` is out and forgot to mention that the good working version was `v0.8.1`. After that, I tried both `master` and `v0.8.2` and they both seemed to work similarily slow for me.

Then I managed to bisect the history and I found that I have problems with this ee081f953dc1a80601c757f641e60b1afa733110 commit. It was merged in #1636.
Seems like the performance decrease was anticipated because of the cache removal, but I guess it hit me harder than expected.
 
Is there a possibility of that cache coming back in some less buggy way?
I can also try to help if there is no one to investigate it right now.

**Comment by joelanford** [comment]
/cc @estroz 

You probably know more about this than I do. Anything we or @buoto can do to improve this before we switch to controller-tools v0.2.0?

**Comment by estroz** [comment]
@buoto @joelanford there might be something we can do once v0.2.0 is merged. I'm hesitant to invest time now because that work will be obsolete once we bump controller-runtime versions (the CRD generation API changes significantly).

**Comment by RoeeShlomo** [comment]
`operator-sdk generate k8s` is also much slower than in 0.8.1. Is it the same issue?

**Comment by estroz** [comment]
@RoeeShlomo yes since v0.8.1 is a patch release and only contains bug fixes. I will be looking into caching to help speed up this process once [controller-runtime v0.2.0 stable](https://github.com/kubernetes-sigs/controller-runtime/releases/) is released.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

I believe that it is fixed in the 0.12 anyway. Am I right?

**Comment by estroz** [comment]
@camilamacedo86 this was not necessarily fixed, as I haven't had time to implement caching to speed up generation. @buoto @RoeeShlomo have you upgraded SDK versions, and if you have, do you still experience slow `generate` commands?

**Comment by estroz** [comment]
@buoto the CRD generator should be fairly quick with changes from #2201. If generation is still slow, feel free to re-open this issue.
