### ISSUE TITLE
Suggestion: Use ASCII doc format instead of MD

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#1796]
## Feature Request

So, I'd like to suggest we use https://asciidoctor.org/ which is the format defined by a doc team from another RedHat projects/dep since it brings facilities as: 
-  ASCII doc makes easier we re-use the content to generate the upstream and downstream documentations. 
- Generates automatic indexes. See here: https://github.com/aerogear/mobile-security-service-operator#mobile-security-service-operator
- Allow we use the content to generate webpages. See https://gist.github.com/briandominick/e5754cc8438dd9503d936ef65fffbb2d and a RedHat example  https://www.aerogear.org/ done by re-using the contents in this format. 
- Allow us to define a default style for all in an easy way. We just need to add the following for example in the top.

```
ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
:namespace: mobile-security-service
endif::[]

:toc:
:toc-placement!:
```
- When we use the tags NOTE, WARNING, and etc it formats the content automatically to present it in a pretty way.  

Following some references:

- http://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/
- https://asciidoctor.org/docs/asciidoc-vs-markdown/
- https://asciidoctor.org/docs/convert-documents/

**Comment by hasbro17** [comment]
This might be a useful change. The table of contents links being generated for each document would be a welcome addition.
But since I'm not too familiar with asciidocs I think we probably need to discuss this a bit more.

There's not a whole lot in the comparisons between markdown vs asciidoc that suggests a pressing need to move to asciidoc for our current docs in the SDK. There's nothing too complicated that we're doing at the moment.
https://asciidoctor.org/docs/asciidoc-vs-markdown/#comparison-by-example
I might need to read up more asciidoc more though.

And for docs that require more elaborate organization we might want to consider using something like [gitbook](https://docs.gitbook.com/) in the future. Which doesn't seem to support asciidocs anymore it seems.
https://docs.gitbook.com/v2-changes/important-differences#asciidoc-support

**Comment by camilamacedo86** [comment]
Hi @hasbro17,

Thank you for your reply. I just raise it because we do not have the downstream docs for it yet and shows that we will have a 1.0.0 soon then in POV it shows the perfect moment for we think about it and check the pros/cons and see how the other teams are doing. 

However, based on this https://docs.gitbook.com/v2-changes/important-differences#asciidoc-support that you point out. I think it is a big final NO GO with this idea/suggestion and probably the advantages of ASCII doc will be incorporated add to MD. 

So I am closing this one. Tks.
