### ISSUE TITLE
generate: subcommands should only require `pkg/apis` exist, not full project

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#1804]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I want to run `operator-sdk generate` subcommands on `pkg/apis` on a project without `cmd/manager/main.go` or `build/Dockerfile`. Neither of these are required to generate code for my APIs in any case.

**Describe the solution you'd like**
Remove project structure checks, and instead ensure `pkg/apis` exists instead, which should only exist in Go projects.

/cc @joelanford @hasbro17 @theishshah @fabianvf @jmrodri

**Comment by camilamacedo86** [comment]
Hi @estroz, 

The Dockerfile has been used in the following check and it is used in many places. Do you know what file and/or dir which is common in all types for we replace this check? 

https://github.com/operator-framework/operator-sdk/blob/757f7a0b9d12cacf407cb12c30b89374206f1ff2/internal/util/projutil/project_util.go#L108

**Comment by camilamacedo86** [comment]
HI @estroz, 

As described in the comment https://github.com/operator-framework/operator-sdk/pull/2054#issuecomment-542262737 was decided not to move forward with this request. The reason for that is because we are looking to give more flexibility to our users. Then, for customizations like this one, we would like to suggest the usage of [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen) directly by a Makefile. Following an example of a Makefile, targets to generate/update the CRD's in the SDK structure. 

```makefile
# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
CRD_OPTIONS ?= "crd:trivialVersions=true"

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# Generate manifests e.g. CRD, RBAC etc.
manifests: controller-gen
	$(CONTROLLER_GEN) paths=./... crd:trivialVersions=true output:crd:artifacts:config=deploy/crds

# find or download controller-gen
# download controller-gen if necessary
controller-gen:
ifeq (, $(shell which controller-gen))
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
CONTROLLER_GEN=$(GOBIN)/controller-gen
else
CONTROLLER_GEN=$(shell which controller-gen)
endif
```
Then, when the command `make manifests` be called the CRD's in the path `deploy/crds` will be created/updated. 

For further information about how to use the controller-gen options/commands see its [docs]
(https://book.kubebuilder.io/reference/controller-gen.html).
