### ISSUE TITLE
How to access k8s object from local environment

### ISSUE THREAD

**Issue by ffoysal** [operator-framework/operator-sdk#1827]
## Type of question

**how to implement a specific feature**

## Question

**What did you do?**
I was following this guide https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#2-run-locally-outside-the-cluster

In reconcile function I was trying to get a secret from default namespace
```
	config, err := rest.InClusterConfig()
	if err != nil {
		panic(err.Error())
	}
	v1, err := clientv1.NewForConfig(config)

	v1.Secrets("default")
	scr, err := si.Get("mysecret", metav1.GetOptions{})
	fmt.Println("cant read secret, ", err)
	fmt.Println("dont' know", scr.String())
```

**What did you expect to see?**

was expecting to see the secret string

**What did you see instead? Under which circumstances?**

at first it was complaining about `KUBERNETES_SERVICE_PORT` and `KUBERNETES_SERVICE_HOST` not set. after doing `export KUBERNETES_SERVICE_PORT=443` and `KUBERNETES_SERVICE_HOST=kubernetes.default.svc.cluster.local` it was say this 
`panic: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory`

**Environment**
* operator-sdk version:

operator-sdk version: v0.9.0, commit: 560208dc998de497bbf59fea1b63426aec430934

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
minikube
**Additional context**
Add any other context about the question here.

**Comment by joelanford** [comment]
@ffoysal You shouldn't need to create a new client to use in your `Reconcile` function. The reason your code isn't working is because you're trying to use the in-cluster client setup function, which will only work when your operator is running in cluster.

Instead, you should be able to use the one that's a member of the reconciler struct that the SDK scaffolds when you create a new controller.

The example reconciler shows how you would get a pod, and the same process should work for getting a secret (just change `corev1.Pod` to `corev1.Secret` and `NamespacedName`  to reference the secret's name and namespace as necessary):

https://github.com/operator-framework/operator-sdk/blob/4ca881a92eb71b19d4689065ae9bf4dcf9b43331/internal/pkg/scaffold/controller_kind.go#L239-L241

**Comment by ffoysal** [comment]
it works. thank you @joelanford
