### ISSUE TITLE
Change imagePullPolicy to speed up the development lifecycle

### ISSUE THREAD

**Issue by matyix** [operator-framework/operator-sdk#186]
The **operator-sdk** build regenerates `operator.yaml` with `imagePullPolicy: Always`
During development phase of an operator the `imagePullPolicy: Always` requires developers to push the image to a Docker repo before being able to test the changes. 

This extra step could be avoided if the **operator-sdk** build generated `operator.yaml` with `imagePullPolicy: IfNotPresent` as in that case the image that is already on the developer's machine will be used.

**Comment by freddy-perez** [comment]
I've not experience the caching problem with `IfNotPresent` policy. I do use the minikube's docker daemon, e.g. `eval $(minikube docker-env)`, to store local built cached images.

**Comment by fanminshi** [comment]
@matyix  We have added `operator-sdk up local` command to speed up local development process:

```sh
$ operator-sdk up local -h
The operator-sdk up local command launches the operator on the local machine
by building the operator binary with the ability to access a
kubernetes cluster using a kubeconfig file.

Usage:
  operator-sdk up local [flags]

Flags:
  -h, --help                    help for local
      --kubeconfig string       The file path to kubernetes configuration file; defaults to $HOME/.kube/config
      --namespace string        The namespace where the operator watches for changes. (default "default")
      --operator-flags string   The flags that the operator needs. Example: "--flag1 value1 --flag2=value2"
```

See [usage](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#2-run-outside-the-cluster) for more detail.

I don't think we no longer need to modify `imagePullPolicy: Always` to speed up the development process. The `imagePullPolicy: Always` in the `operator.yaml` is important for production usage because we want the Kubernetes to always pull for the latest image.

**Comment by matyix** [comment]
Awesome, thanks @fanminshi. I agree and close the issue now. Thanks for the resolution.

**Comment by meschbach** [comment]
For anyone else who travels down this line `operator-sdk up local` has been removed.  Still searching for a method to set `imagePullPolicy: Always` when building && testing on my local device.
