### ISSUE TITLE
How to choose value for MaxConcurrentReconciles?

### ISSUE THREAD

**Issue by gpanagiotidis** [operator-framework/operator-sdk#1938]
How to estimate the best number of MaxConcurrentReconciles someone should use for his deployment? For example, if there are 1000 CRs that need to be created, using the default value, which is 1, would take a lot of time to process. Do more workers demand more memory, or what is the tradeoff of using more workers (high setting in MaxConcurrentReconciles)?

**Comment by camilamacedo86** [comment]
HI @gpanagiotidis, 

Following my understanding over it. 

If you check the SDK doc [here](https://github.com/operator-framework/operator-sdk/blob/05a106abd9ff94bb2f0cc84b5054d0a603c9474f/doc/user-guide.md#controller-configurations) you will see that the Options Struct where this attribute `MaxConcurrentReconciles` is defined are implementations from the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). By default, it will have just 1 worker as you can check in its implementation [here](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L32) which will avoid concurrency issues in the API as for example may it face errors because more than one process is trying to update the same object on it.

So, when the MaxConcurrentReconciles has increased the value of goroutines to run the reconcile will be increased proportionally. E.g 1000 will create 1000 goroutines to exec the reconcile. 

> They're called goroutines because the existing terms—threads, coroutines, processes, and so on—convey inaccurate connotations. A goroutine has a simple model: it is a function executing concurrently with other goroutines in the same address space. It is lightweight, costing little more than the allocation of stack space. And the stacks start small, so they are cheap, and grow by allocating (and freeing) heap storage as required

Ref.: https://golang.org/doc/effective_go.html#concurrency

**NOTE:** For an easier understanding, each goroutine is like a cheap thread and at the end, it will be like we are executing a shell command to each goroutine created to do the reconcile in parallel. 

Regards your questions:

> How to estimate the best number of MaxConcurrentReconciles someone should use for his deployment?

You would need to create metrics and do stress tests to do the measures based on the infrastructure which will be used.  See [Monitoring](https://book-v1.book.kubebuilder.io/beyond_basics/controller_metrics.html) to know how to do that. May you can use [Prometheus](https://prometheus.io) to check it too and see that by default the scaffold projects created by the operator-sdk are creating a MonitorService for Prometheus already. If you are using OCP I'd suggest checking its doc about [Cluster Monitoring](https://docs.openshift.com/container-platform/4.1/monitoring/cluster-monitoring/about-cluster-monitoring.html) as well. 

> Do more workers demand more memory, or what is the tradeoff of using more workers (high setting in MaxConcurrentReconciles)? 

How much more works more goroutines you will have working so it will be up to the infrastructure and how much resources are available, how it is implemented and etc. Definitely it would increase CPU usage and besides, the goroutines share the memory between them I'd recommend you monitoring it as well since more objects can be going and/or mainly kept on the memory. Also, is very important to ensure that your solution has no leak of memory. 

Also, I'd recommend you check too previous threads/issues open over this subject here https://github.com/operator-framework/operator-sdk/search?q=MaxConcurrentReconciles&type=Issues to gathering more info.

@joelanford, @hasbro17 and @shawn-hurley, please let me know if my understanding over it is not accurate and please feel free to supplement it with any info that you wish.

**Comment by camilamacedo86** [comment]
I am closing this since shows that the info requested was provided. Please, feel free to re-open if you believe that something here still required.
