### ISSUE TITLE
Add watch bookmarks support 

### ISSUE THREAD

**Issue by kvaps** [operator-framework/operator-sdk#1939]
## Feature Request

The “bookmark“ watch event is used as a checkpoint, indicating that all objects up to a given resourceVersion requested by the client have already been sent. The API can skip sending all these events, avoiding unnecessary processing on both sides. 

This feature was alpha in 1.15, and now it is going beta in 1.16. More info:

https://sysdig.com/blog/whats-new-kubernetes-1-15/#956

**Comment by camilamacedo86** [comment]
Hi @kvaps,

Tks for raising it.

**Comment by mhrivnak** [comment]
AIUI, bookmarks are only useful when using a label selector on a watch. It's a way for the API service to tell you: "a whole bunch of events happened; you didn't see them because they don't match your selector, but just trust me, the current resource version is now X".

Only if the SDK starts supporting watches with selectors would this become useful. Even at that, I suspect it would be an implementation detail in the reflector.

Is there something you have in mind for the SDK to do more directly with bookmarks?

https://kubernetes.io/docs/reference/using-api/api-concepts/#watch-bookmarks
