### ISSUE TITLE
Go get fails operator-sdk because of thrift

### ISSUE THREAD

**Issue by bipuladh** [operator-framework/operator-sdk#1958]
I am trying to follow instructions: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md
However it fails:
```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/badhikar/go/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
	fatal: unable to access 'https://git.apache.org/thrift.git/': Failed to connect to git.apache.org port 443: Connection timed out
```

**Comment by camilamacedo86** [comment]
Thank you for raising it. 

To solve it you can add the proxy, and/or use the master branch and the command 'make tidy' which will use the proxy and your replicate the dep as `replace git.apache.org/thrift.git => github.com/apache/thrift v0.12.0`. For more info see here: https://github.com/operator-framework/operator-sdk/issues/1873

Since it is duplicated we are closing this one. But please, feel free to re-open if you wish.
