### ISSUE TITLE
Support CRI-O

### ISSUE THREAD

**Issue by hupiper** [operator-framework/operator-sdk#1964]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I've moved to CRI-O, but you are requiring Docker. 

**Describe the solution you'd like**
I think you should support CRI-O too.

**Comment by camilamacedo86** [comment]
Hi @hupiper, 

Could you please add here the error faced?

**Comment by camilamacedo86** [comment]
It shows be related to : https://github.com/operator-framework/operator-sdk/issues/1686

**Comment by hupiper** [comment]
The problem is that you need Docker installed. If I generate a new tree for Ansible and run the build command:
`[mdunnett@mdunnett image-uploader-operator]$ operator-sdk build image-upload-operator:v.1
INFO[0000] Building OCI image image-upload-operator:v.1 
Error: failed to output build image image-upload-operator:v.1: (failed to exec []string{"docker", "build", "-f", "build/Dockerfile", "-t", "image-upload-operator:v.1", "."}: exec: "docker": executable file not found in $PATH)`

If I run the build command pointing at Podman:
`[mdunnett@mdunnett image-uploader-operator]$ operator-sdk build image-upload-operator:v.1 --image-builder podman
INFO[0000] Building OCI image image-upload-operator:v.1 
ERRO[0000] No subuid ranges found for user "mdunnett" in /etc/subuid 
Error: failed to output build image image-upload-operator:v.1: (failed to exec []string{"podman", "build", "-f", "build/Dockerfile", "-t", "image-upload-operator:v.1", "."}: exit status 1)`

If I put mdunnett in subuid: `sudo usermod --add-subuids 10000-65536 mdunnett`

I get `[mdunnett@mdunnett image-uploader-operator]$ operator-sdk build image-upload-operator:v.1 --image-builder podman
INFO[0000] Building OCI image image-upload-operator:v.1 
ERRO[0000] No subgid ranges found for group "mdunnett" in /etc/subgid 
Error: failed to output build image image-upload-operator:v.1: (failed to exec []string{"podman", "build", "-f", "build/Dockerfile", "-t", "image-upload-operator:v.1", "."}: exit status 1)`

It just doesn't seem to work

**Comment by hupiper** [comment]
This is on RHEL8

**Comment by jmrodri** [comment]
@hupiper for a short term have you considered installing `podman-docker`? That would be a short term fix as well.

**Comment by hupiper** [comment]
Once I got the permissions figured out that I mentioned above, I started getting errors for XFS as an overlay being  unsupported. It turns out Podman was not happy when I installed container-tools. I had to delete the storage.conf file for podman, then reinstall it - see  [http://chris.collins.is/2019/01/25/podman-overlay-is-not-supported-over-xfs/](url). My storage.conf file was in a different place than the location mentioned in the Chris Collins blog. Mine was in /home/<user>/.config/containers/storage.conf

**Comment by camilamacedo86** [comment]
Thank for share @hupiper.

**Comment by camilamacedo86** [comment]
Hi @hupiper, 

The https://github.com/operator-framework/operator-sdk/pull/1966  will make the subcommands no longer requires the Dockerfile so I think that it has big chances to be enough to address it. Could you help us and check it with CRI-O as well?

So far is supported docker and podman v1.2.0+ or buildah v1.7+.

**Comment by camilamacedo86** [comment]
HI @hupiper, 

I'd like to share with you that regards, the supportability of CRI-O it is 100% supported by SDK projects already, however, you would need to add its files and customize its generation by using the Makefile as described below.

In order to make it simple, I'd recommend you keep the Dockerfile which is created by default for you be able to still use all SDK current commands and just customize via the build dir and a Makefile the generation of his type. 

Note that if you would like to remove the Dockerfile from the project then it means that the SDK commands which requires this file will no longer work. Also, many commands are checked its existence to ensure the root dir of the project. However,  you would be able to customize the commands by using the [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen) directly by via targets in a Makefile as well. Following an example of a Makefile with targets to generate/update the CRD's in the SDK structure.

```makefile
# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
CRD_OPTIONS ?= "crd:trivialVersions=true"

# Get the currently used golang install path (in GOPATH/bin, unless GOBIN is set)
ifeq (,$(shell go env GOBIN))
GOBIN=$(shell go env GOPATH)/bin
else
GOBIN=$(shell go env GOBIN)
endif

# Generate manifests e.g. CRD, RBAC etc.
manifests: controller-gen
	$(CONTROLLER_GEN) paths=./... crd:trivialVersions=true output:crd:artifacts:config=deploy/crds

# find or download controller-gen
# download controller-gen if necessary
controller-gen:
ifeq (, $(shell which controller-gen))
	go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.0
CONTROLLER_GEN=$(GOBIN)/controller-gen
else
CONTROLLER_GEN=$(shell which controller-gen)
endif
```
Then, when the command `make manifests` be called the CRD's in the path `deploy/crds` will be created/updated. Also, for further information about how to use the controller-gen as its options/commands see its [docs]
(https://book.kubebuilder.io/reference/controller-gen.html).

See that, as described in the comment https://github.com/operator-framework/operator-sdk/pull/2054#issuecomment-542262737 was decided not to move forward with this type of request. The reason for that is because we are looking for changes in the design to give more flexibility to our users.

In this way, we are closing this issue. However, please feel free to re-open if you think that it is required.

**Comment by joelanford** [comment]
Also, here's some background that may help explain our thought process here: https://github.com/operator-framework/operator-sdk/pull/1600#issuecomment-506730405

**Comment by hupiper** [comment]
Thank-you!
