### ISSUE TITLE
Allow a subset of endpoints to be used for ServiceMonitor creation

### ISSUE THREAD

**Issue by alourie** [operator-framework/operator-sdk#1972]
Currently, CreateServiceMonitors will use all the endpoints from the provided service to add them to the ServiceMonitor it creates. If I have a service that exposes few different service ports, all of them will be added to the resulting ServiceMonitor; while not completely disastrous, this would lead to horrible user experience, as seeing "failing" targets in Prometheus dashboard would not be the best possible scenario.

Currently this requires creating a separate service just for the specific subset of the endpoints, which I previously might have already exposed.

I propose allowing to select (by port name) only a subset of endpoints to include in the resulting ServiceMonitor.

**Comment by alourie** [comment]
I can implement this in several ways, but not sure what the right approach would be.

One way would be to change the current interface and supply additional parameters to the `CreateServiceMonitors` and `GenerateServiceMonitor` calls. This would be the simplest change but would break everyone's code on the client side.

Another way would be to create a set of separate function calls, such as `CreateFilteredServiceMonitors` that would have the additional parameter, and allow filtering accordingly.

I would love for some guidance for preferred ways to solve this.

**Comment by camilamacedo86** [comment]
Hi @alourie, 

Have you check it in the sample [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/cmd/manager/main.go#L122)? Could you please let me know if it answers your question and it is what you are looking for.

**Comment by alourie** [comment]
@camilamacedo86 no, that's not what I was looking for. This example shows how to construct a service with a set of endpoints and provide it to the `CreateServiceMonitors`. But I already have a way to construct services in my code.

What I meant is that I already have a service that is exposing the required metrics endpoint (port). I really don't want to split it into 2 services, where one service doesn't expose the metrics endpoint and the other one does. So for instance, if I have a web service that exposes 8080 as its own web port and 7900 as the metrics port, I just want to create it once, and then run something like `CreateServiceMonitor(....myservice, []string{metricsPort}...)`, so that the resulting ServiceMonitor only includes a specific endpoint(s) by picking from the service and filtering using the provided list.

This way I would be able to create the service once, and have the ServiceMonitor constructed so that it only includes relevant (i.e. metrics) endpoints.

**Comment by camilamacedo86** [comment]
Hi @alourie,

So, following my understanding about what you are looking for here. Please, let me know if it is correct. 

A Feature Request as follows:

**Is your feature request related to a problem? Please describe.**

Yes, when I use [CreateServiceMonitors](https://github.com/operator-framework/operator-sdk/blob/f5d20c4819b98a60ec782a9a5cac784b55ea2951/pkg/metrics/service-monitor.go#L33) bypassing preexistence services it will create endpoints for all ports expose and not just that oe which are specific for the metrics.  Because of this, I have been seen failing" targets in Prometheus dashboard for the endpoints created based on the ports that are exposed in the service but should not be used for the metrics.

**Describe the solution you'd like**

Create a new func as for example `CreateServiceMonitorBySpecificPorts([]*v1.Service, []string{metricsPort}...)` which will work as [CreateServiceMonitors](https://github.com/operator-framework/operator-sdk/blob/f5d20c4819b98a60ec782a9a5cac784b55ea2951/pkg/metrics/service-monitor.go#L33) but allows pass the list of ports as well. 

Then the [populateEndpointsFromServicePorts](https://github.com/operator-framework/operator-sdk/blob/f5d20c4819b98a60ec782a9a5cac784b55ea2951/pkg/metrics/service-monitor.go#L68) should just create endpoints for the ports which are exposed and contains in the []string{metricsPort} instead use all exposed ports as it is done [here](https://github.com/operator-framework/operator-sdk/blob/f5d20c4819b98a60ec782a9a5cac784b55ea2951/pkg/metrics/service-monitor.go#L98)

**Comment by alourie** [comment]
@camilamacedo86 perfect! That's exactly what I wanted. I will use the examples you've provided for the function names and will open PR soon with suggested changes.

Thank you!

**Comment by camilamacedo86** [comment]
If you find better names please feel free to use them. I am very glad that I could help with and will be very cool to receive your PR as contribution with as well.

**Comment by alourie** [comment]
@camilamacedo86 I've opened a PR at #1991, please let me know if it goes in the right direction. Thanks!

**Comment by camilamacedo86** [comment]
Hi  folks, 

We have 2 prs related to it. This one is to allow pass valid ports in order to ignore others which may expose in the pre-existence service.

And this PR  https://github.com/operator-framework/operator-sdk/pull/1963 shows be to allow specify labels.

Since both are related to the same feature I flag them as need help and discussion for you are able to check if we can move in this way or not. 

@joelanford, @estroz @jmccormick2001 @hasbro17 @jmrodri
