### ISSUE TITLE
Enable owner reference annotations for existing dependents

### ISSUE THREAD

**Issue by rammohanc** [operator-framework/operator-sdk#1977]
## Feature Request

**Is your feature request related to a problem? Please describe.**
With Ansible operator, after enabling inject_owner_reference and watchDependentResources only new objects created from CR have the owner reference annotations and not the existing ones. Any modifications to the objects created before enabling above flags will not trigger reconciliation. 

**Describe the solution you'd like**
when inject_owner_reference and watchDependentResources flags are turned on. all dependent objects created from the CRs both existing and new, should have owner reference annotations .

**Comment by camilamacedo86** [comment]
Hi @rammohanc, 

Could you please share the steps that you are performing in the order we are able to reproduce this scenario?

**Comment by fabianvf** [comment]
This one is a little tricky technically, the ownerRef injection is happening in the proxy whenever it receives a CREATE event, but if the resources already exist a CREATE won't be issued (only a PATCH or UPDATE), and the proxy won't really have any idea whether or not it's looking at a resource it should own. The operator only knows that it owns a resource because of the ownerReference/annotation, there's no tracking of it outside of that.

For now we should at the very least least document that enabling those features on an existing operator will require some manual migration (ie, you'll need to add the ownerreferences by hand).

This should only be a one-time migration so perhaps that's not too burdensome, would providing documentation and instructions for the migration be sufficient?
