### ISSUE TITLE
Add operator-sdk support to aarch64 architecture

### ISSUE THREAD

**Issue by ssbano** [operator-framework/operator-sdk#1996]
## Feature Request

Add operator-sdk support to aarch64 architecture

**Comment by hasbro17** [comment]
@ssbano Do you mean supporting `arm64` binaries?

Just a heads up that this is not on our immediate roadmap.
https://github.com/operator-framework/operator-sdk/blob/master/doc/dev/release.md#operating-systems-and-architectures

Community PRs are always welcome though. 
You will need to add `arm64` support for the SDK binary and the Helm/Ansible base images similar to how it was added for `ppc64le` https://github.com/operator-framework/operator-sdk/pull/1533

Although I should point out that even `ppc64le` isn't complete since the ansible-operator base images aren't multi arch yet.

**Comment by ssbano** [comment]
@hasbro17 

Yeah... arm64v7|8/aarch64 

I can create the build to (SDK/ansible) engine

Best Regards,
Fabio Sbano

**Comment by fr34k8** [comment]
no progress here ? @ssbano @hasbro17

**Comment by estroz** [comment]
@ssbano @fr34k8 this isn't necessarily a high priority issue, but we'd welcome a PR. See the reference PR in the comment above: https://github.com/operator-framework/operator-sdk/issues/1996#issuecomment-536783478.

**Comment by estroz** [comment]
@ssbano @fr34k8 we recently added arm64 support: #2742

**Comment by geerlingguy** [comment]
I'm assuming standard arm/armv7 is not on the roadmap, though? I just thought about using some of my operators built with Ansible to a Pi cluster... and realized that I can't get any of them to start because of:

```
root@turing-master:/home/pirate# kubectl logs drupal-operator-7f4b5dcdcb-xb5s6 -c ansible
standard_init_linux.go:211: exec user process caused "exec format error"
root@turing-master:/home/pirate# kubectl logs drupal-operator-7f4b5dcdcb-xb5s6 -c operator
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by agaffney** [comment]
@geerlingguy That `exec format error` message is probably due to #3233. I noted a workaround in that issue.
