### ISSUE TITLE
Ansible Operator Failure Backoff

### ISSUE THREAD

**Issue by cajundave** [operator-framework/operator-sdk#1999]
## Type of question

General Support Question for Ansible Operator

## Question

Is there a way to configure the backoff time period for an ansible operator on a failure?

**What did you do?**
Sometimes, we will see failures in the custom resources we request, especially when developing, testing, and qa'ing.

**What did you expect to see?**
We expected the operator for these custom resources to see a changed/edited spec, and issue the appropriate changes in a relatively short period of time.

**What did you see instead? Under which circumstances?**
After one failure, the ansible operator seems to back off, and we are not seeing it attempt to re-run on the project with the failure.

This seems to happen with operator-sdk v0.9.0 and v0.10.0.  We are using minishift minishift v1.34.1, but have witnessed this in our openshift cluster master v3.11.0, kube master: v1.11.0

**Comment by jmccormick2001** [comment]
Hi, curious if you tried setting reconcilePeriod (an optional setting)?   This is defined as the reconciliation interval, how often the role/playbook is run, for a given CR.

**Comment by cajundave** [comment]
We had not set this.  It was our understanding that the default was 1 minute, and this seems to be how often it continues to check those that do not experience a failure.  Does reconcilePeriod also work for failures?

**Comment by camilamacedo86** [comment]
Hi @cajundave, 

In order to trigger the reconcile when the resources used by it was changed, then you can use `watchDependentResources` is set as true. If you would like to trigger the reconcile after X period always then you can use `reconcilePeriod`. 
 
I understand that the above information provided answered your question then because of this I am closing this one. However, please feel free to re-open if you feel that is required.
