### ISSUE TITLE
Failed to get proxyPod issue when running scorecard on the lightbend-console-operator deployed with OLM

### ISSUE THREAD

**Issue by dirgim** [operator-framework/operator-sdk#2000]
## Bug Report

**What did you do?**

Running the following command on the operator metadata for the `lightbend-console-operator` and `prometheus` community operators in [this pull requests](https://github.com/operator-framework/community-operators/pull/717) and [this pull request](https://github.com/operator-framework/community-operators/pull/667):
```
operator-sdk scorecard --olm-deployed --csv-path /tmp/operator-test/operator-files/0.0.1/lightbend-console-operator.v0.0.1.clusterserviceversion.yaml --namespace test-operator --proxy-image quay.io/operator-framework/scorecard-proxy:master --crds-dir /tmp/operator-test/operator-files/0.0.1 --init-timeout 60
```

**What did you expect to see?**
Standard human-readable output of the scorecard command with graded basic and olm tests.

**What did you see instead? Under which circumstances?**
The error output we got was this:
```
time="2019-09-30T20:39:24+02:00" level=warning msg="Could not load config file; using flags"
time="2019-09-30T20:39:24+02:00" level=warning msg="Plugin directory not found; skipping external plugins: stat scorecard: no such file or directory"
time="2019-09-30T20:40:24+02:00" level=error msg="Plugin `basic-tests` failed with error (failed to get proxyPod: timed out waiting for the condition)"
time="2019-09-30T20:41:24+02:00" level=error msg="Plugin `olm-tests` failed with error (failed to get proxyPod: timed out waiting for the condition)"
Failed Plugin: basic-tests:
Failed Plugin: olm-tests:

Total Score: 0%
```
Trying to manually run the operator-sdk binary built from the version `"v0.10.0-64-gff284ea0", commit: "ff284ea01e7ecc5cea0f9b69a6cc6d9083e84b02` returned this output:
```
{
  "metadata": {
    "creationTimestamp": null
  },
  "log": "time=\"2019-10-01T17:15:45+02:00\" level=info msg=\"Using config file: /tmp/scorecard.yml\"\ntime=\"2019-10-01T17:15:45+02:00\" level=error msg=\"Plugin `Basic Tests` failed with error (unrecognized install strategy)\"\ntime=\"2019-10-01T17:16:45+02:00\" level=error msg=\"Plugin `OLM Integration` failed with error (failed to get proxyPod: timed out waiting for the condition)\"\n",
  "results": [
    {
      "name": "Basic Tests",
      "description": "",
      "error": 1,
      "pass": 0,
      "partialPass": 0,
      "fail": 0,
      "totalTests": 0,
      "totalScorePercent": 0,
      "tests": null,
      "log": "unrecognized install strategy:\nLogs: "
    },
    {
      "name": "OLM Integration",
      "description": "",
      "error": 1,
      "pass": 0,
      "partialPass": 0,
      "fail": 0,
      "totalTests": 0,
      "totalScorePercent": 0,
      "tests": null,
      "log": "failed to get proxyPod: timed out waiting for the condition:\nLogs: "
    }
  ]
}
```

**Environment**
* operator-sdk version:
v0.10.0

* go version:
go version go1.12.9 linux/amd64

* Kubernetes version information:
oc v4.1.16

* Kubernetes cluster kind: 
OCP 4.1.16

**Additional context**
Scorecard command was run as part of the CVP operator pipeline and replicated locally using a testing OCP 4.1.16 cluster provisioned with AWS.

**Comment by camilamacedo86** [comment]
Hi @dirgim 

Your project is falling in the minimal criteria " The operator failed the minimal scorecard criteria of passing the 'Spec Block Exists' and 'Status Block Exists' basic tests."

We are working on to improve the scorecard in order to show better outputs. 

Your CSV is missing the CRD's fields. See [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/deploy/olm-catalog/postgresql-operator/0.1.1/postgresql-operator.v0.1.1.clusterserviceversion.yaml#L73) in this example of CSV which pass in all tests.

Unfortunately, operator-sdk is not generating yet all mandatory fields based on your CRD's. However, in order to help with you may be able to use the PR https://github.com/operator-framework/operator-sdk/pull/1162 to auto-generated the spec Descriptor and etc ... Or do it manually. 

The above example shared with you was done using this PR. Also, see in this example that for the feature implemented in the PR be able to generate the CSV with this specs you need add the annotations as it is done [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/apis/postgresql/v1alpha1/backup_types.go#L21).
