### ISSUE TITLE
function to provide Kubernetes version and vendor information.

### ISSUE THREAD

**Issue by aaronmcohen** [operator-framework/operator-sdk#2001]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Depending on the vendor or version of k8s an application may want to be deployed differently. For instance "k8s PSP versus Openshift SCCs" or workarounds for version specific behavior. 

**Describe the solution you'd like**
Ideally a function that returns the k8s version, the vendor (eg. Redhat, Azure, etc..), and the vendor version (3.11, 4.2, etc...).

**Comment by fabianvf** [comment]
I think generally it's recommended to look at API availability directly, rather than checking vendor/version to determine which APIs to use, though vendor/version-specific workarounds are another story. k8s version at least shouldn't be hard to report, though vendor/vendor version might not be as generically surface-able.

**Comment by camilamacedo86** [comment]
Hi @aaronmcohen, 

Thank you for raise this request.  Note that the PR https://github.com/operator-framework/operator-sdk/pull/2327 was created to add the print of the Cluster Version. You can follow up it.

However, see that is not recommended to develop solutions based on the vendor. 

**Why**

Let's think about the scenario where we have an Operator that will take further actions only if the [OLM](https://github.com/operator-framework/operator-lifecycle-manager) is installed in the cluster. Then, couldn't we check if the cluster is an OpenShift platform since the [OLM](https://github.com/operator-framework/operator-lifecycle-manager) is provided on it by default? 

No, we cannot. Observe that besides [OLM](https://github.com/operator-framework/operator-lifecycle-manager) be installed and available in OpenShift 4.X via the default installation, it also might not always be true. 

**What would be the best approach then?**

The best approach is to handle this kind of scenario by always checking the exact API resource which is required for the solution instead of using some resource to make the assumption that the Operator is running or not in some specific Kubernetes platform. 

**Examples**

- In the above example, where we were looking for to check if the [OLM](https://github.com/operator-framework/operator-lifecycle-manager) was installed or not; we should verify if the [OLM](https://github.com/operator-framework/operator-lifecycle-manager)'s Custom Resources Definitions (API Resource) which are essential to the solution, are present or not. 

- If we are looking forward to create a [Route](https://docs.openshift.com/container-platform/4.2/networking/routes/route-configuration.html) resource when the project is running in the OpenShift and an [Ingress](https://kubernetes.io/docs/concepts/services-networking/ingress) instead of, for example, just only if it is running in the Minikube, then we should be trying to check if the specific [v1.Route](https://docs.okd.io/latest/rest_api/apis-route.openshift.io/v1.Route.html) is installed or not.

**How to implement it?**

**Step 1: Creating the `discoveryClient`**

First, let's create the `discoveryClient`. 

```
    // Get a config to talk to the apiserver
    cfg, err := config.GetConfig()
    if err != nil {
        log.Error(err, "")
        os.Exit(1)
    }
    
    // Create the discoveryClient
    discoveryClient, err := discovery.NewDiscoveryClientForConfig(cfg)
    if err != nil {
        log.Error(err, "Unable to create discovery client")
        os.Exit(1)
    }
```

**NOTE:** Observe that the `cfg *rest.Config` is created in the `main.go`, by default in all projects built with [operator-sdk](https://github.com/operator-framework/operator-sdk).


**Step 2: Getting the API Resources**

Now, we could search for all resources as follows. 

```
    // Get a list of all API's on the cluster
    apiGroup, apiResourceList , err := discoveryClient.ServerGroupsAndResources()
    if err != nil {
        log.Error(err, "Unable to get Group and Resources")
        os.Exit(1)
    }
```

**NOTE:** See that by using the `kubectl api-resources` is possible to check the resources available in the cluster. Following an example. 


```
$ kubectl api-resources
NAME                              SHORTNAMES   APIGROUP                       NAMESPACED   KIND
bindings                                                                      true         Binding
componentstatuses                 cs                                          false        ComponentStatus
configmaps                        cm                                          true         ConfigMap
endpoints                         ep                                          true         Endpoints
events                            ev                                          true         Event
limitranges                       limits                                      true         LimitRange
namespaces                        ns                                          false        Namespace
nodes                             no                                          false        Node
persistentvolumeclaims            pvc                                         true         PersistentVolumeClaim
persistentvolumes                 pv                                          false        PersistentVolume
pods                              po                                          true         Pod
podtemplates                                                                  true         PodTemplate
replicationcontrollers            rc                                          true         ReplicationController
resourcequotas                    quota                                       true         ResourceQuota
secrets                                                                       true         Secret
serviceaccounts                   sa                                          true         ServiceAccount
services                          svc                                         true         Service
mutatingwebhookconfigurations                  admissionregistration.k8s.io   false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io   false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds     apiextensions.k8s.io           false        CustomResourceDefinition
apiservices                                    apiregistration.k8s.io         false        APIService
...
```

**Step 3: Verifying Resources**

Then, validations will be possible as in the following example.

**NOTE:** Notice that is possible to check the Group, Version and Kind as well. For further information, check the [APIGroup](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#APIGroup) godoc. 

```
    // Looking for group.Name = "apiextensions.k8s.io"
    for i := 0; i < len(apiGroup); i++ {
        if  apiGroup[i].Name == name {
             // found the api
        }
    }
```

It is possible to use the result of `apiResourceList`:

```
    // Looking for Kind = "PersistentVolume"
    for i := 0; i < len(apiResourceList); i++ {
        if  apiResourceList[i].Kind == kind {
            // found the Kind
        }
    }
```

**NOTE:** Check the [APIResourceList](https://godoc.org/k8s.io/apimachinery/pkg/apis/meta/v1#APIResourceList) godoc to see other options. 

I hope that the above information helps you with. Please, let me know if has anything else that we can do to help you with or if we can close this issue.
