### ISSUE TITLE
Drop dependency on k8s.io/kubernetes

### ISSUE THREAD

**Issue by howardjohn** [operator-framework/operator-sdk#2030]
Kubernetes intentionally ships a broken go.mod file to discourage people from depending on k8s.io/kubernetes (see kubernetes/kubernetes#79384). As a result, in order to depend on operator-sdk, we must go through major hacks to get go modules working.

Is it feasible to drop this dependency?

kubernetes/kubernetes#79384 (comment) indicates it may be possible to move the controller library out of k8s.io/kubernetes, and I think the only other usage is kubectl which can already use k8s.io/api and k8s.io/kubectl

**Comment by joelanford** [comment]
@howardjohn I would love to drop the dependency on `k8s.io/kubernetes`. Last I checked, the only reason `k8s.io/kubernetes` is required by operator-sdk is because of a transitive dependency from Helm (which is mentioned in kubernetes/kubernetes#79384).

Based on the discussion in https://github.com/helm/helm/issues/6606, it sounds like only Helm 3 will be targeted, which will mean some moderate refactoring in this project's helm-operator to facilitate this. That's not a huge concern, because we're planning to bump to Helm 3 anyway.

Lastly, it is possible we will have to wait on a controller-runtime release that supports the same version of Kubernetes that the Helm 3 release that removes this dependency supports.

**Comment by joelanford** [comment]
Looks like `operator-framework/operator-lifecycle-manager` also requires `k8s.io/kubernetes`, so we'll have to look into dropping that dependency there too.

**Comment by egaudet** [comment]
@joelanford  Turned out to be running the go get command from a directory with a go.mod that doesn't have the k8s dependencies (i.e. replace).  I was trying to test out doc generation from the project https://github.com/ahmetb/gen-crd-api-reference-docs so I was running in that directory.  Running elsewhere and I don't see the problem.  Thanks!

BTW, is there any other recommended way to generate API docs?

**Comment by jmrodri** [comment]
@howardjohn  Seems you are using it as a library, what parts of the SDK are you using when importing it? We've talked about making a library at some point which might help with this issue depending on what parts are being used. Clearly, if it's helm a separate library that supported that probably wouldn't fix the issue. But I'd like a little more information about your use cases.

**Comment by howardjohn** [comment]
We were using some very small amounts of code, like a light wrapper around leader election and some constants or something similar. We removed these a while back, so it doesn't personally impact me, but may be useful forohters

**Comment by joelanford** [comment]
It's been awhile since I looked at this, but it appears that the only remaining blocker for this issue is that operator-sdk has a transitive dependency on `k8s.io/kubernetes` via its OLM dependency.

```
$ go mod graph | grep ' k8s.io/kubernetes'
github.com/operator-framework/operator-sdk k8s.io/kubernetes@v1.16.2
github.com/operator-framework/operator-lifecycle-manager@v0.0.0-20191115003340-16619cd27fa5 k8s.io/kubernetes@v1.16.0
```

If you're wondering why that first `operator-sdk` entry shows up, it is because it is listed as indirect in the `go.mod` file. Searching operator-sdk code for `k8s.io/kubernetes` imports yields no results:
```
$ find . -name '*.go' -exec grep 'k8s.io/kubernetes' {} \; | wc -l
0
```
