### ISSUE TITLE
Are ansible operators typed checked against the CRD or can the CRD remain empty and if this is expected vs a bug

### ISSUE THREAD

**Issue by atinsood** [operator-framework/operator-sdk#2036]
**What did you do?**
Can someone confirm that the CRD in case of ansible operators can pretty much remain empty and you can keep adding fields to CR and the CR is never validated against CRD.

**What did you expect to see?**
I was expecting that similar to the go based operators, ansible operators will be more strictly type checked against the CRD, but seems like the CRD can remain empty and we can keep evolving the CR

**What did you see instead? Under which circumstances?**

**Environment**
* operator-sdk version: 

https://github.com/operator-framework/operator-sdk/releases/tag/v0.10.0

* go version:

* Kubernetes version information:

1.12

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go?
ansible

**Comment by camilamacedo86** [comment]
Hi @atinsood, 

By checking [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#define-the-memcached-spec) in the ansible guide, we can see that the specs are defined in the ansible files.  So, I understand that you should not update the CRs directly with this type. 

@fabianvf since you know more about the ansible one. Could you please confirm my understanding?.

**Comment by fabianvf** [comment]
Currently we don't support automatically creating the OpenAPI spec (we've been talking about how to do this, but it's tricky because unlike Go-based operators we have no type information). 

If you want to add validation, at least for now you will need to manually add the desired OpenAPI schema to the resource. I've done this with my Minecraft operator, if you'd like to see what it looks like that's here: https://github.com/fabianvf/game-server-operator/blob/master/deploy/crds/crds.yaml#L20

We should at least provide some additional documentation and a starting point for now though.

**Comment by atinsood** [comment]
@fabianvf appreciate the response. Can you confirm that if I add a schema to the resource the CR will be validated against the CRD, because so far I keep my CRD as whatever gets generated OOB and keep changing my CR, but nothing complains about CR not following the CRD spec. 

My broader point is, even if I make changes to CRD, if there's no validation then there;s a chance that my schema is totally wonky without me ever noticing.

**Comment by camilamacedo86** [comment]
Definitely, we should doc it. Add the labels. Thank you for the clarification @fabianvf.

**Comment by atinsood** [comment]
@fabianvf (we've been talking about how to do this, but it's tricky because unlike Go-based operators we have no type information) interesting. one way to go about this might be to leverage the CR to detect the type information and generate the CRD from it. its also a simpler approach for the end user  but the tricky bit is if we have a combination of CRs each working with a different set of fields then which one takes precedence, but that can be solved using 

a. support only one CR as master copy
b. support multiple but handle the merge

**Comment by fabianvf** [comment]
@atinsood If you provide validation information then it should begin rejecting documents that don't match it. 

+1, using the CR is a good idea, it can at least provide a sane starting point. I think there even are already some tools that can generate openAPI schemas when given a sample object.

**Comment by huizengaJoe** [comment]
@atinsood just to verify,  did you add openapi validation to your crd and verify that you get the behavior you desire?

**Comment by atinsood** [comment]
@huizengaJoe not yet, but I am planning to. will update the issue as soon as I try that out.
