### ISSUE TITLE
Get platform type using operator sdk API

### ISSUE THREAD

**Issue by petro404** [operator-framework/operator-sdk#2066]
Hi,

I am running my operator on vanilla k8s  and also on openshift , for identifying the type of the platform i am using parameter as part value.yaml 

is there a way to perform this using API code in go using the operator sdk framework so i can get the platform type using code and not as input parameter to the operator?

Thanks

**Comment by camilamacedo86** [comment]
Hi @petro404,

I am afraid that the K8s API has not func to provide this info in order to you know if you are running the operator in the Kubernetes or OCP for example. However, following a suggestion for you solve this need by using env vars.

In the `deploy/operator.yaml` add the ENV to inform the cluster kind.

```yaml

 - name: CLUSTER_KIND
      # Replace this with the valid kind
      value: "ocp"

``` 

Then, impl a utils func to obtain this info. 

```go

const (
	clusterKindEnv = "CLUSTER_KIND"
         ocp = "ocp"
         vanilla = "vanilla"
)

// GetAppNamespaces returns the kind of  the cluster where the operator is running
func getClusterKind() (string, error) {
	kind, found := os.LookupEnv(ClusterKindEnv)
	if !found {
		return "", fmt.Errorf("%s must be set", ClusterKindEnv)
	}
         if kind != ocp && kind != vanilla {
                 return "", fmt.Errorf("%s is a invalid value for  CLUSTER_KIND", kind)
         }
	return kind, nil    
}

func IsOpenshift (bool, error) {
     kind, err := getClusterKind()
     if err != nil {
         return err
     } 
     return  kind == "ocp"  
}

func IsVanilla (bool, error) {
     kind, err := getClusterKind()
     if err != nil {
         return err
     } 
     return  kind == vanilla 
}
```

In this way, shows that your question is covered. In this way, I am closing this one. 
However, please feel free to re-open if you fell that would be required.

**Comment by petro404** [comment]
10x alot for your reply i already implemented it in this way but just want to make sure that there is an another option ,which seems to be no :)

Thanks

**Comment by camilamacedo86** [comment]
Hi @petro404, 

IMHO, it would be the best approach. It is how I would solve it.  
I am glad that you liked it.

**Comment by joelanford** [comment]
@petro404 This question has come up a few times. What is your use case for knowing the platform? 

Your operator should use the Kubernetes Discovery API to find out which APIs are supported and then fail if requried APIs are missing and gracefully handle missing optional APIs.

**Comment by petro404** [comment]
My case is to add pod security context to my pods in case my platfrom is not openshift

**Comment by camilamacedo86** [comment]
Hi @joelanford, 

I am not sure if I misunderstanding something. However, I tried to do it programmatically from the operator in the past but it did not work well because it will get the info from the pod which is not the same found in the kubeconfig locally which is where the info came from when we run the commands[1]. 

So, the ENV VAR was the best approach which I could found so far. Using the commands, I can see that would be possible to customize with sed as for example done in [the getting started](https://github.com/operator-framework/getting-started#1-run-as-a-deployment-inside-the-cluster) and [Makefile targets](https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/Makefile) in order do not be required set the value manually. 

So, please let me know as well if you know a better approach to do it. I really would like to know if has another/ a better way to do it. 

[1] - https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/

**Comment by joelanford** [comment]
@petro404 The way we usually tell users how to handle this would be to use client-go's support for the discovery API to lookup a resource that you expect to be in a given cluster.

So for example, with OpenShift 4.x, you could look for the `config.openshift.io` `clusterversion` resource. If it's there, you're in an OpenShift 4.x cluster. If it isn't there, you're not in an OpenShift 4.x cluster.

**Comment by camilamacedo86** [comment]
I  will keep this one open and assign to me in order to:
- Create a POC following the suggested approach
- Then, create a RedHat dev blog post with this solution. 
@joelanford

**Comment by camilamacedo86** [comment]
I am closing this one since the blog posts have been done and are in process to be published. (it can take a while in order to follow all process)
