### ISSUE TITLE
Generated CRD doesn't work on Okd 3.11

### ISSUE THREAD

**Issue by JaroslavMajera** [operator-framework/operator-sdk#2069]
## Bug Report

I have updated operator to version 0.11. Regenerated CRDs cannot be imported to Okd 3.11.

**What did you expect to see?**
Crds could be imported to Okd 3.11.

**What did you see instead? Under which circumstances?**
Crds cannot be imported with "must only have "properties", "required" or "description" at the root if the status subresource is enabled" error

**Environment**
* operator-sdk version:

0.11

* go version:

go version go1.13 linux/amd64

* Kubernetes version information:

kubernetes v1.11.0+d4cacc0

**Possible Solution**
Remove "type: object" from generated CRDs

**Additional context**
https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/issues/640

**Comment by camilamacedo86** [comment]
Hi @JaroslavMajera, 

The 3.11 is no longer compatible since SDK is using upper versions of k8s API. We would like to suggest you use Minkube, see [here](https://kubernetes.io/docs/tasks/tools/install-minikube/) how too install or OCP 4.X.

Also, note that the 1.13 version of go is not supported yet. You need to use 1.12+.

In this way, I am closing this one. However, please feel free to re-open if you felt that still required
