### ISSUE TITLE
GO111MODULE=on go get fails with invalid version: unknown revision 000000000000

### ISSUE THREAD

**Issue by ilackarms** [operator-framework/operator-sdk#2103]
# BUG

cannot `go get` operator sdk in v0.11.0

# REPRODUCE

```
GO111MODULE=on go get github.com/operator-framework/operator-sdk
```

# output

```
go get: github.com/operator-framework/operator-sdk@v0.11.0 requires
	k8s.io/cloud-provider@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by ilackarms** [comment]
closing, i believe this is because i was trying with go 1.12

**Comment by ilackarms** [comment]
tried with 1.13 and it still fails with the same error

**Comment by camilamacedo86** [comment]
It is the PROXY. Use export GOPROXY=https://proxy.golang.org/ in order to solve it.

**Comment by ilackarms** [comment]
@camilamacedo86 tried it, still seeing the same error

**Comment by joelanford** [comment]
Actually, I don't think the proxy is related. It's worth a shot, but I doubt that helps. In fact, with Go 1.13 the proxy is used by default unless specificially overridden by setting `GOPROXY`.

I think this may not be solvable due to our dependency on `kubernetes/kubernetes`, which basically requires `replace` to be used to correctly bring in all of its dependencies correctly.

I don't think `go get` pays attention to the `replace` lines, unfortunately.

@ilackarms Are you trying to install the binary from source or use it as a library?
- If installing the binary, does this work: https://github.com/operator-framework/operator-sdk/blob/master/doc/user/install-operator-sdk.md#compile-and-install-from-master
- If using as a library, you probably need to add [these same replace lines](https://github.com/operator-framework/operator-sdk/blob/39c65c36159a9c249e5f3c178205cc6e86c16f8d/go.mod#L98-L111) to your `go.mod` file.

**Comment by ilackarms** [comment]
@joelanford that did the trick! thank you

i'm using SDK libraries atm

**Comment by kiros-sc** [comment]
Tried with go 1.14.6 darwin and still the same. error

**Comment by chphong** [comment]
code in go.mod below works for me.
`replace github.com/codegangsta/cli => github.com/codegangsta/cli v1.20.0`
