### ISSUE TITLE
What's the use case of creating several controllers for the same operator?

### ISSUE THREAD

**Issue by gpanagiotidis** [operator-framework/operator-sdk#2132]
I want to create two CRDs that are a bit different, and two controllers, each one watching on of the CRDs, doing more or less the same job, except returning a different status. For this operation I will use a private library that's doing the API requests to an external server.

My question is, should I create two operators with a controller in each, or create one operator with two controllers?

**Comment by camilamacedo86** [comment]
Hi @gpanagiotidis,

An operator project is designed to have resources where each type of resource(CR/CRD) has its own controller. Note that having many types/resources managed by the same controller goes against the controller-runtime design.

I'd like to suggest you check [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) since it has a better explanation with some examples of this idea.

**Comment by camilamacedo86** [comment]
Hi @gpanagiotidis, 

It is up to your solution/business requirements.In the suggested link has some explanations and an example which I thought would clarify and make its concepts more evident. 

However, in order to try to make it simple, following an explanation and answer for your question.  

By concept, each kind (CRD) would represent a unit/piece which is required for all/full solution managed by the operator works as expected. Think about Microservice architecture and, then this requirement probably will start to be more evident.  

Note that when we run for example `operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached`, the purpose of this command is to generate a Custom Resource Definition (CRD). So, it will create the API with the group `cache.example.com`, and version `v1alpha1` and the Memcached CRD. Consequently, it means that we are creating our own APIs and objects which will represent our solution on these platforms.

See that the CRD is a definition of a resource and we can associate the CR to an instance of this object in the cluster.  Then, have only one CRD to define many domains would be hurting concepts such as encapsulation, the single responsibility principle, and cohesion and damaging these concepts could cause unexpected side effects, such as difficulty in extending, reuse, or maintenance, just to mention a few. 

Just to clarify, have all possible domains and its specs defined in the same CRD would be the same to design a system with just 1 class for all. I mean that it, for example, would be the same as defining a user class which will have attributes related to other domains such as; clients, fruits and shoes. 

So, to answer your question by analogy:  In the same way, that usually would not make sense has 1 system design with just 1 class to manage all possible domains would not make sense have 1 Operator project with just 1 CRD besides may it be technically possible. 

Also, if you do not mind I would like to suggest you a book which is very aligned with this idea and I love, it is [Domain-Driven-Design](https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215). I hope that you like it.
