### ISSUE TITLE
Single Controller with Multiple CRDs and multiple deployments

### ISSUE THREAD

**Issue by vthapar** [operator-framework/operator-sdk#2151]
## Type of question

**How to implement specific feature**

## Question
Is it possible to have single controller manage multiple deployments with multiple CRDs?

**What did you do?**
I have an operator that creates a deployment based on primary CRD. Now I want to add additional optional CRDs that will result in additional deployments. These additional deployments require primary to be present but are optional.

I created CRDs as:
```
operator-sdk add api --api-version=project.example.com/v1alpha1 --kind=MainResource
operator-sdk add api --api-version=project.example.com/v1alpha1 --kind=OptionalResource1
```
Then I added following to `controller.go`

```
err = c.Watch(&source.Kind{Type: &projectv1alpha1.MainResource{}}, &handler.EnqueueRequestForObject{})
err = c.Watch(&source.Kind{Type: &projectv1alpha1.OptionalResource1{}}, &handler.EnqueueRequestForObject{})
```

**What did you expect to see?**
Expected Reconcile() to be called for OptionalResource when I create CRDs for it.

**What did you see instead? Under which circumstances?**
Reconcile is not called when OptionalResource is created.

**Environment**
```operator-sdk version
operator-sdk version: "v0.11.0", commit: "39c65c36159a9c249e5f3c178205cc6e86c16f8d", go version: "go1.12.6 linux/amd64"``

* Kubernetes version information:

```kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T18:30:39Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by camilamacedo86** [comment]
Hi @vthapar, 

Technically is possible to manage N CRD's in the same controller. Shows that it is not working in your example because of the watch implementation that was not done for a secondary resource. See [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/memcached-operator/pkg/controller/memcached/memcached_controller.go#L55).

However, it goes implicit against the design of the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime). Note that by concept, each kind (CRD) would represent a unit/piece which is required for all/full solution managed by the operator. See that the CRD is a definition of a resource and we can connect the CR to an instance of this object in the cluster. Then, have only one CRD to define many domains would be hurting concepts such as encapsulation, the single responsibility principle, and cohesion and damaging these concepts could cause unexpected side effects, such as difficulty in extending, reuse, or maintenance, just to mention a few.

Also, it is important to highlight that you are able to do operations in the controller of one CRD by checking other kinds of CR's. For example, in the case of you have to have A is required B. See [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/backup/controller.go#L131) an example of a code implementation which requires check a CR for another kind which is not managed by its controller. (To have a backup resource/object is required to have the database one in the example).

I'd like to suggest you check [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) since it has a better explanation with some illustration of this idea. Also, I'd like to recommend you design your solutions following the DDD concept. For further information, see the [book](https://www.amazon.com/Domain-Driven-Design-Tackling-Complexity-Software/dp/0321125215). 

In this way, I am closing this one. However, please feel free to re-open if you believe that the info provided above does not answer your question and it requires further assistance.
