### ISSUE TITLE
Get ansible k8s syntax to validate in Visual Studio Code

### ISSUE THREAD

**Issue by mikkeschiren** [operator-framework/operator-sdk#2177]
Normaly i use Visual Studio Code to edit ansible, but I can't figure out how to fix so Visual Studio Code understands the k8 syntax:

![bild](https://user-images.githubusercontent.com/712838/68604433-c12b1900-04aa-11ea-9295-e67b8567fb05.png)

Any ideas or suggestions?

**Comment by camilamacedo86** [comment]
HI @mikkeschiren, 

It shows a subject related to, I mean more appropriate to VS channels and etc.  However, it may https://code.visualstudio.com/docs/azure/kubernetes#_install-the-kubernetes-extension is what you are looking for.

I'd recommend you looking for extensions and plugins of your IDE.

I am closing this one since shows sorted besides is not be part of operator-framework and sdk scope.

**Comment by mikkeschiren** [comment]
@camilamacedo86 that extension is on one of them I am using, it thought that the project were responsible for it's own schemas? Or were could I find the schema?

**Comment by camilamacedo86** [comment]
Hi @mikkeschiren,

The schemas are provided /defined by the k8s API. However, what is the best plugin to work with k8s API in Visual Studio is not really a operator-framework scope.  If you are using an extension/plugin for your IDE and it still not work well maybe is the version of the extension or plugin that does not support the version of Kube API used with. 

So, I'd recommend you check it and in the go.mod of your project you can see the kube version that it is using. 

I hope that it clarifies your question and help you with.

**Comment by mikkeschiren** [comment]
I do not think k8 version is something to do with it - it is yaml files for ansible, used by the ansible operator that do no validate. To make it validate it need a schema for the ansible operator. Maybe I can write my own, it should not be so much to add for the offical ansible schemas.

**Comment by camilamacedo86** [comment]
I see you are checking the files for example task.yml. Am I right? 

So, if you would like to edit ansible files in the Visual Studio I'd recommend you looking for a plugin/extension for your IDE. See for example: https://marketplace.visualstudio.com/items?itemName=vscoss.vscode-ansible

Have you tried to check this one?  

Also, perhaps see if someone already raise this question in https://github.com/ansible/ansible and/or 
https://github.com/github/VisualStudio. 

Please, let me know if the above-suggested plugin worked for you.

**Comment by mikkeschiren** [comment]
Thanks, but I already have the ansible extension - the problem is not ansible itself - it is that the schema used in the ansible operator does not validate against the existing schemas, like: https://github.com/SchemaStore/schemastore/blob/8af13cd3afa7ca67a1c246b38e19602c7e242783/src/api/json/catalog.json#L13

And then it does not validate, the editor itself (any editor) is more or less useless for editing yaml files for the the ansible operator. So what I am looking for is a ansible schema for the ansible operator.

**Comment by camilamacedo86** [comment]
Hi @mikkeschiren, 

Are you able to see errors when you check the [.travis](https://github.com/operator-framework/operator-sdk-samples/blob/master/ansible/memcached-operator/.travis.yml) file as well? If yes, so your question is: How to make  **Visual Studio** recognize YML files? 

It is important to highlight that the operator-sdk and its Framework are NOT creating any new type of file and it will just use ansible annotations, and python files, as generating k8s resources using its APIs. So, your question would be  `How to not see errors in the **Visual Studio** when I open **Ansible YML files**?` So, are not the same issues appearing by checking any YML ansible file which was generated or NOT by the operator in your Visual Studio?

In order to help you with: `Note that the same behaviour is NOT faced by using Golang IDE and IntelliJ for example.`

I checked that I have just the k8s plugin: 

<img width="1215" alt="Screenshot 2019-11-12 at 09 01 10" src="https://user-images.githubusercontent.com/7708031/68657457-ac429a00-052b-11ea-97ef-fac63f571765.png">
 
<img width="1215" alt="Screenshot 2019-11-12 at 09 01 10" src="https://user-images.githubusercontent.com/7708031/68657499-c41a1e00-052b-11ea-93f6-6c0c8380d962.png">

Then, I installed the Ansible plugin just to check it with. All still working fine. 

<img width="747" alt="Screenshot 2019-11-12 at 09 01 55" src="https://user-images.githubusercontent.com/7708031/68657651-0a6f7d00-052c-11ea-9d7f-6b5673ac134a.png">

So, I'd recommend you raise the question in the https://github.com/github/VisualStudio and/or https://github.com/ansible/ansible since it is specific questions for then and it has more relation to their scope. 

Please, let me know if is clear now why it is out off the context of the Operator-SDK and Operator-Framework.

**Comment by mikkeschiren** [comment]
I still believe it is a schema problem - where is the schema for the ansible operator? I cant see how it is relevant for general questions for an editor or the ansible project - the schema of the file is not recognized, and therefor it does not validate, and you do not get stuff like autocompletion etc. Do you get autocompletion in the editors you tried? I have tried a bunch of editors. All have the same problem, they do not understand ansible operator schema.

**Comment by camilamacedo86** [comment]
HI @mikkeschiren, 

Can you please check the [Ansible Sample](https://github.com/operator-framework/operator-sdk-samples/tree/master/ansible/memcached-operator) and le us know what and where you see an error as example in your IDE?

**Comment by mikkeschiren** [comment]
Same results:

![bild](https://user-images.githubusercontent.com/712838/68761274-0b7bd980-0614-11ea-820e-d001fc243712.png)

But if I am using the deprecated k8s_raw:

![bild](https://user-images.githubusercontent.com/712838/68761333-28181180-0614-11ea-80a5-13732778c4ea.png)

No warnings any more.

**Comment by mikkeschiren** [comment]
Anyhow, I guess this should be an ansible issue, will create issue overhere.

**Comment by camilamacedo86** [comment]
Hi @mikkeschiren, 

Just to clarifies. See the same file open in the Intellij: 
> - Note that I am using just the k8s extension/plugin for IDE and I am not seen any issue). 

<img width="1080" alt="Screenshot 2019-11-13 at 12 23 25" src="https://user-images.githubusercontent.com/7708031/68763648-d91cad00-0610-11ea-86f0-fca2cdace894.png">

So, how this behaviour cannot be something specific of Visual Studio IDE and/or extensions used on it? I hope that it can clarify. I'd you suggest raise and issue for ansible and/or visual studio to see if someone can help you find out **How to not see errors in ansible files opened in the Visual Studio?**

Really thank your attention and close this issue.
