### ISSUE TITLE
Depends on folder name when generate binary: "operator-sdk build"

### ISSUE THREAD

**Issue by vincent-pli** [operator-framework/operator-sdk#2333]
## Type of question
Scope design

## Question

**What did you do?**
I have a `operator` generated by `operator-sdk`, and my project name is `my-test`, with some reason I clone it to another location with name `test`.
When I try to use `operator-sdk build` I hit error: 
"build/_output/bin/my-test not existed not existed"

**What did you expect to see?**
Everything works

**What did you see instead? Under which circumstances?**
Error raised

**Additional context**
The error is caused by these reasons:
1. When generate scaffold, the generated docker file: `./build/Dockerfile` has a commend like this:
```
COPY build/_output/bin/my-test ${OPERATOR}
```
Seems `operator-sdk` expect use the `project name` as binary name  

2. When run `operator-sdk` later, the binary will be compiler and output with name of current `folder name`.

I know when scaffold generated the folder name is exactly the project name but we can not guarantee it later, so could we generate some manifest information, such as `project name` or anything?

**Comment by camilamacedo86** [comment]
Hi @vincent-pli,

The name of the project will be used in a lot of places when the init project is generated by the tool. However, note that GO will also use the path of your project and, in this way, its name to do the imports. 

In your scenario will be required to replace all these places manually. Regards the go imports if you use an IDE, for example, to do this change it could be solved by it. 

In order to fix the build, you need to replace the old name for the new one in the `build/Dockerfile` and `build/bin/entrypoint`. Also, will be required to replace the project references the YAML files in the `deploy` directory as well. 

I understand that we could sort out your question with the information provided above. Then, I am closing this one. However, feel free to re-open if you think that it still required.

**Comment by vincent-pli** [comment]
@camilamacedo86 
For the fix, I think we can use some parameter when generated  `build/Dockerfile`,
I mean:
```
COPY build/_output/bin/${base dir} ${OPERATOR}
```
for the golang, I think we should no worry about it, since we adopter `go mod`, what do you think?

**Comment by JoelColledge** [comment]
Hi @camilamacedo86,

I have also run into problems due to this behavior and to me it seems unconventional that a project's build would depend on the directory it happens to be in. I would appreciate it if this could be fixed and might even be able to provide a PR.

> However, note that GO will also use the path of your project and, in this way, its name to do the imports.

What do you mean by this? @vincent-pli points out that the generated operator uses `go mod`. Thus imports within the project use the module name defined there and are not dependent on the path of the project in the local filesystem. Other go projects are not dependent on their directory name.

I think the fix would involve more-or-less the following:
1. When doing `new`, write the project name into a file, e.g. `build/project_name`, which should be checked in to VCS.
2. Add a tiny function to read the project name from this file.
3. Review locations using `filepath.Base`, most or all of which have the purpose of getting the project name, and replace them with a call to the function from 2.

If backwards compatibility is required, just add some extra logic in the function from 2. to read the name of the current directory instead.

**Comment by shivanshs9** [comment]
I agree it's an important issue to fix since it's an undocumented issue that pops up, often in forks and clones with a different root directory.
Quite recently, I spent hours debugging why operator build in CI works in my fork but not in the upstream repo with the exact same commit. Who would've guessed the fork name would have such drastic consequences? :eyes: 

I also noticed there's no need to actually name the binary according to the project folder's name. I mean, even if we simply use 'operator' as binary name and in `build/Dockerfile` the image would still correctly copy binary into the correct path (according to the project name specified initially) hence everything will work fine.

If needed, I can push a PR with the above logic when building operator.

**Comment by camilamacedo86** [comment]
Hi @JoelColledge and @shivanshs9,  

SDK is in a process to be integrated with KB which means that its project layouts will be aligned which is part of the changes for 1.0.0 release. More info : [Integrating Kubebuilder and Operator SDK](https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md)

With this, the implementation for the Dockerfile change and we haven't so longer the `build/bin/entrypoint` which shows that address your RFE made here already. 

So, could you please check your needs in the new layout and then, if you see that you still requiring something could you please raise a new issue for that? The migration guide to the migrate the projects is in https://sdk.operatorframework.io/docs/golang/project_migration_guide/.

Really thank you for your collaboration.
