### ISSUE TITLE
Help operator: support multiple charts per operator

### ISSUE THREAD

**Issue by mitar** [operator-framework/operator-sdk#2386]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I am new to the operator SDK, but I was reading user documentation for Helm operator and it seems to me that it is just about creating one operator per Helm chart. I understand that this aligns with what the operator SDK is about, but in practice, wouldn't it make more sense to have only one operator which knows how to manage multiple charts? I mean, this is then proper separation of concerns. Helm charts describe apps, operator manages life of instances of any of those apps, but it is independent from charts and apps themselves.

**Describe the solution you'd like**

So I am not completely sure if this is aligned with operator SDK goals, but I think it would be cool to have support for creating a meta-helm operator, where you would configure not one chart, but for example configure the repository of charts and the operator would then allow creating instances of any app from that repository. One would add CRD per app instance which the operator would pick up an create an instance of the app. If CRD is changed, operator updates the app to match the new CRD state. And that for any chart from the repository.

**Comment by joelanford** [comment]
@mitar The helm operator does support reconciling multiple CRDs and charts. To do that, simply add another watch in `watches.yaml`, add the associated chart to `./helm-charts/`, and update `./deploy/role.yaml` to give your operator permissions to manage the new CRD and chart resources.

However, we don't recommend creating a single helm operator that can manage many unrelated charts because there are security concerns with granting a single process permission to manage ALL the resources of ALL the charts it can deploy. This was the primary reason that the Helm project transitioned away from Tiller in Helm 3.

**Comment by mitar** [comment]
I see. Thank you.
