### ISSUE TITLE
Scorecard external plugins are not currently supported with v1alpha2

### ISSUE THREAD

**Issue by jdockter** [operator-framework/operator-sdk#2398]
## Type of question

operator-sdk scorecard future support for external plugins

## Question

**What did you do?**
When running operator-sdk scorecard version 0.13 and 0.14 got the following error:
`Error: error validating plugin config: revert to v1alpha1 to use external plugins: external plugins are not currently supported with v1alpha2`

**What did you expect to see?**
Support for external plugin

**What did you see instead? Under which circumstances?**
see above

**Environment**
* operator-sdk version: 0.13.0 and 0.14.0

operator-sdk version
operator-sdk version: "v0.14.0", commit: "4fb185b9d45682473b4951c9788f845ba2fa5b12", go version: "go1.13.3 linux/amd64"

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+dea7fb9", GitCommit:"dea7fb9", GitTreeState:"clean", BuildDate:"2019-11-19T17:18:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by jdockter** [comment]
@joelanford wondering if you can comment on this

**Comment by joelanford** [comment]
Yep, so in `v1alpha2` we introduced `--selector` so that callers could select just a subset of the scorecard tests to run (e.g. required vs. recommended) and `--list` so that callers could see which tests were selected without actually running them.

In `v1alpha1` these features don't exist so the external plugin interface (and external plugins) have no way of answering the question "What labels do you have?" to support the selector flag and they have no way of getting information from the plugin without actually running the plugin.

For that reason and because there are a bunch of other fundamental questions to answer about the exact use cases of external scorecard plugins, the decision was made to drop support for them in `v1alpha2` and to revisit in a later version of the scorecard after we have a better understanding of the use cases.

**Comment by jdockter** [comment]
@joelanford thanks
