### ISSUE TITLE
Install Python dependency in Ansible Operator image to validate managed resources

### ISSUE THREAD

**Issue by erikgb** [operator-framework/operator-sdk#2433]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I would like to use the k8s validate feature introduced in Ansible version 2.8. This will allow me to validate the native Kubernetes resources managed by my operator. Currently this is not possible since the required Python module (`kubernetes-validate`) is not installed in the ansible-operator image.

**Describe the solution you'd like**
Install the `kubernetes-validate` Python module with pip3 alongside `openshift` in https://github.com/operator-framework/operator-sdk/blob/aa1c5ea2fbb0c300b24810ba8031ad2871c296a8/ci/dockerfiles/ansible.Dockerfile#L32

I will prepare a PR.

**Comment by asmacdo** [comment]
Thanks for the issue and PR!  You should be able to any deps you need in your `build/Dockerfile`. 

https://github.com/operator-framework/operator-sdk/blob/master/doc/faq.md#my-ansible-module-is-missing-a-dependency-how-do-i-add-it-to-the-image

I'm closing for now to keep the base image minimal feel free to reopen if you would like more discussion.

**Comment by erikgb** [comment]
@asmacdo : I do fully understand why you want to keep the base image as small as possible. It's just that without this Python dependency you cannot use the full feature set of the k8s Ansible module - which is already pre-installed in the base image - and this does not seem right to me.

**Comment by fabianvf** [comment]
@erikgb the issue isn't the size of the base image, but the surface area for support. While the `k8s` module does support the validate argument via the `kubernetes_validate` package, we don't currently have the bandwidth to provide troubleshooting/support for any issues users may encounter with that package. We try to keep the packages in the base image limited to ones that we will support and troubleshoot if issues are encountered. That being said, I agree that it seems wrong to not include that package and allow that option by default, and we should consider including the package by default, at least for the upstream.

**Comment by erikgb** [comment]
@fabianvf thank you for your partial understanding and support? 😉 I think it makes a lot of sense to install this missing Python library in the base/upstream image. I wouldn't worry too much about supporting issues in a dependent library. The client side validation provided by kubernetes-validate is not "core" functionality where an easy workaround exists if faced with a bug - just skip validation.

The rationale for us to adopt the client side validation feature of k8s module is to be able to perform stricter validation of the native Kubernetes resources managed by our operators. This validation will have to be disabled for Openshift proprietary resources anyway, since the kubernetes-validate module has no knowledge of the Openshift schemas. (Our current target platform is currently Openshift.)

We prefer to add stricter (client side) validation where we can, since current Kubernetes practice is just to ignore unknown attributes. This may change in the future, but we would like to fail fast in the operator playbooks. We have tests for most of the functionality, but it is hard to achieve 100% test coverage.

Would you consider the closing pull request again, please?

**Comment by camilamacedo86** [comment]
Hi @erikgb,

> I wouldn't worry too much about supporting issues in a dependent library.

The point is that, If we add this lib in the SDK, then we need support/help the users who decided to use ansible operator with and encounter issues. And then, sometimes is required to spend a lot of effort to find out that some issue X is because of a problem Y in a lib Z. Note that, to introduce new dependencies in the project, we need to think a lot about regards many aspects as well, such as; its adoption, its documentation, if it will be kept maintained for an extended period, etc. 

I think that we can agree that would not be nice the experience of after implementing many projects using some dep which was provided by SDK then, be required to change all because the lib was deprecated for example. 

However, note that users are always able to customize their projects and use any lib as they wish. In this way, any user still able to adopt this lib in their projects too. 

Is it make sense? Could we agree in close this RFE and PR? WDYT?

**Comment by erikgb** [comment]
@camilamacedo86 : Managing dependencies is always hard, regardless if it is in a framework/library or in an application. While I agree on your general comments about dependencies, I do not think they apply in this particular case. :-)

I consider missing stricter server-side validation in Kubernetes as the root of this issue. Without it, clients will have to implement different solutions for validating resources. And I do not think that people really care about how the (for now, client-side) validation is implemented in the Ansible k8s module. They just want a (strict) validating feature to be available.

While it makes sense to make this dependency optional in the Ansible k8s _module_, I think it makes less sense to not include it in a _framework_ like the Operator SDK.

All this said, there is a simple workaround that I have already implemented: Install the missing Python dependency in my operator Dockerfile. I am closing this issue and PR now to let you focus on more important stuff. You are doing a great job with the Operator framework!

**Comment by camilamacedo86** [comment]
HI @erikgb, 

Really thank you for your feedback and reply. Just to clarifies, I was looking at this dependency. 
See: https://pypi.org/project/kubernetes-validate/

<img width="334" alt="Screenshot 2020-02-05 at 11 34 36" src="https://user-images.githubusercontent.com/7708031/73838454-9df2da00-480b-11ea-95db-1d1a25ed3c45.png">

It has just its the author as maintainer and 5 starts which shows that besides it be very cool and useful for some cases and users it still not really adopted and maintained by the community yet. Then, in my POV, it matches exactly with some scenarios described above regards supportability which would be one of the highlighted reasons that would not allow the dep to be incorporated and shipped by default with SDK currently. However, it also can be re-evaluated in the future as well. 

Really thank you for your contributions and suggestions. Please, keeping sharing with us your thoughts because it is very important for SDK.
