### ISSUE TITLE
Impact of WATCH_NAMESPACE on Kubernetes RBAC in ansible operator

### ISSUE THREAD

**Issue by glothriel** [operator-framework/operator-sdk#2461]
## Impact of WATCH_NAMESPACE on Kubernetes RBAC in ansible operator

Hi. The problem I'm facing is possibly a bug, but given I don't understand how operator-sdk runs ansible I'm starting it as a support question.

## Question

I have:
* a single namespace `osdk-test`
* an operator without WATCH_NAMESPACE envvar set - so running in cluster scope
* RBAC rules, that allow ServiceAccount that operator's Pod full access to stuff inside `osdk-test` namespace, including Secrets.
* a single Secret named `test` inside `osdk-test` namespace.

**What did you do?**
I created a simple playbook with single task:
```
    - name: Fetch controller secret
      k8s_facts:
        api_version: v1
        kind: Secret
        name: "{{ secret }}"
        namespace: "{{ namespace }}"
      register: secret

```

**What did you expect to see?**
I expected the playbook to run successfully when CR is created.

**What did you see instead? Under which circumstances?**
I see a lot of errors in `operator` container:
```
E0123 08:12:03.053533       8 reflector.go:123] pkg/mod/k8s.io/client-go@v0.0.0-20191016111102-bec269661e48/tools/cache/reflector.go:96: Failed to list *unstructured.Unstructured: secrets is forbidden: User "system:serviceaccount:osdk-test:poc-mysql-operator" cannot list resource "secrets" in API group "" at the cluster scope
```

**Environment**
* operator-sdk version: v0.15.0
* Kubernetes version information:
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:21:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.9", GitCommit:"500f5aba80d71253cc01ac6a8622b8377f4a7ef9", GitTreeState:"clean", BuildDate:"2019-11-13T11:13:04Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind:  kind

**Additional context**

The situation can be resolved in two ways:
* by adding WATCH_NAMESPACE='osdk-test' envvar to operator pod
* by adding ClusterRole to read secrets for the operator's ServiceAccount

Is this a normal behavior? Why WATCH_NAMESPACE influences operator's access to resources despite valid RBAC roles set?

Here is a demonstration of my problem, the readme describes how to run it, it uses operator-sdk test framework: https://github.com/glothriel/testoperator2

**Comment by djzager** [comment]
What I believe you are encountering with this issue is a mismatch between the caching client that is created for you based on the `WATCH_NAMESPACE` environment variable and the permissions given to the operator pod's service account.

> The situation can be resolved in two ways:
> 
> * by adding WATCH_NAMESPACE='osdk-test' envvar to operator pod
> * by adding ClusterRole to read secrets for the operator's ServiceAccount

Before I go any further I want to point out in code what is happening. The `WATCH_NAMESPACE` environment variable is retrieved [here](https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/run.go#L66) and later used to create a new manager [here](https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/run.go#L82-L96). When calling `manager.New()`, a caching client is created for you. This client is what's responsible for doing things with the cluster; GETing, LISTing, CREATEing, PATCHing, etc.

With that in mind what I think you are seeing is:

1. You set `WATCH_NAMESPACE` to `""` and namespace scope your operator pod's service account. The client is attempting to work at the cluster scope but doesn't have permissions to do so.
1. You set `WATCH_NAMESPACE` to `"osdk-test"` and namespace scope your operator pod's service account. The client is working at the same scope as the permissions granted to the operator pod's service account and the operator behaves as you would expect.
1. You set `WATCH_NAMESPACE` to `""` and give your operator pod's service account cluster wide permissions on Secrets. The client is working at the same scope as the permissions granted to the operator pod's service account and the operator behaves as you would expect.

Based on my current level of understanding of the pieces involved, it sounds like it is working as expected (ie. not a bug).

**Comment by joelanford** [comment]
@glothriel IIUC, I believe @djzager is correct. This doc may help clear things up: https://github.com/operator-framework/operator-sdk/blob/master/doc/operator-scope.md#cluster-scoped-operator-usage

**Comment by joelanford** [comment]
If not, let us know and we can re-open this issue!
