### ISSUE TITLE
Keep autogenerated code in separate package to increase code coverage reports

### ISSUE THREAD

**Issue by wreed4** [operator-framework/operator-sdk#2467]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When building unit tests for codebases generated with the operator-sdk, we would like to avoid testing the autogenerated code.  However, when testing the Reconcile loop, coverage reports that we're missing a good portion of the file because the top bits are all autogenerated code and we don't want to test those bits.

**Describe the solution you'd like**
Either, provide standard unit tests in the generated code to test the generated code (might be a better solution than the title) OR, simply make a new package for reconcile handling so that users only need to test code they've written and not the code generated by operator-sdk.

**Comment by camilamacedo86** [comment]
Hi @wreed4, 

Thank you for contacting us and share your thoughts and needs. So, I understand that you are looking for the SDK tool scaffold unit tests for the automated / generated code by it. 

@joelanford do you think that it would be possible to get done before the integration with kubebuilder? wdyt?

**Comment by joelanford** [comment]
@wreed4 This is a great suggestion!

As @camilamacedo86 mentioned, we're in the midst of integrating with Kubebuilder such that operator-sdk will soon be generating Go code based on Kubebuilder's scaffolding. The idea is that since Kubebuilder and operator-sdk generate Go projects that heavily depend on controller-runtime, we can join forces on the actual scaffolding of Go project files and we'll make more progress faster working together.

So having said that, I hesitate to spend much effort doing this for SDK's existing Go scaffolds since we'll be changing those out for Kubebuilder's scaffolds in the next month or two (if all goes to plan).

[Kubebuilder's controller template](https://github.com/kubernetes-sigs/kubebuilder/blob/55e342048e4381947ffda902f8316b82954ded77/pkg/scaffold/v2/controller/controller.go#L76-L110) is much simpler than SDK's and Kubebuilder already scaffolds a test file alongside the controller, so we may be able to close this with the Kubebuilder integration work.

@wreed4 WDYT?

Also, ff you're interested in following the progress of that work, the first step is here: https://github.com/kubernetes-sigs/kubebuilder/pull/1290
