### ISSUE TITLE
Regarding CronJob.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#2488]
Do operator-sdk support batch api for cronjob.
apiVersion: batch/v1beta1

---
- name: start postgres
  k8s:
    definition:
      kind: CronJob
      apiVersion: batch/v1beta1
      metadata:
        name: postgres-backup-sheduled
      spec:
        schedule: "/5 * * * *"
        jobTemplate:

I was unable to use apiVersion: batch/v1beta1 in operator-sdk.

**Comment by camilamacedo86** [comment]
HI @AnilKumarBandi27, 

Could you add the error faced for we we try to help you? Also, could you please let us know what is the cluster type and version as the SDK  version used as well? 

Also, I'd like to share with an example of a project which is using the `"k8s.io/api/batch/v1beta1"`. See [here](https://github.com/dev4devs-com/postgresql-operator/blob/1c875a8ca074fd46a48e60f658437b3e59a19e19/pkg/service/generic_fetches.go#L34).

**Comment by AnilKumarBandi27** [comment]
I am using Kubernetes version: "v1.16.3" and operator-sdk version: "v0.11.0".
I am working on Postgresql operator using ansible and for backup of databases. I want to set a cron job for schedule backup. 

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup-sheduled
spec:
  schedule: "/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: postgres-backup
              image: "{{ image }}"

I used cron job API and created a backup pod for scheduled backups. But when I include this code inside the operator-SDK it is failed to create the pod. When I include the same YAML file as a role in watches.YAML file. I am not able to create a pod Error message displayed was Failed to find the exact match for batch/v1beta1. API version.in operator logs.

Could you please share any example in ansible using this batch/v1beta1. I am using ansible type of operator.

**Comment by camilamacedo86** [comment]
Hi @AnilKumarBandi27,

Thank you for your replay. Following some comments inline. 

> I am using Kubernetes version: "v1.16.3" and operator-sdk version: "v0.11.0".

I'd recommend you upgrade your project for the latest version of SDK 0.15+ in order to ensure the compatibility. Note that, the version v0.11.0 will use kubernetes-1.14.+ when the latest one, 0.15.1, is using kubernetes-1.16.+.

> 
I used cron job API and created a backup pod for scheduled backups. But when I include this code inside the operator-SDK it is failed to create the pod.

Could you share your project? Could you let us know exacly what do you mean with `include this code inside the operator-SDK`? Can you provide the steps to reproduce this issue ( perform a POC )?
