### ISSUE TITLE
Need a way for ansible operators to set requeueAfter when reconciliation can't complete

### ISSUE THREAD

**Issue by Cerebus** [operator-framework/operator-sdk#2502]
## Feature Request

**Is your feature request related to a problem? Please describe.**
If reconciliation can't complete, an ansible operator can currently only set `reconcilePeriod`  or fail the play and trigger exponential backoff.  In some cases, e.g., where reconciliation is dependent on an external system or human action, neither option is appropriate.

Example use case:  An external certificate issuer with auto-enrollment may in some cases accept a request but queue it for human review.  If the operator fails reconciliation in this case, exponential backoff will waste resources since the time scale of the approval may be hours or days.  Setting an appropriate `reconcilePeriod` on the watcher will result in slow reconciliation when other failures occur that have faster recovery periods  (e.g., a transient network failure, or a dependent resource waiting its own reconciliation).

**Describe the solution you'd like**
Go operators can set `result.RequeueAfter` to set retry on a per-resource basis.  Exposing this to the ansible-operator would allow operators to set appropriate retry timers.

**Comment by camilamacedo86** [comment]
Hi @Cerebus, 

Thank you for raising your input. So, let's go to the current behaviour and your scenario. 

If some task fails by default it will be keeping trigger the reconcile until it is done successfully. However, to deal with a situation that you know that the reconcile should not be automatically re-trigger, as you described, then you can use the ` ignore_errors: true` in order to flag that if some error in your task is faced then, it should be ignored. 
 
``` yaml
---
- name: set example-memcached namespace to {{ state }}
  k8s:
    api_version: v1
    kind: Namespace
    name: example-memcached
    state: "{{ state }}"
  ignore_errors: true
```

This information is the [user_guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/dev/developer_guide.md).

And then, you can configure `reconcilePeriod` in order to ensure that the operator will try to perform the task again after X period. 

Its is make sense? Is not it solving the scenario described by you above?

**Comment by Cerebus** [comment]
I'm not tracking completely.  As I read `reconcilePeriod` it controls the requeue interval for a failed reconciliation, i.e., when ansible exits with an error (unsuppressed task failure or the `fail` module).  Is that not the case?  

Also, setting `reconcilePeriod` globally wouldn't be a good idea anyway.  I don't need to continually re-evaluate the CR after reconciliation completes. 

The example I gave above is my actual use case.  See https://cert-manager.io.  cert-manager reconciles Certificate CRs in two stages.  First, by creating a CertificateRequest CR tagged for a selected Issuer.  Issuer controllers watch CertificateRequest CRs and reconcile them by getting a cert from an authority and updating the CertificateRequest CR status with the certificate.  The Certificate controller completes reconciliation by watching the CertificateRequest CR and updating the TLS Secret referenced in the Certificate CR with the `tls.crt` and `ca.crt` values. 

I'm implementing an out-of-tree Issuer controller.  The controller watches CertificateRequest CRs and submits the PKCS#10 for signing.  The problem is in some cases the request may be held for human review.  In other cases it might be rejected with a permanent error.  In other cases, transient network or service issues might cause the playbook to fail.

I can deal with transient errors by failing the play and letting the control loop's backoff/retry function take over.

I can deal with the permanent reject b/c Certificate controller recognizes a 'failed' state on the CertificateRequest CR and stops reconciliation of the Certificate CR.  That's actually a *successful* reconciliation of the CertificateRequest CR, if you will.

It's that middle error where the cert is stuck in a pending state--it was successfully submitted, but I didn't get a signed cert back.  The cert-manager's in-tree Issuer controllers have a state for this and can handle it, but they use the `result.requeueAfter` return in Go.  

I need a similar way to *selectively* set a CertificateRequest CR to be re-reconciled at some future time.  Setting it globally wastes resources on CRs that have completed reconciliation.  The exponential backoff has a small increment and spams re-reconcile attempts that I already know won't succeed.

Does that help?

**Comment by camilamacedo86** [comment]
Hi @Cerebus, 

**See:**

<img width="947" alt="Screenshot 2020-02-06 at 14 28 32" src="https://user-images.githubusercontent.com/7708031/73945919-f8b03280-48ec-11ea-9591-e672f9ed7239.png">

From the [doc](https://github.com/operator-framework/operator-sdk/blob/f9f0d18684a071ee2a2332cf4e1e509bf0875c54/doc/ansible/user-guide.md#watches-file)

**Example:**

```yaml
---
- version: v1alpha1
  group: app.example.com
  kind: AppService
  playbook: playbook.yml
  maxRunnerArtifacts: 30
  reconcilePeriod: 5s
  manageStatus: False
  watchDependentResources: False
  finalizer:
    name: finalizer.app.example.com
    vars:
      state: absent
```
From [Advanced Options for Operator SDK Ansible-based Operators](https://github.com/operator-framework/operator-sdk/blob/f9f0d18684a071ee2a2332cf4e1e509bf0875c54/doc/ansible/dev/advanced_options.md#advanced-options-for-operator-sdk-ansible-based-operators)

In the above example, if an error is faced when the CR of `AppService` be reconciled it will be ignored and it will not re-trigger the reconciliation since the  ` manageStatus: False` and then, after each '5' seconds its CR will be reconciled again.  

**Regards:**

> As I read reconcilePeriod it controls the requeue interval for a failed reconciliation, i.e., when ansible exits with an error (unsuppressed task failure or the fail module). Is that not the case?

No. It means that the CR will be reconciled always after X time, and that the role/playbook will be executed after each X period. ( like a cron )

> Also, setting reconcilePeriod globally wouldn't be a good idea anyway. I don't need to continually re-evaluate the CR after reconciliation completes.

I am not sure if I understood what do you mean with "globally", the option will be specific for the "watch"(playbook/role) configuration made and not across ALL project which can have how many CRD/CRS (playbook/roles) as required. 

**Extra:**

Also, by using Ansible you are able to indeed create conditionals and checks to define what action should or not be performed in the scenario and avoid errors as well. 

Is it make sense? If not, could you please give an example of a watch set up with the option/RFE that you are requesting and a small description of how it should works?

**Comment by Cerebus** [comment]
What you describe is the behavior I understood.  By "globally" I mean "on every CR of that group/kind/version."

This won't work in my use case.  Once I reconcile the CertificateRequest CR (by adding the certificate to it), reconciliation is finished and does not need to be repeated.  Setting `reconcilePeriod` would cause these resources to be processed.  Yes, I can detect this and abort early, but it's inefficient.

cert-manager handles the rest of CertificteRequest's lifecycle, and will update it (currently it deletes/recreates the CR, but that may change) when it needs to be reconciled by the Issuer controller again.

I'll knock up an proposal and example and post it later.

**Comment by fabianvf** [comment]
I've looked into this one a bit and it looks like it's a little tricky to communicate that information back to the operator process. The most promising approach I've looked of so far is to add a custom module (`requeue_after` or `set_requeue` or something like that) to the [operator-sdk ansible collection](https://github.com/operator-framework/operator-sdk-ansible-util) and add a bit of logic to the [core event loop](https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/controller/reconcile.go#L171-L189) to detect and set the requeue period when that module is called. I haven't had time to dig into implementation yet myself but I'd be happy to provide some guidance if anyone wanted to pick this up.

**Comment by camilamacedo86** [comment]
After spoke with @fabianvf I could understand better the need and his suggestion. So, following the summary of the info as the @fabianvf suggested solution.   

### Suggested Solution 

**Story**

- I am as an Ansible-Operator dev, would like to have a mechanism to stop the reconciliation and have it resume after waiting for a specific amount of time when some specific conditional is defined in the events but not as cronJob (reconcilePeriod).

**Example**

```
- name: Lookup CSR
  k8s_info:
    api_version: certificates.k8s.io/v1
    kind: CertificateSigningRequest
    name: my-csr
    namespace: '{{ meta.namespace }}'
  regiser: csr
- when: not csr or csr.status.state != Approved
  block:
  - name: Create a Certificate signing request
    k8s:
      definition: "{{ lookup('template', 'csr.yaml.j2') }}"
  - name: Set requeueAfter to 1 day because we need to wait for administrator approval
    operator_sdk.util.requeue_after:
      time: 24h
  - name: End play early
    meta: end_play
```

**Acceptance Criteria*

- When the `operator_sdk.util.requeue_after` be added in the events it should call the `result.requeueAfter` with the `time` amount.  
- docs update with this new custom Ansible module for SDK. 

**Extra info*
- SDK has a custom module implemented which is the `k8s_status`. See [here](https://github.com/operator-framework/operator-sdk-ansible-util/blob/master/plugins/modules/k8s_status.py)
- To achieve it will be probably required to: 
Check that the event has the `requeueAfter` [here](https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/controller/reconcile.go#L172) and then when the ansible actually terminates we will use it. May [here](https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/controller/reconcile.go#L198)

@Cerebus feel free to contribute with as well if you wish.

**Comment by tobernguyen** [comment]
I'm willing to pick this up if nobody started on this yet.

**Comment by camilamacedo86** [comment]
Hi @tobernguyen, 

Please, feel free to assign it to yourself and your help on it is more than welcome 👍

**Comment by camilamacedo86** [comment]
Hi @fabianvf, 

It shows already implemented. See https://sdk.operatorframework.io/docs/ansible/development-tips/#ansible-operator-annotations. We can use the annotation ansible.operator-sdk/reconcile-period: "30s" via annotations in the CR. 

Also, see the code [here](https://github.com/operator-framework/operator-sdk/blob/master/pkg/ansible/controller/reconcile.go#L50). 

So, I think we could close this one. WDYT?

**Comment by fabianvf** [comment]
@camilamacedo86 I think this is a little different, this is asking for a way to set a timed requeue for a specific CR intentionally during the operator run, not a way to run the operator on a specific schedule. You could kind of approximate this behavior with the annotation on the resource I suppose, but I don't think it's quite the same as using the built-in requeueAfter behavior that Golang operators have access to.
