### ISSUE TITLE
How to get the old CR

### ISSUE THREAD

**Issue by ustcsunshine** [operator-framework/operator-sdk#2506]
Link: https://github.com/operator-framework/operator-sdk/issues/2501

**Context**
I define a CRD called EventSchema which stores the table schema. When users want to add a table column, they should update the schema. Therefore I need to get the old CR and compare it with the new CR to know what columns they add.

**Question**
How can I get the old CR?
In my understanding, it's necessary to know what difference between the old one and the new one which we can use them to backup or log or any other usage.

@camilamacedo86 I still don't clear why operator sdk cannot get the old CR. I see informer of another operator can get the old one. 
Here is the link: https://github.com/kubernetes/sample-controller/blob/master/controller.go#L118

```
UpdateFunc: func(old, new interface{}) {
			newDepl := new.(*appsv1.Deployment)
			oldDepl := old.(*appsv1.Deployment)
			controller.handleObject(new)
}
```

**Comment by camilamacedo86** [comment]
HI @ustcsunshine, 

**Regards:**
 
> How can I get the old CR?
> In my understanding, it's necessary to know what difference between the old one and the new one which we can use them to backup or log or any other usage.

Just to start, let's keep in mind that: [CustomResourceDefinitions can be used to implement custom resource types for your Kubernetes cluster. These act like most other Resources in Kubernetes, and may be kubectl apply'd, etc.](
https://github.com/kubernetes/sample-controller#use-cases)

Basically, the CRDs are a definition of our customized K8S "Objects" (our API), and the CRs are an "instance" of them. So, if you update the CR then, you will NOT find the new and old versions of them stored in the cluster. You will have just the same CR with the new values (you can check it via the `kubectl edit` command). 

> @camilamacedo86 I still don't clear why operator sdk cannot get the old CR. I see informer of another operator can get the old one.
> Here is the link: https://github.com/kubernetes/sample-controller/blob/master/controller.go#L118

The old and new are vars in its context which shows how to develop observers/"watches".  **By using the Operator Framework, you have this feature implemented already and will not be required to do this implementation.** Note that by using the watch feature provided, you will be able to re-trigger the reconcile when some change occurs (handling create/update/delete events), however, **you will NOT have the information over what was changed exactly.**  

**Example:**

```
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}
```

**(+More Info)**

- See the [Controller configurations](https://github.com/operator-framework/operator-sdk/blob/e4d29c8ca1ff3ccc5ebef6f1695730b84cf8729e/doc/user-guide.md#controller-configurations) 
- See the godocs of [EnqueueRequestsFromMapFunc](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/handler#EnqueueRequestsFromMapFunc)

---


PS.: _The [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime), which is responsible for providing the controller logic, knows that has a change in the resource by checking the resource version and not all CR values as it is done in the sample sent by you.  [newDepl.ResourceVersion == oldDepl.ResourceVersion](https://github.com/kubernetes/sample-controller/blob/master/controller.go#L133) . See [here](https://github.com/kubernetes-sigs/controller-runtime/blob/fde7f3899510e4361a7043f8fdafc660defb71ef/pkg/source/internal/eventsource.go#L82) an part of controller-runtime code._

---

> I define a CRD called EventSchema which stores the table schema. When users want to add a table column, they should update the schema. Therefore I need to get the old CR and compare it with the new CR to know what columns they add.

In order to know the previous values of the CR's status/specs when the watch re-trigger the reconcile handling create/update/delete events then, is required to keep it since as described above Kubernetes API will not hold an old/new version of its resources in the cluster.  

A possible solution may be:
 
- Make a copy of all resources controlled by with a name such as `cp_<name>`
- Then, when the reconcile be retrigged, you will be able to the get the latest copy version (old) and compare with the (new) one which is the newest version in the cluster.  

**IMPORTANT:** The above idea is just to illustrate a possibility and I am not saying that it is ideal since it is really something up to the business requirements and context that you're trying to address.

WDYT @joelanford @hasbro17 @estroz? Have you a better idea just to illustrate the possibilities?  Also, please, let me know if I am wrong here. 

**NOTE:** The link provided is not a good reference for you check how you can achieve your needs with Operator Framework. I'd like to recommend you use the [Getting Started](https://github.com/operator-framework/getting-started) and [Memcached Sample](https://github.com/operator-framework/operator-sdk-samples/tree/master/go/memcached-operator) as reference. 

Please, let us know if it clarifies your concern.

**Comment by joelanford** [comment]
@ustcsunshine The reconcile pattern intentionally forces you into this problem :). The reason is that CR updates may be coalesced or missed, and your operator should be impervious to those issues.

You should not try to "save" the schema data somewhere in the Kubernetes API because that can become out-of-date from reality.  For example, a DB admin could login and change the schema outside the scope of the operator.

So the solution is for your operator to always fetch the state of the world during a reconciliation. In your case, it sounds like you need to have your operator connect to the database and get the current schema, compare the current schema to what your CR specifies, and then apply the necessary schema changes based on the difference.

See the [controller-runtime docs](https://github.com/kubernetes-sigs/controller-runtime/blob/master/FAQ.md#q-how-do-i-have-different-logic-in-my-reconciler-for-different-types-of-events-eg-create-update-delete) for more info about this.

**Comment by ustcsunshine** [comment]
Thanks @camilamacedo86 @joelanford 

@camilamacedo86 for your example below, how can I know what the operation like `Create` or `Update` or `Delete`? 
```
// Watch for changes to primary resource Memcached
err = c.Watch(&source.Kind{Type: &cachev1alpha1.Memcached{}}, &handler.EnqueueRequestForObject{})
if err != nil {
    return err
}
```

**Comment by camilamacedo86** [comment]
Hi @ustcsunshine, 

As explained in the previous comment: 

>  Note that by using the watch feature provided, you will be able to re-trigger the reconcile when some change occurs (handling create/update/delete events), however, you will NOT have the information over what was changed exactly.

So, you will NOT have this information. And then, as described by @joelanford  above: 

> The reconcile pattern intentionally forces you into this problem :). The reason is that CR updates may be coalesced or missed, and your operator should be impervious to those issues. 
See: https://github.com/operator-framework/operator-sdk/issues/2506#issuecomment-583460961

The idea is the solution be independent where you will ensure in the implementation that the resources are in the expected states.

Regards your scenario, @joelanford suggested that: 

> So the solution is for your operator to always fetch the state of the world during a reconciliation. In your case, it sounds like you need to have your operator connect to the database and get the current schema, compare the current schema to what your CR specifies, and then apply the necessary schema changes based on the difference.

Which means that you will not need to know the type of event. E.g if is deleted you will not find the resource and if it was created/updated you will reflect the action according to your business rules. 

Also, I'd like to recommend you to follow up the [Getting Started](https://github.com/operator-framework/getting-started) and see the blog [Getting started with Golang Operators by using Operator SDK](https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/) which were suggested before if you did not yet, it is explained with examples there which make easier the understanding and I hope that it helps you get better how you can attend your needs as well. 

In this way, shows that your question is pretty covered with the answers provided so far and then, I am closing this one. However, please feel free to raise new issues with other needs and/or questions as ask for we re-open this one if you see that it still required.

**Comment by abdulhaseeb2** [comment]
Hi,
Just wanted to know any update on retrieving old CRs?

**Comment by mstrYoda** [comment]
Lets assume we are creating pods according to our CR spec.replicas field. User created a CR with replicas count 3. And then update that resource with replicas count 1. How do we know that we need to find other pods and delete all of them? Are not we need to compare current resource with the previous one?

Or... Finding and deleting old pods using ownerReference is the best practice?
