### ISSUE TITLE
update deprecated apiextensions.k8s.io/v1beta to apiextensions.k8s.io/v1

### ISSUE THREAD

**Issue by haoqing0110** [operator-framework/operator-sdk#2579]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Example: "I have an issue when (...)"

**Describe the solution you'd like**
Now the operator-sdk generates CRD with default apiVersion `apiextensions.k8s.io/v1beta1 `.

Refer to https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/ , the `apiextensions.k8s.io/v1beta1` version of CustomResourceDefinition is deprecated in v1.16 and will no longer be served in v1.19. Need use `apiextensions.k8s.io/v1` instead.

Does `operator-sdk` has any plan to update `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` ?

**Comment by camilamacedo86** [comment]
Hi, @haoqing0110, 

The SDK currently is using the 1.16.2. The plan is follow up the Kubernetes API versions and its API. However, we cannot give an ETA for that.

**Comment by arthurbarr** [comment]
@camilamacedo86 You say that the Operator SDK is using Kubernetes 1.16.2, but it isn't supporting the available APIs in Kubernetes 1.16.  It seems to me that the single most important API to the Operator SDK is the version of apiextensions.k8s.io, and it's not yet been updated in the five months since it went GA.

Is there any way we can track progress towards full Kubernetes 1.16 support?  Is there any way we can contribute to this work (I haven't found any other issues related to it), as we would really rather not put effort into working with deprecated APIs.  For example, I think we need apiextensions.k8s.io/v1 support to use default values, which seem like a real pain to implement directly in the Go code, especially when native support in the Open API schema is right around the corner.

**Comment by camilamacedo86** [comment]
Hi @arthurbarr, 

> You say that the Operator SDK is using Kubernetes 1.16.2, but it isn't supporting the available APIs in Kubernetes 1.16.

Sorry, but it shows a misunderstand. Where did you saw it? 

The SDK is using the  Kubernetes 1.16.2 and all resources generated by it is 100% compatible with that. The question raised here was over when the SDK will generate the CRDs with `apiextensions.k8s.io/v1` instead of `apiextensions.k8s.io/v1beta1` which was deprecated but still valid until k8s in v1.19. 

Unfurtunilly,  @arthurbarr we have not an ETA to share with about it.
However, I am ree-opening this one and pinging @dmesser in the case of he would like to supplement it as well

**Comment by arthurbarr** [comment]
I agree that `apiextensions.k8s.io/v1beta1` is still technically valid in Kubernetes V1.16.  However, we really want to use the features offered by `apiextensions.k8s.io/v1`, which is also valid and supported by Kubernetes, but can't be generated by the current Operator SDK.  Thanks for re-opening the issue.

**Comment by Nik-Novak** [comment]
I couldn't agree more. There are tools being developed that strictly focus on v1, and not being able to use them with operators is frustrating

**Comment by thegridman** [comment]
Currently though the Operator SDK README.md says that you need:

> Access to a Kubernetes v1.12.0+ cluster

Presumably if you change the Operator SDK to generate CRDs with `apiextensions.k8s.io/v1` this will not be valid for a 1.12.0 K8s cluster so the Operator SDK will only work on k8s 1.16.0+. Believe it or not, a lot of us are for various reasons stuck on older k8s versions.

**Comment by arthurbarr** [comment]
Presumably the current version of the SDK would continue to work.  Also I imagine the Operator SDK *could* feasibly offer the choice of which CRD version to create, given that all the code to create the beta version already exists.  It's worth noting though that the [proposal for Kube 1.17 support](https://github.com/operator-framework/operator-sdk/blob/master/doc/proposals/kubernetes-1.17.md) says "The goal is to update the Kubernetes dependencies of the Operator SDK to use 1.17", which could be read as saying that an upcoming version might remove backwards compatibility.  That may be me reading too much into it though.

**Comment by camilamacedo86** [comment]
Hi @arthurbarr, @Nik-Novak and @haoqing0110, 

See that the  `apiextensions.k8s.io/v1beta1` was deprecated in the 1.16 and it will still be supported until the K8S version v1.19. And then, the latest release of K8S API is 1.17 which means that we are really far away of 1.19. 

The SDK will following API the K8S API since it is used by it, however, we cannot provide at the moment an ETA for the SDK start to generate the CR/CRDS using `apiextensions.k8s.io/v1`. Also, I'd like to share that we will take in count your suggestions regards keep the supportability for both.

However, could you please let us known what need that you are not able to achieve so far by using the  `apiextensions.k8s.io/v1beta1`?  Could you please share what scenario is not achievable with?

c/c @dmesser

**Comment by dmesser** [comment]
I think it would make sense to offer a CLI switch when adding a new `kind` when we change the default to be `v1` instead of `v1beta1`

**Comment by arthurbarr** [comment]
There are a couple of issues with `apiextensions.k8s.io/v1beta1` that I'm aware of:

1. No support for default values.  Although we can specify default values with kubebuilder annotations, and have them appear in the Open API schema and CRD, we can't deploy that CRD.  It appears that Kubernetes stops you using that until you get to the v1 API.  Managing defaults across a large CRD is going to be a real pain.
2. The v1 API also introduces Open API schema validation for multiple versions of our operator's API.  e.g. if we create a v1, v2 and v3 of our custom API, then `apiextensions.k8s.io/v1beta1` will only have schema validation for the v3 API.  We will need validation across all versions, which requires the `apiextensions.k8s.io/v1` API.

I'm more than willing to be corrected if I'm wrong here.

The argument that it's OK to use beta APIs even though they've been superceded and deprecated is not encouraging.  We would like to fully adopt the Operator SDK, but a big delay in support for new features could present real problems, *especially* when we're talking about missing out on quality improvements (e.g. switch from beta to GA).

**Comment by arthurbarr** [comment]
There are a couple of issues with `apiextensions.k8s.io/v1beta1` that I'm aware of:

1. No support for default values.  Although we can specify default values with kubebuilder annotations, and have them appear in the Open API schema and CRD, we can't deploy that CRD.  It appears that Kubernetes stops you using that until you get to the v1 API.  Managing defaults across a large CRD is going to be a real pain.
2. The v1 API also introduces Open API schema validation for multiple versions of our operator's API.  e.g. if we create a v1, v2 and v3 of our custom API, then `apiextensions.k8s.io/v1beta1` will only have schema validation for the v3 API.  We will need validation across all versions, which requires the `apiextensions.k8s.io/v1` API.

I'm more than willing to be corrected if I'm wrong here.

The argument that it's OK to use beta APIs even though they've been superceded and deprecated is not encouraging.  We would like to fully adopt the Operator SDK, but a big delay in support for new features could present real problems, *especially* when we're talking about missing out on quality improvements (e.g. switch from beta to GA).

**Comment by dmesser** [comment]
@arthurbarr I think you raise valid points. Would you mind discussing this in our next community meeting? https://github.com/operator-framework/community/projects/3
We are also always happy to accept contributions in this space.

**Comment by arthurbarr** [comment]
@dmesser Tried to join the community meeting, but I got a message saying it was either over, or I wasn't authorized.  Perhaps we can try again at the next meeting.

**Comment by arthurbarr** [comment]
@dmesser Tried to join the community meeting, but I got a message saying it was either over, or I wasn't authorized.  Perhaps we can try again at the next meeting.

**Comment by camilamacedo86** [comment]
Hi @arthurbarr, 

I am sad that you could not attend it. Regards this issue I'd like to share with you that it is prioritized. Note that this change does not just impact the generation of CR/CRDs but the features which will consume that as well. Also, it is important to highlight that SDK is integrated with OLM, then we would also need to check it there. So, it shows a little more effort that just gen the resources as you can see. However, all is already tracked and properly addressed. 

Really thank you for raising it and feel free to contribute with.

**Comment by Ahtahany** [comment]
Dears,
i upgrade the  crd to  apiVersion: flink.k8s.io/v1 and cannot upgrade  the flink operator in this version  is there is any upgrade for flink operator to apiVersion: flink.k8s.io/v1 ??

**Comment by Ahtahany** [comment]
Dears,
i upgrade the  crd to  apiVersion: flink.k8s.io/v1 and cannot upgrade  the flink operator in this version  is there is any upgrade for flink operator to apiVersion: flink.k8s.io/v1 ??
