### ISSUE TITLE
How to update CR when an operator is upgraded

### ISSUE THREAD

**Issue by 27149chen** [operator-framework/operator-sdk#2616]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**
community best practices

## Question

When an operator is upgraded to a new version, should the field of the previous CR be upgraded too?
There are some situations (The premise of this question is that one version of operator can only manage one version of application):
1. no crd changes, but some fields are changes in CR, like the image link, should these fields be upgraded automatically?
2. crd is changed, but api version is not, should the CR be upgraded to new version automatically? like setting some default values for new fields?
3. crd and its api version is changed, should the CR be migrated to new api version automatically?

**Environment**
* operator-sdk version:
v0.14.0

* Kubernetes cluster kind: 
OpenShift

**Comment by camilamacedo86** [comment]
Hi @27149chen , 

When following the Getting Started, one of the first steps is to run the command `operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached`. The purpose of this command is to generate Custom Resource (CR) and Custom Resource Definition (CRD) resources for the Memcached Kind. This command is creating the API with the group/domain `cache.example.com`, and version `v1alpha1`  which uniquely identifies the new CRD of the Memcached Kind.

Consequently, by using the Operator SDK tool, we can create our APIs and objects that will represent our solutions on these platforms. The Getting Started tutorial adds only a single kind of resource; however, it could have as many Kinds as needed (1…N). Basically, the CRDs are a definition of our customized Objects, and the CRs are an instance of it.

So, the apiVersion in related to the interface defined in the CRD. If the CR be recreated or needs not updated with new values then it should not the apiVersion. 

In this way, the apiVersion should just upgrade if the CRD changed. Please, see the [doc](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/migrating-existing-apis.md#migrating-existing-kubernetes-apis)

Also, please let us know if the above information answered your question and if we can close this one.

**Comment by 27149chen** [comment]
@camilamacedo86 , sorry it doesn't answer my question. I know how to update the code, my question is how to handle the existing crs (the crs which were deployed into the ocp cluster previously) during operator upgrade. Operator v1 is deployed, now I'm going to upgrade it to v2, should the crs be updated automatically? or should they be updated by user manually? Which one is better and recomended?

**Comment by 27149chen** [comment]
@camilamacedo86 please reopen it

**Comment by camilamacedo86** [comment]
Hi @27149chen, 

Sorry if the first comment was not clear enough. So, following all answers and comments inline:

> When an operator is upgraded to a new version, should the field of the previous CR be upgraded too?

When following the Getting Started, one of the first steps is to run the command `operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached`. The purpose of this command is to generate Custom Resource (CR) and Custom Resource Definition (CRD) resources for the Memcached Kind. This command is creating the API with the group/domain `cache.example.com`, and version `v1alpha1` which uniquely identifies the new CRD of the Memcached Kind.

Consequently, by using the Operator SDK tool, we can create our APIs and objects that will represent our solutions on these platforms. The Getting Started tutorial adds only a single kind of resource; however, it could have as many Kinds as needed (1…N). 

**Basically, the CRDs are a definition of our customized resources (Objects), and the CRs are an instance of it.**

So, CR is an instance of CRD. Then, it will be updated If you need update/change the values used on it.

> no crd changes, but some fields are changes in CR, like the image link, should these fields be upgraded automatically?

We do not recommend configuring the image in the CR. The recommendation is stored the image/tags versions in the Operator EnvVars. Then, each Operator version will use its supportable/compatible images versions. 

> crd is changed, but api version is not, should the CR be upgraded to new version automatically? like setting some default values for new fields?

If the CRD is changed then it means that you should change the API version since you change the interface. So, the scenario `crd is changed, but api version is not,` should not be done.

> crd and its api version is changed, should the CR be migrated to new api version automatically?

If you change the CRD then you will have a new version of its API which means that you can have new CR's which will use the new version or indeed both if the previous version also still valid.  For example, could you not have a Deployment applied in the cluster which using an old version of the K8S API (apps/v1beta)  and other using a new version(apps/v1) if both API definitions are available on it?

So, as illustrated in the above example, you can have more than one API version available and provide by your project and then each CR will implement the specific version defined of its CRD. In this way, you might have a CR A which is using/defined by the CRD B version beta as the CR B which is using/defined by the CRD B version alpha.

Also, see:
- [Migrating Existing Kubernetes APIs](https://github.com/operator-framework/operator-sdk/blob/master/doc/user/migrating-existing-apis.md#migrating-existing-kubernetes-apis) to understand how is recommend migrate the APIs. 
- If you are using and looking for to understanding how the upgrade versions and how to work with when you are using OLM and its recommendations, then you should check in its docs. See: [How do operator upgrades work in Operator Lifecycle Manager (OLM)?](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md)
- If you are looking for know how to work with the dependency between different operators in OLM see in the section  key concepts section [dependency resolution](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/README.md#dependency-resolution) 

I am closing this one, however, please feel free to ping us if you think that it should be re-opened

**Comment by 27149chen** [comment]
Hi, @camilamacedo86 thank you for your reply.

> We do not recommend configuring the image in the CR. The recommendation is stored the image/tags versions in the Operator EnvVars. Then, each Operator version will use its supportable/compatible images versions.

Can you show me an example?

> If the CRD is changed then it means that you should change the API version since you change the interface. So, the scenario crd is changed, but api version is not, should not be done.

It is recommended to change the api version frequently? I can see that some k8s apis keep adding new fields, but the api version is always v1 (for example, field `overhead` is introduced in 1.16 for PodSpec, but the api version is still core/v1) 

> If you change the CRD then you will have a new version of its API which means that you can have new CR's which will use the new version or indeed both if the previous version also still valid. For example, could you not have a Deployment applied in the cluster which using an old version of the K8S API (apps/v1beta) and other using a new version(apps/v1) if both API definitions are available on it?

I understand that it is actually a new crd if api version is changed, my question is that: should the old cr be migrated to new cr version automatically? For example, cr instance A in example.com/v1 reprensents an app v1, and then the operator is upgraded to v2 (example.com/v2 for the same CRD is intruduced), but the cr A is still app v1. How to upgrade this app to v2 (I mean upgrade, not delete it and create a new v2)? Should it be done during operator upgrade automatically or we should ask the user to do it after the operator is upgraded?


please reopen it, thanks.

**Comment by camilamacedo86** [comment]
Hi @27149chen, 

> Can you show me an example?

In the operator.yaml you will add the EnvVar. E.g

```ymal
          env:
            - name: IMAGE
              value: "quay.io/example/my-image:v0.0.1"
```

Then you can get it from the code such as:

```go
image, found := os.LookupEnv("IMAGE")
```

> It is recommended to change the api version frequently? I can see that some k8s apis keep adding new fields, but the api version is always v1 (for example, field overhead is introduced in 1.16 for PodSpec, but the api version is still core/v1) 

If it has not a breaking change then it means that you might keep the version. And then, also means that all CR's using the CRD X version Y will still be working and valid and can be or not updated with new values. 

See: [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/)  

> I understand that it is actually a new crd if api version is changed, my question is that: should the old cr be migrated to new cr version automatically? For example, cr instance A in example.com/v1 reprensents an app v1, and then the operator is upgraded to v2 (example.com/v2 for the same CRD is intruduced), but the cr A is still app v1. How to upgrade this app to v2 (I mean upgrade, not delete it and create a new v2)? Should it be done during operator upgrade automatically or we should ask the user to do it after the operator is upgraded?

When you say "Operator Upgrade" I understand that you are speaking over "OLM lifecycle" since SDK has none related feature. So, I'd recommend you check the doc [How do operator upgrades work in Operator Lifecycle Manager (OLM)?](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/doc/design/how-to-update-operators.md) and if the information into it do not answer your questions raise an issue in https://github.com/operator-framework/operator-lifecycle-manager with your specific question over how is recommend work with. 

Please, let us know if it make sense.

**Comment by 27149chen** [comment]
> In the operator.yaml you will add the EnvVar. E.g
> 
> ```
>           env:
>             - name: IMAGE
>               value: "quay.io/example/my-image:v0.0.1"
> ```
> 
> Then you can get it from the code such as:
> 
> ```go
> image, found := os.LookupEnv("IMAGE")
> ```

It doesn't make sense. The image is a cr instance property, what if I want to create two instances with different images? How to do it in the operator manifest?

**Comment by 27149chen** [comment]
@camilamacedo86 please reopen it, thanks.

**Comment by camilamacedo86** [comment]
HI @27149chen, 

Our recommendation for the images:tags will add they in the EnvVar of the operators because in this way you can define that the Operator A version X can only work with the image:tag N.

Another possible option for your scenario could be in the EnvVar add a range of supportable versions and then, in the controller, you will verify the CR spec to ensure that the image tag informed is compatible/supportable by the Operator A version X. 

Please, let me know if it makes sense for you.

**Comment by 27149chen** [comment]
@camilamacedo86 it is not just because of versioning, in some cases, the user may need to use their private image registry. So I think it is impossible to validate the supported versions by image name and tag

**Comment by camilamacedo86** [comment]
Hi @27149chen, 

If you allow the user add any image:tag whiteout do any validation then it means that your operator A version X supports and it's compatible with all which I do not think that would be achievable. 

You are free to add the images:tag in the CR, however, as described above we recommend you use the EnvVars in order to be able to create a matrix of compatible. The operator envVars will be associated with the Operator version. 

All your questions were answered, could you please let us know what do believe that still missing address here for we are able to close this one?

**Comment by 27149chen** [comment]
ok, thanks. close it.

**Comment by camilamacedo86** [comment]
Hi @27149chen, 

Thank you for your reply. Please, feel free to raise new issues with. other questions, issue and or RFE as well.
