### ISSUE TITLE
Failed to list *apiextensions.CustomResourceDefinition: v1.ListOptions is not suitable

### ISSUE THREAD

**Issue by robotmaxtron** [operator-framework/operator-sdk#2633]
## Bug Report

**What did you do?**
Using the rbac-permissions-operator, refresh the roles above based on the CRDs deployed in the OSD cluster

**What did you expect to see?**
Expected to be able to list the CRD as part of a reconcile loop.

**What did you see instead? Under which circumstances?**
When testing the controller in crc with `operator-sdk up local`, it loops over this error.

```
E0304 13:17:11.492826  498364 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a/tools/cache/reflector.go:98: Failed to list *apiextensions.CustomResourceDefinition: v1.ListOptions is not suitable for converting to "apiextensions.k8s.io/__internal" in scheme "pkg/runtime/scheme.go:101"
```

**Environment**
* operator-sdk version: 

operator-sdk version: "v0.12.0", commit: "2445fcda834ca4b7cf0d6c38fba6317fb219b469",

* go version:

go version go1.13.6 linux/amd64

* Kubernetes version information:

* Kubernetes cluster kind: Using crc for testing locally, v4.3

* Are you writing your operator in ansible, helm, or go? go

**Additional context**
Tried to isolate the controller into a new operator in https://issues.redhat.com/browse/OSD-3016, the operator is attached to the Jira and seems potentially related to https://github.com/operator-framework/operator-sdk/issues/1927

**Comment by camilamacedo86** [comment]
HI @robotmaxtron, 

Could you please answer the following question?

1. What is `rbac-permissions-operator`? Is a project that you have?

2. What do you mean with ` refresh the roles above based on the CRDs deployed in the OSD cluster`? Did you update the roles configuration? Did you change it? 
3. 

The error faced:

> Failed to list *apiextensions.CustomResourceDefinition: v1.ListOptions is not suitable for converting to "apiextensions.k8s.io/__internal" in scheme "pkg/runtime/scheme.go:101"

Let to me believe that  your project is using some module that is no longer compatible, or is missing some required version/module declaration. In this way, wdyt about try to upgrade your project to use the latest version of SDK and ensure that it is using the versions of the modules as described in the in `https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v015x`?

**Comment by robotmaxtron** [comment]
@camilamacedo86 I created a new operator using operator-sdk v0.12, where the changelog show the bulk of the changes relating to CRDs. I believe the reconcile loop should be able to list and read CRD objects. 

https://github.com/robotmaxtron/isolated-crd-controller/blob/master/pkg/controller/customresourcedefinition/customresourcedefinition_controller.go

**Comment by camilamacedo86** [comment]
Hi @robotmaxtron, 

Your scenario is faced because you are adding third-party apis then, you also need to customize the metrics code implementation for it. See: https://github.com/camilamacedo86/operator-sdk/blob/master/doc/user-guide.md#default-metrics-exported-with-3rd-party-resource

This issue is similar scenario of: #2577 #1858 

Closing it as sorted out. Please, feel free to ping us and let us know if you would like to re-open it and in this way, let us know what is missing to be addressed here or we keep it open.

**Comment by lisa** [comment]
Hi @camilamacedo86 and anyone who might come across this. I have some more information to add about the issue Max and us were seeing.

I used Max's [bare repository](https://github.com/robotmaxtron/isolated-crd-controller) to try and isolate the problem. I read your comment @camilamacedo86 about metrics and thought the best course was to eliminate as much as possible from the equation to see where the problem was.

In main.go I commented out, and disabled everything relating to metrics to ensure the operator would not attempt to set up metrics. Further, in the controller's Reconcile method, I simply `return reconcile.Result{}, nil` so there's no interaction at all with the API server within the method.

I also applied a hook to the manager Kubernetes client to dump out the URLs of the API calls. The purpose is to get a sense of what the software is doing because it can often be a black box. That was based on [this gist I created for another purpose](https://gist.github.com/lisa/07128ebfa37e491b08b65036567f7037).

What I learned from purging the metrics, minimizing the Reconcile method, and printing API calls is that there doesn't appear to be any obvious connection to the errors Max (and I) receive. Further, around the error Max reported, there are no API calls. This leads me to believe the root issue is deeper in the stack. For the purposes of what Max and our team were doing, we were able to approach our use case from a different angle (aggregated roles), and thus we do not need this issue solved. However, in case others find this, or the project wishes to dig deeper, I do not think it's with metrics.

In absence of digging deeper by tracing the running code, we only have speculation. We solved our underlying need and so don't have time to dig deeper. Perhaps others might find a more in depth investigation of use.

**Comment by alexeldeib** [comment]
FWIW, I ran into a similar error in a project which was trying to do something like discovery under the hood. This is the raw error returned for  List call against the indicated type. Some code, perhaps in a deep library, or if you are using discovery perhaps somewhere in that, is trying to make the List call without appropriate permissions.

**Comment by alvaroaleman** [comment]
If you are getting this error you are most likely trying to use the internal version of the api rather than one of the external ones, xref https://github.com/kubernetes-sigs/controller-runtime/issues/1262#issuecomment-729917992

**Comment by alvaroaleman** [comment]
Also ftr if you are sure that you are using an external version of an api, your registration is most likely missing this: https://github.com/kubernetes/apiextensions-apiserver/blob/a7ee1efe41fc19623ce57f047c7595d624df4c17/pkg/apis/apiextensions/v1beta1/register.go#L53

**Comment by wreed4** [comment]
THANK you @alvaroaleman! I've been looking at this forever.  trying to do mock type in envtest.  For anyone else who finds this, this is the magic incantation that worked.

```golang
	mockCrd := &apiextensions.CustomResourceDefinition{
                 // CRD IMPL HERE (I generated it in a different project then constructed it from the yaml that project gave me)
	}

	s := scheme.Scheme
	gv := schema.GroupVersion{
		Group:   "mock.io",
		Version: "v1",
	}
	s.AddKnownTypes(gv, &MockObj{})
	metav1.AddToGroupVersion(s, gv)

	testEnv = &envtest.Environment{
		Scheme: s,
		CRDs:   []*apiextensions.CustomResourceDefinition{mockCrd},
	}
	cfg, err := testEnv.Start()
```

The missing line was as @alvaroaleman said
```golang
	s.AddKnownTypes(gv, &MockObj{})
```

I have no idea if this is right, but the way I read that is you need to inform the metav1 package about the new group and version you're creating as well as the scheme you're setting up so that they match.
