### ISSUE TITLE
Any plans to support admission controllers?

### ISSUE THREAD

**Issue by n3wscott** [operator-framework/operator-sdk#269]
Context https://kubernetes.io/docs/admin/admission-controllers/

It would be neat to allow a handler the ability to add webhooks to validate and mutate the CR if required, see https://github.com/kubernetes/kubernetes/blob/01c74145c7b655525fcfcd00720b918d926aa298/pkg/apis/admission/types.go#L79

**Comment by spahl** [comment]
Assigned to Haseeb to take a look.

**Comment by anandsinghkunwar** [comment]
Isn't it possible to just use the `controller-runtime` webhooks as is?

**Comment by hasbro17** [comment]
Since this is already supported via the controller-runtime APIs I would defer to that for now.
https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg#hdr-Webhook
https://github.com/kubernetes-sigs/controller-runtime/tree/master/example

We could possibly add some scaffolding and docs to show how to use the webhook server APIs.

**Comment by hasbro17** [comment]
Closing this in favor of #1217 and #1218 
We'll track the feature requests for adding scaffolding/docs for validating and mutating admission webhooks over there.
