### ISSUE TITLE
Delete events are not reliable

### ISSUE THREAD

**Issue by lionelvillard** [operator-framework/operator-sdk#270]
The sdk informer keeps an in-memory list of delete objects (https://github.com/operator-framework/operator-sdk/blob/v0.0.5/pkg/sdk/informer/informer.go#L42) which means that delete events are not reliable (ie. they are lost when the informer dies). 

Instead the sdk should rely on CRD finalizers.

**Comment by hasbro17** [comment]
@lionelvillard Agreed. Keeping the list of in-memory delete objects was a workaround to fulfill our initial API specification that the handler would receive a delete event with the last know object state. However as you pointed out that's inherently unreliable if the operator is down and misses the delete event.

In most cases the operator simply [ignores](https://github.com/operator-framework/operator-sdk/blob/ef94d7384ebb7385478ed8d1aa332cddfbd6c675/example/memcached-operator/handler.go.tmpl#L30-L34) delete events since it's expected that all secondary resources will be cleaned up by the garbage collector. So we were planning on not even sending any delete events to the handler.
But if there is some other action required after a delete then Finalizers is the way to do it.

**Comment by blaggacao** [comment]
Just to clarify:

> So we were planning on not even sending any delete events to the handler.

You _were_ planning or are you _still_ considering? (apart from it's early alpha & anything can happen)

**Comment by hasbro17** [comment]
The plan is to remove the `Delete` field from the event. And also not track the in memory deleted objects list.
With CRD finalizers the SDK won't need to indicate a Delete event separately. The handler can just figure that out by looking at the DeletionTimestamp.

**Comment by joelanford** [comment]
Closing since this API was removed as of SDK version 0.1.0. Operators developed using the new SDK must use finalizers if cleanup logic goes beyond Kubernetes' garbage collection.
