### ISSUE TITLE
Operator SDK is incompatible with GoCentral go proxy because of replace directive usage

### ISSUE THREAD

**Issue by AlexeyUzhva** [operator-framework/operator-sdk#2723]
## Bug Report

**What did you do?**
Trying to use GOPROXY with operator SDK

**What did you expect to see?**
It should work

**What did you see instead? Under which circumstances?**
It's rejected because of Kubernetes v.0.0.0 version & replace directive

**Environment**
* operator-sdk version:

0.16.x

**Possible Solution**
Use standard approach to version reps instead of doing replace.

**Additional context**
Symmetric ticket to GoCentral - https://github.com/jfrog/gocenter/issues/42

From explanations:

As described [here](https://github.com/golang/go/wiki/Modules#gomod), Go Modules replace directives are only applied to the root module. If you have replace directives in a module and tries to add it as a dependency to another one, those statements will be ignored and only the require statements will be used to discover transient dependencies. To get the expected transient dependencies intended by the module authors, consumers would need to repeat the same replace statements present in the dependency go.mod file. We don't believe this is ideal in terms of dependency management.

When we process modules in GoCenter, as part of our validation process, we check if they are ready to be consumed as dependencies. We do that by mimicking the same behavior users are expected to do, which is a regular go get command fetching the module, and checking for a success. If this validation step fails it means the module is not healthy or requires additional steps to be consumed as a dependency. GoCenter will consider the module to be on a bad state and will not make it available for consumers. All information about the validation process will be available in the UI though.

**Impacts**

We're using go proxy in a corporate build servers for security reasons. Currently it doesn't work with operator-sdk.

As operator-sdk is positioned like a tool to help big k8s deployments. Which are typically developed in corporate world... I suppose some solution to this is needed. Either from Operator-SDK or GoCentral side.

**Comment by joelanford** [comment]
@AlexeyUzhva 

> To get the expected transient dependencies intended by the module authors, consumers would need to repeat the same replace statements present in the dependency go.mod file. We don't believe this is ideal in terms of dependency management.

We agree, but it is sometimes necessary, and it _is_ supported by the Go tooling.

> When we process modules in GoCenter, as part of our validation process, we check if they are ready to be consumed as dependencies. We do that by mimicking the same behavior users are expected to do, which is a regular go get command fetching the module, and checking for a success. If this validation step fails it means the module is not healthy or requires additional steps to be consumed as a dependency. GoCenter will consider the module to be on a bad state and will not make it available for consumers. All information about the validation process will be available in the UI though.

This seems to be the true source of the problem. There are many healthy projects that require `replace` directives due to a variety or reasons (e.g. conflicts between dependencies, dependencies not being module aware, etc.)

---

The good news is that as more and more projects become module-aware, the need for `replace` directives is decreasing. 

For Kubernetes, the use of `replace` directives has been necessary for awhile. The Kubernetes community made great strides to help resolve this around the time that 1.17 was released. When we update our dependencies to Kubernetes 1.17, many of the v0.0.0 and corresponding `replace` directives will be able to be removed.

However, I will caution again that `replace` directives ARE supported by the Go tooling, and there are valid reasons they are used. We would rather not have `replace` directives in our  `go.mod` file for the reason you describe, and we only add `replace` directives when they are required. Rest assured that it is our goal to reduce our use to 0, but thus far it has not been possible.

Lastly, if you notice that we have extraneous or unnecessary replace directives, we would gladly accept PRs to remove them :)
