### ISSUE TITLE
How does one generate human readable documentation for the API's registered through the operator-sdk

### ISSUE THREAD

**Issue by davesargrad** [operator-framework/operator-sdk#2804]
## Feature Request
How do I generate documentation (either in html, or md) of the CRD API's that I create using the operator sdk?

It would be nice to see this clearly documented within the operator-sdk documentation.

Proper html documentation might look like the apis found within the [ K8S documentation](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/), for example [this ](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#daemonset-v1-apps)is the API documentation of daemonset.

Alternatively if the documentation were in a markdown (md) that would be good too. I've seen [genkubedoc ](https://github.com/kubernetes/kubernetes/blob/master/cmd/genkubedocs/gen_kube_docs.go)use this mecahnism. It uses cobra to generate markdown for core k8s applications.

It also looks like [genswaggertypedocs ](https://github.com/kubernetes/kubernetes/tree/master/cmd/genswaggertypedocs)might be related to API documentation generation. I am not sure if it is

**Comment by hasbro17** [comment]
@davesargrad We were tracking this feature upstream in controller-tools https://github.com/kubernetes-sigs/controller-tools/issues/240 although doesn't look like there's been much progress since.

There are some existing tools out there to generate the API docs from the Go type definitions although I'm not sure of the limitations if any.
This one does it in html:
https://github.com/ahmetb/gen-crd-api-reference-docs

**Comment by hasbro17** [comment]
@davesargrad For now the workaround is to use one of the existing tools like the one I linked above.
For markdown there's also the the prometheus-operator's [docgen util](https://github.com/coreos/prometheus-operator/tree/master/cmd/po-docgen) which lets you generate markdown, although I had some issues running that when I last tried it.
https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md

But longterm we still need to follow up on the upstream issue to get this added to controller-tools. We need a proposal/POC for that first though.

In any case I'm going to close this issue since we won't be adding this feature directly to the SDK but please feel free to follow up on the upstream issue.

**Comment by davesargrad** [comment]
@hasbro17 Ty for your response.. I appreciate this much. I'll look into your suggestion.
