### ISSUE TITLE
More documentation required around Unit testing with Operator SDK

### ISSUE THREAD

**Issue by mithuns** [operator-framework/operator-sdk#2805]
## Type of question

**how to implement a specific feature**
Unit testing with 3rd party objects being created in reconcile function. 
How to mock out such objects.

## Question

**What did you do?**
Tried following this 
https://github.com/operator-framework/operator-sdk/blob/master/doc/user/unit-testing.md#testing-with-3rd-party-resources

**What did you expect to see?**
Be able to mock out a third party resource. (https://github.com/prometheus/client_golang) in my case.
https://github.com/prometheus/client_golang/blob/master/api/client.go#L64
Trying to mock by adding to schemebuilder

**What did you see instead? Under which circumstances?**
Unable to add , 3rd party resource object does not implement methods that would help to typecast as runtime.Object

```
func TestUTVolumeResizeController(t *testing.T){

	//setup dummy pvc resource
	pvc := corev1.PersistentVolumeClaim{
		TypeMeta:   v1.TypeMeta{},
		ObjectMeta: v1.ObjectMeta{
			Name:                       name,
			Namespace:                  namespace,
		},
		Spec:       corev1.PersistentVolumeClaimSpec{
			Resources:        corev1.ResourceRequirements{},
			VolumeName:       volumename,
		},
		Status:     corev1.PersistentVolumeClaimStatus{},
	}
    //setup mocked prometheus client object.
	config := &promApi.Config{}
	promClient, _ := promApi.NewClient(*config)
	objs := []runtime.Object{
		&pvc,
		&promClient,  //This is what does not work.
	}

	// Register operator types with the runtime scheme.
	s := scheme.Scheme

	// Create a fake client to mock API calls.
	cl := fake.NewFakeClientWithScheme(s, objs...)
}
```
Then I tried adding this type to schemebuilder in cmd/manager/main.go
but that also complains about not having implemented deepCopy() methods

```
schemeBuilder := &scheme.Builder{GroupVersion: schema.GroupVersion{Group: "promclient.k8s.io", Version: "v1"}}
schemeBuilder.Register(&promApi.Config{},&promApi.Client{})

```

This is the actual error 
![Screen Shot 2020-04-08 at 8 32 04 AM](https://user-images.githubusercontent.com/3937267/78803301-ada9ae80-7973-11ea-903d-cf2ea1695cc3.png)

**Environment**
* operator-sdk version:

v0.16.0

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:17:09Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.10", GitCommit:"575467a0eaf3ca1f20eb86215b3bde40a5ae617a", GitTreeState:"clean", BuildDate:"2019-12-11T12:32:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
Running it in a kind cluster locally for now
kind version 
`kind v0.7.0-alpha go1.13.4 darwin/amd64`

**Additional context**
Add any other context about the question here.
So, this is more of a question, I am pretty new to doing kubernetes operators, is this even possible ? 
Am I doing something wrong ? 
Is there some other better way to unit-test reconcile function ?
If mocking out 3rd party resources is possible, can we improve the documentation around it as well ? 
This would greatly help me in having unit-tests and code coverage for my operator.
Thanks in advance.

**Comment by camilamacedo86** [comment]
Hi @mithuns, 

It is hard with the information provided and without any context over your project knows exactly what you are trying to test. However, note that you need to use the [fake client](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/fake) to perform the tests. 

By looking at your code example It shows not like the example and accurate since it is not using the fake client. See the [Step 5: Use the API to implement unit tests](https://developers.redhat.com/blog/2020/02/04/how-to-use-third-party-apis-in-operator-sdk-projects/) of this blog post. I think it may help you. 

Also, you can check a personal project to use as an example. See [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/database/fakeclient_test.go#L12) that I am creating the fake client which will be used in the tests. And then, see [here](https://github.com/dev4devs-com/postgresql-operator/blob/master/pkg/controller/database/controller_test.go#L77) the test ver the controller using it. 

Please, let us know if the information provide was enough for you are able to move forward with.

**Comment by camilamacedo86** [comment]
HI @mithuns, 

I think we could provide all information required and examples that can help you with. So, I am closing this one and please feel free to contribute by doing a PR if you see that something could be added in the docs in order to address better this subject. 

Also, feel free to ping us to re-open this one if you see that it is required.
