### ISSUE TITLE
getting Failed to list *unstructured.Unstructured: the server could not find the requested resource

### ISSUE THREAD

**Issue by raffaelespazzoli** [operator-framework/operator-sdk#2807]
## Bug Report

When I activate metrics, I constantly get this error:
```
Failed to list *unstructured.Unstructured: the server could not find the requested resource
```

I believe this issue is related to #2798 . And I am following the guidance provided in that issue (or at least I think I am).

my serveCRMetrics looks like:

```
func serveCRMetrics(cfg *rest.Config) error {
	// Below function returns filtered operator/CustomResource specific GVKs.
	// For more control override the below GVK list with your own custom logic.
	gvks, err := k8sutil.GetGVKsFromAddToScheme(apis.AddToScheme)
	if err != nil {
		return err
	}

	gvks1 := []schema.GroupVersionKind{
		schema.GroupVersionKind{Group: "redhatcop.redhat.io", Kind: "EgressIPAM", Version: "v1alpha1"},
	}

	log.Info("metrics for types", "gvks", gvks1)
	// Get the namespace the operator is currently deployed in.
	operatorNs, err := k8sutil.GetOperatorNamespace()
	if err != nil {
		return err
	}
	// To generate metrics in other namespaces, add the values below.
	ns := []string{operatorNs}
	// Generate and serve custom resource specific metrics.
	err = kubemetrics.GenerateAndServeCRMetrics(cfg, ns, gvks1, metricsHost, operatorMetricsPort)
	if err != nil {
		return err
	}
	return nil
}
```

When the container starts it prints:
```
{"level":"info","ts":1586394342.6268907,"logger":"cmd","msg":"metrics for types","gvks":[{"Group":"redhatcop.redhat.io","Version":"v1alpha1","Kind":"EgressIPAM"}]}
```
and naturally I have permissions on that resource because is the main resource managed by this operator.

Notice that the EgressIPAM CRD is scoped based (non namespaced).

I'd like some guidance on how to troubleshoot and resolve this issue.

**What did you do?**
explained above

**What did you expect to see?**
not see the error

**What did you see instead? Under which circumstances?**
the error, see above.

**Environment**
* operator-sdk version:
```
operator-sdk version
operator-sdk version: "v0.14.0", commit: "4fb185b9d45682473b4951c9788f845ba2fa5b12", go version: "go1.13.3 linux/amd64
```

* go version:
```
go version
go version go1.13.6 linux/amd64
```
* Kubernetes version information:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.8-beta.0", GitCommit:"6c143d35bb11d74970e7bc0b6c45b6bfdffc0bd4", GitTreeState:"archive", BuildDate:"2020-01-02T00:00:00Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2", GitCommit:"aa10b5b", GitTreeState:"clean", BuildDate:"2020-03-16T18:11:23Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
* Kubernetes cluster kind: 

openshift 4.3.8

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**
only known workaround is to disable metrics

**Additional context**
none

**Comment by raffaelespazzoli** [comment]
I'm also getting this error message in the log:
```
{"level":"info","ts":1586397733.0712404,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"an empty namespace may not be set during creation"}
```
this is weird because my operator is cluster scoped so the namespace should be empty. 
perhaps here the code should pass the namespace in which the operator is running rather than the namespace that the operator is watching.

**Comment by camilamacedo86** [comment]
HI @raffaelespazzoli, 

So, could you please let us know: 

1. Have you applied the CRD before you started up the operator? See that the error is `the server could not find the requested resource` What is the result of `kubectl get customresourcedefinition -n <namespace>`?
2. What is the scope of this CRD? What is the info [here for an example](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/deploy/crds/cache.example.com_memcacheds_crd.yaml#L12?
3. What is the scope of your project? Is it namespaced or cluster scoped? What is the value of the WATCH_NAMESPACE in the operator.yaml file? E.g see [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/deploy/operator.yaml#L24-L27)
4. Are you checking this error by using `operator-sdk run --local` command or did you deploy the project?

**Comment by camilamacedo86** [comment]
HI @raffaelespazzoli, 

The error:

> {"level":"info","ts":1586397733.0712404,"logger":"cmd","msg":"Could not create ServiceMonitor object","error":"an empty namespace may not be set during creation"}

Was fixed for the latest version of the SDK (0.16). You can get it by just updating your code in the main.go. See the [CHANGELOG](https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#bug-fixes-1):

> Fix ServiceMonitor creation when the operator is cluster-scoped and the environment variable WATCH_NAMESPACE has a different value than the namespace where the operator is deployed. (#2601)
 
Following the steps for you are able to fix it. 
- Do the step [Bug Fixes and Improvements for Metrics](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#bug-fixes-and-improvements-for-metrics) of the migration guide.
- Then, you will see that in the version used by you 0.14 has not the ` kubemetrics.GetNamespacesForMetrics(operatorNs)` so just: 
Replace:
```go
	// The metrics will be generated from the namespaces which are returned here.
	// NOTE that passing nil or an empty list of namespaces in GenerateAndServeCRMetrics will result in an error.
	ns, err := kubemetrics.GetNamespacesForMetrics(operatorNs)
	if err != nil {
		return err
	}
```
With:
```
	ns := []string{operatorNs}
```

Please, let me know if you could solve this issue and then, the answers to the questions made above.

**Comment by raffaelespazzoli** [comment]
@camilamacedo86 with regards to your questions:
`Have you applied the CRD before you started up the operator? See that the error is the server could not find the requested resource What is the result of kubectl get customresourcedefinition -n <namespace>?`

yes I have executed all the prerequisites and the operator is working fine with respect to its business logic.

`What is the scope of this CRD? What is the info here, for example?`

the CRD is cluster scoped (this might be a path that was not tested in operator-sdk). Not sure what examples you are looking for, but the operator in question is [here](https://github.com/redhat-cop/egressip-ipam-operator). At that link you can find examples and instructions on how to run the operator.

`What is the scope of your project? Is it namespaced or cluster scoped? What is the value of the WATCH_NAMESPACE in the operator.yaml file? E.g see here`

I assume you mean the scope of the operator, its scope is cluster wide. The WATCH_NAMESPACE env variable is initialized to `""`

`Are you checking this error by using operator-sdk run --local command or are you deploying the project in the cluster?`

The only way to reproduce this error is by running the operator in the cluster, when running locally metrics is not started and the error does not manifest itself.

**Comment by camilamacedo86** [comment]
Hi @raffaelespazzoli, 

CRD cluster scoped has not the namespace metadata info and will NOT work with the default metrics implementation and then, because of this, your checking `resource not found`. The default kubemetrics will look for the GVK in the namespaces informed. 

The same scenario discussed in the https://github.com/operator-framework/operator-sdk/issues/2707. The feature provide cannot work with and then, I'd recommend you not add CRD which are cluster scoped as well in the GKVs. It is something that we need to address in the docs. 

c/c @joelanford @estroz

**Comment by camilamacedo86** [comment]
Hi @raffaelespazzoli, 

I am closing this one as sorted out. Following the summary. 

### Error `Could not create ServiceMonitor object","error":"an empty namespace may not be set during creation`. 

- Solved for all projects built with 0.16 or upgraded to this version by following the migration guide. - It is the same scenario of #2602
- The steps required to let you know how to solve it in your project as well ( without upgrade it ) was shared here in https://github.com/operator-framework/operator-sdk/issues/2807#issuecomment-611293255

### Error `Failed to list *unstructured.Unstructured: the server could not find the requested resource`

- We could identify that you are facing it because your CRD is cluster-scoped and the default metrics implementation will not be able to work with since kubemetrics will look for the GVK in the namespaces informed.
- It is a duplicated of #2707. 

However, please feel free to ping us to re-open it if you think that is required.

**Comment by joelanford** [comment]
@camilamacedo86 I could be wrong, but I'm tracing through the code and I don't think it works for operators that are watching all namespaces because there's no way to tell `GenerateAndServeCRMetrics()` to generate metrics for all namespaces. It looks like it requires an explicit list of namespaces.

Passing just the operator namespace into that function will result in kube-state-metrics only being generated for the watched GVKs in that namespace. For cluster-scoped operators, it is likely that the operator namespace will never contain those GVKs.

I think we need to leave this open and think about what the right solution is here.

IMO, the SDK metrics helper functions are causing lots of confusion, and don't seem to cover all use cases. This is an area that needs lots of improvement.

**Comment by joelanford** [comment]
Talking this through with @camilamacedo86 we're both in agreement that the metrics packages are a bit unwieldy and do not support some common use cases.

As @camilamacedo86 said, there have been some recent improvements that should make things at least a little more clear about what the limitations are.

I created a meta-issue (#2811) to capture metrics use cases to make sure we cover all of them. If there's something I missed, let me know and I can add it to the list.

For now, I'll re-close this one since the immediate issue seems to be fixed or have better documentation about the existing limitations. If there's something we missed for this specific issue, we'll re-open and make sure we resolve it.
