### ISSUE TITLE
The command: `operator-sdk generate crds` does not support kubectl explain?

### ISSUE THREAD

**Issue by routerhan** [operator-framework/operator-sdk#2886]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Due to some product requirement, I would like to enable the `kubectl explain` command for my CRDs. It can be done by adding `preserveUnknownFields: false` key in the CRD definitions.

However, this feature will be overwritten when running `operator-sdk generate crds`.

**Describe the solution you'd like**
I am not sure if there are commands/scripts or tools in `operator-sdk` that I can leverage to enable this `kubectl explain` feature.
Thanks a lot !

**Comment by estroz** [comment]
You can set `preserveUnknownFields` using the field-level [`+kubebuilder:pruning:PreserveUnknownFields`](https://book.kubebuilder.io/reference/markers/crd-processing.html). The docs say this cannot be set to false, but that may not be the case for `v1` CRDs since controller-gen allows that [top-level field](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/crd/gen.go#L47-L54) to be false.

**Comment by routerhan** [comment]
Thank you for the answer. 
I will close this issue.
