### ISSUE TITLE
goproxy for operator sdk new operator creation.

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#2888]
## Type of question

general context question on the goproxy for building a new operator.

## Question

without setting goproxy 'https://proxy.golang.org,direct '
we are unable to build the new operator. 
My environment is restricted for external access.
need inputs on such environments for building operators without
setting goproxy. 
need info on alternate ways of building without goproxy and what are we fetching via goproxy for building a new operator.

Thanks in advance.

**Environment**
* operator-sdk version:
"v0.16.0"
  insert release or Git SHA here

* Kubernetes version information:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by kaushiksrinivas** [comment]
@camilamacedo86
need your valuable inputs for this.

**Comment by camilamacedo86** [comment]
HI @kaushiksrinivas  and @britoaldan, 

To create the project is required to have its dependencies. So, because of this, by default in go 1.13+, we will find the `GOPROXY` envvar with 'https://proxy.golang.org,direct '. See the [Module downloading and verification](https://golang.org/cmd/go/#hdr-Module_downloading_and_verification) to understand it better.

In this way, to attend the requirements defined in restrictive environments, we can :

**Use vendor**

A possible solution would be `vendor` the modules, ([go vendor](https://golang.org/cmd/go/#hdr-Vendor_Directories)), which means that we will have all modules source code in the `vendor` directory inside of the project. You can check how we did it for the SDK project [here](https://github.com/openshift/ocp-release-operator-sdk) in the downstream version.

However, note that it also requires light changes in the Dockerfiles for Ansible and Helm based-
operators as well to looking for the modules in the `vendor directory` instead of the internet. See the [dowsntream Dockerfile for Ansible based-operator image](https://github.com/openshift/ocp-release-operator-sdk/blob/master/release/ansible/Dockerfile#L4).

**Configure a private proxy**

See [Module configuration for non-public modules](https://golang.org/cmd/go/#hdr-Module_configuration_for_non_public_modules) to know how you can configure non-public ones and then keep the modules required available on it. 

**Some considerations**

Usually, the vendor solution is easier to get done and work with. Though its pros and cons may be considered an anti-pattern and it is a very debatable subject. For you have a better idea, check [here](https://gist.github.com/datagrok/8577287) and follow up its comments.  

In this way, we believe that if you just got one project set up, the whole private proxy seems like more work than it's worth. However, if you have multiple projects, it could make more sense. 

PS.: In a similar fashion, we know that some RedHat users work with their own Redhat Satellite that was holding all their RPMs on a disconnected environment. However, the alternative solution as described above for this scenario would be the vendoring approach. 

Let's keep it's open for we are able to address this information in an SDK document since it shows that it can help others as well.

**Comment by camilamacedo86** [comment]
Closing the issue as sorted out.
