### ISSUE TITLE
Is it possible to use a third-party test framework like Ginkgo ?

### ISSUE THREAD

**Issue by kanekoh** [operator-framework/operator-sdk#2913]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

About how to implement e2e test using a third party test framework.

## Question

**What did you do?**
A clear and concise description of the steps you took (or insert a code snippet).

I'm new into operator-sdk and I'd like to know how I implement e2e test using Ginkgo.

Trying to use Ginkgo for e2e test, however I couldn't find any way to pass `testing.T` into `framework.NewContext()` and functions like `e2e/util/WaitForOperatorDeployment`.

Are there any example or documentations for my understanding?

**Comment by mkimuram** [comment]
I had the exact same use case and managed to implement it like [this](https://github.com/mkimuram/operator-sdk-samples/commit/a70d8321bbf1d78ce664703765b6be1ef8e594e7).

I've tested it with my kind environment like below way and confirmed that it seems to work well.
```
sed -i "s/REPLACE_IMAGE/memcached:v0.0.1/" deploy/operator.yaml
sed -i "s/Always/IfNotPresent/" deploy/operator.yaml
operator-sdk build memcached:v0.0.1
kind load docker-image memcached:v0.0.1

operator-sdk test local ./test/e2e_ginkgo --debug --go-test-flags="-v -ginkgo.v"
operator-sdk test local ./test/e2e_ginkgo --debug --go-test-flags="-v -ginkgo.v -ginkgo.skip=\[slow\]"
```

Note that passing `testing.T` like [this way](https://github.com/mkimuram/operator-sdk-samples/blob/a70d8321bbf1d78ce664703765b6be1ef8e594e7/go/memcached-operator/test/e2e_ginkgo/main_ginkgo_test.go#L47) is [not recommended](https://github.com/onsi/ginkgo/issues/9#issuecomment-26206617) in ginkgo. So, it would be nice to avoid passing `testing.T` in operator-sdk's e2e framework side, in the future. (I guess that just using it for logging won't be harm, although it is too noisy in the last output of the tests. So, I hope my current implementation is still good enough, practically.)

@estroz  @kanekoh 
Any feedback is welcomed, for I'm planning to implement e2e tests in my project by using this way.
Also, I can create a PR for this sample to operator-sdk-samples, if it makes sense.

**Comment by kanekoh** [comment]
I am not the expert of Ginkgo/Gomega however, I don't think that is good idea implementing e2e tests using operator-sdk with the unrecommended way which was mentioned the issue you linked.

**Comment by mkimuram** [comment]
> So, it would be nice to avoid passing testing.T in operator-sdk's e2e framework side, in the future. 

Just for removing dependency to `testing.T`, changes like [this](https://github.com/mkimuram/operator-sdk/commit/a0c46ab9b616fd16efb982c0a9d76c216456a2e9) in operator-sdk will be fine, as similar approach was done [here](https://github.com/operator-framework/operator-sdk/pull/1195). Then, it will allow passing `nil` to `testing.T`, so we don't need to access to it in ginkgo test like [this](https://github.com/operator-framework/operator-sdk-samples/commit/338f6f0548fe20791246c6b32dfc53401317bcfc).

I guess that it will be difficult to change the interface not to pass `testing.T` in framework, because there must be already many existing users using current one. Therefore, above approach would be the realistic solution. (Until someone decide to define v2 interface, which I don't think there are such motivations.)

One remaining issue is `--skip-cleanup-error` won't work well if `testing.T` is nil, for it relies on [`t.Failed()`](https://github.com/operator-framework/operator-sdk/blob/master/pkg/test/context.go#L107). (However, from source code, it allows such a case, for it check `t != nil`.)

@estroz

Any comments on this?

**Comment by estroz** [comment]
Even though passing `testing.T` like you have done is not recommended, it is probably the best way to use Ginkgo/Gomega in conjunction with the SDK's e2e testing library for the foreseeable future.

Instead of continuing development of the SDK's e2e framework, we are going to start promoting [`envtest`](https://godoc.org/sigs.k8s.io/controller-runtime/pkg/envtest) as the go-to operator e2e test framework. It has better UX, is under active development, and is already suggested for use with kubebuilder projects (which we are migrating to for Go-based operators). We recently discussed this switch at our issue triage meeting [this morning](https://github.com/operator-framework/community/projects/3#card-34081393). Docs on this to come.

**Comment by camilamacedo86** [comment]
It shows solved. in this way, I am closing this one and please feel free to re-open if you need and/or raise new issues as well.
