### ISSUE TITLE
`go test` fails because of global vars and init()

### ISSUE THREAD

**Issue by larham** [operator-framework/operator-sdk#292]
Repro:

```
cd $GOPATH
mkdir MyTestGroup
cd MyTestGroup
operator-sdk new test --api-version MyTestGroup/v1alpha1 --kind MyTestKind
cd test/pkg/stub
echo "package stub_test" > handler_test.go
go test
```

output like:

```
panic: lookup kubernetes.default.svc: no such host

goroutine 1 [running]:
MyTestGroup/test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient.mustNewKubeClientAndConfig(0x1012d68, 0x10, 0x1b69220)
	/Users/pivotal/go/src/MyTestGroup/test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient/client.go:102 +0xc2
MyTestGroup/test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient.init.0()
	/Users/pivotal/go/src/MyTestGroup/test/vendor/github.com/operator-framework/operator-sdk/pkg/k8sclient/client.go:43 +0x34
exit status 2
FAIL	MyTestGroup/test/pkg/stub	0.268s
```

This appears to be a result of global vars and init() causing an initialization of the k8sclient *after* the test system is run, and the test (an empty file) passes.

In other words, no test framework can work with the current implementation.

**Comment by fanminshi** [comment]
@larham Thanks for reporting the issue. We are aware of the global state and are planning to remove them. ref: https://github.com/operator-framework/operator-sdk/issues/169

**Comment by justinbarrick** [comment]
Is there any work around for this?

**Comment by hasbro17** [comment]
@larham @justinbarrick We have a temporary fix for this in #340 
This should allow you to run unit tests without the client getting in the way by initializing and attempting to connect to the kubernetes server.

However you still won't be able to use the client APIs(e.g `sdk.Create()`) in any unit tests since that will lazily initialize the underlying k8s client to try and connect with the server which will fail as before. To fix that we need to be able to mock the SDK client which needs more work on removing the overall global state.

But just for this issue you can try out the master to see if #340 works and we can close this issue.

**Comment by CSdread** [comment]
@justinbarrick @larham If you want to use the SDK methods that are global and still unit test you can create an interface and class that do all the work that references the SDK, then you call those methods on the class instance.

```type Client interface {
	GetClusterPods(clusterName, namespace string, clusterLabels map[string]string) (*corev1.PodList, error)
}

type client struct {
}

func (c *client) GetClusterPods(clusterName, namespace string, clusterLabels map[string]string) (*corev1.PodList, error) {```

**Comment by hasbro17** [comment]
Closing this since the original issue seems to be fixed. There's more refactoring work on removing the global state in general but that's already tracked in other issues.
