### ISSUE TITLE
Upgrade guide for v0.17 is not clear

### ISSUE THREAD

**Issue by rcernich** [operator-framework/operator-sdk#2986]
## Bug Report

**What did you do?**

Modified `go.mod` by replacing the existing entries in `requires` and `replaces` with the versions listed in the upgrade guide.

**What did you expect to see?**

Successful execution of `go mod vendor`.

**What did you see instead? Under which circumstances?**

The following errors:

```
github.com/maistra/istio-operator/pkg/controller/common/helm imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/discovery/v1beta1: module k8s.io/api@latest (v0.18.2) found, but does not contain package k8s.io/api/discovery/v1beta1
github.com/maistra/istio-operator/pkg/controller/common/helm imports
	k8s.io/client-go/kubernetes/scheme imports
	k8s.io/api/flowcontrol/v1alpha1: module k8s.io/api@latest (v0.18.2) found, but does not contain package k8s.io/api/flowcontrol/v1alpha1
github.com/maistra/istio-operator imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk/cli imports
	github.com/operator-framework/operator-sdk/cmd/operator-sdk/execentrypoint imports
	github.com/operator-framework/operator-sdk/pkg/ansible imports
	github.com/operator-framework/operator-sdk/pkg/ansible/proxy imports
	k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme: module k8s.io/apimachinery@latest (v0.18.2) found, but does not contain package k8s.io/apimachinery/pkg/apis/meta/internalversion/scheme
```

**Environment**
* operator-sdk version:

N/A

* go version:

go version go1.13 linux/amd64

* Kubernetes version information:

N/A

* Kubernetes cluster kind: 

N/A

* Are you writing your operator in ansible, helm, or go?

go

**Possible Solution**

**Additional context**

This project was upgraded from v0.10.1 to v0.15.2 to v0.16.0.  Upgrade steps to v0.17 did not work.

**Comment by rcernich** [comment]
Here's a link to the [go.mod](https://github.com/Maistra/istio-operator/blob/36451f837d56e64fb8c08cdecb7db5741ecad79d/go.mod) for v0.16

**Comment by rcernich** [comment]
We're using helm internally and removing the replaces section which pins k8s 1.16.2, causes import issues with helm.

**Comment by camilamacedo86** [comment]
HI @rcernich, 

The go.mod[1] linked by you on top is NOT updated/changed as described in the migration guide. 
Did you link the correct version one? If yes, please see that the versions were not updated as you are still using the old replaces and versions which are no longer required. 
[1] - https://github.com/Maistra/istio-operator/blob/36451f837d56e64fb8c08cdecb7db5741ecad79d/go.mod

**Comment by rcernich** [comment]
That is correct, it is old.  The documentation does not say anything about removing any of the existing requires or replaces, so I didn't remove anything.  That said, removing those allowed me to progress, but I was still getting errors.  Initially, it would pull in v1.13.0 for k8s.io/kubernetes.  Changing that to v1.17.4, allowed me to get past those errors, but then I started getting v0.0.0 errors for all the other k8s.io imports.  Pinning those to v0.17.4 resulted in import errors related to helm (kubectl and cli-runtime incompatibilities, iirc).

That said, I don't have time to pursue this and try to unwind the dependency incompatibilities atm.

**Comment by joelanford** [comment]
Yeah, this seems like a dependency issue that is a result of some extra libraries that your operator is importing/using. Kubernetes is a rats nest of dependency resolution problems (but at least that has been improving lately :slightly_smiling_face: )

I'd have to also spend on time trying to help you chase this down for your repo, but one place to start that _may_ help is the operator-sdk's [go.mod file for v0.17.0.](https://github.com/operator-framework/operator-sdk/blob/v0.17.0/go.mod)

We _also_import helm and have dealt with similar issues before. Maybe there's something simple in there you're missing?

**Comment by rcernich** [comment]
From a docs perspective, I think the important thing here is that there is no mention about removing that other replaces section.  I deal with my own import issues, and removing the replaces section that pinned to k8s 1.16.2 did help.  I suspect users may also need to remove many of the k8s.io imports in their requires section too, to have them updated with newer versions.

**Comment by camilamacedo86** [comment]
HI @rcernich, 

Each upgrade section is from -1 version to the specific one. So, the migration section guide 0.17 expected that you have a project which is already upgraded to 0.16 successfully. So, as the first step we have:

> Ensure that the following require modules and replace directives with the specific versions are present in your go.mod file:
> require (
> 	github.com/operator-framework/operator-sdk v0.17.0
> 	sigs.k8s.io/controller-runtime v0.5.2
> )
> 
> replace (
>   k8s.io/client-go => k8s.io/client-go v0.17.4 // Required by prometheus-operator
>   github.com/Azure/go-autorest => github.com/Azure/go-autorest v13.3.2+incompatible // Required by OLM
> )

POV is that since it is a common process to upgrade the projects is quite intuitive that it means to replace the previous modules for [0.16](https://sdk.operatorframework.io/docs/migration/version-upgrade-guide/#v016x), which exists in the same doc, for the new ones. However, please feel free to contribute with if you see a hall to improvements. Would you like to do a PR against master with your suggestions? 

Now, regards your scenario, in order to try to help you with, see that if you are not sure what module was added by yourself as part of the customizations made in the default scaffold I understand that you can just check the [0.16](https://sdk.operatorframework.io/docs/migration/version-upgrade-guide/#v016x) and replace them for the new ones. 

Please, let us know if you could successfully upgrade it after the information provided and if you are still facing any issue please send the issue and the go.mod updated for we are able to check and see if something is missing.

**Comment by joelanford** [comment]
> I suspect users may also need to remove many of the k8s.io imports in their requires section too, to have them updated with newer versions.

IIUC, go auto-promotes dependency versions in the `requires` section if a transitive dependency requires a more recent version. An example of this is the client-go version being sticky on its `v12.0.0+incompatible` version, and us having to use `replaces` to pin it to `v0.18.2`.

The difficult part is that operator-sdk and controller-runtime have a subset of the k8s.io dependencies as their dependencies. So the only versions that would need to be changed or removed in an operator's go.mod file would be ones that the operator depends on, but the other transitive dependencies don't. 

The intention of the migration guide section is that we say "these are the minimal set of requires and replaces you need to use this version of SDK". Simple projects can fully overwrite their go.mod files with what is shown in the migration guide.

Complex projects with lots of dependencies need to take more care. I think this is just an unfortunate outcome of the transition to go modules.

With all of that being said, we're definitely open to having more clear instructions in the migration guide. Is there something specific we could change that would make this more clear?

**Comment by rcernich** [comment]
@camilamacedo86, I guess that wasn't clear to me.  I did ensure that those were present and it didn't work.  What it didn't say was that I also had to remove what was required from the previous release.  And because this wasn't clear, I've also got replacements from previous upgrades, which I assume are no longer necessary.  I think what really threw me off were the `Pinned to kubernetes-1.16.2` comments in the previous upgrade notes (going back a few versions too).  It might be beneficial to keep a consistent comment above those sections to make it more clear, e.g. `// replacements for operator-sdk` and keep all replacements in that section.  Older versions also had additional replacements, which I'm assuming also need to be removed (based on your last comment, e.g. docker => moby).  If I had seen this, I would have thought, I need to replace this section with the specifics for the new version.  Easy peasy.

**Comment by camilamacedo86** [comment]
Hi @rcernich, 

Really tks for the reply. The `Pinned to kubernetes-1.16.2` was required before 0.17. Now, it is no longer required and is really more implied which I hope that help the users in the one migrations. 

I am closing this one since shows that all is sorted out. However, please feel free to contribute with and/or ping us to re-open this one or create a new one if you still needing some help ok.

**Comment by rcernich** [comment]
@joelanford, TBH, it probably makes sense to continue to include the replacements for k8s.io dependencies, so you have something that is at least consistent with a particular operator-sdk version.  If a particular operator requires some other k8s.io module that isn't imported through operator-sdk, they should be able to deal with that.  I think this also holds true for k8s.io version too, e.g. if an operator needs a newer/older version of api or something (assuming it's compatible with the operator-sdk).  Just my two cents.

**Comment by joelanford** [comment]
Hmm. `v0.17.0` no longer requires `k8s.io/kubernetes`. This repo is what necessitated the use of `replaces` for a bunch of `k8s.io` repos (because `k8s.io/kubernetes` go.mod used v0.0.0 versions in `requires`)

Now that SDK no longer requires `k8s.io/kubernetes`, projects that import SDK _AND_ don't themselves depend on `k8s.io/kubernetes` can remove those `k8s.io` replacements. That's why they aren't included in the migration guide.

Am I understanding this correctly?

**Comment by rcernich** [comment]
Thanks @joelanford. As you said, this could be a result of our dependencies.  That said, my biggest issue was with the helm import, which I expected would work given that operator-sdk supports helm.  I think the other issue was that kubectl moved into its own project.  Anyway, I'm willing to accept that it's because of my requirements, not operator-sdk.  And my original problem was that it wasn't clear to me that I needed to remove all the old operator-sdk specific entries from go.mod, which did fix most of my problems.
