### ISSUE TITLE
Connecting to a Kubernetes Service when running the operator locally

### ISSUE THREAD

**Issue by zroubalik** [operator-framework/operator-sdk#3006]
## Feature Request

**Is your feature request related to a problem? Please describe.**
When I run operator locally via `operator-sdk run --local,` it would be nice if the operator could connect to and resolve internal kubernetes services eg. `myservice.default.svc.cluster.local`

**Describe the solution you'd like**
It would be beneficial for users, as they would have the same experience when developing operator locally or running the operator image in the cluster. 
This is example of a functionality I am looking for: https://github.com/txn2/kubefwd
Would be great if `operator-sdk` could provide this feature out of the box.

**Comment by estroz** [comment]
Might also be worth addressing in kubebuilder since we're transitioning.

/kind feature

**Comment by camilamacedo86** [comment]
Hi @zroubalik and @adnzn, 

Sorry for the delay to get a response on it. I never used https://github.com/txn2/kubefwd, however, shows that it create service for deployments. is it? Could you please clarify more what problems and needs would you like to achieve with it?

Note that for 1.0+ we have no longer the `operator-sdk run --local` and instead you will find in the Makefile a target called `make run`: 

https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/memcached-operator/Makefile#L36-L38

How do you see https://github.com/txn2/kubefwd used on it? Could you describe how you imagine it working?

**Comment by zroubalik** [comment]
@camilamacedo86 sorry for the delay, I missed this somehow.

The problem is: I have an operator that is consuming some cluster internal services. When I run operator locally for development/debug purposes, the operator is not able to reach internal cluster services (which are not exposed). 

`kubefwd` is an example of how to solve this issue, it forwards requests from outside the cluster to the cluster internal services.

**Comment by estroz** [comment]
My 2c: I’d rather see something like this described in an FAQ than downloaded by/built into operator-sdk projects.
1. It’s another tool dependency to version and manage.
1. It’s only useful for running locally, which isn’t where operators are intended to live. In fact, as an operator becomes more complex, more out-of-cluster tools could be required to connect components to in-cluster ones. That’s not something out of the box projects should prepare users for. Correct me if you think I’m wrong here.

There are tons of tools out there for managing k8s resource development that would benefit operator-sdk operator projects. operator-sdk can’t/shouldn’t include many of these, which is why the decision was made to reduce the number of CLI commands in favor of including a modifiable `Makefile` with every project. A slim, extensible core lets you use whatever tools you want.

To start, let’s inform other devs that forwarding to services is possible via the FAQ. Feel free to make a docs PR!

/remove-kind feature
/kind documentation
