### ISSUE TITLE
Support ordering of status conditions

### ISSUE THREAD

**Issue by Jamstah** [operator-framework/operator-sdk#3010]
## Feature Request

**Is your feature request related to a problem? Please describe.**
The `status.conditions` array of a CR can be ordered to be able to place conditions of a higher importance at the top of the list, which will then be reflected in UIs and on the Kubernetes command-line to help users identify problems.

When using the Operator SDK, new conditions are appended to the array, so ordering is not possible unless the array is managed independently.

https://github.com/operator-framework/operator-sdk/blob/4622d6bb7eb6e1f09256a28b19ebd6b9ac1c91ea/pkg/status/conditions.go#L133

**Describe the solution you'd like**
Ability to provide ordering to the array.

Perhaps with an OrderConditions/SortConditions method that takes a list of types, and sorts existing conditions into that order

Perhaps by adding an optional index field to the SetCondition method that will insert the condition at the provided index if it doesn't already exist in the array.

**Comment by joelanford** [comment]
@Jamstah `Conditions` [currently sorts the conditions by type](https://github.com/operator-framework/operator-sdk/blob/700bef14e0514660ebae45f26213c74c4a66f51e/pkg/status/conditions.go#L185-L187) when marshaling and sending to the server.

The original idea was that the order of conditions doesn't matter semantically, BUT it is important for the order to be deterministic so that simple/accidental re-orderings don't induce unnecessary writes to the server. This was actually super important in the original implementation of the `Conditions` type (which was a map) since map iteration is non-deterministic.

Now that the `Conditions` type is an array, it seems reasonable for us to relax this constraint. I _do_ think it would be nice to have a default sort order to help users avoid the scenario I described above.

There _is_ a problematic gotcha with this though. I'm fairly sure the `Conditions` type _has_ to be `type Conditions []Condition`. It can't be a struct that contains a field with the conditions because that doesn't play nice with the CRD generation done by controller-tools, which is pretty picky about not coercing Go types to different types in the OpenAPI schema.

So with these constraints/goals in mind, is there a reasonable design for introducing custom sorting, while also supporting a default sort order? The only way I see after a quick glance is to have an exported global sort function that is used by `MarshalJSON`, but that seems like a non-starter because many operators would define and reconcile multiple GVKs that each need different condition sort orders.

Perhaps the default sorting by type is too opinionated, and SDK should allow/force operator developers to handle the condition order themselves. Thoughts?

**Comment by Jamstah** [comment]
Thanks Joe.

Although I do think that allowing ordering could be useful for helping users, there is also this discussion where I asked about ordering:
https://github.com/kubernetes/community/pull/4521

I'm not k8s API expert so I don't know the ins-and-outs of how arrays are handled internally as maps etc, but it sounds like in a future revision of the spec, the Conditions array is going to be explicitly unordered by virtue of being `listType=map`.

It may be best to close this one as impractical.

**Comment by tengqm** [comment]
Given that conditions are defined on a per resource type basis, it would be difficult to devise a sorting function for conditions, if possible at all.
Just my 2 cents.

**Comment by joelanford** [comment]
@Jamstah Thanks for the links. I had been following the Conditions KEP, but hadn't seen the community discussion. Based on the most recent comment there, I'll close this since it sounds like the direction will be `listType=map`, as you expected.

I'm definitely happy to revisit this if the upstream specification/guidance changes.
