### ISSUE TITLE
Can we deploy one operator from the other operator ?

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#3019]
I want to invoke one operator from other operator. Is it possible to deploy an operator from other operator.

**Comment by akram** [comment]
@AnilKumarBandi27 the responsibility of an operator is generally restricted to the CR it manages and the resources that are linked to this CR.
Invoking another operator whatever the way may not be a great design.

What would make more sense maybe is to create a CR object in your operator B that will trigger the expected actions of Operator A, and potentially read the status to execute what you want in operator B.

**Comment by camilamacedo86** [comment]
HI @AnilKumarBandi27, 

**If you are looking for to define that the Operator A depends on the Operator B:**

Then, I'd recommend you check the [Dependency Resolution](https://github.com/operator-framework/operator-lifecycle-manager#dependency-resolution) option from OLM which allows you to do that. 

**If you are looking for using the API from Operator A in Operator B:**

Yes, it is possible. Let's understand what is an Operator API first:

> When following the Getting Started, one of the first steps is to run the command `operator-sdk add api --api-version=cache.example.com/v1alpha1 --kind=Memcached`. The purpose of this command is to generate Custom Resource (CR) and Custom Resource Definition (CRD) resources for the Memcached Kind. This command is creating the API with the group cache.example.com, and version v1alpha1  which uniquely identifies the new CRD of the Memcached Kind.
> 
> Consequently, by using the Operator SDK tool, we can create our APIs and objects that will represent our solutions on these platforms. The Getting Started tutorial adds only a single kind of resource; however, it could have as many Kinds as needed (1…N). Basically, the CRDs are a definition of our customized Objects, and the CRs are an instance of it.

Ref.: https://developers.redhat.com/blog/2019/10/04/getting-started-with-golang-operators-by-using-operator-sdk/

IMO the best practice would be each operator works respecting its domain. So, I'd NOT recommend you design an Operator A that is implemented to do the responsibilities defined for an Operator B. Following an example to illustrate it. 

> **Exemplo**
> The operator's projects built with SDK has a metric feature that will create a ServiceMonitor(CR) resource which is a Kind(CRD) from the Prometheus Operator. However, the feature just creates the required resources to export the specific operator metrics which is a requirement of the project and is part of its domain. Note that, manage the Prometheus itself is part of the Prometheus Operator domain and is not the responsibility of the project that is exporting metrics to it. 

**NOTE**: I'd recommend you check the blog post [How to use third-party APIs in Operator SDK projects](https://developers.redhat.com/blog/2020/02/04/how-to-use-third-party-apis-in-operator-sdk-projects/) to know how you can do it. 

**If you are just looking for to automate the setup of 2 projects, for example, for e2e tests purpose**

So, you might be able to solve it with a shell script and/or make commands. 

For example, see [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/Makefile#L7) in the Memcached Sample that we have a make command that will install all require sources to check the project running. Then, you also could create a target to fit a third-party project. For example:  See [here](https://github.com/operator-framework/operator-sdk/blob/master/hack/lib/common.sh#L38) a shell script used in the SDK to install the Prometheus operator before to do e2e tests with. 

I am closing this one because I understand that the above answer fully covered your question. However, please feel free to ping here if you think that would be required re-open it or open new issues with other questions as well. 

I hope that it helps you with.
