### ISSUE TITLE
Failed to build image with operator-sdk build api on s390x platform

### ISSUE THREAD

**Issue by apasrini** [operator-framework/operator-sdk#3050]
## Bug Report

https://github.com/operator-framework/operator-sdk/issues/2392 - Facing same issue but workaround of getting main.go to the root seem to not work for me. I am using s390x platform build of operator-sdk and hitting with the below issue

"github.ibm.com/Cloud-Integration/ibm-appconnect-operator/cmd/manager"}: exec: "go": executable file not found in $PATH"

**Environment**
* operator-sdk version:

root@zLinux~# go version
go version go1.13.10 linux/s390x

operator-sdk version
operator-sdk version: "v0.17.0", commit: "2fd7019f856cdb6f6618e2c3c80d15c3c79d1b6c", kubernetes version: "unknown", go version: "go1.13.10 linux/s390x"

```
root@zLinux:~# go env
GO111MODULE=""
GOARCH="s390x"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="s390x"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_s390x"
GCCGO="gccgo"
AR="ar"
CC="s390x-linux-gnu-gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -march=z196 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build417036837=/tmp/go-build -gno-record-gcc-switches"
root@zLinux:~# 
```

**Possible Solution**
operator-sdk build command to work with flag --go-build-args

**Comment by camilamacedo86** [comment]
Hi @apasrini, 

See that in #2392 the issue `executable file not found in $PATH"` was faced with `GOARCH="amd64"` and not `s390x`. Also, it was closed because shows that the user could fix his local env and all lead to being related to the wrong local env setup.  

Let's bring here from there the @hasbro17's comment which is relevant for your case. Could you please check and let us know? 

> exec: "go": executable file not found in $PATH) suggests that your go binary path e.g /usr/local/go/bin isn't in your $PATH env var.

> You can see from your own error message that operator-sdk build is just running go build ... 

> Can you print out the error that you get when you run operator-sdk build against a newly scaffolded project via operator-sdk new that's unmodified? And also check your $PATH var, echo $PATH.

Also, could you please check if your `GOPATH="/root/go"` is accurate?  See that the GO bin and tools are installed in `/usr/local/go` so should it really be root? Should not it be something as  `GOPATH="/Users/<youruser>/go"` instead?

**Comment by kensipe** [comment]
Any progress here @apasrini ?

**Comment by camilamacedo86** [comment]
It shows that can be closed. Feek free to raise new issues and/or ping us to re-open this you if you need.
