### ISSUE TITLE
Add support for buildx and QEMU

### ISSUE THREAD

**Issue by leszko** [operator-framework/operator-sdk#3071]
## Feature Request

**Is your feature request related to a problem? Please describe.**
We would like to build multi-arch operator images on amd64 machine.

**Describe the solution you'd like**
We would like to build operator images with [Docker buildx builder](https://docs.docker.com/buildx/working-with-buildx/), so that you could easily build multi-arch operator image from the amd64 machine.

**Comment by camilamacedo86** [comment]
Hi @leszko, 

The command `operarator-sdk build <image>` will mainly execute a `go build` and a `docker build`. See that in the scaffolded projects is possible to find the `build/` directory. There you will find the Dockerfile. Note that, in the comment https://github.com/operator-framework/operator-sdk/issues/2568#issuecomment-594747086 you will find a detailed explanation over how it works. 

However, following the same position in similar requests like as https://github.com/operator-framework/operator-sdk/issues/2972, https://github.com/operator-framework/operator-sdk/pull/1600, and https://github.com/operator-framework/operator-sdk/pull/2046 users are able to customize their projects to attend their specific needs like this one and the short-time goal is to provide Makefile to help them with. For further information see: https://github.com/operator-framework/operator-sdk/issues/1655

In this way, I'd like to recommend you create a Makefile, see [here](https://github.com/operator-framework/operator-sdk-samples/blob/master/go/memcached-operator/Makefile) one example, with a target which will allow you to build the operators images in any arch/format. 

Also may help to share that the tool binary is provided in many arch-types. See in the assets in the [releases](https://github.com/operator-framework/operator-sdk/releases). Also, feel free to check [How the operator-sdk binaries are built](https://sdk.operatorframework.io/docs/contribution-guidelines/developer-guide/#how-the-operator-sdk-binaries-are-built).

I am closing this one since shows that all is sorted out, however, please feel free to ping us if you see that has any reason for it be re-opened.

**Comment by leszko** [comment]
@camilamacedo86 Thanks a lot for the explanation and the links. I'll follow these steps.

**Comment by camilamacedo86** [comment]
Hi @leszko, 

Tks for the reply and please, feel free to raise new issues with questions if you need our help.
