### ISSUE TITLE
Validation items ".env" that should not appear in a custom CRD

### ISSUE THREAD

**Issue by lut777** [operator-framework/operator-sdk#3090]
##Background

I'm implementing a controller. 
Naturally, I need to define my CRD resources.
According to the doc, I made changes to the xxx_type.go file to define my CRD file.

## Type of question

No exceptions appear after modifying the file. No errors in the compilation.
HOWEVER, when I execute `kubectl apply -f ./relative_crd.yaml`,  validator reports an error.
The error says: `blablablabla, .env in body is required`
When I add the "env" field to the first column, this error will disappear.
But that's weird because I didn't define the "env" field at all.
I did a comparison with the file structure in this file "https://github.com/dev4devs-com/postgresql-operator/blob/master/deploy/crds/postgresql.dev4devs.com_databases_crd.yaml". 
I didn't find an obvious problem.

## Question

Why did this problem come up?
What can I do to resolve this ".env" validate problem?

**Environment**
* operator-sdk version: 0.17.0

* Kubernetes version information:
Client version: 1.15.2
Server version: 1.14.0

**Comment by camilamacedo86** [comment]
Hi @lut777, 

Sorry, but with the info provided here is not clear for me what did you did and what you are specifically facing.  See that: 

- You defined the CRD specs in the *_type.go
- then, you run `operator-sdk generate crds` to gen the CRDs files in the `/deploy/crds` dir
- and, you run `operator-sdk generate k8s` to generate the code for custom resource  
 
So,  could you please provide the type.go implementation and CRD generated for we are able to check?

**Comment by camilamacedo86** [comment]
Hi @lut777, 

I'd like to share that the validation errors faced when we apply a resource in the cluster came from k8s api and it shows that something which is required is not applied in your CR. However, in order to try to help you more specifically would be required the information requested in the previous comment: 

> So, could you please provide the type.go implementation and CRD generated for we are able to check? Also, could you provide the full error log faced?    

I assume that you could sort it out with the information provided already since it is open for a while waiting for the information requested. In this way, I am closing this one. However, please feel free to ping us to re-open this one if you see that it is required and or raise new issues.
