### ISSUE TITLE
Link broken in release doc

### ISSUE THREAD

**Issue by krish7919** [operator-framework/operator-sdk#3126]
## Bug Report

In the 0.4.0 pre-release notes , the Version upgrade link pointing to https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/version-upgrade-guide.md#v04x is broken.

**Comment by estroz** [comment]
Can you link which notes you're talking about?

/kind documentation

**Comment by asmacdo** [comment]
I found the link: https://github.com/operator-framework/operator-sdk/releases?after=v0.4.1
(note at the bottom)
![Screenshot from 2020-06-03 11-29-18](https://user-images.githubusercontent.com/1028657/83656426-8810de00-a58d-11ea-95ea-507f07d04046.png)

However, looking at the changelog at the 0.4.0 tag, the note with the broken link is absent.

The only place I see that info is in the release itself. https://github.com/operator-framework/operator-sdk/releases/edit/v0.4.0 

Other releases follow the same format and will also have the broken links, but I'm not sure if we should edit the releases this far after they went out.

**Comment by asmacdo** [comment]
Closing, since it would probably not be worth editing the release metadata so far back. However, for @krish7919 and others who are looking for the doc, it is currently available at https://sdk.operatorframework.io/docs/migration/version-upgrade-guide/ or can be viewed at this permalink: https://github.com/operator-framework/operator-sdk/blob/3eb6d9b50659151a8f83d17e046059dde24199ff/website/content/en/docs/migration/version-upgrade-guide.md#v04x
