### ISSUE TITLE
Does fake client allows to run kaniko jobs..? 

### ISSUE THREAD

**Issue by Uvindu96** [operator-framework/operator-sdk#3171]
# type of question

Running unit tests using fake client

## Question
I'am trying to write unit test using "sigs.k8s.io/controller-runtime/pkg/client/fake", Inside my reconcile loop there is a kaniko job needs to run. So what I need to know is does fake client capable of running it. I'm asking this because when I retrive the job instance it showed me a nil one.

**What did you expect to see?**
need to run the kaniko job as expected

**What did you see instead? Under which circumstances?**
getting a nil job object after run the kaniko job

**Environment**
* operator-sdk version: v0.7

**Additional context**
I'm not using any clusters, just running the tests using fake client

**Comment by camilamacedo86** [comment]
Hi @Uvindu96, 
 
I have no knowledge over `kaniko`. However, the fake client will allow you `fake` all operations that are done by the client-go. E.g CREATE, UPDATE, DELETE  a resource.  

It is important to say as well that thee fake client is deprecated and then, that is suggested the usage of eenv test instead of. See: 

> Deprecated: please use pkg/envtest for testing. This package will be dropped before the v1.0.0 release.`
From: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client/fake

Also, it is important to highlight that you are using a very old SDK version which means an old version of controller-runtime as well. Then, in order to avoid technical debts, I'd recommend you upgrade your project to use the latest one. 

Closing this one as sorted out. Please, feel free to ping us to re-open this one if you still have seen that something is required about the question made. For other ones, please raise a new issue.

**Comment by Uvindu96** [comment]
Thanks for your response @camilamacedo86  but it looks like pkg/envtest is for integration tests, but what I'm trying to do is unit testing, according to https://sdk.operatorframework.io/docs/golang/unit-testing/....it says to use fake client

**Comment by camilamacedo86** [comment]
Hi @Uvindu96, 

Yes, the SDK docs still sying to use the fake-client because still possible to use it. However, as described above, it came from controller-runtime and it is deprecated. So, just beware that at some point it will no longer be available and the recommendation is to use `pkg/envtest` to test your controller instead of it. See the [doc](https://book.kubebuilder.io/reference/testing/envtest.html ) to have an idea of how you can do it. 

Regards the SDK docs it also is in our radar and will be updated after the integration of the project with Kubebuilder probably.

And then, regards your question `Inside my reconcile loop there is a kaniko job needs to run. So what I need to know is does fake client capable of running it.`

The fake client will simulate any client operations such as : `r.client.Create(context.TODO(), dep)`. 
I hope that it helps you with.
