### ISSUE TITLE
Helm operator install all CRD automatically on start. 

### ISSUE THREAD

**Issue by mohamadnikan2013** [operator-framework/operator-sdk#3218]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I have an issue when deploying the helm operator. it has panic if CRD no installed in cluster. 

**Describe the solution you'd like**
if the helm operator has an option to install all managing CRD on startup if not already installed it gonna be great.

**Comment by camilamacedo86** [comment]
Hi @mohamadnikan2013,

> I have an issue when deploying the helm operator. it has panic if CRD no installed in cluster.

The error occurs because the operator requires that its API be applied in the cluster to be able to perform the operations. You will see the msg `if kind is a CRD, it should be installed before calling Start`.

> if the helm operator has an option to install all managing CRD on startup if not already installed it gonna be great.

You can use Makefile targets to apply all resources as in the [Helm Mencached Sample](https://github.com/operator-framework/operator-sdk-samples/blob/master/helm/memcached-operator/Makefile#L7). It might help you with. 

Also, with go operators, you have more flexibility and could perform a customized implementation to address this need when the operator is initialized in the `main.go`. However, with Helm, I cannot see how it would be possible. 

@joelanford wdyt?

**Comment by camilamacedo86** [comment]
Hi @mohamadnikan2013, 

We discussed this today in the bug triage meeting and then was decided that we shouldn’t put this in helm-operator because it is [OLM’s](https://github.com/operator-framework/operator-lifecycle-manager) job to do it. Operators that self-install CRDs need higher-level access.

Something that was raised as an option by @fabianvf was that you might add an initContainer to the operator deployment that creates the CRDs. So, it would be totally separate from the helm operator, just something that runs before the operator container. 

However, was defined that it would not be something that would be incorporated at this moment. Because of this, we are closing this one. However, please feel free to ping us and ask to re-open if you think that would be required.

**Comment by mohamadnikan2013** [comment]
hey @camilamacedo86 
If I use init container to create all my CRDs we have a problem if the CRDs deleted from the cluster by the way the operator going to crash and init container never start again. 
I try using entrypoint and  build my docker image and it's doing well 
but I think it will be good If we have something in our operator to create CRDs on demand

**Comment by mohamadnikan2013** [comment]
I document my Dockerfile and entrypoint here. 
so we someone face this issue they can use my approach.

```
FROM quay.io/operator-framework/helm-operator:v0.16.0

USER root

WORKDIR /tmp
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl
RUN chmod +x kubectl
RUN mv kubectl /usr/local/bin

COPY hack/entrypoint.sh /usr/local/bin/internal-entrypoint.sh
RUN chmod +x /usr/local/bin/internal-entrypoint.sh

COPY config/crd/bases/ /etc/kubernetes/crds/

COPY helm-operator/watches.yaml ${HOME}/watches.yaml
COPY helm-operator/helm-charts/ ${HOME}/helm-charts/

ENTRYPOINT ["/usr/local/bin/internal-entrypoint.sh"]

```

```
#!/bin/sh -e

kubectl --kubeconfig /etc/kubernetes/kubeconfig/config apply -f /etc/kubernetes/crds/
exec /usr/local/bin/entrypoint $@
```

**Comment by mohamadnikan2013** [comment]
@camilamacedo86 
thank you for your response :)
