### ISSUE TITLE
Operator hangs after executing few roles and remaining roles are never executed.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#3232]
I am working on Ansible Operator on OpenShift Cluster 4.3. Most of the times when I apply the CR the operator executing few roles and randomly hangs at some task with out reporting further logs.
The problem is happening inconsistently  and not sure how to resolve the issue. Kindly help me out with some solution to resolve the issue.

**Comment by camilamacedo86** [comment]
Hi @AnilKumarBandi27, 

Could you provide more info?  
- What is the version of the SDK used in the operator project? Could you provide its Dockerfile? 
- Are you using the env var ANSIBLE_LOGS=True to get further information?

**Comment by tengqm** [comment]
the env var should be `ANSIBLE_DEBUG_LOGS`, btw.

**Comment by AnilKumarBandi27** [comment]
Hi @camilamacedo86 

I am using Operator-SDK V0.15.0

Please find the below Dockerfile and let me know the changes.

FROM quay.io/operator-framework/ansible-operator:v0.15.0

### Required OpenShift Labels
LABEL name="Sample Operator" \
      vendor="Anil" \
      version="v1.0.1" \
      release="1" \
      summary="This is Sample ansible operator." \
      description="This operator will deploy  Sample Ansible Operator to the Openshift Namespace."

# Required Licenses
COPY licenses /licenses

COPY watches.yaml ${HOME}/watches.yaml
COPY roles/ ${HOME}/roles/

COPY playbooks/ ${HOME}/playbooks/

I am able to run all the roles and there respective tasks with out any issues. But some  times same  operator hangs at random task and do not move forward.

Please share me your suggestions to fix the issue.

**Comment by camilamacedo86** [comment]
Hi @tengqm, 

In this version, you will not have the `ANSIBLE_DEBUG_LOGS`. For you are able to check the Ansible logs you need to check its container. You can:

- Run the command: `kubectl get all -n <namespace>` 
- Get the operator deployment name and check the ansible logs `kubectl logs deployment.apps/<operator-name> -c ansible -n <namespace>

In this way:

1) The best option here would be upgrade your project to the latest version. Could you upgrade your project to the latest version and see if the problem is solved?
2) If not, could you provide the logs when you face the scenario?

**Comment by tengqm** [comment]
@camilamacedo86 Good to know that ... `ANSIBLE_DEBUG_LOGS` is such a new thing. :)
Anyway, we may want to improve the site by adding a debug/trouble-shooting section.

**Comment by camilamacedo86** [comment]
Hi @tengqm, 

Sorry, not clear your latest comment. 

> @camilamacedo86 Good to know that ... ANSIBLE_DEBUG_LOGS is such a new thing. :)
Anyway, we may want to improve the site by adding a debug/trouble-shooting section.

The website by default shows the master branch docs. We are working on to allow users to check the docs per tag release which means that users would be able to check the old versions as well in the future. 

So far, you re able to check the old version docs via the tags

- v0.15.1 : https://github.com/operator-framework/operator-sdk/tree/v0.15.1/doc
- v0.15.2 : https://github.com/operator-framework/operator-sdk/tree/v0.15.2/doc
- v0.16.0 : https://github.com/operator-framework/operator-sdk/tree/v0.16.0/doc

In this way, we should not add in the website docs how to check the Ansible logs in the old versions. 

Regards the issue raised here `Most of the times when I apply the CR the operator executing few roles and randomly hangs at some task without reporting further logs.`

Could you figure out what happens in your project? Are you able to check the Ansible logs now? Could you confirm that the problem was that you were not knowing how to check to follow up the Ansible logs? if not, could you upgrade your project to the latest version and see if the problem is solved?

**Comment by tengqm** [comment]
Regarding my last comment, adding a debug/trouble-shooting section, I mean we may want to improve the site by adding a section for debugging. This would be very useful because when running ansible operators, for example, there are many moving parts: the operator, the ansible-runner, the proxy, ... We have some tips documented already, such as the environment variable, the verbosity setting, ... which can be consolidated. Just a quick thought.

**Comment by camilamacedo86** [comment]
Hi @tengqm, 

Your collab with the project is very welcome. Please feel free to raise PR against the master with your ideas for improvements in the docs as well. 

Regards the issue raised `here Most of the times when I apply the CR the operator executing few roles and randomly hangs at some task without reporting further logs.`

Could you figure out what happens in your project? Are you able to check the Ansible logs now? Could you confirm that the problem was that you were not knowing how to check to follow up the Ansible logs? if not, could you upgrade your project to the latest version and see if the problem is solved?

**Comment by AnilKumarBandi27** [comment]
Hi @camilamacedo86 
I have updated my operator and also able to check the ansible logs. My operator getting hang after executing few roles randomly at random tasks. I am  creating almost more than 85 OpenShift resources  [Pods – 17, DCs – 17, Image Streams – 17, Services – 17, HPA – 15, Routes – 5 ]. My observation is that Operator hangs at some random location (could be while executing 20th or 37th or 68th task etc.) and stops doing further operations. Reconciliation actions are not performed either.
Only way to come out of this situation is delete Operator instance, operator and re-install operator.

**Comment by camilamacedo86** [comment]
Hi @AnilKumarBandi27, 

It means that you update your operator to the latest version (0.18.1 ) which means that all logs will be found in the same place and is possible to use the env var `ANSIBLE_DEBUG_LOGS` = True to get all Ansible logs. 

So, for we are able to try to help you we need more information as described in the above comments. 

- Logs from the operator and Ansible when the problem happen.
- Info over the events in the cluster (kubectl get all events -n <namespace where the operator is eployed>) 
- If possible, could you share the code source of your project? 

Without troubleshooting the scenario and gathering further information OR describe how we can reproduce your issue I am afraid that we cannot move forward here. In this way, this issue is flagged with "needs-information" and we are looking for them.

**Comment by camilamacedo86** [comment]
Hi @AnilKumarBandi27, 

It means that you update your operator to the latest version (0.18.1) which means that all logs will be found in the same place and is possible to use the env var `ANSIBLE_DEBUG_LOGS` = True to get all Ansible ones. 

So, for we are able to try to help you we need more information as described in the above comments. 

- Logs from the operator and Ansible when the problem happen.
- Info over the events in the cluster (kubectl get all events -n <namespace where the operator is eployed>) 
- If possible, could you share the code source of your project? 

So, this issue is flag with `needs-information`. Could you please provide them?

**Comment by AnilKumarBandi27** [comment]
Hi @camilamacedo86 

For OCP 4.4 What is the recommended version of operator-sdk ?
Please provide the information.

**Comment by AnilKumarBandi27** [comment]
Hi @camilamacedo86 

These are my operator logs 
--------------------------- Ansible Task StdOut -------------------------------

TASK [mysql : Create Deployment Config for MYSQL ] ***********************
task path: /opt/ansible/roles/mysql/tasks/main.yml:80



"level":"info","ts":1592226365.8014367,"logger":"logging_event_handler","msg":"[playbook task]","name":"dptest5","namespace":"anil-test","gvk":"mysql.app.com/v1alpha1, Kind=MYSQL","event_type":"playbook_on_task_start","job":"3916589616287113937","EventData.Name":"mysql : Create Deployment Config for MYSQL"}
{"level":"info","ts":1592226367.7302597,"logger":"proxy","msg":"Cache miss: apps.openshift.io/v1, Kind=DeploymentConfig, anil-test/mysql-gateway-engine-test5"}
{"level":"info","ts":1592226367.773195,"logger":"proxy","msg":"Injecting owner reference"}

I am using openshift 4.3

Sorry ! I will not be able to expose source code.

My Operator source code has no issues. It is executing successfully. But some times it is stopping at some random role and not showing any error message or logs. But it is not moving forward.

**Comment by fabianvf** [comment]
@AnilKumarBandi27 There was a python3 related hanging issue fixed in v0.16.0 https://github.com/operator-framework/operator-sdk/blob/master/CHANGELOG.md#changed-1 , it sounds like that may be what you're hitting. If you want to fix it in your image without updating to a newer version of the base image, you need to pull in a newer version of the `kubernetes` python library. It's `python-kubernetes` in Fedora/RHEL repositories and `kubernetes` in pip.

**Comment by AnilKumarBandi27** [comment]
Hi @fabianvf 
Thanks! for your help. Issue got resolved after updating the python-kubernetes library.
