### ISSUE TITLE
Best way to make HTTP requests/gRPC requests required by Reconciliation.

### ISSUE THREAD

**Issue by tomqwpl** [operator-framework/operator-sdk#3299]
I'm asking for some best practice advice on how to implement an operator using the operator sdk.

Lets say that reconciling could potentially involve doing something like making an HTTP request or a gRPC call. What's the best way of approaching that?

- Just let the Reconcile method call block until it returns, and rely on the concurrent reconcile options to ensure that other reconciliations can still proceed?
- Ship things across to a dedicated go-routine that performs the work. Return from Reconcile with "reschedule after 5 seconds" say and then check the results next time round?
- Ship things across to a dedicated go-routine that performs the work, then when it's done uses its own client to update the Status of the CRD

The naive thing to do would seem to be to just make a blocking HTTP request in the Reconcile method, I'm just wondering whether that's going to cause any issues I'm not aware of. Given that the action I'm thinking of might take a non-trivial amount of time though it feels like I should be updating the status then letting the Reconcile method return while the HTTP request is performed

**Comment by joelanford** [comment]
@tomqwpl I think I would start out making a blocking HTTP request and handling the result synchronously once the request completes. As you suggested, you can tune your max concurrent reconciles to scale to handle simultaneous CR reconciliations. You may consider making that an externally configurable option of your operator so that it can be tuned for the environment it's deployed in.

You certainly _can_ go down the path of asynchronous HTTP calls, but that can get ugly quickly. Consider the scenario where a series of updates to a particular CR occurs faster than the asynchronous HTTP calls finish. When you're reconciling one of the subsequent updates, do you cancel the previous request, wait for it to complete, blindly make another request, etc?

If you do it synchronously, controller-runtime will guarantee that there is never more than one Reconcile running for a particular CR.

**Comment by tomqwpl** [comment]
> If you do it synchronously, controller-runtime will guarantee that there is never more than one Reconcile running for a particular CR.

Ah, that's interesting, yes. That will certainly help.
OK. I won't worry too much and do it the simplistic way.
Thanks.
