### ISSUE TITLE
Standardised Status Blocks

### ISSUE THREAD

**Issue by philbrookes** [operator-framework/operator-sdk#3310]
### Problem Statement
When provisioning a product via it’s operator, the most common flow is:
- Install the operator
- Create a CR
- Wait for the product to be ready

Currently, the final step is performed in a unique way for each operator, this could be as low-tech as checking if an end-point is responding correctly, or as automated as watching the status of the CR for something like “Status: Ready”.

### Describe the solution you'd like

The ideal scenario would be for each CR to contain recommended fields (could be included in the boilerplate generation) including a “ready” field, a “version” field, a “phase” field, a “message” field.
#### Ready
This is best consumed, by humans and computers as a boolean, every status block that results in a system that can be consumed would have a 
```
Status
  Ready: true|false
```
#### Version
It should be trivial to find out what version of an operand was provisioned, as a result of the creation of a CR, this would be kept up to date after upgrades to the product, every status block that results in a running product would have: 
```
Status
  Version: x.y.z
```
#### Phase
This should show the current status of the operation triggered as a result of the CR, values for this should be one of:
- Pending
- Progressing
- Complete / Reconciling

##### Pending
The operator has not yet started processing this CR, maybe it is blocked by other actions.
##### Progressing
The operator has now begun to process this CR, but has not yet completed the required actions.
##### Complete / Reconciling
This implies that the service is ready for use, if the configuration of the service is not maintained by the operator, then it should be “complete”, if the operator will continue to check and reconcile values, then the value should be “reconciling”, this phase should coincide with the ready field being set to true.
#### Message
This is used in conjunction with status to give a human-readable idea of what the operator is currently doing with the CR (e.g. “waiting for API server to start”, “service is active”).

**Comment by chirino** [comment]
An operator could manage multiple operands at different version numbers.

**Comment by philbrookes** [comment]
If an operator managed multiple versions of the same operand, I expect it would still know what version it installed and be able to update the status of the CR with the version that CR caused it to install.

**Comment by chirino** [comment]
You saying one operand image type of different versions. I’m saying different operant image types. Like a caching layer operand image and a business logic operand image.

**Comment by philbrookes** [comment]
Oh, I see what you mean. I suppose I'd hope that a specific bundle of images (backend, frontend, data layer, etc) ares grouped into a single version of the delivered product, but if we need to handle when this is not the case, we could have the version field being an array like so:
```
status:
  version:
   - backend: 1.2.3
   - frontend: 1.2.3
``` 

Or would it be better to suggest a CR per component, e.g. a backend CR, a frontend CR, etc, and the version of each can be written into each?

**Comment by kensipe** [comment]
@philbrookes This came up in a triage meeting today... there are a couple of questions that came up.

1. Is it your desire to standardize all operators to proposed standard?  There is a concerned if this should be an upstream conversation.  However I'm not sure there is confidence in standardizing (as detailed below)
2. Is this request mainly for operator sdk to provide standardized generates to aid for common status fields?  or are you pushing for a "valid" definition of what status should look like?
3. Is the interest here more geared towards reducing dev overhead of generating schema details?  

The discussion in the triage meeting today involved a few people and I don't know if I can speak for all of them.. but I will do my best to consolidate thoughts.  Most of us see the value of standardization especially around automation.  There were concerns if this was possible / likely.   Unknown types will have unknown structural needs for status.  That said, perhaps considering support around the 80% use case is a good idea.

It would be great to get some follow up on your thoughts.   There is a scheduled operator sdk meeting for wed July 1
https://docs.google.com/document/d/1ujWb-rSJ4JWeHLVxK0WS5ZuSJgeESG42MDeYjSl9Q6U/edit#heading=h.dp4gt7gj3cn
It would be great to add it to the agenda.

**Comment by slaskawi** [comment]
I like this idea! 

In a couple of weeks, our development team will be looking more into using community-based Postgresql Operator for Keycloak. Having a standardized `Ready` flag would be very helpful for us. We could assume, that whichever database Operator we'll pick, we could inspect this field to check if the database is up and running.

**Comment by philbrookes** [comment]
@kensipe thanks for the update. 

It would be good if the generates had standardised status fields, but my main goal is to define a recommended or "best practice" format for the status block, that we can refer to.

I do see that there will be some operators that simply do not operate in a manner that will apply to this format, and in that case I do not see an issue with them using their own status format. I am very much aiming at the 80% of operators that can apply a standardised status block.

I have added a note to the agenda, and am looking forward to discussing it further.

**Comment by philbrookes** [comment]
I have removed my note from the agenda, as I am on PTO this afternoon and away from my computer. I notice you have a weekly triage call on Mondays, so I will attend this meeting next week to discuss there. I hope this is OK.

**Comment by kensipe** [comment]
@philbrookes looking forward to the discussion.  enjoy the day and holiday!

cc: @joelanford

**Comment by camilamacedo86** [comment]
Hi @philbrookes, 

I just would like to share that: 

> Some resources in the v1 API contain fields called phase, and associated message, reason, and other status fields. The pattern of using phase is deprecated. Newer API types should use conditions instead.
Ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties

And then, see that SDK already provides a helper to work with conditionals. See: https://github.com/operator-framework/operator-sdk/blob/master/pkg/status/conditions.go. 

PS.: It shows related to https://github.com/kubernetes-sigs/kubebuilder/issues/1574 and then, I am starting to thinking that this kind of requirement could be an RFE to controller-runtime preferably.

**Comment by tengqm** [comment]
Also related to managing conditions. Some new helpers are just added to the upstream API machinery.
See: https://github.com/kubernetes/kubernetes/pull/92717/files#diff-96c14496c795cdcef80eed40c124f70a

**Comment by philbrookes** [comment]
@camilamacedo86 thanks for the doc. If we want to go in the direction of conditions, I would still like to see the name and values of them standardised, so that we can have a reasonable expectation of what to look for, in all CRs. I do not personally think that version should be a condition in any case.

However this comment leads me to believe that their is a trend to move away from using conditions, which is why I chose not to use them: https://github.com/kubernetes/kubernetes/issues/7856#issuecomment-335687733

**Comment by camilamacedo86** [comment]
Hi @philbrookes, 

> However this comment leads me to believe that their is a trend to move away from using conditions, which is why I chose not to use them: kubernetes/kubernetes#7856 (comment)

> Promote established/essential conditions to simple fields, as discussed above

Where you check that has `a trend to move away from using conditions`? My understanding by checking the thread is that it to move away from `Phase` and `simplify Conditions` which matches with `The pattern of using phase is deprecated` described above. Could you please clarify? I might be missing something.

**Comment by philbrookes** [comment]
I have been unclear. To clarify: I am fine with proposed stage field being moved to a condition and I am also fine with the proposed message field being migrated into that same condition. However the statement:

> Promote established/essential conditions to simple fields

I believe `CR.Status.Ready: true`, aligns with that statement.

**Comment by camilamacedo86** [comment]
I am not sure if `CR.Status.Ready`would make sense as a default `ContionalType`.

What `Ready` actually means for the controller's domain? Would not it have different meaning according to the logic implemented in each project? What  CR `ready` means in the controller/reconcile domain?  So, as part of the controller's domain, I can just see status such as `Reconciled`,`Irreconcilable`,`Reconciling`.

Because of this, IMO would be fine we think about what helpers we could provide to the users are able to manage their own status conditionals beyond the implementation that already exist [here](https://github.com/operator-framework/operator-sdk/blob/master/pkg/status/conditions.go) and/or to push this to upstream to address kubernetes-sigs/kubebuilder#1574 as get more inputs to shape that in the better way as possible which shows that is happening already too. See: https://github.com/kubernetes/kubernetes/pull/92717 point out by @tengqm.  

However, the `ContionalType` and `ConditionReason` shows part of the domain of each project itself. As for example, for [Helm](https://github.com/operator-framework/operator-sdk/blob/master/pkg/helm/internal/types/types.go#L58-L75) we have types that would not make sense for Go or Ansible.

**Comment by tengqm** [comment]
Sometimes ... things like these are all about tradeoffs.
Here is another thread of relevant discussions [Update Condition guidance](https://github.com/kubernetes/community/pull/4521), just in case folks here are unaware of it.

**Comment by camilamacedo86** [comment]
Hi @philbrookes, 

Following the link for the controller-runtime project where might would fit better the request. 

https://github.com/kubernetes-sigs/controller-runtime

Let's keep it open, but as we spoke today in the bug triage meeting would be very nice raise it in upstream since it shows beneficial to other projects as kubebuilder for example. I think you also got a few inputs so far that could be helpful to shape this proposal.  Also, I think that https://github.com/kubernetes-sigs/kubebuilder/issues/1574 and the other links can help you with it. So, wdyt about reformulated this RFE and raise there? If you move forward with, please let us know and if possible share the link here with us for we are able to follow up and try to contribute with it.

**Comment by philbrookes** [comment]
opened a proposal with controller-runtimes here: https://github.com/kubernetes-sigs/controller-runtime/issues/1036

**Comment by joekohlsdorf** [comment]
The proposed solution is to have a standardised set of fields to indiciate status but...
From an end-user perspective, it would be best to have `kubectl rollout status crd cr` become usable.

**Comment by camilamacedo86** [comment]
HI @philbrookes, 

It shows great and was flag as next milestone.  Controller-runtime has meetings as well where the issues are discussed. Feel free to join. Since it shows addressed in the appropriate place, IMO we can close this one. 

However, please feel free to ping us to re-open it if you think that would be required and let us know the reason as to ping us if you need any help.
