### ISSUE TITLE
deepcopy-gen: No such file or directory

### ISSUE THREAD

**Issue by cnuss** [operator-framework/operator-sdk#334]
Greetings!

I'm following the user guide (https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md)

And I'm attempting to do a new operator:

```
operator-sdk new memcached-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached
```

The process runs and successfully generates source and runs dep ensure, but it gets held up with the following error:

```
Run code-generation for custom resources
Error: failed to perform code-generation for CustomResources: (Generating deepcopy funcs
vendor/k8s.io/code-generator/generate-groups.sh: line 65: /Users/christian/cchh/gopath/bin/deepcopy-gen: No such file or directory
)
```

Any advice?  Thanks in advance!

**Comment by hasbro17** [comment]
The code-generation step is basically just running [generate-groups.sh](https://github.com/kubernetes/code-generator/blob/91d3f6a57905178524105a085085901bb73bd3dc/generate-groups.sh) from the vendored code-generator. Part of that is to first install the generator binaries like [deepcopy-gen](https://github.com/kubernetes/code-generator/blob/91d3f6a57905178524105a085085901bb73bd3dc/cmd/deepcopy-gen).

So your error suggests the script should have failed to [install deepcopy-gen](https://github.com/kubernetes/code-generator/blob/91d3f6a57905178524105a085085901bb73bd3dc/generate-groups.sh#L49) since we can't find it in `$GOPATH/bin`. But that means it should have exited with an error at that step and not 

Can you try to install the deepcopy-gen binary yourself from inside the operator project and see if it shows up in `$GOPATH/bin`:
```sh
$ go install github.com/example-inc/memcached-operator/vendor/k8s.io/code-generator/cmd/deepcopy-gen
$ ls $GOPATH/bin | grep deepcopy-gen
deepcopy-gen
```

**Comment by cnuss** [comment]
Thanks for your response @hasbro17 

My go environment was borked up and my $GOPATH was wrong.  Sorry for the interrupt! Cheers!
