### ISSUE TITLE
resource update event

### ISSUE THREAD

**Issue by carllhw** [operator-framework/operator-sdk#335]
Resource update event triggered when `ResourceVersion` do not change.

I think when `ResourceVersion` do not change, do not triggered update event,  or event has a bool attribute to know.

**Comment by hasbro17** [comment]
This is an intended consequence of setting the resync period parameter:
```Go
sdk.Watch(apiversion, kind, namespace, resyncPeriod)
```
That means your handler will periodically receive the current object state from the cache even if there is no update to the resource.

Ignoring an update event when the resourceVersion does not change(like in #336 or #294) will effectively disable the periodic resync. The reason we can't disable periodic resync right now is because the SDK lacks the ability to watch secondary resources owned by the primary resource and trigger the handler on changes to the secondary resource #146 
You can set the resyncPeriod to 0 to disable periodic updates as a work around for now.

In the long run after some upcoming design changes to the Watch API (related #146) we might be able to remove the periodic resync altogether and ignore updates with no resourceVersion changes. 
Or add a boolean field like you suggested to let the user ignore the event in the handler.

**Comment by hasbro17** [comment]
Consolidating this issue with #268 since this issue can be solved with predicated based filtering. 
And users can filter out and ignore events that don't have their resource version changed.
