### ISSUE TITLE
What is the current policy on security updates for past versions

### ISSUE THREAD

**Issue by bitscuit** [operator-framework/operator-sdk#3471]
## Type of question

**Are you asking about community best practices, how to implement a specific feature, or about general context and help around the operator-sdk?**

## Question

**What did you do?**
I have read the [security policy page](https://github.com/operator-framework/operator-sdk/blob/master/SECURITY.md), but I am still unsure of what it means currently with the major version being 0 right now. For example, I have been using the v0.17.0 helm-operator base image [here](https://quay.io/repository/operator-framework/helm-operator?tag=latest&tab=tags), and I am refraining from upgrading to v0.19.0 because there are several breaking changes. I see that there is a newer v0.17.2, but how long will v0.17.x keep being updated? Specifically, how long will the version keep getting updates to fix security vulnerabilities reported in the underlying OS that the image is based on?

**What did you expect to see?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**What did you see instead? Under which circumstances?**
A clear and concise description of what you expected to happen (or insert a code snippet).

**Environment**
* operator-sdk version:

  insert release or Git SHA here

* Kubernetes version information:

  insert output of `kubectl version` here

* Kubernetes cluster kind: 

**Additional context**
Add any other context about the question here.

**Comment by camilamacedo86** [comment]
Hi @bitscuit, 

The Backport Policy is described [here](https://sdk.operatorframework.io/docs/contribution-guidelines/backport-policy/). Usually, only very critical issues are backported. Also, it is just done to the most recent release which means -1. 

Note that it, if the fix that you are looking for was solved just for upper versions of Helm I am afraid that would not be possible to provide them for 0.17.x. And then, see that the breaking changes from 0.17 to 0.19 valid for Helm-based Operators are related to the Helm itself.  

Could you please let us know more in order to help you with? What is the fix that you are looking for to patch in the `0.17.x`? Do you need auto migration of Helm v2 releases because of this you cannot upgrade your project? If yes, 
not that it does NOT affect support for v2 Helm charts, which are still supported by Helm v3.

**Comment by bitscuit** [comment]
I'm not looking for any specific fixes to `0.17.x`. I was just curious about whether the image will be updated to fix package security vulnerabilities reported in the security scan https://quay.io/repository/operator-framework/helm-operator?tag=latest&tab=tags.

**Comment by camilamacedo86** [comment]
Hi @bitscuit, 

Ok. It depends on the scenario as described above. Please, feel free to attend the bug triage meeting to discuss your needs. Also, since you are speaking over security vulnerabilities then, I will not ask for you be specific and describe it. However, please feel free to reach out us in the Slack channel to seek further information as well.   

I am closing this one as. sorted out. However, please feel free to ping us if you think. that would be required re-open it.
