### ISSUE TITLE
use of operator-sdk vs kube builder

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#3558]
Hi 

We see few docs highlighting the integration of operator-sdk with kubebuilder.
How ever its not very clear, about the impact of this on the existing operator-sdk users.

Does this integration mean, operator-sdk framework would get deprecated ?
is it recommended to move on to kube-builder instead of operator-sdk or users can continue using operator-sdk ?

Thanks,
Kaushik

**Comment by kaushiksrinivas** [comment]
@camilamacedo86 
Need your inputs.

**Comment by camilamacedo86** [comment]
Hi @kaushiksrinivas, 

SDK is a process to be integrated with Kubebuilder which is our goal for 1.0.0. The idea is both projects share the same core-base which means that SDK wins some features that are available for Kubebuilder currently. Note that with it we are able to spend more effort in the advantages and facilities that SDK tool can promote on the top of that also, for example, to integrate your project with OLM and allow users distribute their projects on the https://operatorhub.io/. 

For more information over the integration see: https://github.com/kubernetes-sigs/kubebuilder/blob/master/designs/integrating-kubebuilder-and-osdk.md 

Also, feel free to attend the SDK meetings and the ML where this discussion also has been raised. 

I hope that it answers your question. So, I am closing this one, however, feel free to ping us to re-open if you need. 

c/c @dmesser

**Comment by kaushiksrinivas** [comment]
Hi @camilamacedo86 
Have below questions

1. Is this integration only with respect to project scaffolding ? or all the features of operator-sdk and kuberbuilder will be available in both the frameworks ?
   The documentation link below is already available, but v1.0.0 is not yet out.
   https://deploy-preview-3543--operator-sdk.netlify.app/docs/building-operators/golang/project_migration_guide/

   can you please give some more details on when one should be doing this migration ?
   Also, migration steps looks mostly files/directory changes, so the actual reconcile logics of controllers would not need any changes ?

2. If one chooses v0.19 version of operator-sdk, what project layout structure should we be using ? and the commands to create apis, controllers etc ?
   As of now v0.19 only is the latest, what layout structures should one use with this latest available release ?
   
3. When is the expected release of v1.0.0 and would this version release removes the old layout and commands completely ?

**Comment by camilamacedo86** [comment]
Hi @kaushiksrinivas, 

> The documentation link below is already available, but v1.0.0 is not yet out.
> https://deploy-preview-3543--operator-sdk.netlify.app/docs/building-operators/golang/project_migration_guide/

After 0.19, new Go projects can just be created with the new layout. We are working to do the same for Helm and Ansible. If you check the master Helm is already in a good shape as well for 1.0.0. 

The Go migration doc is available for 0.19 docs as well. However, the above link is a preview of the PR which has fixes improvements in order to close  #3460. I sent it for you because it will give a better context since all concerns from other users are addressed and approved by them as well. 

> can you please give some more details on when one should be doing this migration ?

If you will create a new project than I'd recommend you use 0.19 and do it in the new layout. You also can already start to migrate your legacy projects as well. They will need to migrate to work with 1.0.0. After, 1.0.0 the legacy layout will no longer be supported. 

> Also, migration steps looks mostly files/directory changes, so the actual reconcile logics of controllers would not need any changes ?

See the steps in the https://deploy-preview-3543--operator-sdk.netlify.app/docs/building-operators/golang/project_migration_guide/. Note that it described how to migrate the controller as well. You need to port controller/reconcile logic and apply a few caveats. All steps required to migrate your projects as what changed is described detailed on it. 

 > If one chooses v0.19 version of operator-sdk, what project layout structure should we be using ? and the commands to create apis, controllers etc ? 

If you will create a new project then you will use the new layout, however, with 0.19 the tool commands still working for the legacy layout. 

> As of now v0.19 only is the latest, what layout structures should one use with this latest available release ?

I understand that it was answered above already. 

> When is the expected release of v1.0.0 and would this version release removes the old layout and commands completely?

Yes. After 1.0.0 the legacy layout will no longer be supported. We have not an ETA for v1.0.0 but its alpha version is planned to be released very soon.

**Comment by estroz** [comment]
We need to discuss this in our docs overview/FAQ.

/kind documentation

**Comment by estroz** [comment]
Closed by #4411
