### ISSUE TITLE
operator-sdk up local depends on  OPERATOR_NAME flag

### ISSUE THREAD

**Issue by fanminshi** [operator-framework/operator-sdk#356]
The section user_guide about how to use `operator-sdk up local ` doesn't work anymore due to a newly introduced `OPERATOR_NAME` flag that's required to set.

``` sh
$ operator-sdk new app-operator --api-version=app.example.com/v1alpha1 --kind=App
$ cd app-operator/
$ kubectl create -f deploy/crd.yaml
$ operator-sdk up local
INFO[0000] Go Version: go1.10
INFO[0000] Go OS/Arch: darwin/amd64
INFO[0000] operator-sdk Version: 0.0.5+git
FATA[0000] Failed to init operator service: OPERATOR_NAME must be set
exit status 1
```

A work around is to add the `OPERATOR_NAME` manually such as `OPERATOR_NAME=<your-operator-name> operator-sdk up local`

We probably should default the `OPERATOR_NAME` when `operator-sdk up local` is called. Also we should have a test to catch this.

cc/ @hasbro17 @AlexNPavel

**Comment by hasbro17** [comment]
The issue is that we're doing a `logrus.Fatalf()` on failing to init the metrics service
https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/metrics.go#L20
This should be `logrus.Errorf()`

Same here:
https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/metrics.go#L24

So we can easily fix the above issue for now.

And as a followup task we need to add an e2e test for testing out the workflow with `operator-sdk up local` to catch issues like this. That should be it's own issue.
