### ISSUE TITLE
Rbac files created in v0.19 version operator-sdk

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#3594]
Hi,

We see upon make generate and make manifests, a lot of yaml files with respect to service account/roles/role bindings are created in the folder config/rbac/ v0.19

Can we combine these role bindings and roles to a single file and deploy them ?
why are so many roles and role bindings created ?

ex output:
-rw-------. 1 root root 429 Jul 27 12:01 leader_election_role.yaml
-rw-------. 1 root root 381 Jul 27 12:01 kustomization.yaml
-rw-------. 1 root root 261 Jul 27 12:01 role_binding.yaml
-rw-------. 1 root root 268 Jul 27 12:01 auth_proxy_service.yaml
-rw-------. 1 root root 263 Jul 27 12:01 leader_election_role_binding.yaml
-rw-------. 1 root root 280 Jul 27 12:01 auth_proxy_role.yaml
-rw-------. 1 root root 257 Jul 27 12:01 auth_proxy_role_binding.yaml
-rw-------. 1 root root 153 Jul 27 12:01 auth_proxy_client_clusterrole.yaml
-rw-------. 1 root root 332 Jul 27 12:03 memcached_viewer_role.yaml
-rw-------. 1 root root 375 Jul 27 12:03 memcached_editor_role.yaml
-rw-------. 1 root root 370 Jul 27 13:36 role.yaml

Thanks,
Kaushik

**Comment by kaushiksrinivas** [comment]
@camilamacedo86 
Any inputs

**Comment by camilamacedo86** [comment]
HI @kaushiksrinivas, 

> why are so many roles and role bindings created ?

Projects are now scaffolded using [kustomize](https://github.com/kubernetes-sigs/kustomize) to manage Kubernetes resources needed to deploy your operator. So, each file has its own purpose. See:

- The *_auth ones are related to the RBCA configurations done for the [kube-auth-proxy](https://github.com/brancz/kube-rbac-proxy) which is also something new.
- The purpose of the `<kind>_editor/viewer` is to be helpers for cluster admins are able to configure permissions based on the Kinds for groups of users. They are not used by the controller/manager. 
- The leader_elections are specific permissions for the leader election
- The `kustomization.yaml` is the config for RBCA using [kustomize](https://github.com/kubernetes-sigs/kustomize). See that, for example, for you disable the  [kube-auth-proxy](https://github.com/brancz/kube-rbac-proxy) you will comment lines in this file.
- Finally, the role and role binding are equivalents to the files scaffolded in the legacy layout. 

> Can we combine these role bindings and roles to a single file and deploy them ?

I do not think so since the idea is to provide the features described by default. However, note that users are able to customize their projects as please them.  

Also, could you please let us know what is the use case that justifies this change? What is the problem that you are facing which would justify trying to combine all these files as suggested by you?

**Comment by estroz** [comment]
As @camilamacedo86 has suggested, the new project layout uses a bunch of kustomize files in `config/` to generate a final set of operator manifests. This has been standard practice in [kubebuilder](https://book.kubebuilder.io/cronjob-tutorial/basic-project.html#launch-configuration) for a while, which the SDK has adopted. If you still think your idea is relevant, re-open this issue in the [kubebuilder repo](https://github.com/kubernetes-sigs/kubebuilder/).
