### ISSUE TITLE
fatal: write failure on 'stdout': Bad file descriptor

### ISSUE THREAD

**Issue by dougbtv** [operator-framework/operator-sdk#363]
I'm having some trouble during the `git init` -- apparently the commit is failing with this.

```
Run git init ...
Initialized empty Git repository in /home/centos/go/src/github.com/dougbtv/hello-operator/.git/
fatal: write failure on 'stdout': Bad file descriptor
Error: failed to exec git []string{"commit", "-m", "INITIAL COMMIT"}: exit status 128
```

The command I'm running is:

```
operator-sdk new hello-operator --api-version=cache.example.com/v1alpha1 --kind=Memcached
```

I followed the getting started guide, and I'm using `CentOS Linux release 7.4.1708 (Core)`. I can provide the details on how I installed the deps, but, git itself is from the CentOS RPM repos.

**Comment by hasbro17** [comment]
@dougbtv Hard to say what's the issue since I don't have a CentOS system at hand right now to try and reproduce this.

But the last few steps in `operator-sdk new ...` basically do:
```sh
$ git init
$ git add --all
$ git commit -m "INITIAL COMMIT"
```
https://github.com/operator-framework/operator-sdk/blob/master/commands/operator-sdk/cmd/new.go#L182-L184


In your case the last one seems to failing. The only thing different with that is that `exec.Cmd` has stdout set to nil meaning stdout is redirected to os.DevNull(/dev/null).
And I'm seeing `fatal: write failure on 'stdout': Bad file descriptor` so maybe it's an issue in writing to /dev/null.
https://github.com/operator-framework/operator-sdk/blob/master/commands/operator-sdk/cmd/new.go#L184

First off can you confirm that you can write to /dev/null.
Secondly can you try changing [L184](https://github.com/operator-framework/operator-sdk/blob/master/commands/operator-sdk/cmd/new.go#L184) to direct stdout to the terminal:
```Go
execCmd(os.Stdout, "git", "commit", "-m", "INITIAL COMMIT")
```
 and then `make install` and try `operator-sdk new ...` again.

**Comment by Cristian-Hernandez** [comment]
I had the same problem with all my local repositories.

oddly it was resolved when I restarted my computer.

**Comment by KurKestutis** [comment]
For my it was enough to close and open git bash:)

**Comment by zihad247414** [comment]
I did same, restart computer and it was solved my issue 👍

**Comment by mudivili** [comment]
Restarting is not necessary. Simply close and open the git bash. Or find out the way to increase git bash displayed lines count.
The issue is because, data displayed in git bash reached maximum size that is configured.

**Comment by crispaulcastaneda** [comment]
First thing I made a solution by closing the git terminal or if you run VS Code you should close it. If this doesn't work, try to restart your machine.
