### ISSUE TITLE
Website: Broken Link to memcached_controller.go example on quickstart

### ISSUE THREAD

**Issue by RiRa12621** [operator-framework/operator-sdk#3637]
## Bug Report

**What did you do?**
Accessed https://sdk.operatorframework.io/docs/golang/quickstart/ and clicked the link to the memcached_controller.go example

**What did you expect to see?**
The memcached_controller.go example located at https://github.com/operator-framework/operator-sdk/blob/master/example/memcached-operator/memcached_controller.go.tmpl

**What did you see instead? Under which circumstances?**
a 404 page from github because the website points to https://github.com/operator-framework/operator-sdk/blob/master/example/kb-memcached-operator/memcached_controller.go.tmpl

**Possible Solution**
The latest version of the website includes the right link https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/golang/quickstart.md

**Comment by asmacdo** [comment]
This has been fixed in the v0.19.x branch:
https://v0-19-x.sdk.operatorframework.io/docs/golang/quickstart/#implement-the-controller

We've made the decision to keep the `latest` branch (which is what is published at sdk.operatorframework.io) aligned with the git tag for the latest release, so those changes won't show up on the main site until we cut another release.

**Comment by camilamacedo86** [comment]
It also is fixed in the master: https://master.sdk.operatorframework.io/docs/building-operators/golang/quickstart/. And s @asmacdo said it will be available in the latest one after the next release with docs (probably 1.0.0).

Also, I'd like to recommend you follow up the migration steps by checking the preview of the PR https://github.com/operator-framework/operator-sdk/pull/3543  which we are working and has many fixes and updates. 

I am closing it a sorted out since it is fixed in the master.
