### ISSUE TITLE
Is it possible to not reconcile on existing CRs if the operator pod restarts

### ISSUE THREAD

**Issue by mikeshng** [operator-framework/operator-sdk#3660]
## Type of question
general context and help around the operator-sdk.

## Question

**What did you do?**
I am running an ansible operator generated from operator-sdk locally with the `operator-sdk run --local` command. I have a few CRs deployed already. I simulated an operator pod restarts by ctrl-c the local run and then run it again.

**What did you expect to see?**
I see all the previously reconciled CRs, started to reconcile again.

**What did you see instead? Under which circumstances?**
I think this is the right default behaviour but is there something that comes with operator-sdk that can stop reconciles on existing CRs on restart?

**Environment**
* operator-sdk version:
operator-sdk version: "v0.19.0", commit: "8e28aca60994c5cb1aec0251b85f0116cc4c9427", kubernetes version: "v1.18.2", go version: "go1.13.10 linux/amd64"

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2020-01-14T01:25:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

* Kubernetes cluster kind: 
just a local development `kind` cluster

**Comment by hasbro17** [comment]
> but is there something that comes with operator-sdk that can stop reconciles on existing CRs on restart

@mikeshng Can you specify how an existing CR (already reconciled) would look different from, say a new CR that created while your operator was restarting/offline?

The reason why your operator gets (create) events for all existing CRs when it restarts is so that your operator is idempotent and can declaratively manage all objects.

You could try to define a boolean switch on your CR e.g `isReconciled` and set that to true when it first gets reconciled but that means you're introducing state into the CR which is an anti pattern.

Even for already reconciled CRs ideally your operator should be able to go through the normal reconciliation loop only to figure out from the state of the objects on the cluster that the CR is already reconciled instead of storing that state on the CR.

So if you could define your use case for knowing what a reconciled CR looks like (based on the state of the cluster objects) that might help you avoid doing this.

Also /cc @fabianvf incase there's already something in the ansible-operator that let's you manage state.

**Comment by mikeshng** [comment]
@hasbro17 Thank you for your explanation and suggestion. 

An example of my use case is:
- The CR creation/update represent a REST call to a server.
- It's possible that the REST call is not idempotent. So I don't want it call it more than once unless there are some real changes made to the CR.

Please feel free to close this issue. I think your suggestion of `isReconciled` is probably what I needed.

**Comment by asoorm** [comment]
@mikeshng You should be able to create a status field in the resource. Then based on the status field, even if the reconcile func is called, it can exit early.

If your REST call is not idempotent, I think that you can get around this by performing a GET then perform some validation on the response before performing a POST, PUT, PATCH request on the REST server.
