### ISSUE TITLE
It is possible use the interactive mode just once 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3671]
**What did you do?**
- Create a project and generated the bundle
```
mkdir memcached-operator
cd memcached-operator
operator-sdk init --domain=example.com --repo=github.com/example-inc/memcached-operator
operator-sdk create api --group cache --version v1 --kind Memcached --resource=true --controller=true
make bundle
```
- Run again the make bundle 

**What did you expect to see?**
The interactive mode ask if I would like to keep the previous values informed or inform them again 

**What did you see instead? Under which circumstances?**
The bundle is re-created with the same values informed before.

**Possible solution**
IMO it should ask: would you like to change the values [y/n]?

**Environment**
* operator-sdk version: 4282ce9acdef6d7a1e9f90832db4dc5a212ae850

**Comment by joelanford** [comment]
`make bundle` uses `operator-sdk generate kustomize manifests -q`. The default behaviour is to prompt when the CSV metadata does not exist, and not to prompt when it does (since it already exists). If we asked every time, that would make `make bundle` require interactive input every time, which is a bad UX. 

The metadata should change rarely. When it needs to change, there are two options:
1. Run `operator-sdk generate kustomize manifests --interactive` to fully re-populate the UI metadata fields.
2. Manually edit `config/manifests/bases/<projectName>.clusterserviceversion.yaml`

**Comment by camilamacedo86** [comment]
HI @joelanford,

> If we asked every time, that would make make bundle require interactive input every time, which is a bad UX. 

IMO it should ask: would you like to change the values [y/n]?

**Comment by camilamacedo86** [comment]
In the bug triage meeting, we agreed in just add in the output the information that the interactive mode will not appear by default in the next times and how users can update and change these values (by the command and/or directly in the file)
