### ISSUE TITLE
Tool allow users choose between --project-version  "2" or  "3-alpha"

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3674]
The tool allows users to choose between `--project-version  "2" or  "3-alpha"`, however, both will perform the same GO v2 plugin scaffold. The only diff between both is the project name that is added to the PROJECT file now because of what was done in https://github.com/kubernetes-sigs/kubebuilder/pull/1611 which would be valid just for v3-alpha.  

- Should not the `3-alpha` project-version scaffold the project with SDK plugin alpha based on the default upstream Go plugin for 3-alpha?

**Comment by camilamacedo86** [comment]
Hi @joelanford, @estroz, 

We probably might be able to check/address it after 1.0, however, in POV it is valid just think a little about it and the possible impacts of this change after 1.0 to make sure that everything is fine.

**Comment by estroz** [comment]
Users should be able to choose between the two supported _project_ versions. Until project version 2 is deprecated, `--project-version 2` is still valid. The project version and plugin version are orthogonal concepts; one just happens to be scaffolded by the other. Since deprecation of a project version is a fully upstream issue (we get `PROJECT` from kubebuilder), the issue of 2's deprecation should be recreated upstream.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

The point is that in upstream when we choose  --project-version=3-alpha it will use the v3 plugin and in SDK the behaviour is not the same. so, it is not something that needs to be done in upstream but in sdk.

**Comment by joelanford** [comment]
@estroz @camilamacedo86 can you clarify one thing for me? My understanding is:

- project version `v2` supports and is inherently equal to Kubebuilder's Go v2 plugin. v2 projects do not support the layout or plugin keys. So if someone runs `operator-sdk init --project-version="2", that results in the _exact_ same output as `kubebuilder init --project-version="2"`

- project version `v3-alpha` is required for Helm and Ansible layouts AND for our phase2-ish `go.sdk.operatorframework.io` plugin. With this, users get the extra bundle and samples kustomization in Go projects and they get access to Helm and Ansible layouts.

Is this understanding correct?

**Comment by camilamacedo86** [comment]
Hi @joelanford and @estroz 

OK. I also re-checked all to see if I am not missing the boat in anything here. 

See `$ operator-sdk init -h ` (== in both tools )
>  --project-version string   project version, possible values: ("2", "3-alpha") (default "3-alpha")

**If we run `$ operator-sdk init` or `operator-sdk init --project-version=3-alpha`:** (default "3-alpha")

**SDK == KB**
-  PROJECT version `3-alpha` with `layout: go.kubebuilder.io/v2` and `plugins:go.sdk.operatorframework.io/v2-alpha:`
- It will add the projectName in the PROJECT file since we merge kubernetes-sigs/kubebuilder#1611 ( add projectName when the project version is v3-alpha )

**If we run `$ operator-sdk init --project-version=2`:** **(NOT Default)**

**SDK != KB**

- SDK is == V3-alpha but has not the projectName
- KB has no plugins at all as you said. 

PS.: I am unable to gen with version 2 in sdk with the master branch: See: https://github.com/operator-framework/operator-sdk/issues/3690

**Regards my comments over v3-alpha plugin**: I was missing the boat since KB do NOT use the `go.kubebuilder.io/v3-alpha` by default in the v3-alpha projects as well. To gen that we need to pass the plugin version as well. 

So, the only think that we need to do in this task is after fix https://github.com/operator-framework/operator-sdk/issues/3690 ensure that if we run `operator-sdk init --project-version=2` it will not scaffold layout and plugins. Am I right?

**Comment by estroz** [comment]
Plugin|Plugin Phase|Plugin Version| Project Versions
---|---|---|---
go.kubebuilder.io|1|v2|2, 3-alpha
go.kubebuilder.io|1|v3-alpha|3-alpha
go.sdk.operatorframework.io|2|v2-alpha|3-alpha
ansible.sdk.operatorframework.io|1|v1|3-alpha
helm.sdk.operatorframework.io|1|v1|3-alpha

I use plugin phase to differentiate the current phase 1 plugins from future phase 2 plugins, which we have implemented as post-plugin modifiers ([manifests](https://github.com/operator-framework/operator-sdk/tree/v1.0.0-alpha.2/internal/plugins/manifests), [scorecard](https://github.com/operator-framework/operator-sdk/tree/v1.0.0-alpha.2/internal/plugins/scorecard)) in a forwards-compatible way under the `go.sdk.operatorframework.io` plugin umbrella. I think this is where the confusion lies, since this umbrella plugin cannot be seen in `operator-sdk init -h` output as a phase 1 plugin; this is intentional.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

The following one is not supportable by SDK just for KB currently. Am I right? Would we like to support it as well as post 1.0? 

go.kubebuilder.io | 1 | v3-alpha | 3-alpha
-- | -- | -- | --

Regards the project-version=2: 
- Should the PROJECT file scaffolded by SDK has the plugin and layout which has NOT in KB?
- Since project-version=2 actually do not support plugins would not make more sense we do not support it and have not this option at all for SDK?

**Comment by camilamacedo86** [comment]
I understand that the scenario project-version=2 will be solved with https://github.com/kubernetes-sigs/kubebuilder/pull/1628/files 👍

**Comment by estroz** [comment]
Closed by #3697
