### ISSUE TITLE
Webhooks.md for golang is not working as expected.

### ISSUE THREAD

**Issue by bharathi-tenneti** [operator-framework/operator-sdk#3693]
Descroption: Following https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/golang/webhooks.md, I am not able to create webhooks. Might be missing cert-manager installation setup, and instructions to uncomment Webhook related code in the operator implementation.

**Comment by bharathi-tenneti** [comment]
As per instructions from the document, below is the error faced.
```shell
I0807 20:12:16.873307       1 leaderelection.go:242] attempting to acquire leader lease  memcached-operator-system/f1c5ece8.example.com...
2020-08-07T20:12:16.876Z	INFO	controller-runtime.manager	starting metrics server	{"path": "/metrics"}
2020-08-07T20:12:16.876Z	INFO	controller-runtime.webhook.webhooks	starting webhook server
2020-08-07T20:12:16.877Z	ERROR	setup	problem running manager	{"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
	/workspace/main.go:99
runtime.main
	/usr/local/go/src/runtime/proc.go:203
```

**Comment by joelanford** [comment]
I'm curious if we even need to keep this doc. Can we just link to an upstream kubebuilder doc about webhook development and usage?

**Comment by bharathi-tenneti** [comment]
> I'm curious if we even need to keep this doc. Can we just link to an upstream kubebuilder doc about webhook development and usage?

The steps are the same as far as I understand.

**Comment by camilamacedo86** [comment]
Hi @bharathi-tenneti, 

The error `"error": "open /tmp/k8s-webhook-server/serving-certs/tls.crt: no such file or directory` occurs when the required steps to set up the cert-manager were performed. See that we need to change things in the templates. As you did in the samples: https://github.com/operator-framework/operator-sdk-samples/blob/master/go/kubebuilder/memcached-operator/config/default/kustomization.yaml#L45-L70

The webhooks works in k8s clusters because it is tested by Kubebuilder CI as well. See: [here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v2/e2e_suite.go#L108-L150) and [here](https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/e2e/v2/e2e_suite.go#L264-L286).

**Comment by bharathi-tenneti** [comment]
True, as per @joelanford 's suggestion, Since the actual steps are included in KB book, we can  directly point to upstream docs.

**Comment by camilamacedo86** [comment]
IMO we should remove the webhooks info from the tutorial. This info does NOT shows accurate and relevant to the example and brings a lot of confusion. We have no step in the tutorial that users should create and/or use a webhook. Also, IHMO if we will add a doc it should be part of an advanced/reference where we would have a continuation of the tutorial to explain how to make the Memcached-operator be implemented with webhooks.

**Comment by bharathi-tenneti** [comment]
Closing this issue for now, until we are clear about what needs to be done.
