### ISSUE TITLE
Helm operator does not provide obvious way to execute helm test

### ISSUE THREAD

**Issue by aaronmcohen** [operator-framework/operator-sdk#3763]
## Bug Report

**What did you do?**

Import an existing helm 2.x chart

**What did you expect to see?**
The existing [chart test](https://v2.helm.sh/docs/developing_charts/#chart-tests) to be surfaced and runnable against an existing deployments. 

**What did you see instead? Under which circumstances?**
The existing helm tests were indeed imported into the new operator but there wasn't an obvious way to invoke them.

**Environment**
* operator-sdk version:

operator-sdk version: "v1.0.0", commit: "d7d5e0cd6cf5468bb66e0849f08fda5bf557f4fa", kubernetes version: "v1.18.2", go version: "go1.14.7 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"

* go version:

go version go1.15 darwin/amd64

* Kubernetes version information:

Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}

* Kubernetes cluster kind: 

* Are you writing your operator in ansible, helm, or go? helm

**Comment by camilamacedo86** [comment]
Hi @aaronmcohen, 

Thank you for raising it. The Helm tests in the chart dir which are called with `helm tests` are specific for the chart and not to the operator. So, I do not think that the SDK tool should use them to verify the Operator project since they ensure just the chart. 

For that, the best approach maybe would be use scorecard and kuttl features which are provided by the SDK tool to ensure the quality of the Operator.  @jmccormick2001 have we any doc over how to use them with Ansible/Helm already?

**Comment by aaronmcohen** [comment]
Thank you @camilamacedo86  for responding. While I agree `kuttl` can be used to test the helm operator it isn't the same as `helm test`. They target two different users.  Any `adopter` of a helm chart can run a `helm test` on an already installed helm release. So it is a sanity or DVT test the `consumer` can run. Something like `kuttl` Is for the `developer` running tests that are not necessarily shipped with the operator itself. 

Ideally it would be nice to have something like another `kind` in the watches.yaml which would allow the user to run the `helm.sh/hook` resources against an existing deployment.

**Comment by joelanford** [comment]
@aaronmcohen Can you expand on the use case and maybe write up a bit more description of the feature request to explain what you'd like to see?

**Comment by semoac** [comment]
I encounter a similar problem, since I need to validate the status of the resources after the upgrade. Helm doesn't have a good way to ensure that the resources were properly deployed, so `operator-sdk` doesn't have a good way to report the status of the child resources either.
I was hoping to use `helm test` in my pipeline to confirm the status of the rollout after a few seconds.

**Comment by joelanford** [comment]
It should be possible to directly use `helm test <crName>` once the operator has reconciled the CR.

Does that work (and solve the problem)?  If so, we should document this to make it more obvious that this should work out of the box.

**Comment by aaronmcohen** [comment]
@joelanford Please document this to make it more obvious. Additionally do you still need me to expand our use-case?

**Comment by joelanford** [comment]
If running `helm test` directly meets your needs, then I think that answers my question. Thanks!

**Comment by camilamacedo86** [comment]
Hi @aaronmcohen and @semoac, 

Would you not like to contribute to the project by documenting it? @aaronmcohen do you see any other a point that still requires some implementation or can we address all as described above by @joelanford ?

**Comment by estroz** [comment]
This issue will serve as documentation rather than adding this to SDK docs.

/remove-kind documentation

**Comment by aaronmcohen** [comment]
@camilamacedo86 @joelanford Per https://github.com/operator-framework/operator-sdk/issues/3763#issuecomment-696087557 . How do you run helm tests against a helm based operator? What `tiller` do you point the client to?
