### ISSUE TITLE
Add doc to explain how to grant admin permissions for the user 

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#3778]
Would be very nice we have a doc on the website with quite similar info of https://cloud.google.com/kubernetes-engine/docs/how-to/role-based-access-control#iam-rolebinding-bootstrap to link on the Prerequisites. We cannot link the cloud.google.com doc, however, it is exactly the info that shows missing.

**What we need to here?**
- Add the doc
- Link the doc in the tutorials and quickstarts

**Comment by jberkhahn** [comment]
Would also be a good idea to add a blurb saying that because kube doesn't have an explicit user abstraction, any actual cloud platform is going to have it's own solution for this - so setting up these permissions FOR REAL for an actual operator is going to involve some non-trivial work that is beyond the scope of our docs.

**Comment by sujil02** [comment]
https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#restricting-roles-and-permissions
