### ISSUE TITLE
Could I watch a specific object ?

### ISSUE THREAD

**Issue by sbose78** [operator-framework/operator-sdk#3780]
With operator-sdk or controller-runtime, 
Is it possible to watch a specific object instead of a specific type? In other words, could I add a watch on a secret named "foo" instead of watching all secrets ?

**Comment by joelanford** [comment]
A controller-runtime watch is a helper function for the API server's `watch` verb on resources, so the reason things are structured that is due to the design of the Kubernetes API server.

Watches _do_ support various filter functions, but controller-runtime does not currently support setting server-side filters when invoking watches, mainly because the controller-runtime client uses a cache for reading and it populates the cache by watching any resources that were requested.

There's some discussion and prototyping ongoing to support filtered list/watches, but its a pretty complex problem that will take awhile to solve.

In the meantime, your best bet would be to use a predicate that only passes events through to the handler if they have the specified name. Of course, this assumes your controller can tolerate being sent all secret events and filtering them client-side.

**Comment by sbose78** [comment]
Thanks @joelanford , this really helps.

Does that mean the resource footprint between 
* watching all secrets, and
* watching all secrets owned by my CR
is roughly the same since the cache anyway gets populated by all secrets since my controller had expressed an interest in watching secrets?

**Comment by joelanford** [comment]
Yep, that's exactly right. Closing, since this seems answered, but let us know if you have any more follow-ups!
