### ISSUE TITLE
documentation: Link to project migration guide is 404

### ISSUE THREAD

**Issue by jensfr** [operator-framework/operator-sdk#3862]
#### What did you do?

[kni@provisionhost-0-0 kata-operator]$ operator-sdk version
[Deprecation Notice] Operator SDK has a new CLI and project layout that is aligned with Kubebuilder.
See `operator-sdk init -h` and the following doc on how to scaffold a new project:
https://v0-19-x.sdk.operatorframework.io/docs/golang/quickstart/
To migrate existing projects to the new layout see:
https://sdk.operatorframework.io/docs/golang/migration/project_migration_guide/

operator-sdk version: "v0.19.3", commit: "d529ba46aa04b85dfe2dba9074a6f7943ce7886d", kubernetes version: "v1.18.2", go version: "go1.13 linux/amd64"

#### What did you expect to see?

To click on the link project migration guide and see it

#### What did you see instead? Under which circumstances?

A 404 error page

`$ operator-sdk version`

v0.19.3

#### Possible Solution

Fix the URL. Maybe this is the right one? -> https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/

**Comment by camilamacedo86** [comment]
Hi @jensfr, 

Thank you for raising it. Since it is version 0.19.x we need to push a Pull request against its branch. The correct link there would be: https://v0-19-x.sdk.operatorframework.io/docs/golang/project_migration_guide/. However, note that the guide on 1.0 and master (https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/) has improvements. So, shows that we could do here;

- Update the docs on 0.19.x to have the same guide https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/. See: https://github.com/operator-framework/operator-sdk/blob/v0.19.x/website/content/en/docs/golang/project_migration_guide.md
- Update the tool to link : https://v0-19-x.sdk.operatorframework.io/docs/golang/project_migration_guide/. See: 
https://github.com/operator-framework/operator-sdk/blob/v0.19.x/cmd/operator-sdk/main.go#L51

Would you like to collab with the project by pushing a PR?

**Comment by pradeepnnv** [comment]
Hi @camilamacedo86 , I would like to try fixing this issue.

**Comment by camilamacedo86** [comment]
Hi @pradeepnnv, 

It is very nice.  Please, feel free to push the PR and assign this issue to you. (To assign you just need to do a new comment with `/assign <your git hub name>`)

**Comment by jensfr** [comment]
Thank you, @pradeepnnv!

Camila Macedo <notifications@github.com> schrieb am So., 13. Sept. 2020,
19:10:

**Comment by joelanford** [comment]
Closed by #3876
