### ISSUE TITLE
Retrieving watch namespace in operator-sdk 1.0

### ISSUE THREAD

**Issue by gee4vee** [operator-framework/operator-sdk#3948]
## Type of question

How to implement a specific feature
We are migrating to operator-sdk 1.0. In our main.go, we need to create additional resources. Previously we used `namespace, err := k8sutil.GetWatchNamespace()` to get the namespace in which to create the resources. Now `k8sutil` is internal and cannot be used. Is there an alternative we can use in main.go to get the namespace in use?

#### What did you do?

Migrating our operator to use operator-sdk 1.0 and latest project format.

#### What did you expect to see?

An API to get the watch namespace.

#### What did you see instead? Under which circumstances?

`k8sutil` package is now internal

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**
OpenShift

`$ operator-sdk version`

1.0.1

`$ go version` (if language is Go)

`go version go1.15 darwin/amd64`

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.2+554af56", GitCommit:"554af56", GitTreeState:"clean", BuildDate:"2020-07-27T23:14:32Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by estroz** [comment]
@gee4vee that function was [removed in v1.0.0](https://github.com/operator-framework/operator-sdk/releases/tag/v1.0.0) from the SDK since it is a [simple wrapper](https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#configuring-namespace-scoped-operators) around `os.LookupEnv("WATCH_NAMESPACE")`. We suggest writing that function yourself as described in the linked docs.
