### ISSUE TITLE
Add controller-gen and kustomize to the SDK base image

### ISSUE THREAD

**Issue by SteveMattar** [operator-framework/operator-sdk#4000]
#### Describe the problem you need a feature to resolve.

My project is using the new Kubebuilder-style layout
I need a base image containing the following tools in order to build my operator bundle
* `controller-gen`
* `kustomize`
* `operator-sdk` v1+
* `envtest`

#### Describe the solution you'd like.
Include `controller-gen` and `kustomize` to your SDK base image
The original PR is #3902 

/language go

**Comment by joelanford** [comment]
We should probably include the `envtest` binaries in the base image as well.

**Comment by aemperador** [comment]
it looks like the PR for this was merged. should this issue be closed? 

PR ref: https://github.com/operator-framework/operator-sdk/pull/3902

**Comment by SteveMattar** [comment]
> it looks like the PR for this was merged. should this issue be closed?
> 
> PR ref: #3902

@aemperador this PR does not include the tools we need
`controller-gen`, `kustomize` and `envtest`

**Comment by aemperador** [comment]
ok @SteveMattar thanks for the update. I can take this on

**Comment by aemperador** [comment]
I've created a PR for adding kustomize first as a base image that includes the operator-sdk and kustomize: https://github.com/operator-framework/operator-sdk/pull/4130

controller-gen is not included in this one

**Comment by SteveMattar** [comment]
@aemperador Thanks for your work! Is there any reason why `controller-gen` is not part of this [PR](https://github.com/operator-framework/operator-sdk/pull/4130)?

**Comment by estroz** [comment]
Packaging all binaries into one image is complicated by multiple plugins and versions. From #4428:

[There are t]hree ways to tackle this:
1. Make an image for each plugin version with the appropriate tool version.
	- `quay.io/operator-framework/operator-sdk-go-v2:v1.3.0` containing all go/v2 tools
2. Download multiple versions of tool binaries into the same image, with each binary name containing its version, ex. `kustomize-3-5-4`.
	- `quay.io/operator-framework/operator-sdk-go:v1.3.0` containing all tools for go/v2 and go/v3 with versioned binary names
3. Make an image for dependency tool and version supported.
	- `quay.io/operator-framework/kustomize:v3.5.4`, `quay.io/operator-framework/kustomize:v3.8.7`

I personally prefer (3) because it scales the best, produces the smallest images, and is plugin-agnostic. The major problem with the first two is that the kustomize version (and controller-gen's for Go operators) is dependent on plugin version (and type, even though a divergence hasn't happened yet), while a given operator-sdk version supports multiple plugins. We'd have to maintain a build matrix of `operator-sdk version x plugin type x plugin version`, for which tagging would not scale as well (see examples) and we'd have to rebuid these images each time a new operator-sdk version was released. Additionally we'd only ever have to publish a new tool image once, if the default version of some plugin changed.

**Comment by estroz** [comment]
Moving this to the backlog to await further discussion, as no one has responded to ^.
