### ISSUE TITLE
Helm operator to respond to Namespace resources.

### ISSUE THREAD

**Issue by davidnortonjr-sps** [operator-framework/operator-sdk#4046]
#### Describe the problem you need a feature to resolve.

I'd like to be able to apply a Helm chart in response to a Namespace resource, using labels or annotations on the Namespace resource. I think it is fairly common to want to have operators do things in response to off-the-shelf Helm resources, and Namespace is one of those.

#### Describe the solution you'd like.

A few potential features might be needed:

1. Helm operator would need to be able to handle cluster-scoped resources ([currently can only handle namespaced resources](https://github.com/operator-framework/operator-sdk/issues/1666)) 
2. It seems that Helm Operator can only operate on CRDs -- due to the fact that it needs to [set a HelmAppStatus](https://github.com/operator-framework/operator-sdk/blob/master/internal/helm/release/manager.go#L67) on the resource
3. Would need a way to pass labels and annotations into the values of the Helm chart, since we can't add a `spec` to Namespace.

/language helm

**Comment by camilamacedo86** [comment]
Hi @davidnortonjr-sps, 

Thank you for raise this RFE. Could you please describe further what do you mean with `I'd like to be able to apply a Helm chart in response to a Namespace resource`? Are you looking for the scenario where the operator will watch a specific namespace and then when it is created/edit/update/delete the Helm chart will be applied? 

Regards your comment `Helm operator would need to be able to handle cluster-scoped resources (currently can only handle namespaced resources)`, I'd like to share that the Operators project has new layout since 1.0+ and they are cluster scope by default.  

In this way, I'd like to recommend you migrate your project to the new layout (1.0+). See; https://sdk.operatorframework.io/docs/building-operators/helm/migration/. Note that the version 0.19.x can receive only bug fixes and the previous versions are no longer supported.

**Comment by camilamacedo86** [comment]
Also, would like to raise an EP in https://github.com/operator-framework/enhancements where you would detail more how it would work?

**Comment by asmacdo** [comment]
Lets have more discussion here before anyone starts an enhancement proposal.

**Comment by camilamacedo86** [comment]
Hi @davidnortonjr-sps, 

It is open for a while without a response in the raised questions made https://github.com/operator-framework/operator-sdk/issues/4046#issuecomment-710147046 for we have a better understanding of the RFE wish by you here as your scenario. 

In this way, shows that you might figure out that is no longer required and then would be fine close this one. However, if you see that it is something that we could address then, could you please ping us to re-open this or raise a new issue by providing the. further details. Also, maybe add the steps to reproduce the issue/scenario that you are trying to solve with the current behaviour and then, with its outcome after this RFE could be very helpful as well. I'd like to indeed recommend you add the use cases scenarios as well such as `"I am as a Helm operator-based developer, I'd like to ... so that I could to do ..."`. It would be very helpful for we have a better understanding of your scenario. May the steps to reproduce it

Really thank you for your collab with btw.
