### ISSUE TITLE
Create channel in Kubernetes slack: operator-sdk-users

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#4065]

**Comment by camilamacedo86** [comment]
Have we not the #kubernetes-operators for that? What is the motivation to add a new channel?

**Comment by joelanford** [comment]
I was the one that originally floated the idea. We've been getting questions from users in the `operator-sdk-dev` channel since that is the only channel that exists with `operator-sdk` in the name.

After the initial influx of questions, I did add a channel topic:

> Discussion for contributors of github.com/operator-framework/operator-sdk
>
> For discussion about _using_ operator-sdk, see the #kubernetes-operators channel.

I don't recall seeing any user questions since, so maybe we hold off on this to see how well the channel topic works to redirect users?

**Comment by asmacdo** [comment]
We are not going to create the channel for now, the consensus is that #kubernetes-operators on kubernetes slack is the place where users should ask operator-sdk questions.

However, if this doesn't work for everyone, feel free to comment and reopen.
