### ISSUE TITLE
Operator reconcile behaviour and best-practices

### ISSUE THREAD

**Issue by zonnie** [operator-framework/operator-sdk#4077]
## Type of question

Best practices
General operator-related help

#### What did you do?

I have an operator that is linked to a CRD that is responsible for multiple applications under-the-hood (via `Deployments`).
I want to be able to deploy and upgrade only that resource, let's name it `MgmtApp`, and that the underling applications will be created/updated accordingly.

**My question is:**
What is the pattern to follow for this type of CRD ?
- Loop over desired applications and create/update in the same reconcile loop ?
- Loop over desired application and create/update and then re-queue and handle next application in the next reconcile ?
- How do I detect deletion vs deployment just not created yet ?
- How can I implement a rollback that will propagate down to the deployments ?

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

GKE

`$ operator-sdk version`

`operator-sdk version: "v1.0.1", commit: "4169b318b578156ed56530f373d328276d040a1b", kubernetes version: "v1.18.2", go version: "go1.15.2 darwin/amd64", GOOS: "darwin", GOARCH: "amd64"`

`$ go version` (if language is Go)

`go version go1.13.15 darwin/amd64`

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.1504", GitCommit:"fb367de18820fe57bac5d97ad60b7a2cef8765e9", GitTreeState:"clean", BuildDate:"2020-09-09T01:00:23Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by camilamacedo86** [comment]
The recommendation would be that the reconcile solution ought to be idempotent which means that it will be looking for the state in the cluster in order to have the desired state at the end. Regards to manage many operators as the dependency between then, the recommendation would be using [OLM](https://github.com/operator-framework/operator-lifecycle-manager) for that.  

An operator project is designed to have resources where each type of resource(CR/CRD) has its own controller and you can indeed manage any resource in any controller since the resources impl in your operator project works in exactly the same way that the API resources as "corev1.Service" for example.

See that when a CR/CRD is created/defined means a new resource/class(representation) with these attributes. So, if we use the same class to define all the different sorts of resources, we may be hurting concepts such as encapsulation, single responsibility principle and almost for sure cohesion that may cause unexpected sides effects such difficulty to read, maintain/improve and extend, to mention a few. 

PS. See the changes proposed in https://github.com/operator-framework/operator-sdk/pull/4021, which might help you better get its idea.  

**Regards your questions**

Note that we have not a context about your business rules, however: 

> I have an operator that is linked to a CRD that is responsible for multiple applications under-the-hood (via Deployments).
> I want to be able to deploy and upgrade only that resource, let's name it MgmtApp, and that the underling applications will be created/updated accordingly.

You might be able to have an approach where each CRDs represents an APP instead or indeed an operator for each APP whcih would be managed by [OLM](https://github.com/operator-framework/operator-lifecycle-manager). 

> Loop over desired applications and create/update in the same reconcile loop ?
> Loop over desired application and create/update and then re-queue and handle next application in the next reconcile ?

The reconcile function is responsible for synchronizing the resources and their specifications according to the business logic implemented on them. In this way, it works like a loop, and it does not stop until all conditionals match its implementation. The following is pseudo-code with an example that clarifies it.

```go
reconcile App {
 
   // Check if a Deployment for the app exists, if not create one
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   } 
    
   // Check if a Service for the app exists, if not create one 
   // If has an error, then go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{}, err 
   }  
 
   // Looking for Database CR/CRD 
   // Check the Database Deployments Replicas size
   // If deployment.replicas size != cr.size, then update it
   // Then, go to the beginning of the reconcile
   if err != nil {
       return reconcile.Result{Requeue: true}, nil
   }  
   ...
    
   // If it is at the end of the loop, then:
   // All was done successfully and the reconcile can stop  
   return reconcile.Result{}, nil
 
}
```

The following are a few possible return options to restart the Reconcile:

- With the error:
```go
return ctrl.Result{}, err
```

- Without an error:
```go
return ctrl.Result{Requeue: true}, nil
```

- Therefore, to stop the Reconcile, use:
```go
return ctrl.Result{}, nil
```

- Reconcile again after X time:
```go
return ctrl.Result{RequeueAfter: nextRun.Sub(r.Now())}, nil
```

**Note:** For more details, check the Reconcile and its [Reconcile godoc](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile).

> How do I detect deletion vs deployment just not created yet?
> How can I implement a rollback that will propagate down to the deployments?

When we request a delete operation of an object then, the K8S api flags it by setting the attribute DeletionTimestamp of tits object/recourse (instance.ObjectMeta.DeletionTimestamp). To manage actions that should be done before the resource/object be deleted you can use  Finalizers. See: https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#handle-cleanup-on-deletion.

However, to manage many operators where each operator is reasonable for one solution you can use [OLM Dependency Resolution](https://github.com/operator-framework/operator-lifecycle-manager#dependency-resolution)

Shows that your questions are answered. So, I am closing this one. However, please feel free to ping us if you need and/or raise new issues. I'd like to kindly ask for you try to deal with one topic/closed question/problem if possible per issue for we are able to better assist you. Also, since the issues can indeed help others as well it might be helpful to others to find question/answers too.
