### ISSUE TITLE
Refactor internal/generate generators into an interface to be more easily testable

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#4082]
Currently the coupling between the cmd layer and the generators is messy and hard to test. Refactor the generators to be implementations of an interface that can be faked out with [counterfeiter](https://github.com/maxbrunsfeld/counterfeiter) and unit tests can then be written in the cmd layer. This is a sub-part of #3246.

Current open PR is #3747

**Comment by estroz** [comment]
There's a big generator refactor coming that fixes #3998, which I'd like to see get in first because
1. It fixes a UX problem that a lot of users are having right now
1. Will likely make this refactor easier since it removes a concrete type parameter from generators.

Therefore I'm bumping this to v1.3
