### ISSUE TITLE
Make CI jobs run inside Github actions

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#4110]
Per the discussion from #3712, we would like to investigate the possibility of running our CI jobs themselves inside Github actions. 

Couple of known caveats:
1. Github actions can't be dependent on other Github actions.
2. Github actions don't support all the architectures we build for, so our tests will have to be decoupled from deploys (building and pushing images to quay). This might be a good thing for performance reasons

**Comment by joelanford** [comment]
Another detail:

Right now `master` branch builds and tag pushes do the same set of CI tests that PRs do. Then, if and only if the tests pass, the deploy stage runs.

If we move tests into GitHub Actions, we lose that coupling and conditional logic. There was some discussion in a community meeting that we could perhaps remove the CI tests from `master` and tag builds due to the fact that we know commits that make it into `master` have already been tested during the CI run for the originating PR.

**Comment by estroz** [comment]
Closed by #4253
