### ISSUE TITLE
Make bundle wipes out changes to scorecard config

### ISSUE THREAD

**Issue by psav** [operator-framework/operator-sdk#4119]
#### What did you do?

Running `make bundle` wipes out any changes that have been made to the scorecard config in `bundle/tests/scorecard/config.yaml`

#### What did you expect to see?

`make bundle` should not wipe out the changes to scorecard config

#### What did you see instead? Under which circumstances?

`make bundle` wiped out the config

#### Environment

**Operator type:**

**Kubernetes cluster type:**

Openshift CRC

`$ operator-sdk version`
1.0.1

`$ go version` (if language is Go)

1.13

`$ kubectl version`

Using `oc`

**Comment by joelanford** [comment]
@psav This is the expected behavior. The `./bundle` directory is idempotently re-generated every time you run `make bundle` from other source files. To persist scorecard config changes, edit the kustomize files in `./config/scorecard/`.

If this doesn't solve your problem, let us know and we can re-open.

**Comment by joelanford** [comment]
This will be clarified in docs changes based in #4108
