### ISSUE TITLE
Issue while upgrading operator on k8s 1.14 to 1.16

### ISSUE THREAD

**Issue by chowmean** [operator-framework/operator-sdk#4135]
While upgrading kubernetes we had an operator YAML with `deployment apps/v1 api`. When we checked in `1.14` the deployment api is converted to `extensions/v1beta1`. Now when we run the same yaml in `1.16` the api used in `apps/v1`.
Is there any conversion that Kubernetes does for backward compatibility in `1.14` for `apps/v1` but since `apps/v1` is available from `1.10` why it does so?

Kubernetes: Amazon EKS 1.14 -> Amazon EKS 1.16

**Comment by camilamacedo86** [comment]
Hi @chowmean, 

We need further information to help you with it as for example if your operator is go, ansible or helm?   I'd kindly ask for you fill the issue template. 

Also, note that versions lower than 0.19 is no longer supported and it is recommended migrate the projects to use 1.0+. See: https://sdk.operatorframework.io/docs/building-operators/golang/project_migration_guide/

In the latest versions, you will find the `--crd-version` flag to specify what version of k8s api should be made the scaffold. and if you have a Go based operator by default it will use de deprecated version v1betav1 and for 1.0+ version see that you need to update the Makefile with : 

```
# Produce CRDs that work back to Kubernetes 1.11 (no version conversion)
CRD_OPTIONS ?= "crd:crdVersions=v1"  
```

Could you please let us know if the info provided is enough and we can close this one? Otherwise, could you please fill the first comment of this issue with the bug template and provide all info.

**Comment by kensipe** [comment]
@chowmean your question seems centered around core types... There pretty disciplined rules around versions of core types and their support.  Older versions continue to be supported through a deprecation period until they are removed.  It would be good to understand the deprecation policy: https://kubernetes.io/docs/reference/using-api/deprecation-policy/

Once a version of a kind is removed, there aren't any conversation tools for backward compatibility that I'm aware of... it is expect that users and operators bump to a supported version.  I'm not sure about the specifics of your example.. but awareness of the group,version, kind and their support is often needed for operator developers.  This question seems more directed to the `api-machinery` which leads me to close it.   We are happy to help / provide more guidance if needed.  Please re-open if you have an issue / question specific to operator sdk.    It is also worth getting more details in https://k8s.slack.com/

**Comment by chowmean** [comment]
Thanks, the issue was based on kubectl preferring local cluster api order while displaying information. https://github.com/kubernetes/kubernetes/issues/95974
