### ISSUE TITLE
Can you change operator language between releases?

### ISSUE THREAD

**Issue by dubauski** [operator-framework/operator-sdk#4145]
#### What did you do?

We are planning to release v1.0 of our Ansible based operator. We anticipate the need to implement complex logic in v2.0 of the operator and for that reason it will be necessary to switch to Go based operator implementation. 

What kind of problems should we expect with such switch in technologies? If it is not supported or potentially a messy transition would you recommend refactoring Ansible based operator into Go based **before** v1.0 has been released?

Thank you for your help

#### Environment

**Operator type:**  Ansible

**Kubernetes cluster type:** "OpenShift"

**Comment by camilamacedo86** [comment]
Hi @dubauski,

The Ansible based-operators behind the scene is Go operators. The Ansible operators allow users write their projects with a language that they are more familiarized with it, however, it has some limitations which are not faced with the Golang projects since it is possible to develop and customize your solutions as you wish.   

> What kind of problems should we expect with such switch in technologies? 

IMO it is not about-face problems, however, how big and complex is your project more complex can be to port to Golang operator since you need to change the ansible tasks by code implementations. 

> If it is not supported or potentially a messy transition would you recommend refactoring Ansible based operator into Go based before v1.0 has been released?

IMO we are not in a place to answer that, it is really something up your business role, strategy, design and code implementation. However, how much more complex your Ansible operator gets more complexity will be added to port it for another language. 

@estroz @asmacdo @jmrodri would you like to share your thoughts?

**Comment by dubauski** [comment]
Thank you for quick reply, @camilamacedo86.

**Comment by asmacdo** [comment]
This is a tough question to answer for Ansible-based operators generally. If you have the time, I think the community could really benefit from a blog post or similar as you go through this process.

**Comment by joelanford** [comment]
It should be totally possible to migrate from Ansible to Go without any user-facing changes. You can re-implement all of your Ansible logic in Go without changing your CRD, and transparently upgrade users from the Ansible-based operator to a Go-based operator, and it wouldn't even _have_ to be a new major version number.

The one thing to look out for is CRD validations. Ansible-based operators don't currently have a mechanism for auto-generating validations, but Go operators do. I would advise manually configuring CRD validations in your Ansible-based operator such that when you switch to Go the validations won't change.
