### ISSUE TITLE
User Guide: clarification around reconciliation loop

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#417]
There is a comment in the [User Guide](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#define-the-handler):

    Note: The provided handler implementation is only meant to demonstrate the use of the SDK APIs and is not representative of the best practices of a reconciliation loop.

It would be helpful to have additional information about the best practices.  Those who do not contribute to core kubernetes will know these best practices.

**Comment by joelanford** [comment]
@benjaminapetersen I know we've asked in a couple of other issues, but with all of the changes we've made over the past few months, do you think this issue is still applicable? The line you mention from the User Guide is no longer present, and we think the examples have been updated to be a bit more representative of best practices.

If you get a chance to read over the user guide again and find anything that isn't clear or needs improvement about how to author a reconciliation loop, definitely feel free to reopen this issue.

**Comment by benjaminapetersen** [comment]
@joelanford sounds good, thanks!
