### ISSUE TITLE
OLM Integration Package Manifests Quickstart

### ISSUE THREAD

**Issue by wtrocki** [operator-framework/operator-sdk#4277]
`make packagemanifests` is is not in the kubebuilder template anymore.

See > https://sdk.operatorframework.io/docs/olm-integration/quickstart-package-manifests/

**Comment by camilamacedo86** [comment]
If users would like to use `make packagemanifests` than it needs to be added manually. See the first text of the link added:

<img width="963" alt="Screen Shot 2020-12-04 at 13 43 10" src="https://user-images.githubusercontent.com/7708031/101170686-b6ec3780-3636-11eb-9ba8-605fba318c52.png">

It is properly described. If you click on `and have added the packagemanifests target to your Makefile as described [here](https://sdk.operatorframework.io/docs/olm-integration/generation/#package-manifests-format).` you will find the code for you copy and past. 

The reason for `make packagemanifests` has not been scaffolding by default is because the tool provided the bundle feature. Besides OLM still supporting the packagemanifests (CSV) it is recommended to users move forward to use the bundle instead of it. See: https://sdk.operatorframework.io/docs/olm-integration/quickstart-bundle/

In this way, shows fine we close this one as sorted out. However, please feel free to ping us if you think that it should be re-opened.
