### ISSUE TITLE
Helm operator: how to not update all deployed CR instances at once

### ISSUE THREAD

**Issue by pre** [operator-framework/operator-sdk#4357]
## Type of question

General operator-related help

## Question

When the Chart of a Helm operator is updated, deploying the helm-operator with this updated Chart will trigger an update to all of the CR instances at once. 

This causes problems such as:
- changing a default image tag of a Deployment causes all pods to be recreated _at once_. This creates a burden to the image server when there are many pods and all of them are pulling new images at the same time. Eg. delaying the update to a period of 1..60 minutes would balance the amount of image pulls significantly. 

- if the updated Helm chart causes a problem, the problem is deployed to all CR instances at once. Having some kind of control to the rollout would be helpful. Some issues are only found after the first actual deployment in the production environment. 

Questions:

1) Is it possible to throttle the Helm operator's reconciliation loop? So that existing resources are not updated immediately after the new version of the helm-operator starts? Note that the new helm-operator pod has empty internal caches since it was just started. 

2) Is it possible to use the Helm chart's version number to control when a CR instance is to be updated? Even though the helm-operator has the Chart version, I have not found a way to connect the deployed CR instance with the Chart version managed by the operator. 

3) Have I understood correctly, that a helm-operator can only manage a single version of a Helm chart at a time? 

I know that the CRD has a version, but many changes to the Chart are configuration changes such as "update default image tag" or "change parameter X value to Y". These do not warrant a new CRD version, however, the Helm Chart version is updated for each change.

It would be useful if a single instance of an Helm Operator was aware of different versions of a Chart.

#### Environment

**Operator type:**

/language helm

**Comment by joelanford** [comment]
Simultaneous updates of CRs when the operator is updated is the expected behavior. There was some discussion of this issue on the SDK community call today, and the consensus was that introducing delays and non-determinism would likely cause more problems that it would solve.

For example one possible scenario would be that a CR is updated after the operator is deployed, but before the operator's delay has elapsed. Should the operator go ahead and handle that change early?

Another possible scenario is a CR that is created after the old operator version has stopped but before the new operator has started. Should it be exempt from the delay? When an operator starts up, controller-runtime populates a cache of the existing CRs by emitting `CREATE` events for each existing CR, so there would not be a straightforward way to distinguish old from new.

> changing a default image tag of a Deployment causes all pods to be recreated at once. This creates a burden to the image server when there are many pods and all of them are pulling new images at the same time. Eg. delaying the update to a period of 1..60 minutes would balance the amount of image pulls significantly.

If I understand kubelet correctly, it will pull the image once per node, even if there are multiple pods referencing that image running on that node. So the maximum bound of image pulls is the number of schedulable nodes in your cluster.

> if the updated Helm chart causes a problem, the problem is deployed to all CR instances at once. Having some kind of control to the rollout would be helpful. Some issues are only found after the first actual deployment in the production environment.

I believe there are facilities in Helm itself that can solve this problem. The Helm operator will automatically rollback a failed release, so if you can build health checks into your deployments, it should be possible to convince Helm that your deployment has failed, which would cause a rollback to occur.

> Is it possible to use the Helm chart's version number to control when a CR instance is to be updated? Even though the helm-operator has the Chart version, I have not found a way to connect the deployed CR instance with the Chart version managed by the operator.

I'm not sure I'm completely following this, but I think the answer is no. In general, the fact that the CR's release is upgraded is really just an implementation detail of the Helm operator. Users expect that a CR fully describes the desired state of their resource and operators are expected to achieve that state as quickly as possible.

> Have I understood correctly, that a helm-operator can only manage a single version of a Helm chart at a time?

Yes, that's correct.

> I know that the CRD has a version, but many changes to the Chart are configuration changes such as "update default image tag" or "change parameter X value to Y". These do not warrant a new CRD version, however, the Helm Chart version is updated for each change.

Agreed. The CRD version should only change when the syntax or semantics of the CR changes.

> It would be useful if a single instance of an Helm Operator was aware of different versions of a Chart.

There are definitely pros and cons (and lots of debate) about whether operators should support multiple operand versions simultaneously. For the Helm operator, such a model would require some breaking changes to the current CRD and watches file design. I think we should carve this part of the discussion out into a separate issue since it seems to stand on its own.
