### ISSUE TITLE
requeue object key

### ISSUE THREAD

**Issue by dragon9783** [operator-framework/operator-sdk#436]
After 15 times handle  error, operator-sdk will forget object key, 
```
// handleErr checks if an error happened and makes sure we will retry later.
func (i *informer) handleErr(err error, key interface{}) {
	if err == nil {
		// Forget about the #AddRateLimited history of the key on every successful synchronization.
		// This ensures that future processing of updates for this key is not delayed because of
		// an outdated error history.
		i.queue.Forget(key)
		return
	}

	// This controller retries maxRetries times if something goes wrong. After that, it stops trying.
	if i.queue.NumRequeues(key) < maxRetries {
		logrus.Errorf("error syncing key (%v): %v", key, err)

		// Re-enqueue the key rate limited. Based on the rate limiter on the
		// queue and the re-enqueue history, the key will be processed later again.
		i.queue.AddRateLimited(key)
		return
	}

	i.queue.Forget(key)
	// Report that, even after several retries, we could not successfully process this key
	logrus.Warnf("Dropping key (%v) out of the queue: %v", key, err)
}
```

when i handle delete object, how can i requeue object key?  for example, i create memcache resource, deploy tree pod, when i delete memcache resource, i want to delete pod first, then delete memcache resource .

**Comment by CSdread** [comment]
for this you would set the deletion and gc process and use finalizers on your pods:

https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/
https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods

**Comment by dragon9783** [comment]
thanks for reply soon, and i have another question, when i resize memcache resource, scale pod from 3 to 5, the kubernetes cluster have insufficient resources, after 15 times to try update memcache, will operator-sdk requeue memcache object key? or forget object key? resize failed?

**Comment by hasbro17** [comment]
@dragon9783 Sorry for the late response.
Configuring the number of requeues is not possible at the moment. And the SDK will only requeue the object key upon an error.
And as you pointed out right now it's hard coded to forget the key after 15 failed reconciles.

We can introduce a temporary fix for configuring the number of retries via the [watch options](https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/watch-opt.go#L17-L21).

But since we're close to finishing the controller-runtime refactor #382  we should be able to support explicit requeuing and not have the object key forgotten after 15 retries.
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/reconcile/reconcile.go#L80-L83

**Comment by estroz** [comment]
@dragon9783 now that we're done refactoring to use controller-runtime's `Reconciler` interface, object keys will not be forgotten and can be configured to be requeued. Use our [migration docs](https://github.com/operator-framework/operator-sdk/blob/master/doc/migration/v0.1.0-migration-guide.md) to update your project structure if you haven't done so already to SDK `v0.1.0+`, which has these changes.
