### ISSUE TITLE
docs: Quickstart for Go-based Operators docs do not mention "make kustomize"

### ISSUE THREAD

**Issue by bentito** [operator-framework/operator-sdk#4362]
Actually, I realized that the problem with the docs isn't platform dependent (see https://github.com/operator-framework/operator-sdk/issues/4361). The docs never call for the user of the docs to issue `make kustomize` step, and it's not called from any other make steps, so by the time the user calls `kustomzie` for the delete step, it will fail.

Doc link is here:

https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/

Suggest: adding a `make kustomize` step to the quickstart doc.

**Comment by camilamacedo86** [comment]
HI @bentito,

> The docs never call for the user of the docs to issue make kustomize step
 
The docs never call it because ALL targets that require kustomize already calls the kustomize target which will install it if the same not be installed already. 

Then, I still not thinking that we should add it in the quickstart. The users will copy and paste the quickstart instruction, I do not think that it has any instruction that would fail because of it. However, I might be missing something. So, what instruction described in the quickstart fails for you because of it?

**Comment by bentito** [comment]
None now. The docs showing publicly are not current. The current docs no longer use kustomize for delete. I closed the PR with suggested change because of that.

**Comment by camilamacedo86** [comment]
Hi @bentito, 

So, what would be the motivation for `adding a make kustomize step to the quickstart doc.`? Sorry, but it still not clear for me. What is the target that you are using which requires kustomize and is not installing it? OR what is the command/step that you did use sdk or its helpers that did not work because of that?

**Comment by bentito** [comment]
There is none any more. The version being rendered for the docs was out of
date.
Brett Tofel

**Comment by camilamacedo86** [comment]
Really thank you for let me know. I am closing this one so. Please, feel free to open new issues with your questions, suggestions and concern.
