### ISSUE TITLE
Method to identify k8s distribution the operator is running on -> apply different manifests in that case

### ISSUE THREAD

**Issue by jomeier** [operator-framework/operator-sdk#4366]
Hi,

is there any method that can determine out of the box on which k8s distribution an operator is running on in the SDK?

In the case of OpenShift / OKD sometimes it is necessary to apply additional k8s manifests that are specific to this distribution as for example SecurityContextConstraints (as in the Rook Operator).

It would be great if I could have a simple switch/case somewhere in the operator's controller that can apply additional manifests to the cluster or not.

That would it make much easier to write PRs for Vanilla k8s Operators getting them ready for OpenShift/OKD operators. Currently often enough this requires forks of operators or lots of manual fiddling.

```
if( k8sDistribution == "OpenShift_OKD" ) {
  applyManifests(SCCs)
}
```

Greetings,

Josef

**Comment by camilamacedo86** [comment]
Hi @jomeier, 

Could you please let us know why you need to identify what is the vendor? I mean, why do you need to know the vendor? Because if is for example to use some schema that has one vendor and not in another the best approach would check if the schema is or not in the cluster instead. See: [Why not couple an Operator’s logic to a specific Kubernetes platform?](https://developers.redhat.com/blog/2020/01/22/why-not-couple-an-operators-logic-to-a-specific-kubernetes-platform/)

However, in the SDK for test purpose, we check if the type of the cluster to load the images to run the tests. So, if you are looking for that with this purpose we can see how it is done [here](https://github.com/operator-framework/operator-sdk/blob/master/test/e2e-go/e2e_go_suite_test.go#L61) where we use the command-line tool (kubectl) to get the config via `kubectl config current-context`

**Comment by jomeier** [comment]
@camilamacedo86 
Thanks for your answer. There are lots of operators e.g. the rook operator that need do make special preparations in an OpenShift/OKD cluster compared to a vanilla k8s cluster.

My idea is to have some utility function in the SDK that determines the type of cluster. So if programmers like to implement specialities for some of the cluster types, they wouldn't have to implement this logic over and over again.

Because the reality is that there are often differences. And for me an operator is of less value if the user must find out the specialities on its own or apply stuff manually to the cluster to get the operator working as intendet.

**Comment by joelanford** [comment]
> Because the reality is that there are often differences. And for me an operator is of less value if the user must find out the specialities on its own or apply stuff manually to the cluster to get the operator working as intendet.

I totally agree with you on this. To the extent possible, it should be on the operator to discover its environment and handle it automatically.

I think what Camila is suggesting is that OpenShift/OKD is effectively Kubernetes with some extra extensions present by default, right?

So the stance of the SDK is generally to use the discovery API to determine the available extensions that you care about, and then have your operator make decisions based on that.

So for example, if you're trying to decide whether to use a Route vs an Ingress, its better to check if the Route API exists rather than to check if the cluster "is" OpenShift. If you use this discovery approach, you end up with a more resilient operator that can work in ANY cluster that meets your operator's prerequisites.

I don't think we want to start encoding vendor-specific cluster detection logic into the upstream vendor-agnostic SDK project unless there's a general upstream supported way for all kubernetes distributions to indicate their name, version, etc. As far as I know the closest thing to this is the [ServerVersionInterface](https://github.com/kubernetes/client-go/blob/9761a13537eb881bb91c13819ba223eda84ac0af/discovery/discovery_client.go#L118-L121).

**Comment by jomeier** [comment]
Thanks to you both for your feedback. I understand what you mean and think that this are valid points.

I also found something that could fix the problem with additional SecurityContextConstraints that are required for some operators on OpenShift/OKD:

The ClusterServiceVersion manifest contains a section where we can define permissions that are translated into RoleBindings, ClusterRolebinding and also ... SCCs bindings :-)

For instance:
```
  install:
    spec:
      clusterPermissions:
      - rules:
        - verbs:
          - use
          apiGroups:
          - security.openshift.io
          resources:
          - securitycontextconstraints
          resourceNames:
          - anyuid
          ...          
````

**Comment by joelanford** [comment]
That's a great question. My guess would be that OLM tries to blindly apply that role, and it would fail. If that's true, you would need different CSVs for different platform targets.

**Comment by estroz** [comment]
Regardless of whether this library will be implemented, it should be added to https://github.com/operator-framework/operator-lib/. @jomeier if the above suggestions to solve your problem don't, or if you think there's some scaffolding that can be done to do so, feel free to reopen this in operator-lib.
