### ISSUE TITLE
Need inputs on evolving an api with required fields between two versions.

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#4367]
Below is the scenario we are trying to accomplish with operators using operator sdk.

V1 of operator controller:
Has required fields in the api: field1, field2

V2 of operator controller:
Has required field in the api: field2, field3 (Note : field1 is deleted in this version).

Now user has installed V1 version of operator. And old CR and Controllers are running fine.
Now comes the concern, where in user needs to upgrade to V2 of the software.

case1: If upgrade CR to V2 first, old controller will react to the new CR update and fails since field1 is missing.
case2: If upgrade controller to V2 first, new controller will react to the old CR existence and fails since new field3 is missing.

How can we overcome issues like this across different api versions and evolution in case of operators. ?

**Comment by kaushiksrinivas** [comment]
@camilamacedo86 Any inputs on this would be helpful.

**Comment by camilamacedo86** [comment]
Hi @kaushiksrinivas, 

So, I understand that you have the scenario: 

- An operator project with a release A where it's using an API version == v1.
- Then, you want to do a new release A+1 where it will provide a new version of API ==v2. The new API version will have new fields. 

Then, I'd recommend you create a new API for the new version and its controller which means that GroupKindVersion1 will have a controller which will responsible for synchronizing the state of its resource on the cluster when  GroupKindVersion2 will have another controller responsible for the same. Also,  I'd like to suggest you check [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/).
 
Please, let me know if it answers your question and if we can close this one.

**Comment by kaushiksrinivas** [comment]
Hi @camilamacedo86 
below is my example scenario,
Release A : Use GroupKindVersion1 and its controller to deploy a pod running application 'A'.
Release A+1: Use the same api version GroupKindVersion1 with modifications (i.e for ex: delete of a field and addition of a new field together) and enhanced controller to deploy the same but an enhanced version of application 'A'.

We need the pod running application A to get upgraded when we upgrade the operator controller and update the CR.
But not run two different api versioned controllers and their corresponding CustomResources which indirectly means running two different pods instead of one (new and old api ones). 
Our intention is to reconcile the same old pod and do an upgrade from release A to release A+1.

**Comment by camilamacedo86** [comment]
Hi @kaushiksrinivas, 

>  Use the same api version GroupKindVersion1 with modifications (i.e for ex: delete of a field and addition of a new field together) and enhanced controller to deploy the same but an enhanced version of application 'A'.

If you add or remove a field/attr/spec of an API/CRD then you would need to have another version of the same group and kind. It is no longer the same. You cannot change the spec definitions and says that it is the same because it is not true. You might find a way to change the controller logic to make it works, however, I'd not recommend you follow up this approach.

So, if you want that your project is able to deal with the both Kind/Group with diff versions you need to have 2 controllers. I mean, a controller for each API. 

> Our intention is to reconcile the same old pod and do an upgrade from release A to release A+1.

So, if you want that your project is able to automatically upgrade the api versions you will need to implement it such as the controller of the old version will read all CRs with the previous version and will create a new CR for each one whcih will have the new required attrs/values. Then, the new controller for the new API will reconcile it. You can indeed use finilizers to ensure the operations before remove the old ones. 

If you check the k8s doc [Versions in CustomResourceDefinitions](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/) you will find all detailed information and concepts over CRD versions which might help you understand better it.

**Comment by camilamacedo86** [comment]
HI @kaushiksrinivas, 

I think we can close this one. All info required shows shared already. However, please feel free to ping us to re-open if you need or raise new issues.
