### ISSUE TITLE
namespace not found for current environment 

### ISSUE THREAD

**Issue by ccnankai** [operator-framework/operator-sdk#4369]
#### What did you do?

I ran the following steps in the terminal：

operator-sdk new project 
operator-sdk add api --api-version=xxx.com/v1  --kind=yyy
Add the corresponding fields in the *_types.go file

kuctl apply -f  deploy/crds/*_crd.yaml
export WATCH_NAMESPACE=default
go run cmd/manager/main.go

#### What did you expect to see?
No error

#### What did you see instead? Under which circumstances?

namespace not found for current environment，I have exported environment variables WATCH_NAMESPACE，but it still shows errors.
![image](https://user-images.githubusercontent.com/33537489/103905461-99c8ee00-5139-11eb-8ed4-913f11324da8.png)

#### Environment

**Operator type:**

language go

**Kubernetes cluster type:**

`$ operator-sdk version`

v0.13.0   commit:"1af9c95bb5....."  go version: "go1.13.3 linux/amd64"

`$ go version` (if language is Go)

go1.15.5 linux/amd64

`$ kubectl version`

v1.19.2

#### Possible Solution

Caused by different versions of go language?

**Comment by camilamacedo86** [comment]
Hi @ccnankai, 

Version 0.13 is too old and is no longer supported. I'd like to recommend you upgrade your projects to the latest version. Note that for 1.0+ the layout changes. So, I'd like to recommend you follow up the guidance to update your project until the latest 0.19 version at least. And then, migrate your project to the latest layout. Following the steps: 

- Follow up all steps in the migration guide from 0.13 to 0.14 then, 0.14 to 0.15 until 0.18 to 0.19. It is required because it will ensure that you fixed ALL breaking changes that you might face indeed because of the deps upgrade such as controller-runtime. ([here](https://sdk.operatorframework.io/docs/upgrading-sdk-version/version-upgrade-guide/) you will find the steps from until 0.17x then check [0.18.x](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v0.18.0/) and [0.19.x](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v0.19.0/))
- Now, I'd recommend you upgrade the project to the latest layout. See: [Migrating Projects to 1.0.0+](https://sdk.operatorframework.io/docs/building-operators/golang/migration/). The steps are mainly you recreated a new project with the tool and move the code of your operator to the new layout.
