### ISSUE TITLE
Operator crashes on invalid cr.yaml

### ISSUE THREAD

**Issue by mcgG** [operator-framework/operator-sdk#437]
Operator itself will keep crashing if an invalid cr.yaml is applied, according to the [code](https://github.com/operator-framework/operator-sdk/blob/master/pkg/util/k8sutil/k8sutil.go#L92), the `Marshal` step will cause `panic` to crash the operator. 

So why using `panic` here?  It will be better if we can get some `error`s instead of the `panic`, so that we can implement our own logic to delete the invalid `crd` as operator's failover revert

**Comment by hasbro17** [comment]
@mcgG Thanks for pointing that out. You're right it should just return an error instead of a panic and crashing the operator. That panic was only meant to be a placeholder initially.

So what we can do is just ignore an invalid CR (or an object that we can't deserialize into a runtime object) and have the operator log and ignore it until it gets removed from the queue in the informer sync.
https://github.com/operator-framework/operator-sdk/blob/master/pkg/sdk/informer-sync.go#L77

We can't really pass it on to the handler since we can't get a runtime object at that point. And besides the operator really shouldn't delete a CR just because it's invalid. That should be done by the user who created it and controls the CR lifecycle.

**Comment by mcgG** [comment]
@AlexNPavel，thanks for the quick move!
