### ISSUE TITLE
import (cachev1alpha1 "github.com/example/memcached-operator/api/v1alpha1") in memcached_controller.go for Memcached-operator not working

### ISSUE THREAD

**Issue by Jitesh817** [operator-framework/operator-sdk#4371]
## Type of question

 
General operator-related help

#### What did you do?
Following the golang based operator tutorial [https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/](here). Followed it step by step. After making all the code changes went on to build the operator using following command :
`$ make install`

#### What did you expect to see?
for build to complete without any errors

#### What did you see instead? Under which circumstances?

`controllers/memcached_controller.go:35:2: cannot find module providing package github.com/example/memcached-operator/api/v1alpha1`

#### Environment
Ubuntu

**Operator type:**

language go 

**Kubernetes cluster type:** minikube (though never reached this stage)

`$ operator-sdk version`
`operator-sdk version: "v1.3.0", commit: "1abf57985b43bf6a59dcd18147b3c574fa57d3f6", kubernetes version: "1.19.4", go version: "go1.15.5", GOOS: "linux", GOARCH: "amd64"`

`$ go version` (if language is Go)
`go version go1.15.6 linux/amd64`

`$ kubectl version`
`Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}`

#### Additional context

I was able to build and run the operator one time locally. Tried after about an hour or so and got the specified error. After getting this error, checked the github repo specified but got 404. I am fairly new to kube and operators, so any help would be appreciated.

**Comment by varshaprasad96** [comment]
Hi @Jitesh817 
The Golang import paths are relative to your $GOPATH. Can you please check if your project is inside `github.com/example/memcached-operator` ? If you followed the tutorial, I suspect it should be in `example-inc/memcached-operator`, since the initial part of the tutorial directs to create project inside `example-inc`. The import statement should basically reflect the location of `v1alpha1` package locally. Changing `example` to `example-inc` (the folder in which the project is present) should work.

**Comment by Jitesh817** [comment]
Hi @varshaprasad96 
Thank you... that did the trick. Apparently I copied the controller code from the specified repo which changed the package location.
