### ISSUE TITLE
Functionality of helm operator

### ISSUE THREAD

**Issue by chowmean** [operator-framework/operator-sdk#4384]
## Type of question
Clarification of functionality

## Question
As I understand when you convert a helm chart using helm operator, what operator does it convert the chart to resource yaml and put watchers on those resources. So when that particular k8s resource is down it can be started again. 

Can you please help here if I am correct or any doc which can help in better understanding of this.

**Comment by estroz** [comment]
Yes. The helm-operator will constantly reconcile the manifest such that the release contains the state seen in the cluster, outside of managing underlying k8s resources themselves (the cluster does this for you).

We don't have any docs that describe the nuances of helm-operator, although the above summary basically captures the essence of how it works. helm-operator also respects helm functionality. Perhaps docs should be added on this since the existing design doc does not discuss current functionality.

/kind documentation

**Comment by chowmean** [comment]
Awesome. Just one more query how can we add custom logic to it like executing commands in conatiners. Any ways to do that? Also I would like to take up the documentation of this  if possible

**Comment by estroz** [comment]
That's a great question. If helm can somehow execute a command in a container, then your operator should be able to as well.

That'd be awesome if you could help out with docs! I will note that a big refactor to `helm-operator` is [in the works](https://github.com/joelanford/helm-operator) so it might be worth waiting until that's done. It will be moved to a separate repo as well. The semantics won't change much/at all but the user-facing interface will be greatly expanded.
