### ISSUE TITLE
Helm-based operator ability to update

### ISSUE THREAD

**Issue by mrethers** [operator-framework/operator-sdk#4436]
## Feature Request

When working with helm charts as a foundation for the operator, I'm able to use the SDK init operation to scaffold the project, but I cannot update the generated resources after a change is made to the chart externally. For example, if I wanted to add a new resource that required additional permissions, and potentially new values, I would like to update the rbac/role.yaml accordingly as well as the sample CRD.

Seems like there's no way to keep an operator and associated charts in sync.

#### Describe the solution you'd like.

A update command similar to the init and create commands. Ideally this could be part of a CI/CD pipeline that detects changes to a helm chart source, and updates the operator as a result, without having to re-generate the operator from scratch. This is what I'm doing right now but it's overriding customizations that I make on top of the initial scaffolding. 

For example

operator-sdk create api --domain=com.myorg--group=mygroup --version=v1alpha1 --kind=MyKind --helm-chart=/path/to/helm/chart

then

operator-sdk update api --domain=com.myorg--group=mygroup --version=v1alpha1 --kind=MyKind --helm-chart=/path/to/helm/chart

/language helm

**Comment by estroz** [comment]
This would probably be useful, but is complicated since `operator-sdk update api` can't know what you've changed in between `create api` and `update api`. This could probably be solved (completely?) with marker comments in relevant files. I do think this should be a mode of `create api` rather than a separate subcommand, to keep the CLI simple, ex. `operator-sdk create api --update ...`.

/kind feature

**Comment by mrethers** [comment]
Totally agree with you.
