### ISSUE TITLE
Wrong "Conditions" import in Advanced Topics

### ISSUE THREAD

**Issue by ErezArbell** [operator-framework/operator-sdk#4463]
In this page: <https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/>
This section:
```
import (
    "github.com/operator-framework/operator-lib/status"
)

type MyAppStatus struct {
    // Conditions represent the latest available observations of an object's state
    Conditions status.Conditions `json:"conditions"`
}
```

should be replaced with
```
import (
    "github.com/operator-framework/operator-lib/conditions"
)

type MyAppStatus struct {
    // Condition represent the latest available observations of an object's state
    Conditions conditions.Condition `json:"condition"`
}
```

**Comment by varshaprasad96** [comment]
Hi @ErezArbell 
The `Advanced Topic` section has been replaced to use [upstream](https://master.sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions) conditions instead of the one from `operator-lib` since the operator-lib's `status` package is removed. `github.com/operator-framework/operator-lib/conditions` is a different library which helps communicating Operator Conditions to OLM (ref: https://olm.operatorframework.io/docs/advanced-tasks/communicating-operator-conditions-to-olm/#updating-your-operator-to-use-olm-operatorcondition)

**Comment by ErezArbell** [comment]
Thank you.
When will this master become latest?
Is there full example of operator using the new conditions?

**Comment by varshaprasad96** [comment]
Operator-SDK 1.4.0 is to be released soon (tentatively within this week). This [page](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions) has an updated example of using upstream conditions for adding `Conditions` to Objects's status.
In case, you are referring to Operator Conditions which are used by OLM, [here](https://olm.operatorframework.io/docs/advanced-tasks/communicating-operator-conditions-to-olm/#operatorconditions) is some documentation from OLM's end.

**Comment by estroz** [comment]
Because this is fixed in master, I'm closing this issue.
