### ISSUE TITLE
Best practice to build an operator that need another resources

### ISSUE THREAD

**Issue by cpanato** [operator-framework/operator-sdk#452]
Hello

What is the best practice to build an operator that needs, for example, mysql/postgres?

We need to install first those operators or we create a login inside the operator to install all requirements?

thanks!

**Comment by ironcladlou** [comment]
My understanding is the operator-sdk is scoped to a single operator. Any controller should tolerate the absence/unavailability of a dependent service (i.e. be level driven and generally resilient); how the dependent service is materialized in the cluster (i.e. via Ansible, Helm, or even some other higher order operator) is probably far outside the scope of concern of the SDK.

Perhaps I misunderstood the scenario?

**Comment by hasbro17** [comment]
Right, as @ironcladlou pointed an operator is meant to reconcile the state for every instance of your custom resource. If you need to spin up a dependent service that's not meant to be owned by your custom resource then your operator should not be setting that up.

For instance when we deployed the vault-operator via OLM it would require the presence of an etcd-operator in the same namespace so it could create an etcd cluster to back every vault cluster. So that requirement was specified to OLM to fulfill.
And in your case if you need a database or some other service, then you would need to set those up separately beforehand.
