### ISSUE TITLE
Error: cannot use resyncPeriod (type int) as type time.Duration in argument to sdk.Watch

### ISSUE THREAD

**Issue by jianzhangbjz** [operator-framework/operator-sdk#453]
I created a Operator named `jian-operator` via the `Operator-SDK`, seems it works well. But, I got below errors when I building its image:
```command
[root@localhost jian-operator]# operator-sdk build quay.io/example/jian-operator
Error: failed to build: (building jian-operator...
# github.com/example-inc/jian-operator/cmd/jian-operator
cmd/jian-operator/main.go:35:11: cannot use resyncPeriod (type int) as type time.Duration in argument to sdk.Watch
)
```

Below is the main.go file, seems like need to add a conversion between the `type int` and the `type time`.
```go
[root@localhost jian-operator]# cat cmd/jian-operator/main.go 
package main

import (
	"context"
	"runtime"

	stub "github.com/example-inc/jian-operator/pkg/stub"
	sdk "github.com/operator-framework/operator-sdk/pkg/sdk"
	k8sutil "github.com/operator-framework/operator-sdk/pkg/util/k8sutil"
	sdkVersion "github.com/operator-framework/operator-sdk/version"

	"github.com/sirupsen/logrus"
	_ "k8s.io/client-go/plugin/pkg/client/auth/gcp"
)

func printVersion() {
	logrus.Infof("Go Version: %s", runtime.Version())
	logrus.Infof("Go OS/Arch: %s/%s", runtime.GOOS, runtime.GOARCH)
	logrus.Infof("operator-sdk Version: %v", sdkVersion.Version)
}

func main() {
	printVersion()

	sdk.ExposeMetricsPort()

	resource := "jian.example.com/v1alpha1"
	kind := "App"
	namespace, err := k8sutil.GetWatchNamespace()
	if err != nil {
		logrus.Fatalf("Failed to get watch namespace: %v", err)
	}
	resyncPeriod := 5
	logrus.Infof("Watching %s, %s, %s, %d", resource, kind, namespace, resyncPeriod)
	sdk.Watch(resource, kind, namespace, resyncPeriod)
	sdk.Handle(stub.NewHandler())
	sdk.Run(context.TODO())
}
```
It's strange that it works before, you can see other operators I created before, but why failed now?
```command
[root@localhost example-inc]# ls
app-operator  jian-operator  memcached-operator
```

I also checked the [the template for cmd/main.go](https://github.com/operator-framework/operator-sdk/blob/master/pkg/generator/templates.go#L129) , seems this issue has been fixed. We can see the `time` package now. So, do I need to update my `operator-sdk` tool? If yes, how to update it?
```command
[root@localhost example-inc]# operator-sdk --version
operator-sdk version 0.0.5+git
```

**Comment by fanminshi** [comment]
@jianzhangbjz we decided to use `time.duration` instead of `int` for `sdk.Watch` via https://github.com/operator-framework/operator-sdk/pull/427.
That's why it breaks on you.

`do I need to update my operator-sdk tool?`
To be safe, you should update regardless. I don't know how old your tool is because `operator-sdk version 0.0.5+git` doesn't tell me which hash it is built upon. To update your tool, you should simply run `make install` in your operator-sdk dir e.g `.../github.com/operator-framework/operator-sdk`.

**Comment by hasbro17** [comment]
@jianzhangbjz That was breaking change made recently.
It's been a long time since we've cut a new tag for the SDK so `v0.0.5` is quite outdated.
For now can you please checkout and build the SDK from the master branch:
```sh
git checkout master
make install
```

And for an existing operator project you can update the `Gopkg.toml` file to update the dependency to the master branch:
```TOML
[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  # version = "=v0.0.5"
```
And then run `dep ensure` to update.

We're planning to do a release at the end of this week to not force users to use the master branch. At that point you can use the latest tag.

**Comment by jianzhangbjz** [comment]
@fanminshi @hasbro17 Thanks a lot! It works now! 
>  I don't know how old your tool is because operator-sdk version 0.0.5+git doesn't tell me which hash it is built upon.
```
[root@localhost operator-sdk]# operator-sdk --version
operator-sdk version 0.0.5+git
```
Do we have a issue to trace the version problem?

**Comment by AlexNPavel** [comment]
@jianzhangbjz v0.0.6 has been released. You can set your projects' Gopkg.toml files to use that version instead of the master branch.
