### ISSUE TITLE
Is it able to use k8s client in Validation webhook 

### ISSUE THREAD

**Issue by cuttingedge1109** [operator-framework/operator-sdk#4585]
## Feature Request

I have 2 types of CRs.
The first one is `school` CR and the other one is `classroom` CR.
In the `classroom` CR's spec, the `school` name is specified.
When the `classroom` is created and the `school` specified in the `classroom`'s spec is not existing, then I want to disallow the `classroom` creation.

I thought this can be done by using admission controller, validation webhook. But I realized that only *semantic validation* is able to be performed in that.

OR am I wrong?
Thank you.
/language go

**Comment by cuttingedge1109** [comment]
Hi team, how is it going?
I am willing to contribute if I can help at least.

**Comment by estroz** [comment]
Great question. What you describe isn't really something a webhook should be doing. As you allude to, validating webhooks are useful for determining whether an object meets a set of predefined criteria. They do not easily allow incorporation of cluster state into that assessment, nor should they, since this is the job of the controller.

A better solution is to permit creation of a `Classroom` in all cases, but mark the [condition](https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#manage-cr-status-conditions) of all `Classroom`s that do not have an associated `School` as `NoAssociatedSchool`, and handle marked `Classroom`s specially in the Reconciler. This scheme lets you later create a `School` for an un-associated `Classroom`.

/triage support
