### ISSUE TITLE
Custom resource and CRD terms are wrongly used across the whole operator-framework documentation

### ISSUE THREAD

**Issue by antaloala** [operator-framework/operator-sdk#4595]
### What is the URL of the document?
[https://operatorframework.io/operator-capabilities/](https://operatorframework.io/operator-capabilities/)
as an example of one of the doc pages where these terms are wrongly used (but the mistake appears in so many other pages)

### Which section(s) is the issue in?

TERMINOLOGY

### What needs fixing?

Custom Resource is defined as "an instance of the CustomResourceDefinition the Operator ships that represents the Operand or an Operation on an Operand (also known as primary resources)"

That is really a custom object (for a given custom resource referred from the custom object's "apiVersion" and "kind" mandatory fields). A custom resource is (as its name indicates) a non built-in (so custom) resource managed by the k8s API server in the same way we have statefulsets built-in resources, deployments built-in resources, etc.
Custom resources are created through CRDs and once "enabled" in the k8s API server it is possible to create custom objects for it.
Operator-framework documentation is wrongly using CRDs to name custom resources and using custom resources term to name custom objects !

CRD is defined as "an API of the Operator, providing the blueprint and validation rules for Custom Resources"
That is really the definition for custom resource.
customresourcedefinitions is a k8s built-in resource for which CRD objects can be created in order to define custom resources.
Confusing a CRD object with the custom resource created from it is a mistake.

IMHO part of the confusion comes from the fact that the k8s API is a RESTful interface and RESTful APIs use the "resource" term in a different way. As an example: a deployment object (for the k8s built-in "deployments" resource) in a given namespace gets an URL once a POST request to create it is accepted and so it gets a REST endpoint/resource URL ("resource" from a REST pov), but it is NOT a "resource" from a k8s API server point of view (it is an object for the built-on deployments resource)

#### Additional context

References providing the right definitions:

- [https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#custom-resources](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#custom-resources)
- [https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#customresourcedefinitions)

**Comment by dmesser** [comment]
Fair point. I guess we leaned towards the lingo commonly used so far in the better part of the k8s community. Any proposals for what a better term could be?

**Comment by estroz** [comment]
The k8s docs do say

>After the CustomResourceDefinition object has been created, you can create custom objects

so "custom object" would be a reasonable replacement. However, in the context of the k8s API (disregarding it's underlying RESTfulness, which is an implementation detail to most people), "custom resource" is used interchangeably with "custom object", if the latter is used at all. Therefore I have no strong opinion about changing it, and a weak opinion that custom resource can stay.

**Comment by camilamacedo86** [comment]
I am not sure if I agree that is the wrong TERMINOLOGY only because it is not exactly the same text/word used in the link provided without considering the context and audience. 

A CRD is yaml files (manifests) that represents an object for Kubenertes in the same way that the CR will become an instance of this object at the end. So, imo that clarifies a lot of the meaning for a developer who will write their APIs for their projects which is the goal of the docs and need understand how things work to develop the Go operator for example. Note that the dev needs to understand why/what goes in https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/api/v1alpha1/memcached_types.go for example. However, in the context of the doc liked it is considering and describing that from the point of view of the REST API where the nomenclature Endpoint shows more appropriate.

Example:
- Pod is a Kind of object
- And then we can create many instances of Pod   

Indeed see from the link provided, click on the `API objects` in `A resource is an endpoint in the Kubernetes API that stores a collection of API objects of a..`

> For example: in Kubernetes, a **Deployment is an object that can represent an application** running on your cluster.... > The Kubernetes system reads the Deployment spec and starts three **instances of your desired application** --updating the status to match your spec

**Conclusion**
IHMO I would not say that doc is wrong, however, I have no objection to change that and I just not think that it should be considered a priority.

**Comment by camilamacedo86** [comment]
I am not sure if I agree that is the wrong TERMINOLOGY only because it is not exactly the same text/word used in the link provided without considering the context and audience. 

A CRD is a yaml file (manifests) that represents an object for Kubenertes in the same way that the CR will become an instance of this object at the end. So, imo that clarifies a lot of the meaning for a developer who will write their APIs for their projects. The context of this doc is the same as what we can find in another k8s doc.

> For example: in Kubernetes, a **Deployment is an object that can represent an application** running on your cluster.... > The Kubernetes system reads the Deployment spec and starts three **instances of your desired application** --updating the status to match your spec

**Conclusion**

IHMO I would not say that doc is wrong and also I have not big opinion regards the nomenclature. So, I'd not say that is a priority and I's suggest check with the k8s folks what nomenclature is more appropriate for each context before start to change.

**Comment by camilamacedo86** [comment]
Conclusions/thoughts from the discussion with k8s folks:

> Manifests contain objects. In concrete terms, all Kubernetes objects are instances of a type. With custom resources, we can say the "custom objects" are an "instance of" the CustomResourceDefinition object since that is mostly interchangeable with the idea of the type. 

> The word resource or instance is usually used to refer to an instance of a CustomResourceDefinition, CR seems to be a bit misleading to me, given that you're not creating a custom resource, but just a resource of a CRD

Also, the team that shows be responsible for that is `API Machinery`. 

Another options are "custom objects" as @estroz point out or just also link the k8S doc instead if it is possible without losing the meaning/idea that we are trying to pass.

**Comment by antaloala** [comment]
K8s doc is written by many people in parallel and not being fully consistent (sometimes being really confusing).
The CRD related k8s documentation is the most exact one when treating these concepts...as that part of the documentation defines these concepts (so no room for making mistakes).

A CRD object maps 1:1 with the custom resource it defines, but that does not mean they are the same: one is a k8s API object for the CustomResourceDefinitions built-in resource (so cluster-scoped as 'its' governing resource is cluster-scoped) the other is a k8s API resource (i.e. specification governing all the API objects for the apiVersion and kind set but this k8s API resource) needed to be able to later create k8s API objects for that (custom)  resource ...  being namespaced or cluster-scoped depending on how the related custom resource is defined (using the .spec.scope field of the related CRD object).

My comment is really about using the right k8s defined terminology (more than ok from my side to first ask the right k8s groups to confirm my understanding on these terms) and from it to review the whole documentation; this would really help to properly understand and use all these concepts in the right way.

I quickly checked kubebuilder documentation and I found some mistakes on using CRD when really referring to custom resource (where treating the Webhook conversion); it is only some few places where to solve it (if so decided)

I do not see the need to use custom type as it would be a synonymous for custom resource (as I understand it) so why not then to use custom resource once being clear with all these terms?

**Comment by estroz** [comment]
I'd like to see full operator-framework buy-in on this before updating operator-sdk repo docs.

**Comment by camilamacedo86** [comment]
Regards the TERMINOLOGY section which I understand is the point raised here, I think would be better we just link k8s docs to avoid any misunderstanding instead of trying to explain that. 

 @antaloala, Would not it solve your concern and this issue? 

Then, regarding other places in the docs would be required to be raised and point out each place for we are able to check and understand better what are the concerns/motivations and etc.

**Comment by antaloala** [comment]
It Is fine with me to do like that, raising new issues on the exact doc  links ... plus the kubebuilder doc links.
