### ISSUE TITLE
Operators Scope

### ISSUE THREAD

**Issue by fjammes** [operator-framework/operator-sdk#4699]
In this chapter of the documentation: https://sdk.operatorframework.io/docs/building-operators/golang/operator-scope/#watching-resources-in-a-set-of-namespaces, following sentence is not clear to me:
_'IMPORTANT: Note that this is not intended to be used for excluding Namespaces, this is better done via a Predicate.'_

Could you please provide an example which excludes Namespaces from being managed by an operator?

**Comment by camilamacedo86** [comment]
Hi @fjammes. 

It means that it should not be used to watch all ns of a cluster less one or two. For these scenarios is recommended use Predicates. For example, see the reconcile: https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L61

You can use the  `req.NamespacedName` to check if is not A or B to allow it to continue. Otherwise, does nothing.

**Comment by fjammes** [comment]
This doesn't actually show how to use predicate but suggest to just add conditional checks in the Reconcile logic itself which doesn't answer how to skip the namespaces using predicates, as stated in the official documentation.

**Comment by estroz** [comment]
An example predicate for excluding namespaces is worth documenting.

/kind documentation

**Comment by camilamacedo86** [comment]
The predicates are only an if, at the beginner of the reconcile to check if is a request made from or not the ns A, B or C then does the action. We need to add this example in:

- https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/multi_namespace_cache.go#L41-L46

@theishshah could you please give a hand in this one? unfortunately, I am not finding time to work on that.
