### ISSUE TITLE
Handling references to upstream documentation in SDK

### ISSUE THREAD

**Issue by varshaprasad96** [operator-framework/operator-sdk#4831]
After the integration of Operator SDK with Kubebuilder, there are many areas in the SDK tool where upstream implementation is re-used. Since there is sufficient documentation already available upstream, we redirect users to refer upstream docs. Though it is not reasonable to rewrite or explain the already existing upstream concepts, it is an inconvenient experience for users to frequently context switch. Also sometimes the examples presented upstream are different than what we have currently in our docs which makes it difficult to follow.

A solution for this would be to first explain briefly about the concept and then direct users upstream. If required it would also be helpful to have examples, especially when the upstream docs use a different sample operator.
The extent to which we explain the concept in our docs and then direct upstream is completely dependent on its complexity. Some of the places which require more explanation in SDK doc's site are:

1. Scaffolding and creating webhooks: https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#manager 
2. How Operator-SDK handles metrics: https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#metrics
3. Handling migration from single group to multi group projects: https://sdk.operatorframework.io/docs/building-operators/golang/advanced-topics/#metrics
4. Examples for writing controller-tests using envtest framework: https://sdk.operatorframework.io/docs/building-operators/golang/migration/#migrate-your-tests

**Comment by aharbis** [comment]
I'd like to add a point of view to this as I'm currently working through Operator SDK migration from `v1.2.0` to `v1.3.2`. The Operator SDK's [1.3.0 migration guide](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.3.0/#upgrade-your-go-project-from-gokubebuilderiov2-to-gokubebuilderiov3) points to upstream kubebuilder [migration docs](https://master.book.kubebuilder.io/migration/v2vsv3.html), which [recommend](https://master.book.kubebuilder.io/migration/migration_guide_v2tov3.html) creating a new v3 project with `kubebuilder` and copying over controller/api code into the new project.

As an Operator SDK user, I'm confused because I scaffolded and manage my project with `operator-sdk`, yet the migration guidance essentially states that to migrate kubebuilder v2 -> v3 I should scaffold a new project with `kubebuilder` CLI instead.

Should I instead use `operator-sdk` at `v1.3.2` to scaffold my project?

I certainly understand the value in leaning on upstream documentation where possible in the Kubernetes ecosystem, but this is an example where I think it would be better for the Operator SDK documentation to provide more prescriptive guidance on migration.

**Comment by laxmikantbpandhare** [comment]
Created proper doc for `create admission webhook`. It got merged as part of PR #5019
