### ISSUE TITLE
Cannot find  metrics  module github.com/operator-framework/operator-sdk/pkg/metrics

### ISSUE THREAD

**Issue by kirubaap** [operator-framework/operator-sdk#4984]
#### What did you do?

Unable to find the metrics from operator-sdk

go: finding module for package github.com/operator-framework/operator-sdk/pkg/metrics
pkg\k8s\k8s_client.go:22:2: module github.com/operator-framework/operator-sdk@latest found (v1.8.0), but does not contain package github.com/operator-framework/operator-sdk/pkg/metrics

goversion : 1.15

#### What did you expect to see?

Need to download the  necessary module for  metrics package to create ServiceMonitor in k8s using go sdk lib.

#### Environment

**Operator type:**

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by kirubaap** [comment]
Can someone help be on this issue ?

If the metrics.CreateServiceMonitor() is deprecated , what is the new/alternative  method to be used for creating Service Monitor.

**Comment by pbrissaud** [comment]
I am facing the same issue. I found an answer in #4295

**Comment by camilamacedo86** [comment]
Hi @pbrissaud and @kirubaap, 

The operator-sdk/pkg does not live in sdk since its 1.0.0 release. All lib methods on it were moved to  https://github.com/operator-framework/operator-lib. Only the CLI features are in the sdk repo and bin now. 

I would like to recommend: 
- Migrate your project to the latest version. See: https://sdk.operatorframework.io/docs/building-operators/golang/migration/
- Then, use/import https://github.com/operator-framework/operator-lib instead if/when required.  

I am closing this one as sorted out. However, please feel free to ping us if you think that needs to be re-open.
