### ISSUE TITLE
The annotations added on the bundle/metadata/annotations.yaml are not ending up in the bundle.Dockerfile

### ISSUE THREAD

**Issue by camilamacedo86** [operator-framework/operator-sdk#4992]
#### What did you do?

- Add new annotations in bundle/metadata/annotations.yaml
- Run make a bundle

#### What did you expect to see?

- Then, the new annotations would need to end up in the bundle.Dockerfile but they have been lost

#### What did you see instead? Under which circumstances?

![Peek 2021-06-16 18-58](https://user-images.githubusercontent.com/7708031/122273294-2f329000-ced9-11eb-98dd-3ca7ca888107.gif)

#### Environment

SDK 1.5.0

#### Additional context

We need first to check its behaviour on master, it might is fixed already. 
Seems like the make bundle is re-scaffold the annotations when should not.

**Comment by camilamacedo86** [comment]
c/c @estroz do you have thoughts about here? Have we an annotation file in the config/ dir?

**Comment by msugakov** [comment]
Here's what I observed. I added annotations
```yaml
  com.redhat.openshift.versions: 'v4.6'
  com.redhat.delivery.operator.bundle: true
  com.redhat.delivery.backport: false
```
to `bundle/metadata/annotations.yaml`, ran `make bundle`, and these annotations were gone from `bundle/metadata/annotations.yaml`. They were also not added to `bundle.Dockerfile` contrary to what one might expect.

I tried both operator-sdk 1.5.2 and 1.8.0.

**Comment by estroz** [comment]
Changes made to `bundle/metadata/annotations.yaml` should be persisted, so this is a bug. However, `bundle.Dockerfile` needs to be kept in sync manually because not all annotations can/should be synced as Dockerfile `LABEL`s, just those in the bundle spec. @camilamacedo86 can you retitle this issue to reflect that?

/cc @varshaprasad96

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Thank you for give a look here? 

Could you please clarifies `However, bundle.Dockerfile needs to be kept in sync manually because not all annotations can/should be synced as Dockerfile LABELs,just those in the bundle spec.`? Can you please provide an example of annotations that should be synced or not?

**Comment by estroz** [comment]
[Bundle spec labels](https://github.com/operator-framework/operator-registry/blob/master/docs/design/operator-bundle.md#bundle-annotations) should be in sync as per the spec. All others are defined elsewhere and therefore `operator-sdk generate bundle` cannot know if they should be synced or not.

**Comment by camilamacedo86** [comment]
Hi @estroz, 

Why we sync just those ones and not all? Is it not more maintainable in the SDK pov sync all?
Also, this doc does not contain all valid annotations indeed for community-operators.

**Comment by camilamacedo86** [comment]
Hi @varshaprasad96, 

As agreed, following the issues created: 
- https://github.com/operator-framework/operator-sdk/issues/5002 
-

**Comment by fabianvf** [comment]
The changes to `bundle/metadata/annotations.yaml` aren't being persisted because `--overwrite` is set in the Makefile when running bundle generate. To make it so that annotations persist, specify `--overwrite=false` in the call to `operator-sdk generate bundle` in the Makefile, sample diff below: 

```
diff --git a/Makefile b/Makefile
index b683d1d..08a0dcc 100644
--- a/Makefile
+++ b/Makefile
@@ -149,7 +149,7 @@ endef
 bundle: manifests kustomize ## Generate bundle manifests and metadata, then validate generated files.
 	operator-sdk generate kustomize manifests -q
 	cd config/manager && $(KUSTOMIZE) edit set image controller=$(IMG)
-	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite --version $(VERSION) $(BUNDLE_METADATA_OPTS)
+	$(KUSTOMIZE) build config/manifests | operator-sdk generate bundle -q --overwrite=false --version $(VERSION) $(BUNDLE_METADATA_OPTS)
 	operator-sdk bundle validate ./bundle
```

With `--overwrite` set to true this behavior is expected though.

#5002 covers the feature request for syncing the annotations, so I'll close this one out for now.

**Comment by msugakov** [comment]
Hi,

It has been some time but still I'd like to understand how `--overwrite=false` is supposed to help.
`operator-sdk`-s own help tells about it this way:

```
      --overwrite                        Overwrite the bundle's metadata and Dockerfile if they exist (default true)
```

If I turn off `--overwrite`, metadata and Dockerfile will not be updated at all. That obviously keeps their content in place but prevents us from seeing new changes that `operator-sdk` might otherwise introduce.

Thanks,
Misha
