### ISSUE TITLE
Unable to generate deep copy methods for struct which has an interface field

### ISSUE THREAD

**Issue by goofiesnacks** [operator-framework/operator-sdk#5014]
#### What did you do?

I am trying to generate deep copy methods for the `Dog` struct that my CRD references (this is a simplified example).

```
package sample

type Animal interface {
    Breathe()
}

// +kubebuilder:object:generate=true
type Dog struct {
   SomeAnimal Animal
}
```

I ran `make generate` which executes this: `bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."`

#### What did you expect to see?

I expected deep copy methods to get generated successfully.

#### What did you see instead? Under which circumstances?

The `make generate` command threw this error: 
```
invalid field type: interface{Breathe()}
Error: not all generators ran successfully
```

It looks like it threw this error because the `Dog` struct has a field which is an interface.

#### Environment

**Operator type:**

/language go

**Kubernetes cluster type:**

vanilla

`$ operator-sdk version`

`operator-sdk version:"1.9.0", commit: "205e0a0c2df0715d133fbe2741db382c9c75a341", kubernetes version: "v1.20.2", go version: "go.16.5" GOOS: "darwin", GOARCH: "amd64"`

`$ go version` (if language is Go)

`go version go1.16.5 darwin/amd64`

`$ kubectl version`

`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}`

**Comment by kensipe** [comment]
Thanks for the feedback @goofiesnacks .   The Operator SDK leverages a number of dependent projects.   The featuring of generating is a function of those dependent projects and isn't maintained by us directly.  In order to have this feature it would be best to submit an issues against either:  
* [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder)  which is the generator you are referencing or
* [controller-tools](https://github.com/kubernetes-sigs/controller-tools) 

There does appear to be a [closed issue from the past around this topic](https://github.com/kubernetes-sigs/kubebuilder/issues/528)
