### ISSUE TITLE
Should sdk.Get() ever return a typed nil?

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#517]
Asking because I've had this happen, roughly:

```go
cr := &v1alpha1.MyCoolThing 
err := sdk.Get(cr)
// 
// little later, I wanted to check the deletion timestamp...
// 
metadata, err := meta.Accessor(cr)
if metadata.GetDeletionTimestamp() != nil {
// boom, panic and all kinds of excitement like
// Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
// and more
// panic: runtime error: invalid memory address or nil pointer dereference [recovered]
// panic: runtime error: invalid memory address or nil pointer dereference
// [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b380e9]
}
```
No matter how I checked `nil` or otherwise, I couldn't catch this thing, pretty confusing until I did some researching.  I resolved it by deciding I'm just not going to care about `DeletionTimestamp`, though I think best practices might be to pay attention to it if it was possible.

Thanks!

**Comment by ironcladlou** [comment]
Nil checks of interfaces in Go [are very idiosyncratic/unintuitive](https://golang.org/doc/faq#nil_error) (IMO); not sure if this has anything to do with the SDK (assuming the nil pointer dereference you're referring to is a nil value for `metadata`, which is an `Object` interface).

**Comment by shawn-hurley** [comment]
@benjaminapetersen I think in your code above you will want to check the error from this call:
`metadata, err := meta.Accessor(cr)` to figure out why the `metadata` is nil. I have a feeling it might be because of this line. The [code](https://github.com/kubernetes/apimachinery/blob/master/pkg/api/meta/meta.go#L102-L114) for `meta.Accessor` will return a nil for the interface, and it will return this error: `var errNotObject = fmt.Errorf("object does not implement the Object interfaces")`

I am going to close this, If I misunderstood the error please re-open.

**Comment by benjaminapetersen** [comment]
Works for me.  Agree with @ironcladlou, kinda find the `nil interface` in `go` to be a JavaScript level "wat?!" sort of quirk. 😐
