### ISSUE TITLE
Operator causing control plane outage

### ISSUE THREAD

**Issue by paterczm** [operator-framework/operator-sdk#5268]
Hello Operator-SDK community

I'm looking for operator-sdk experts to advise me on the following problem:

We can cause a control plane outage with our custom tenant-operator (golang, operator-sdk based) [3]. The tenant-operator sets up resources for application teams (or tenants) who want to use our OpenShift platform, i.e. creates namespaces, clusterresourcequotas, limits and various other secrets and configs. After I create multiple tenants at once (e.g. 60), the control plane stops responding after a few minutes and oftentimes doesn't recover at all. Before that happens, control plane gets progressively slower, at some point causing the tenant-operator to restart because it times out when trying to renew the lease. This makes things only worse, as the tenant-operator will reconcile all it's resources again after restart, further contributing to control plane load. I have experimented by disabling various components of the tenant-operator and learned that there is no single activity the operator does that causes the control plane to flip. It is the sum of benign operations.

I have reached out to OpenShift support for help. Here is the advise I got:

>  * Please check if you're closing those api call connections properly. 
>  * A solution would be to implement an intermediary queue between requests, it is the easiest way to throttle the requests as they hit the API server

However, I don't quite understand the recommendation, as the framework is managing connections and request queues under the hood. At least that's my understanding.

I also experimented with the API Priority and Fairness framework, but it does not seem to make any difference in the operator's ability to bring the control plane down.

Using operator-sdk v1.4.2 and OpenShift 4.8.

Thank you for any assistance or input you may have.

**Comment by paterczm** [comment]
Looking now at rate limiting explained in https://danielmangum.com/posts/controller-runtime-client-go-rate-limiting/

**Comment by camilamacedo86** [comment]
HI paterczm,

It seems a problem of performance. It shows that your Operator is reached the limits of resources and has been terminated.  So, I'd like to first all suggest you check the configuration in the config/manager/manager.yml to know your limits. Also, see https://kubernetes.io/docs/concepts/configuration/manage-resources-containers

By latest see that the consumption is proportional the logic implemented as the number of kinds, namespaced watched and etc. I'd recommend you also check the design of your solution and see if it cannot be optimized. 

However, it seems more a design/performance issue in the Operator itself instead of the libs used. But if you still needing help with could you provide more info such as:

- Are you monitor the memory/resources usage with metrics? Was the pod terminated when it reach out the limit?
- What are the limits adopted by your project?
- What is the language of your project? Is that go or ansible or helm?

**Comment by camilamacedo86** [comment]
Hi @paterczm, 

> This is not a problem with the operator pod itself, but a problem with the control plane, induced by that operator. The operator pod does not terminate because it runs out of resources.

So, the pods created by your Operator(manager) when reconciling the CRs have been terminating because of reaching the limit. Am I right? 

Then, you need to check its consumption to determine if the values are not good enough or if you ought to do some optimizations. You can use metrics for example.
 
You might need to indeed check the operand and see if this project could not be improved. 

PS.: I am not sure if I can follow up you here `Do not analyze load related issues in CodeReady Containers environment, as it is resource constrained and will exhibit issues even under small load.` It seems very specific to your implementation and context. 

However, that is very specific about the operand( images used by you ) and your project. It does not seem to have a relation with SDK or its default scaffolds. In this way, I am closing this one. However, feel free to raise new issues if you need.
