### ISSUE TITLE
Error: failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.17.1' is incompatible because 'requires 1.13 <= version < 1.17'. 

### ISSUE THREAD

**Issue by zeromsi** [operator-framework/operator-sdk#5284]
```
operator-sdk version
operator-sdk version: "v1.13.0-9-g2c1e81a3", commit: "2c1e81a32a36b6ae24156b72f152a3894d4d7b13", kubernetes version: "v1.21", go version: "go1.17.1", GOOS: "linux", GOARCH: "amd64
```
- Why it's saying me to downgrade my go version?
-  What is the workaround?
- I tried with ```--skip-go-version-check```
- But while creating resource following error shows
```
operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller 
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v1alpha1/memcached_types.go
controllers/memcached_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.6.1
go get: installing executables with 'go get' in module mode is deprecated.
        To adjust and download dependencies of the current module, use 'go get -d'.
        To install using requirements of the current module, use 'go install'.
        To install ignoring the current module, use 'go install' with a version,
        like 'go install example.com/cmd@latest'.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
go get: added github.com/fatih/color v1.12.0
go get: added github.com/go-logr/logr v0.4.0
go get: added github.com/gobuffalo/flect v0.2.3
go get: added github.com/gogo/protobuf v1.3.2
go get: added github.com/google/go-cmp v0.5.6
go get: added github.com/google/gofuzz v1.1.0
go get: added github.com/inconshreveable/mousetrap v1.0.0
go get: added github.com/json-iterator/go v1.1.10
go get: added github.com/mattn/go-colorable v0.1.8
go get: added github.com/mattn/go-isatty v0.0.12
go get: added github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go get: added github.com/modern-go/reflect2 v1.0.1
go get: added github.com/spf13/cobra v1.1.3
go get: added github.com/spf13/pflag v1.0.5
go get: added golang.org/x/mod v0.4.2
go get: added golang.org/x/net v0.0.0-20210428140749-89ef3d95e781
go get: added golang.org/x/sys v0.0.0-20210510120138-977fb7262007
go get: added golang.org/x/text v0.3.6
go get: added golang.org/x/tools v0.1.3
go get: added golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
go get: added gopkg.in/inf.v0 v0.9.1
go get: added gopkg.in/yaml.v2 v2.4.0
go get: added gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
go get: added k8s.io/api v0.21.2
go get: added k8s.io/apiextensions-apiserver v0.21.2
go get: added k8s.io/apimachinery v0.21.2
go get: added k8s.io/klog/v2 v2.8.0
go get: added k8s.io/utils v0.0.0-20201110183641-67b214c5f920
go get: added sigs.k8s.io/controller-tools v0.6.1
go get: added sigs.k8s.io/structured-merge-diff/v4 v4.1.0
go get: added sigs.k8s.io/yaml v1.2.0
/home/zeromsi/go-workplace/memcached-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/usr/local/go/src/net/cgo_linux.go:13:8: no such package located
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [Makefile:82: generate] Error 1
Error: failed to create API: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 2
Usage:
  operator-sdk create api [flags]

Examples:
  # Create a frigates API with Group: ship, Version: v1beta1 and Kind: Frigate
  operator-sdk create api --group ship --version v1beta1 --kind Frigate

  # Edit the API Scheme
  nano api/v1beta1/frigate_types.go

  # Edit the Controller
  nano controllers/frigate/frigate_controller.go

  # Edit the Controller Test
  nano controllers/frigate/frigate_controller_test.go

  # Install CRDs into the Kubernetes cluster using kubectl apply
  make install

  # Regenerate code and run against the Kubernetes cluster configured by ~/.kube/config
  make run


Flags:
      --controller           if set, generate the controller without prompting the user (default true)
      --crd-version string   version of CustomResourceDefinition to scaffold. Options: [v1, v1beta1] (default "v1")
      --force                attempt to create resource even if it already exists
      --group string         resource Group
  -h, --help                 help for api
      --kind string          resource Kind
      --make make generate   if true, run make generate after generating files (default true)
      --namespaced           resource is namespaced (default true)
      --plural string        resource irregular plural form
      --resource             if set, generate the resource without prompting the user (default true)
      --version string       resource Version

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution
      --verbose           Enable verbose logging

FATA[0002] failed to create API: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 2 

```

**Comment by camilamacedo86** [comment]
Hi @zeromsi, 

You need to use the go version which is supported for this SDK version. 
In this case, 1.17 is not supported at all.

**Comment by ryantking** [comment]
This version check is handled downstream in kubebuilder, upgrading that to 1.17 is being tracked [here](https://github.com/kubernetes-sigs/kubebuilder/issues/2421)

**Comment by dramasamy** [comment]
Could anyone let me know the working version of operator-sdk and golang? 

I tried diff combinations and end up with errors always,

1. /usr/local/go/src/net/cgo_linux.go:12:8: no such package located (with golang v17 and SDK v14)
2. failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.15' is incompatible because 'plugin requires go1.16 <= version < go2.0alpha1' (with golang v15 and SDK v14)

**Comment by camilamacedo86** [comment]
Hi @dramasamy, 

Th version supported and recommended is 1.16

**Comment by dramasamy** [comment]
> Hi @dramasamy,
> 
> Th version supported and recommended is 1.16

Thanks, I have tried to build a sample operator on a fresh Ubuntu VM with Golang 16 and OpSDK v14; however, I see the same issue. Could you help me to find the root cause (/usr/local/go/src/net/cgo_linux.go:12:8: no such package located)? 

FYI, this issue exists in kubebuilder too - Looks like I messed up golang installation? 

Here is the multipass cloud-init I use,
https://gist.githubusercontent.com/dramasamy/43eb9992e77d69f1c6e83c3fc5eb2d95/raw/ea3849ba16bafe76655b2af9f6148486c777d114/kind_cluster_cloud_init.yaml 

Commands:

`  16  mkdir memcached-operator
   17  cd memcached-operator
   18  operator-sdk init --domain example.com --repo github.com/dramasamy/memcached-operator
   19  operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller
`

Error:

`

ubuntu@kind:~/memcached-operator$ operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
api/v1alpha1/memcached_types.go
controllers/memcached_controller.go
Update dependencies:
$ go mod tidy
Running make:
$ make generate
go: creating new go.mod: module tmp
Downloading sigs.k8s.io/controller-tools/cmd/controller-gen@v0.7.0
go: downloading sigs.k8s.io/controller-tools v0.7.0
go: downloading github.com/spf13/cobra v1.2.1
go: downloading github.com/gobuffalo/flect v0.2.3
go: downloading k8s.io/apiextensions-apiserver v0.22.2
go: downloading k8s.io/apimachinery v0.22.2
go: downloading golang.org/x/tools v0.1.5
go: downloading github.com/fatih/color v1.12.0
go: downloading k8s.io/api v0.22.2
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading k8s.io/utils v0.0.0-20210819203725-bdf08cb9a70a
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/sys v0.0.0-20210616094352-59db8d763f22
go: downloading github.com/google/go-cmp v0.5.6
go: downloading golang.org/x/mod v0.4.2
go get: added sigs.k8s.io/controller-tools v0.7.0
/home/ubuntu/memcached-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/usr/local/go/src/net/cgo_linux.go:12:8: no such package located
Error: not all generators ran successfully
run `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -w` to see all available markers, or `controller-gen object:headerFile=hack/boilerplate.go.txt paths=./... -h` for usage
make: *** [Makefile:80: generate] Error 1
Error: failed to create API: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 2
Usage:
  operator-sdk create api [flags]

Examples:
  # Create a frigates API with Group: ship, Version: v1beta1 and Kind: Frigate
  operator-sdk create api --group ship --version v1beta1 --kind Frigate

  # Edit the API Scheme
  nano api/v1beta1/frigate_types.go

  # Edit the Controller
  nano controllers/frigate/frigate_controller.go

  # Edit the Controller Test
  nano controllers/frigate/frigate_controller_test.go

  # Generate the manifests
  make manifests

  # Install CRDs into the Kubernetes cluster using kubectl apply
  make install

  # Regenerate code and run against the Kubernetes cluster configured by ~/.kube/config
  make run


Flags:
      --controller           if set, generate the controller without prompting the user (default true)
      --force                attempt to create resource even if it already exists
      --group string         resource Group
  -h, --help                 help for api
      --kind string          resource Kind
      --make make generate   if true, run make generate after generating files (default true)
      --namespaced           resource is namespaced (default true)
      --plural string        resource irregular plural form
      --resource             if set, generate the resource without prompting the user (default true)
      --version string       resource Version

Global Flags:
      --plugins strings   plugin keys to be used for this subcommand execution
      --verbose           Enable verbose logging

FATA[0017] failed to create API: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 2

`

Go ENV:
`

ubuntu@kind:~/memcached-operator$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOENV="/home/ubuntu/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ubuntu/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16.10"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ubuntu/memcached-operator/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3282169785=/tmp/go-build -gno-record-gcc-switches"

`

**Comment by camilamacedo86** [comment]
@dramasamy, 

The root cause is that go 1.17 is not supported at all. You must use go 1.16 until the project starts to support go 1.17

**Comment by dramasamy** [comment]
> @dramasamy,
> 
> The root cause is that go 1.17 is not supported at all. You must use go 1.16 until the project starts to support go 1.17

Thanks for your time in looking into this - I just found that GCC was missing in my server. All looks finer after ' apt install gcc -y'

**Comment by andrianti** [comment]
I have tried to build a sample operator and follow the steps found at [](https://sdk.operatorframework.io/docs/building-operators/golang/quickstart/); however, I always end up with error saying failed to initialize project. 
Could anyone please help me to find the root cause (/usr/local/sbin/pkg/sumdb/sum.golang.org/latest: no such file or directory)?

### Environment
OS: Linux ubuntu
go version: 1.16
operator-sdk version: 1.15.0
i have installed GCC

### Commands:
mkdir memcached-operator
cd memcached-operator
operator-sdk init --domain example.com --repo github.com/example/memcached-operator


### Error: 
xxxx@mymachine:~/memcached-operator$ **operator-sdk init --domain example.com --repo github.com/example/memcached-operator**
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.10.0
go: sigs.k8s.io/controller-runtime@v0.10.0: verifying go.mod: sigs.k8s.io/controller-runtime@v0.10.0/go.mod: open **/usr/local/sbin/pkg/sumdb/sum.golang.org/latest: no such file or directory**
Error: **failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 1**
FATA[0000] failed to initialize project: unable to scaffold with "base.go.kubebuilder.io/v3": exit status 1

**Comment by dramasamy** [comment]
Try this cloud init that has all required things to start the kubebuilder project.

https://gist.githubusercontent.com/dramasamy/43eb9992e77d69f1c6e83c3fc5eb2d95/raw/4031db05f8f852991e781d5746401a0ea7b574b8/kind_cluster_cloud_init.yaml

https://ubuntu.com/blog/using-cloud-init-with-multipass

**Comment by empty2fill** [comment]
Here are a couple workarounds to try to resolve the issue:

Ensure gcc is installed
Set the CGO_ENABLED environment variable to 0 to disable [cgo](https://pkg.go.dev/cmd/cgo)

https://sdk.operatorframework.io/docs/faqs/#running-operator-sdk-create-api-results-in-an-error-with-usrlocalgosrcnetcgo_linuxgo138-no-such-package-located-in-the-error-message

**Comment by Stef16Robbe** [comment]
The docs seem to be misaligned on this currently. In the prerequisites section Go1.18  is mentioned: https://sdk.operatorframework.io/docs/building-operators/golang/installation/#additional-prerequisites

However the latest version (I installed https://github.com/operator-framework/operator-sdk/releases/tag/v1.26.1) of the operator-sdk requires Go1.16?

```
$ go version
go version go1.18.4 linux/amd64
```

```
$ operator-sdk init --domain example.com --repo github.com/example/memcached-operator memcached-operator
Error: failed to initialize project: unable to run pre-scaffold tasks of "base.go.kubebuilder.io/v3": go version 'go1.18.4' is incompatible because 'requires 1.13 <= version < 1.17'. You can skip this check using the --skip-go-version-check flag
```
