### ISSUE TITLE
Bundle validate and run bundle fail on "csv not found" in case of a yaml indentation syntax error in the csv

### ISSUE THREAD

**Issue by itroyano** [operator-framework/operator-sdk#5321]
## Bug Report

In case of a yaml indentation issue with the csv,  both `bundle validate` and `run bundle` display a similar error:

```
% operator-sdk bundle validate MYBUNDLE                
FATA[0005] unable to find a csv in bundle directory /var/folders/pt/whb_vsh96p1d2wyvny7lwnjc0000gn/T/bundle-4085122547/manifests
```

```
% operator-sdk run bundle  MYBUNDLE

FATA[0001] Failed to run bundle: load bundle: unable to find a csv in bundle directory bundle-465036948/manifests
```

The file itself is indeed present inside the bundle image (did a `docker save` and checked the layers).

Pasting the csv into https://operatorhub.io/preview shows the actual error -

`Error parsing YAML: bad indentation of a mapping entry at line 91, column 9: statusDescriptors: ^`

#### What did you expect to see?

```
% operator-sdk bundle validate MYBUNDLE
                
Error parsing CSV YAML: bad indentation of a mapping entry at line 91, column 9: statusDescriptors: ^
```

#### Environment

**Operator type:**

Helm Operator

/language helm

**Kubernetes cluster type:**

OpenShift

`$ operator-sdk version`

1.10.1

**Comment by camilamacedo86** [comment]
/remove-lifecycle stale

this one shows a valid one to be checked/improved. 
I think we could begin looking if the issue was not solved already. 

c/c @ryantking

**Comment by camilamacedo86** [comment]
Hi @itroyano, 

> Thanks for your reply @varshaprasad96.
> Is there a way to throw the actual unmarshalling error as a fail-fast?

we parse all manifests and if we succeed we know that we find the csv, see: https://github.com/operator-framework/api/blob/master/pkg/manifests/bundleloader.go#L150-L152 . Otherwise, it will fail in [LoadBundle](https://github.com/operator-framework/api/blob/37561c93045eee6044ae4748d3aea29fae5b09f8/pkg/manifests/bundleloader.go#L39). 

We would 

a)check when an error is faced if the content contains Kind: CSV. So that we could add its error to be returned

OR 

b)Just append in the default error message something like "it might occur because your CSV file has a syntax issue and cannot be parsable"

However, the change needs to be done in: ttps://github.com/operator-framework/api and not in SDK.
