### ISSUE TITLE
RFE: Multiple informers for single workqueue 

### ISSUE THREAD

**Issue by jsafrane** [operator-framework/operator-sdk#534]
I want to write an operator that not only watches CRD and creates stuff (say Deployment for example), but also watches "the stuff" it created and syncs it back to the CR, e.g. to update CR.Status, or fixes bad changes done to "the stuff".

Right now, I can have multiple `sdk.Informers`. But each of them runs its own workqueue. What I would like is to have only one workqueue, ensuring that a CR (or objects it created) is not processed several times in parallel. Sharing the same backoff for CR and all its objects would be beneficial too.

In addition, my operator is not really interested that a Deployment caused the event. It needs to get the CR that it needs to sync and sync will do the right thing - syncs Deployment into CR.Status and/or fix the Deployment if the Deployment was changed in a bad way.

So the SDK could get the reference to the CR from Deployment.OwnerReference, find the CR in its informer cache and put the CR into the workqueue. There should be a way how to add a custom method to find a CR for an object,  OwnerReference does not work for non-namespaced objects like ClusterRoleBindings. kubebuilkder's [`Watch`](https://book.kubebuilder.io/beyond_basics/controller_watches.html) is a great example how to do it right.  

As optimization, there should be a way how my operator could Get / List objects from the informers instead of the API server to speed things up.

**Comment by fanminshi** [comment]
HI @jsafrane we are switching to use controller runtime internally. So all the issues you are describing can be solved using the controller runtime apis. ref: https://github.com/operator-framework/operator-sdk/issues/382

**Comment by hasbro17** [comment]
@jsafrane Thanks for detailed feature requests.
We're addressing both of the issues you've described with the ongoing controller-runtime refactoring.
See #382 and the [refactor-branch](https://github.com/operator-framework/operator-sdk/tree/refactor/controller-runtime) for the ongoing work on that.
We're currently updating the user-guide to showcase the example of Watching a CR and Deployment to resync only on the CR for all events. #551  

The API for watching resources(and enqueuing reconcile requests) will be the exact same as Kubebuilder's since they use the controller-runtime as well.

Plus with the controller-runtime's [split client](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/split.go#L26-L33) users should be able to read(Get/List) objects from the informer cache as an optimization.

Since we're already tracking the feature requests for multiple informers(or enqueuing a primary resource for a secondary watch event) in #146 
and the Get/List from cache optimization in #258 I'm going to close this issue for now.

If there's a different feature not covered by issues linked above, feel free to open a new one.
