### ISSUE TITLE
Digests of operator-sdk releases change regularly. Could we keep the digests for released tags to be immutable?

### ISSUE THREAD

**Issue by tkrishtop** [operator-framework/operator-sdk#5341]
## Bug Report

In my team, we're working on the support of preflight in DCI, and the idea is to make it work both in connected and disconnected environments. 
Because of disconnected environments, we're asking preflight to refer to the release of scorecard-test by digest (SHA) and not by tag, [here is how this dependency looks like](https://github.com/redhat-openshift-ecosystem/openshift-preflight/pull/314/files).

Unfortunately, operator-sdk regularly changes the digests for already released tags.
For example, 5 hours ago the digest for v1.14.0 released on 27 October was changed from

```
quay.io/operator-framework/scorecard-test@sha256:66023c1e0f6021407811fb2b1d42aa16af6f41f2c791b2bdeb6ba696d000cf5d
```
 to 
```
quay.io/operator-framework/scorecard-test@sha256:sha256:ff3ce0785e706185260a8308c0f40bae950fdba03cbb302fd002dddf3129b189
``` 

This digest change broke the preflight release v1.0.3. This situation happens quite regularly, but it shouldn't happen - the release is supposed to be immutable.

If I got it right, that happened because of the release v1.13.1, which somehow updated all later tags as well (and v1.14.0 which we're using). Could you please fix the release process? 

#### What did you do?

I was using digest corresponding to the release tag v1.14.0
```
quay.io/operator-framework/scorecard-test@sha256:66023c1e0f6021407811fb2b1d42aa16af6f41f2c791b2bdeb6ba696d000cf5d
``` 
and it stopped working because it became replaced.

#### What did you expect to see?

The release is supposed to be immutable.

#### What did you see instead? Under which circumstances?

The release digest regularly changes.

#### Possible Solution

To fix the release process. Both digest (SHA) and tag should be immutable for the release.

**Comment by tkrishtop** [comment]
cc: @samira-barouti  @tonyskapunk

**Comment by tonyskapunk** [comment]
Adding the link to the history of images in quay where the change of tag is shown: https://quay.io/repository/operator-framework/scorecard-test?tab=history

We can see there that this is not limited to only the version `1.14`, other versions have been moved as well. Here I'm including specifically for `v1.14` and `v14.0`:

- `v1.14.0` was moved to SHA256 `ff3ce0785e70` from SHA256 `66023c1e0f60` (Fri, Nov 5, 2021 6:12 AM)
- `v1.14` was moved to SHA256 `ff3ce0785e70` from SHA256 `66023c1e0f60` (Fri, Nov 5, 2021 6:12 AM)

**Comment by jberkhahn** [comment]
To clarify, this is happening because of needed security updates for dependencies getting re-built into the base images, which we do automatically every day or so. If we were to make versions immutable, we would have to cut z-stream releases to push these security updates, which would also not solve your problem. 

The only (possible) solution we can think of would be to keep the current style of tags as floating tags that contain the newest SHA of the image, and then spin off immutable tags as we publish each new image. Does that sound like a tenable solution to you? It would drastically increase the number of images we're pushing to Quay, however.

**Comment by jchunkins** [comment]
Suggested format using semver semantics (see https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions):

```
<version core> "+" <build>
```

version example (where the build identifier is the docker image SHA):
```
v1.0.0+7df4e1f16bfd107acc76bc1e3a5910224b90b317aca697b6541c3e55c27bc2ee
```

**Comment by tonyskapunk** [comment]
@jberkhahn would it be possible to add an extra tag to "manual" releases rather than refreshed releases?
From a security stand point it's clear that re-tagging a release is a good thing, but for reproducibility it would be nice to identify when a manual release (say 1.14.0 or 1.14.1) is being made rather than a re-tag/release due to an underlying dependency, wdyt?

**Comment by asmacdo** [comment]
Its hard for us to tell if this is a widespread issue. As a workaround, you can build your own images or sync an image repository to keep them stable.

We've discussed this in the community meeting and we seem to have a consensus that it may not be general enough of a problem to justify the release difficulty. We are going to close for now, but we are open to more thoughts if anyone wants to reopen.
