### ISSUE TITLE
Helm operator: optionally specify the namespace for a Helm chart deployment 

### ISSUE THREAD

**Issue by mikeshng** [operator-framework/operator-sdk#5433]
#### Describe the problem you need a feature to resolve.

For Helm operator, the Helm chart is installed in the same namespace as the related Helm CR. If there are many different Helm apps in a cluster then the Helm CRs might be in many different namespaces. It will be nice if different Helm CRs can all live in a same namespace but the actual Helm chart deployment takes place in another namespace.
https://github.com/operator-framework/operator-sdk/blob/v1.15.0/internal/helm/release/manager_factory.go#L109
https://github.com/operator-framework/operator-sdk/blob/v1.15.0/internal/helm/release/manager.go#L167

#### Describe the solution you'd like.
I would like an optional way to adjust the namespace of the Helm chart deployment for a particular Helm operator CR. Similar to running the helm client install command with the --namespace flag. Maybe a second optional config is to create the namespace if it doesn't exist, similar to helm client param --create-namespace. 
Is using: https://sdk.operatorframework.io/docs/building-operators/helm/reference/advanced_features/annotations CR annotation a good way to configure this behaviour? Or it should be a watches yaml configuration?

I am willing to drive the implementation if this enhancement is a good idea. Thanks.

/language helm

**Comment by varshaprasad96** [comment]
@mikeshng This seems interesting, but I have a clarifying question. 
Helm operator creates a CR whose spec is basically the values from helm chart. Since CR has resources from the helm chart, why would we want the chart and CR in a separate namespace? If there is a modification in CR, under the hood reconciler kicks in acting on chart. In the example you mentioned, if there are multiple CRs (for each app), then shouldn't there be multiple Helm charts for each CR? (please correct me if I am getting it wrong here).
This would be similar to creating a single operator with multiple APIs and each API is being scaffolded with a helm chart.

**Comment by mikeshng** [comment]
Hi @varshaprasad96 thanks for the reply.

> If there are multiple CRs (for each app), then shouldn't there be multiple Helm charts for each CR? 

Yes, there are multiple helm charts for each CR. 

> why would we want the chart and CR in a separate namespace?

Because a user might have many helm operator CRs (each with their own helm charts and different namespaces), but want to keep track of all the CRs in a single namespace. For example:
CR-xx in namespace abc
CR-yy in namespace abc
CR-zz in namespace abc
but helm charts deployments in namespace xx, yy, zz respectively. This way the user can just look at abc namespace to see some high level status of all the deployments.

**Comment by mikeshng** [comment]
Clarified with customer that this is no longer needed. The Helm operator CR can live in the same namespace as the CR. The higher level delivery mechanism that was used to manages the Helm operator CRs will be enhanced. Closing for now, feel free to reopen. Thanks.
