### ISSUE TITLE
Can Ansible Operator manage resources other than those in k8s world

### ISSUE THREAD

**Issue by morningspace** [operator-framework/operator-sdk#5463]
## Type of question

Open question

#### What did you do?

I'd like to know if Ansible Operator supports the use case of resource management for non-k8s env. It appears the current design of Ansible Operator is aimed to handle k8s resources by leveraging k8s modules, so that we can use Ansible playbooks to manage k8s resources. If I have tuns of Ansible playbooks to handle VM resources, is there a way for operator to drive these playbooks in Kubernetes?

#### Environment

**Operator type:**

/language ansible

**Comment by morningspace** [comment]
Any ideas? @fabianvf

**Comment by asmacdo** [comment]
Yes, you can use ansible playbooks within your operator to manage external resources using arbitrary ansible collections, but we do not currently have a way of kicking off reconciles based on those external resources. @tima thoughs?

**Comment by tima** [comment]
Yes @asmacdo I do. First, you are correct. You can theoretically write Ansible automation to do any type of automation from an Ansible-enabled Operator. You'd need to add the collections and any library or binary dependencies to the container build for whatever external resources though. For instance, if you had a containerized application that uses a cloud database services like AWS RDS, you'd include the AWS collection and boto libraries. You could then write automation to have the Ansible-enabled operator create the database and tables when initialized and manage schema updates later. 

There are other things you'll need to consider before you start though. For instance, how will secrets/credentials be managed for access to these resources? What about logging, audit and reporting activity on these external resources? Perhaps these are not for concern for some, but they need to be considered before automating all the things from your cluster.

**Comment by morningspace** [comment]
Thanks @asmacdo and @tima for your comments that help me a lot to understand the design intension of Ansible operator and also prove some of my thoughts. Correct me if I'm wrong. I was reading the Ansible operator code in Operator SDK these days. I found that the operator actually drives the execution via Ansible Runner, which talks to the target cluster via a proxy. The proxy is used to intercept calls made to target cluster so that can inject owner reference and add watch to controller for any child resource created by Ansible role or playback. I assume these are all aimed to handle the reconciliation . However, for arbitrary Ansible collections, there is no easy way to enforce such reconciliation. It could do the one way automation initiated from a CR watched by the operator, but where there is drifting appeared in target env, there's no way to detect that by the operator.

And, for binary dependencies and credentials, these are all good questions that can not be easily addressed by Ansible operator for now.

Am I right?

**Comment by tima** [comment]
Operators, regardless of what they are written in, are for managing the full lifecycle of applications and services on a Kubernetes cluster in an automated fashion. Managing external resources and handling their drift is outside the scope and intention of operators. That said, Ansible itself was designed for automating these sorts of resources that reaching out to these the resources is pretty straight forward easy to do, but as you noted it is "one way" and initiated from the cluster (its not just the CR that can cause a reconciliation though but that is a minor point) because of the intent of Operators. Operators are possible because of the single standardized API K8s provides. External resources have no such mechanism. 

"Reconciliation" of external resources and dealing with environment drift is what the Ansible platform (independent of anything K8s) was designed for from the very beginning. If something on the outside of the cluster changes and needs to update something on the cluster, you can modify a CR or whatnot from within your Ansible workflow and let the operator do its thing on the cluster.

> And, for binary dependencies and credentials, these are all good questions that can not be easily addressed by Ansible operator for now.

Yes, you'd have to roll something yourself. The intention of Operators was not to manage external resources so they have not been optimized for those uses cases. When it comes to coordinating with external resources from a K8s cluster, my recommendation has been to have the operator work through the automation system in use for managing these traditional (off cluster) environments. You get the benefit of an existing tested RBAC, credential management, activity logging, etc for the cost of your automaton being distributed.

**Comment by morningspace** [comment]
Thanks @tima for your prompt reply! 

> "Reconciliation" of external resources and dealing with environment drift is what the Ansible platform (independent of anything K8s) was designed for from the very beginning.

Not sure if I understand it correctly. Are you referring to the `diff` mode? I raised this question while ago in Ansible community, and the suggestion from the community is the `diff` mode. However, the problem is that not all Ansible modules support this. So, it heavily depends on what modules people use. More details could be found at: https://github.com/ansible/ansible/issues/75248

> ... my recommendation has been to have the operator work through the automation system in use ...

I was not quite sure what the `work through` here means. IIRC, this is exactly what I was looking for originally in this GH issue, in which case, the automation system that we use is Ansible and there are many existing playbooks/roles that we would like to reuse when we move to k8s and the Operator model. Or, the word `operator` here you mean is not the Operator model, but instead the IT operation?

**Comment by asmacdo** [comment]
@morningspace did you get the help you needed? please feel free to reopen!

**Comment by morningspace** [comment]
@asmacdo thanks and yes, we ultimately created [this project](https://github.com/multicloudlab/crossplane-provider-ansible) to address my problems.
