### ISSUE TITLE
operator-sdk plugin docs

### ISSUE THREAD

**Issue by odra** [operator-framework/operator-sdk#5464]
## Type of question

* How to implement a specific feature

* Open question 

## Question

I would like to create an operator-sdk plugin to create python based operators.

I would like to know if there is some kind of documentation  to create an operator-sdk plugin  when running `operator-sdk init ...`, for example: `operator-sdk init --plugins myplugin.com/python`, `myplugin.com/python`being my custom operator plugin.

I see there are some plugin repositories in the operator-framework github org, such as https://github.com/operator-framework/java-operator-plugins, should I get inspiration from those or is there any kind of documentation on how to create one?

Thanks in advance.

**Comment by varshaprasad96** [comment]
@odra Thanks for creating this issue. We are definitely working on improving plugins. Here are some updates on this:
1. There is a small documentation on creating custom plugins in KB doc: https://book.kubebuilder.io/plugins/creating-plugins.html
2. Currently, if you are writing your own plugin, then to bundle it with SDK we would have to rebuild the SDK binary again to be able to execute the plugin code. In order to solve this limitation, the KB community is working on Phase 2 plugins (https://github.com/kubernetes-sigs/kubebuilder/issues/1378) which enable users to easily bring in their external plugin and integrate with SDK/KB. This is still in progress, but the feature should be out soon.

**Comment by odra** [comment]
Ha, so there is no way to attach an external plugin yet :-)

Thanks for sharing those links, I will keep a closer look at those but I think it wouldn't hurt to start working on the pyhton operator plugin.

Thanks!

**Comment by odra** [comment]
Closing the issue.
