### ISSUE TITLE
Static PV creation through Operator.

### ISSUE THREAD

**Issue by AnilKumarBandi27** [operator-framework/operator-sdk#5488]
On openshift, I have an operator which deploys a complex application.
The operator deploys 50 or more pods, each with multiple containers that communicate with one another. **The entire deployment makes use of static persistent volumes.** **There are 30 PV used by the application.**
So far, the volumes have been created manually outside of the operator. I was wondering if it is best practice to include the PV creation in operator roles.

Please let me know if there are any disadvantages or issues that may arise when we create the static pv as part of the operator. Also, I wanted to know if this is best practise for openshift operators.

**Comment by jberkhahn** [comment]
So, PVs can be tricky because they're limited by the resources available to the cluster - what kind of storage there is etc. This makes it difficult to figure this stuff out at runtime. You COULD make your operator provision these during runtime when an instance is created, but this would mean that the cluster your operator is running on would have to match the storage resources you're requesting exactly - and that sounds pretty difficult if you're making 30 PVs for each instance of your operator. If you can't make PVs exactly like you expect, your stuff could blow up.

In general, it's best practice to provision PVs ahead of time, or create a dynamic PV that will match the PVC's created by your operator.
