### ISSUE TITLE
Release ansible base image/binary

### ISSUE THREAD

**Issue by estroz** [operator-framework/operator-sdk#555]
This issue opens discussion of integrating the Ansible operators' release process into the SDK's, as brought up by @shawn-hurley in [this PR comment](https://github.com/operator-framework/operator-sdk/pull/531#discussion_r220566473).

**Comment by jwmatthews** [comment]
I'd like to see something like the below:
 - On each release of operator-sdk the Ansible Operator binary/base image is rebuilt, pushed and tagged with the version of the operator-sdk release.
 - A floating tag of :latest is reapplied to the Ansible Operator base image to track the latest version built
 - On each commit to master the Ansible Operator binary/base image is rebuilt, pushed and tagged with the label :canary 

We then would recommend most developers use :latest for the Ansible Operator base image which will track the latest operator-sdk release.  For those who want the bleeding edge...they use :canary to track master codebase.

Last point, I think we only need to be concerned with publishing the Ansible Operator base image which will include the Ansible Operator binary.  I don't think we need to make the Ansible Operator binary available as a separate download artifact in the release.

Thoughts?

**Comment by mhrivnak** [comment]
@jwmatthews I agree with all of that. My only caveat is that we should emphasize for those that use `latest` that since we are in a pre-1.0, pre-beta, maybe-even-still-pre-alpha development phase, there is a reasonable chance that behaviors will change on `latest` in ways that could be unexpected. So the normal vigilance of using pre-release software is recommended. I'd personally suggest:
* use latest while creating a new operator
* lock to a specific ansible-operator release when you release your operator for production use
* try upgrading to the latest base image regularly, with careful testing

**Comment by AlexNPavel** [comment]
@jwmatthews I like these suggestions. However, for now we'll only be able to do new images or binaries per release without canary images. The reason is that we currently only use travis to test and we build and sign releases manually. We are looking into using prow for testing and releasing images in the future sometime after we finish the controller-runtime migration, which would allow us to release canary images, but for now we're a bit limited there.

**Comment by AlexNPavel** [comment]
The issue with travis isn't signing, it's pushing. Looking through their documentation, to push container images, you need to provide a file in your repo with a username and password that can be used to push. This is a public repo, so we can't do that.

**Comment by shawn-hurley** [comment]
You can use env vars which for a robot account and then us them when you login into docker. 

We are doing this already in water-hope/ansible-operator.

**Comment by joelanford** [comment]
This work was completed with a few tweaks based on further discussions in the PR (#832). The tagging logic is:
* Push `:master` on every commit to master
* Push `:<tag>` on every newly tagged commit
* Push `:latest` on each newly tagged commit where the tag matches the semver format and is the highest semver release in the repo.
