### ISSUE TITLE
operator-sdk bundle validate should ignore missing examples for "internal" APIs

### ISSUE THREAD

**Issue by wallrj** [operator-framework/operator-sdk#5551]
In https://docs.okd.io/4.9/operators/operator_sdk/osdk-generating-csvs.html#osdk-hiding-internal-objects_osdk-generating-csvs
> It is common practice for Operators to use custom resource definitions (CRDs) internally to accomplish a task. These objects are not meant for users to manipulate and can be confusing to users of the Operator. For example, a database Operator might have a Replication CRD that is created whenever a user creates a Database object with replication: true.
> 
> As an Operator author, you can hide any CRDs in the user interface that are not meant for user manipulation by adding the operators.operatorframework.io/internal-objects annotation to the cluster service version (CSV) of your Operator.

So there is no reason to add examples (`alm-examples`) for these internal APIs.

`operator-sdk bundle validate` should only print a "missing example" warning for the APIs which are not listed in the `operators.operatorframework.io/internal-objects` annotation. 

Related to:  
 * https://github.com/k8s-operatorhub/operatorhub.io/issues/14

**Comment by jmrodri** [comment]
I will take this issue and get more information to find out what that validator does and propose some options here in this issue.

**Comment by jchunkins** [comment]
This should be the code path for this validation https://github.com/operator-framework/api/blob/master/pkg/validation/internal/csv.go#L78

**Comment by camilamacedo86** [comment]
If I am not wrong Scorecard also checks the alm-examples. However, no matter the check it raises a WARN and is not an ERROR.  

**In POV: If we decide to move forward with the suggestion over not raising warnings suggesting adding the alm-examples when the CRD is informed via the annotation `operators.operatorframework.io/internal-objects`:**

- The annotation is valid only for UI / console then, we need to check if it is or not OCP specific first
- We need to address it in Scorecard and Validators checks

Also, in the future, the idea is we have a CVSless bundle and these annotations ought to become properties with names that clarify better what component actually uses it. So, I'd also ask, how much real value do we bring by addressing this RFE? What problem do authors actually face because of the WARNING suggesting to use the alm-examples? How many operators are using `operators.operatorframework.io/internal-objects` and would take advantage of it?

**Comment by asmacdo** [comment]
This should be filed against api/
