### ISSUE TITLE
Regression - v1.19.0 reconciles continuously every minute

### ISSUE THREAD

**Issue by venkataramanam** [operator-framework/operator-sdk#5655]
#### What did you do?

The latest Ansible Operator v1.19.0 is reconciling continuously every minute. Did not see this behaviour with the last version v1.18.1. The watches.yaml we use is ...

```
---
- version: v1
  group: wos.cpd.ibm.com
  kind: WOService
  snakeCaseParameters: False
  playbook: reconcile.yaml
  watchDependentResources: False
```

We do not set the `reconcilePeriod` in the watches.yaml for the Ansible Operator that watches the custom resource of kind `WOService`

This looks like a regression. Even though the custom resource is not modified after last reconcile, the reconcile is getting triggered continuously with a gap of a minute post the last successful reconcile.

If this is the expected behaviour in latest version, please let us know what should we be doing to not reconcile.
I tried setting `reconcilePeriod: 0s`, but that does not seem to stop reconciliation.

#### What did you expect to see?

Given the above watches.yaml, it should not have reconciled every minute

#### What did you see instead? Under which circumstances?

Even though the custom resource is not modified after last reconcile, the reconcile is getting triggered continuously with a gap of a minute post the last successful reconcile.

#### Environment

**Operator type:**

/language ansible

**Kubernetes cluster type:**

OpenShift

v1.19.0

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by VenkatRamaraju** [comment]
Hi @venkataramanam,

This is because of the command-line flag ``reconcile-period`` has a [default](https://github.com/operator-framework/operator-sdk/blob/master/internal/ansible/flags/flag.go#L96-#L99) value of 1m. So, to avoid any interval-based reconciles, you can run the Ansible Operator like the following:
```
$ ansible-operator run local --reconcile-period 0s
```
No reconcile period must be specified in the `watches.yaml` file or the custom resource annotations either. By running the above command, no reconciles will take place unless an event comes into the cluster that requires a reconciliation.

Let me know if you have any further questions.

**Comment by venkataramanam** [comment]
@VenkatRamaraju Thanks for looking into this issue.
I will try the suggestion to set the reconcile period as command-line arg to ansible-operator

**Comment by venkataramanam** [comment]
@VenkatRamaraju Passing on the reconcile period to ansible-operator as commandline arg worked. Thank you.

```
ENTRYPOINT ["/tini", "--", "/usr/local/bin/ansible-operator", "run", \
    "--watches-file=./watches.yaml", \
    "--zap-log-level=error", \
    "--max-concurrent-reconciles=1", \
    "--ansible-verbosity=0", \
    "--reconcile-period=0s" \
    ]
``` 

Closing this.
