### ISSUE TITLE
Explain context of "group" when initializing a project

### ISSUE THREAD

**Issue by asmacdo** [operator-framework/operator-sdk#5738]
In the Go docs this is all they have:

```
# we'll use a domain of example.com
# so all API groups will be <group>.example.com 
```

Lets Add a link to API groups and maybe an example of what the author **should** set it to.

**Comment by camilamacedo86** [comment]
@asmacdo,

> # we'll use a domain of example.com
> # so all API groups will be <group>.example.com 

When we init a project we can inform the domain that will be used when/if we create APIs for the project,
This domain is tracked on the PROJECT file, see: https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/PROJECT#L1

Therefore, when we call the command to create an API ( create api [OPTIONS] ) we no longer need to inform the domain ( we indeed have no this option ) and all GKV will be created using that domain. 

We can indeed have diff groups, we just need to use the multi-group layout.  

Currently, the tool does not support users/authors informing other domains to create a new GVK but we have a request to do that which was tracked in the Kubebuilder, which was accepted in the triage in the community meetings: https://github.com/kubernetes-sigs/kubebuilder/issues/2394 (if someone would like to work on this that is totally fine, we just not prioritize it as the most important thing to get accomplished because we had not too much votes from the community or too much users looking to do the same )

c/c @jberkhahn
