### ISSUE TITLE
reconcilePeriod not working with ansible-operator

### ISSUE THREAD

**Issue by whitfiea** [operator-framework/operator-sdk#5780]
#### What did you do?

We upgraded from using ansible-operator 1.17 to 1.20 

#### What did you expect to see?

The operator to reconcile only when it first starts and when a dependent resource changes only.

#### What did you see instead? Under which circumstances?

The operator reconciles every minute regardless as to whether a resource changes or not.

#### Environment

**Operator type:**

 /language ansible

**Kubernetes cluster type:**

Openshift 4.8

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

#### Possible Solution

We found issue https://github.com/operator-framework/operator-sdk/issues/5655 that seems to imply the behaviour changed (or was fixed) but the comment here https://github.com/operator-framework/operator-sdk/issues/5655#issuecomment-1098192850 seems to also say that we should **not** set reconcilePeriod on the watches.yaml or as an CR annotation. This is confusing as the document says it can be set like that [here](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/ansible/development-tips.md#annotations-for-custom-resource) and [here](https://github.com/operator-framework/operator-sdk/blob/master/website/content/en/docs/building-operators/ansible/reference/watches.md) which is reflected in the online documentation https://sdk.operatorframework.io/docs/building-operators/ansible/development-tips/#annotations-for-custom-resource and https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/

So either the documentation is wrong or it is a code bug. The solution in issue https://github.com/operator-framework/operator-sdk/issues/5655 says to set this on the commandline. How does that work when using the ansible operator image in kubernets/openshift, do we override the [ENTRYPOINT](https://github.com/operator-framework/operator-sdk/blob/master/images/ansible-operator/Dockerfile#L37) in the ansible-operator image in our kubernetes deployment spec via a new `command/args` or can we set an env var to get this behaviour?

**Comment by whitfiea** [comment]
Overriding the ENTRYPOINT to set reconcile-period works. I think this issue is still needed as the documentation is incorrect and also doesn't mention setting --reconcile-period as an argument.

**Comment by VenkatRamaraju** [comment]
Hi @whitfiea,

Thanks for opening this issue. I can clarify some of the logic. There are three ways of specifying a reconcile-period for an ansible-based operator:
1. Through the `--reconcile-period` command line flag.
2. Through the `reconcilePeriod` field in the `watches.yaml` file.
3. Through the `ansible.operator-sdk/reconcile-period` field in the custom resource's annotations.

We have had users ask for each one, which is why we support these three methods. It is noteworthy that the default value for the command-line flag (option 1) is 1m. Additionally, a value of `0s` means "Do not do interval-based reconciliations". All these three ways of specifying the reconcile period have been documented individually in our documentation. 

In my [comment](https://github.com/operator-framework/operator-sdk/issues/5655#issuecomment-1098192850) on the other issue, I asked the issue author to not set any of these three values because they did not want to do interval-based reconciliations _at all_. However, if you want to use any of these three ways, they are all supported in our latest release.

Let me know if you have any questions or suggestions on how to improve our documentation. Better yet, feel free to open a pull request if you want to contribute. Thanks!

**Comment by whitfiea** [comment]
@VenkatRamaraju thanks for the update. In our case we don't want to do interval based reconciliations at all and that is what we had when using 1.17, we didn't have any other those three options set. We then upgraded to 1.20 and it started reconciling every minute on all our operators. I set reconcilePeriod to 0s in our watches.yaml but this didn't work. The only thing that worked is setting it on the cmdline (option 1) to be 0s.

So it seems the change in behaviour was that the default value of 1m was now being set as we didn't set this on the cmdline. Setting reconcilePeriod on the watches would be more ideal as we could control it better, but it seems to not work.

**Comment by VenkatRamaraju** [comment]
Yeah, I see what's going on. 

Setting `0s` in `watches.yaml` is saying "I don't want to do event-based reconciliations." However, since the default value of the flag is `1m`, this value is taking precedence during reconciliations. Let me investigate the reason for the default being `1m` and talk to a couple of other team members as well. I'll update this issue shortly. We may end up removing the default, which will revert the behavior to what you described in 1.17.

**Comment by VenkatRamaraju** [comment]
Hi @whitfiea,

After talking it over with a few folks, we have decided to change the default reconcile period to 10h for Ansible-based operators. We are using 10h as the to align the functionality with our Go operator and its [conventions](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/manager#Options) .

A [PR](https://github.com/operator-framework/operator-sdk/pull/5781) is in-flight with this change, it should be in soon. All the customization I discussed above still remains. Let me know if you have any questions/concerns, happy to answer them. Thanks!

**Comment by whitfiea** [comment]
@VenkatRamaraju does this mean the the reconcilePeriod set in the watches will still not work if I set it to 0s (or any value) as the default always overrides it?

**Comment by whitfiea** [comment]
Reading it again I think we are saying that the three options to set reconcile period will work apart from if you want to turn the interval based reconciliation off (via setting 0s). This would only work via --reconcile-period on the cmdline.

The change in the PR looks good, and will make the default behaviour more like the go operator like you said.

**Comment by VenkatRamaraju** [comment]
@whitfiea,

If you specify `reconcilePeriod:0s` or don't specify this field at all in the `watches.yaml` file, then the default value of `10h` will be used. However, if you use any specific value in the `watches.yaml` (ex: `1h2m3s`), then this value will be used.

In essence, if the watches reconcile period is non-zero, it will take precedence over the command-line flag. If you absolutely don't want any interval-based reconcile, then you can set the command-line flag to be 0s, not specify any value in the watches.yaml file or custom resource's annotations.

**Comment by VenkatRamaraju** [comment]
@whitfiea,

Yup! To completely disable any interval-based reconciliation, specifying a 0 value from the command-line flag is the only way. 

Thanks for bringing this to our attention. Feel free to close the issue if everything has been cleared up. If not, I'm happy to go into more detail.
