### ISSUE TITLE
Helm Operator Tutorial

### ISSUE THREAD

**Issue by thomasmckay** [operator-framework/operator-sdk#5792]
In https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper

```
-IMG ?= controller:latest
+IMG ?= $(IMAGE_TAG_BASE):$(VERSION)
```
I may be misunderstanding but shouldn't it be `v$(VERSION)`? As-is it will tag it as `0.0.1`

**Comment by varshaprasad96** [comment]
Yes. It could be, since its a tag. @thomasmckay would you mind submitting a PR to fix the Makefile scaffolding to have `v` in the version, or add the `v` prefix to the `IMG` tag. https://github.com/operator-framework/operator-sdk/blob/280335593c76c1fb14ce96100938f140ddb42659/testdata/helm/memcached-operator/Makefile#L6

Thanks for brining it up!

**Comment by Kanaga13579** [comment]
Hi @varshaprasad96 , I would like to know the use of "overrideValues" in watches.yaml. If the values can be overridden by adding in CR spec, then what is the use of adding overrideValues field again in watches.yaml? Could you please share your thoughts on this? It would be really grateful if you can explain me with an example.

Thanks !

**Comment by Chever-John** [comment]
Hello everyone, I've been following this project recently and would like to contribute. What is the problem with this good first issue? Can you describe it in detail? I want to spend some time trying to solve it.
