### ISSUE TITLE
SDK interface mutates inputs instead of returns values

### ISSUE THREAD

**Issue by benjaminapetersen** [operator-framework/operator-sdk#592]
I still find this a bit awkward:

```go
aThing := &corev1.Thing{}
err := sdk.Get(aThing) // aThing is mutated, this only returns an err 
```
vs something more like:

```go
requestConfig = &timeToGet.Thing{}
aThing, err := sdk.Get(requestConfig) // this is more intuitive, no?
```
This is still pre-alpha, so seems like a good time to raise the issue as it would obviously be a breaking change.  Is there good reason to stick with the mutating convention?

Thanks!

**Comment by AlexNPavel** [comment]
We are currently in the process of migrating the SDK to use the controller-runtime, and we will be using the controller-runtime's client instead of our old client: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client

You can view the current status of the controller-runtime migration on the `refactor/controller-runtime` branch: https://github.com/operator-framework/operator-sdk/tree/refactor/controller-runtime

**Comment by benjaminapetersen** [comment]
Ok great, I'm guessing that will change the API similar to what I mentioned.

Is this a change that will come while still in the pre-alpha state? or post 1.0? Thanks!

**Comment by hasbro17** [comment]
The change will come as soon as the controller-runtime refactor branch is merged onto the master.
We definitely won't be in pre-alpha state by that point. Whether we call it beta or 1.0 isn't decided yet.

**Comment by benjaminapetersen** [comment]
I'm not sure that the `controller-runtime` actually solves the problem:

https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/client.go#L125

https://godoc.org/sigs.k8s.io/controller-runtime/pkg/client#Reader

from the docs:

```
type Reader interface {
    // Get retrieves an obj for the given object key from the Kubernetes Cluster.
    // obj must be a struct pointer so that obj can be updated with the response
    // returned by the Server.
    Get(ctx context.Context, key ObjectKey, obj runtime.Object) error

    // List retrieves list of objects for a given namespace and list options. On a
    // successful call, Items field in the list will be populated with the
    // result returned from the server.
    List(ctx context.Context, opts *ListOptions, list runtime.Object) error
}
```

The fact that you are still passing in an object that will be mutated is what is concerning.  

Perhaps this issue was prematurely closed?

**Comment by shawn-hurley** [comment]
I do not think we should implement this change IMO.

1. There are many changes to the object that could occur when updating it, say you have `aThing` and you update it twice. Instead of a user having to deal with resourceVersions and that stuff this handles it for them. This allows you to `create` and then `update` the object that you are creating/mutating. 

2. It appears this is a pretty normal way to interact with Kube clients and I don't think that we should change. 

3. Passing a pointer to a function is a common idiom for telling the user we are going to change your object. [see](https://golang.org/pkg/encoding/json/#Unmarshal) `json.Unmarshal`.

**Comment by benjaminapetersen** [comment]
`json.Unmarshal` seems generic, deliberately.  I get that, JSON is generic data.  Give it `Unmarshall(data, interface)` and it will parse out the data into the interface.  But I think the interface is generally an "empty thing" that gets "filled up", however, I'll admit that I am new enough to Golang that I may be mistaken.

I still favor avoiding mutation when possible, but chewing on this. Thanks!
