### ISSUE TITLE
Controller Image not pulled

### ISSUE THREAD

**Issue by chinochao** [operator-framework/operator-sdk#5982]
I have a k3s cluster and when I follow the Ansible Operator Tutorial I get errors when the controller needs to start.

It seems the image is not found. Can someone point in the right direction to resolve this issue?

```
  Normal   Scheduled  11m                  default-scheduler  Successfully assigned portal-operator-system/portal-operator-controller-manager-76dbf8cc94-mzvds to ccnet-k3s-server02.local
  Normal   Pulled     11m                  kubelet            Container image "gcr.io/kubebuilder/kube-rbac-proxy:v0.11.0" already present on machine
  Normal   Created    11m                  kubelet            Created container kube-rbac-proxy
  Normal   Started    11m                  kubelet            Started container kube-rbac-proxy
  Warning  Failed     10m (x5 over 11m)    kubelet            Error: ImagePullBackOff
  Normal   Pulling    10m (x4 over 11m)    kubelet            Pulling image "controller:latest"
  Warning  Failed     10m (x4 over 11m)    kubelet            Failed to pull image "controller:latest": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/controller:latest": failed to resolve reference "docker.io/library/controller:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
  Warning  Failed     10m (x4 over 11m)    kubelet            Error: ErrImagePull
  Normal   BackOff    102s (x42 over 11m)  kubelet            Back-off pulling image "controller:latest"
```

**Comment by camilamacedo86** [comment]
How do you deploy it?
It seems that you did not build and push the image `make build push IMG=myresitry/image`.
Then, it seems that you are not using the `make deploy IMG=` command either. 

You need to build and publish the image so that it can be used.
By looking at the logs  `"controller:latest"` it means that you did not build the image ( that is like a placeholder that will be replace by the data when you run the make commands )

See https://sdk.operatorframework.io/docs/building-operators/ansible/quickstart/#direct-deployment.

**Comment by chinochao** [comment]
Oh yes. I missed that step. I did not see it was failing as I did not updated the image name.
