### ISSUE TITLE
Unable to execute Envtest Setup

### ISSUE THREAD

**Issue by orangemail** [operator-framework/operator-sdk#6034]
I'm trying to follow these steps  given in URL : https://v1-5-x.sdk.operatorframework.io/docs/building-operators/golang/references/envtest-setup/  which has details of Envtest Setup. 

![image](https://user-images.githubusercontent.com/20956904/190925056-87b07445-8bb5-4f31-acd2-5b4a6de54e17.png)

I see that URL : https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/hack/setup-envtest.sh do not exisit.

Currently, I'm using https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/v0.7.2/hack/setup-envtest.sh and I don't face any issue in accessing it. 

Can you please confirm on this https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/hack/setup-envtest.sh

**Comment by everettraven** [comment]
Hi @orangemail, I took a look into this and it seems like that is the method that was used for installing and using `envtest` a little while ago. Since then the controller-runtime repository has been updated and it is recommended to install `envtest` another way that uses the `go install ...` command.

In the latest SDK documentation we recommend taking a look at this KubeBuilder documentation for configuring `envtest`: https://book.kubebuilder.io/reference/envtest.html

Also in projects scaffolded with the latest SDK versions there is a new Makefile target for installing `envtest` here:
https://github.com/operator-framework/operator-sdk/blob/76ac4ba5d7d77590ee0e973c5b97595fcf447495/testdata/go/v3/memcached-operator/Makefile#L179-L182

This follows the recommended installation by controller-runtime here: https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest#envtest-binaries-manager

I hope this helps!

**Comment by orangemail** [comment]
> Hi @orangemail, I took a look into this and it seems like that is the method that was used for installing and using `envtest` a little while ago. Since then the controller-runtime repository has been updated and it is recommended to install `envtest` another way that uses the `go install ...` command.
> 
> In the latest SDK documentation we recommend taking a look at this KubeBuilder documentation for configuring `envtest`: https://book.kubebuilder.io/reference/envtest.html
> 
> Also in projects scaffolded with the latest SDK versions there is a new Makefile target for installing `envtest` here:
> 
> https://github.com/operator-framework/operator-sdk/blob/76ac4ba5d7d77590ee0e973c5b97595fcf447495/testdata/go/v3/memcached-operator/Makefile#L179-L182
> 
> This follows the recommended installation by controller-runtime here: https://github.com/kubernetes-sigs/controller-runtime/tree/master/tools/setup-envtest#envtest-binaries-manager
> 
> I hope this helps!

@everettraven : Thanks for the information.  I hope this will help.

**Comment by everettraven** [comment]
@orangemail I am going to close this issue, but if you end up having any more problems feel free to reopen. Thanks!
