### ISSUE TITLE
the version choices of operator-sdk

### ISSUE THREAD

**Issue by THMAIL** [operator-framework/operator-sdk#6072]
hello everyone，

I want to extend kubernetes with operator-sdk，but I don't know which operator-sdk version  should I choose.

So I read the [doc](https://github.com/operator-framework/operator-sdk#dependency-and-platform-support) from github, and it tells me I should go to  [this page](https://sdk.operatorframework.io/docs/overview/#kubernetes-version-compatibility) to find the answer. Then [this page](https://sdk.operatorframework.io/docs/overview/#kubernetes-version-compatibility) tells me to client-go’s [compatibility matrix](https://github.com/kubernetes/client-go#compatibility-matrix) to find the answer. 

Now, I have find out that client-go-release-9.0 is compatible with my **kubernetes cluster whose version is **v1.12.5**** . But I still don't know which operator-sdk version should I choose.
    
Can someone tell me what should I do ? 

Thanks!!!!!!!!!!

**Comment by THMAIL** [comment]
Does anyone know how to resolve this problem?

**Comment by laxmikantbpandhare** [comment]
Not sure what exactly your ask. Do you want to install `operator-sdk` and use our command line tool? Could you please specify what exactly you are trying?

**Comment by varshaprasad96** [comment]
Hi @THMAIL, 
In general, the version of K8s dependencies which are used to build Operator-SDK is the version to which it is strictly compatible. For example, in [Operator-SDK 1.23.0](https://github.com/operator-framework/operator-sdk/blob/1eaeb5adb56be05fe8cc6dd70517e441696846a4/go.mod#L41), specifies the k8s dependencies in its go.mod file as 0.24.2. This means SDK 1.23.0 is strictly compatible with k8s 1.24 (Since for each v1.x.y Kubernetes release, the major version of client-go (first digit) would remain 0).

Now let's understand the backwards compatibility matrix with the upstream K8s cluster versions. Here, we use client-go as the mediator. To elaborate, we can follow the steps below:
1. For the specific version of operator-sdk that you are using, find the corresponding client-go version.
For example, let's take Operator-SDK 1.9.0. It specifies the client-go version 0.20.2 (https://github.com/operator-framework/operator-sdk/blob/v1.9.0/go.mod#L39).
2. For the client-go version which we have found using step (2), we use the compatibility matrix [here](https://github.com/kubernetes/client-go#compatibility-matrix), to fetch the corresponding k8s cluster version https://github.com/kubernetes/client-go#compatibility-matrix. Note that client-go version 0.20.2, corresponds to k8s version 1.20.2. Based on the last row of matrix we can infer that:

-  We have exactly the same features / API objects in both client-go and the Kubernetes 1.20. So k8s 1.20 clusters will work perfectly.
- Some APIs which have been removed or added, due to which client-go 1.20 may not exactly work with k8s 1.15 to 1.19 clusters. 

Hope this answers your question.

**Comment by varshaprasad96** [comment]
@THMAIL Thanks for bringing this up. We can add documentation that explicitly states the K8s version that is supported by SDK. To automate this with an K8s update, we can pick the version from Makefile and add this as a part of release script. @everettraven will be working on this issue.
