### ISSUE TITLE
CVE-2022-23648 CVE-2022-31030 github.com/containerd/containerd package

### ISSUE THREAD

**Issue by FedericoYST** [operator-framework/operator-sdk#6143]
#### What did you do?
I have executed a vulnerability scan on the latest available image: 

- quay.io/operator-framework/helm-operator:latest

#### What did you expect to see?
A vulnerability free image

#### What did you see instead? Under which circumstances?
Two vulnerabilities on the github.com/containerd/containerd package: 

1. CVE-2022-23648
2. CVE-2022-31030

#### Environment

**Operator type:** Helm Operator

**Kubernetes cluster type:** Not applicable

`$ operator-sdk version`

- Not applicable

`$ go version` (if language is Go)

`$ kubectl version`

- Not applicable

#### Possible Solution

Upgrade the following package to the latest available version:

- github.com/containerd/containerd

**Comment by everettraven** [comment]
This should be resolved now as newer releases have been created that have updated the `latest` tag for the `helm-operator` image. 

We can see a clean vulnerability scan on quay for one of the manifests for this image here: https://quay.io/repository/operator-framework/helm-operator/manifest/sha256:7d6d774e88c3fb220e4c97e415b2461e108ccc491f1016e225cbf96bbdc0823c?tab=vulnerabilities

Due to this I will be closing this issue, but please feel free to reopen if you are still encountering the issue.

**Comment by FedericoYST** [comment]
Hi @everettraven,
First of all, thank you for your response!
As you can see, trivy scan found the following CVE:
![image](https://user-images.githubusercontent.com/68863319/203730309-8afe5ef0-17cb-418f-ad3c-bfeb4a63dc1d.png)
I think Quay.io scan found only OS vulnerabilities and not the library ones which are equally important.
Let me know what you think.

**Comment by everettraven** [comment]
@FedericoYST i agree that the libraries are important as well, however I think most of them are pulled in via the ubi(-minimal) 8.7 image that are images use as a base.

I will reopen this issue and bring it up in the community meeting on Monday November 28th.

This raises a question in my mind of whether or not we truly need to be inheriting packages from the base image we use to build and ship our images or if we could slim them down even further.
