### ISSUE TITLE
Operator Pod crashing due to 'port already in use' 

### ISSUE THREAD

**Issue by kavyamani596** [operator-framework/operator-sdk#6148]
## Type of question

General operator-related help 

#### What did you do?

I've implemented 2 operators in the same repo.
In their main.go file I've used different ports
Say for operator A , I've used 8080,8081
Operator B, I've used used 8085,8086

#### What did you expect to see?

Both operators Running when  I deploy them

#### What did you see instead? Under which circumstances?

Operator A runs , but Operator B fails to run and i receive this
runtime.main
        /usr/local/go/src/runtime/proc.go:255
2022-11-03T17:05:18Z    INFO    controller-runtime.metrics      Metrics server is starting to listen    {"addr": ":8085"}
2022-11-03T17:05:18Z    ERROR   setup   unable to start manager {"error": "error listening on :8085: listen tcp :8085: bind: address already in use"}
main.main
        /operatorB/operatorB_main/main.go:83
runtime.main

But when i checked the port
it showed

 ps -eaf | grep 8085
bruce     880560  880316  0 05:50 pts/2    00:00:00 grep --color=auto 8085

I also gave other ports like 9091,9092, still the same issue persists.

**Comment by everettraven** [comment]
@kavyamani596 Thanks for raising this issue!

>2022-11-03T17:05:18Z INFO controller-runtime.metrics Metrics server is starting to listen {"addr": ":8085"}

This log message here is stating that the Operator B metrics server is starting on port 8085. 

>2022-11-03T17:05:18Z ERROR setup unable to start manager {"error": "error listening on :8085: listen tcp :8085: bind: address already in use"}

This error is likely occurring because the manager is attempting to use port 8085 but that port is already taken by the metrics server. I believe changing either the metrics server or the controller manager to use a different port from each other would resolve this issue.


I hope this helps!

**Comment by theishshah** [comment]
Closing for now, if the above doesn't solve the issue feel free to re-open. Thanks
