### ISSUE TITLE
check for tool version in makefile and not just its existence

### ISSUE THREAD

**Issue by coriaedu** [operator-framework/operator-sdk#6173]
#### Describe the problem you need a feature to resolve.

I have an issue after upgrading OSDK version for my operator.

The **Makefile** has two targets that will download [`controller-gen`](https://github.com/operator-framework/operator-sdk/blob/24c8b61b7ce9f0aedbfc0659c8e60fc8b249018f/testdata/go/v3/memcached-operator/Makefile#L195) and [`kustomize`](https://github.com/operator-framework/operator-sdk/blob/24c8b61b7ce9f0aedbfc0659c8e60fc8b249018f/testdata/go/v3/memcached-operator/Makefile#L190) tools, with the versions corresponding to `CONTROLLER_TOOLS_VERSION` and `KUSTOMIZE_VERSION` vars.
The recipes there are currently checking for file existence before installing the tool, but they don't confirm the version.

In my scenario, where I am upgrading the OSDK, I found this issue with the current script:

* checkout clean branch with OSDK 1.24.0
* Run `make controller-gen` -> This will download controller-gen v0.9.2 at `$(LOCALBIN)`
* upgrade OSDK to 1.25.1
    * This includes updating the [`CONTROLLER_TOOLS_VERSION`](https://github.com/operator-framework/operator-sdk/blob/24c8b61b7ce9f0aedbfc0659c8e60fc8b249018f/testdata/go/v3/memcached-operator/Makefile#L186) to `v0.10.0`
* Run any command that uses `controller-gen` thinking that `v0.10.0` will be used, but it is still running `0.9.2`

The same thing applies when I switch branches that have different OSDK versions

This applies to `kustomize` also.

#### Describe the solution you'd like.

I'd like the [`controller-gen`](https://github.com/operator-framework/operator-sdk/blob/24c8b61b7ce9f0aedbfc0659c8e60fc8b249018f/testdata/go/v3/memcached-operator/Makefile#L195) and [`kustomize`](https://github.com/operator-framework/operator-sdk/blob/24c8b61b7ce9f0aedbfc0659c8e60fc8b249018f/testdata/go/v3/memcached-operator/Makefile#L190) targets to check for version so we ensure that it matches the corresponding VERSION var. 

/language go

**Comment by everettraven** [comment]
@coriaedu Thanks for raising this issue! I think that this would be great functionality to add. 

Since this is related to Go operators, I would recommend also [opening an issue in Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder/issues/new/choose) that references this issue. Operator-SDK uses the Go plugin from Kubebuilder for scaffolding Go operator projects so the change would need  to be made in the [Makefile template in the Kubebuilder Go plugin](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go).

**Comment by coriaedu** [comment]
Thank you @everettraven , I opened https://github.com/kubernetes-sigs/kubebuilder/issues/3068 and am going through the step to become a collaborator for that repo so I can hopefully provide the fix along with the issue :)

Should we close this?

**Comment by everettraven** [comment]
@coriaedu If you would like we can close this issue. During our community meeting yesterday I advocated for keeping it open because I feel like this would be a nice addition. Keeping it open would help sdk maintainers with tracking this (many of the operator-sdk maintainers are also contributors to Kubebuilder but may not actively pay attention to those issues).

**Comment by coriaedu** [comment]
Ok, I'd say we leave it open until the https://github.com/kubernetes-sigs/kubebuilder/issues/3068 is addressed  :crossed_fingers:
 
Thanks!

**Comment by coriaedu** [comment]
closed https://github.com/kubernetes-sigs/kubebuilder/issues/3068
