### ISSUE TITLE
curl'ing a script and executing it are bad practice?

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/operator-sdk#6219]
```
$ make bundle
test -s /Users/jberkhahn/workspace/projects/memcached-operator/bin/controller-gen || GOBIN=/Users/jberkhahn/workspace/projects/memcached-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
/Users/jberkhahn/workspace/projects/memcached-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
test -s /Users/jberkhahn/workspace/projects/memcached-operator/bin/kustomize || { curl -Ss "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash -s -- 3.8.7 /Users/jberkhahn/workspace/projects/memcached-operator/bin; }
make: *** [Makefile:189: /Users/jberkhahn/workspace/projects/memcached-operator/bin/kustomize] Killed: 9
```

`make bundle` gets horked on my machine by the security management software i have to have installed. I think wget'ing the script and then running it would work, would it be a good idea to switch this line to that?

**Comment by everettraven** [comment]
@jberkhahn Is there a reason to suspect that `wget` would work better than `curl`? 

I'd be curious to see if the problem with the security management software is just that you are using `curl` or that you are downloading something with `curl` (i.e the security software can't verify the download).

On another note, I think the `curl` command is happening due to the `make kustomize` target:
https://github.com/operator-framework/operator-sdk/blob/cbeec475e4612e19f1047ff7014342afe93f60d2/testdata/go/v3/memcached-operator/Makefile#L189-L192

This particular target is generated as part of the Makefile generated by the `go` plugin and therefore this change would probably need to be made in Kubebuilder here: https://github.com/kubernetes-sigs/kubebuilder/blob/a99b1519f0022c134447e9ec492ffb6a5a77b01f/pkg/plugins/golang/v3/scaffolds/internal/templates/makefile.go#L206

**Comment by varshaprasad96** [comment]
One of the reason for defaulting to curl was because wget is not installed by default in all operating systems. Even in Mac, (afaik remember, could have been changed) wget is not installed by default. This was one of the reasons to use curl instead (not the same issue, but for reference: https://github.com/operator-framework/operator-sdk/issues/4152)

**Comment by jberkhahn** [comment]
this was fixed in kubebuilder and will be fixed  here when we bump that dep, so I'm closing this
