### ISSUE TITLE
Go Operator Tutorial

### ISSUE THREAD

**Issue by sanmaym** [operator-framework/operator-sdk#6228]
In run the Operator Step, there is a step to export an environment variable "export MEMCACHED_IMAGE="memcached:1.4.36-alpine" inside Step 1 [https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#2-run-as-a-deployment-inside-the-cluster](url). It is not clear if this step needs to be performed only for run inside cluster or even for other approaches ( step 2)

**Comment by varshaprasad96** [comment]
@sanmaym That's right, with the deploy-image-plugin that the tutorial points to, only when the operator is run locally outside the cluster (ie when `make run` command is called), image needs to be specified as an env variable. More details about the plugin are [here](https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html#using-make-run).

I'm closing this issue, since the question has been answered. But please feel free to reopen or create a new issue if you have any questions.
