### ISSUE TITLE
The skip-go-version-check flag is not working for prev. go version

### ISSUE THREAD

**Issue by denist-huma** [operator-framework/operator-sdk#6236]
#### What did you do?

```sh
$ operator-sdk init --domain huma.com --skip-go-version-check --license none \
    --project-name huma-azure-storage-operator --component-config true \
    --owner "Huma Therapeutics Limited." 
Writing kustomize manifests for you to edit...
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.13.0
Update dependencies:
$ go mod tidy
go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
Error: failed to initialize project: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 1
```

#### What did you expect to see?

No error. And no overwrite of "go 1.18" already present in my "go.mod"

#### What did you see instead? Under which circumstances?

FATA[0005] failed to initialize project: unable to run post-scaffold tasks of "base.go.kubebuilder.io/v3": exit status 1 

#### Environment

**Operator type:**

/language go 

**Kubernetes cluster type:**

`$ operator-sdk version`

operator-sdk version: "v1.26.0", commit: "cbeec475e4612e19f1047ff7014342afe93f60d2", kubernetes version: "1.25.0", go version: "go1.19.3", GOOS: "linux", GOARCH: "amd64"

`$ go version` (if language is Go)

go version go1.18.3 linux/amd64

`$ kubectl version`

#### Possible Solution

- Respect the existing of "go 1.18" already present in my "go.mod"

- Or do no `go mod tidy`.

**Comment by denist-huma** [comment]
One more question: where is CLI command "init" defined? Cannot find one in this repo, no "skip-go-version-check" substring.

```sh
$ grep -ri "Initialize a new project" ./
./website/content/en/docs/cli/operator-sdk.md:* [operator-sdk init](../operator-sdk_init)        - Initialize a new project
./website/content/en/docs/cli/operator-sdk_init.md:Initialize a new project
./website/content/en/docs/cli/operator-sdk_init.md:Initialize a new project including the following files:
./website/content/en/docs/cli/operator-sdk_init.md:  # Initialize a new project with your domain and name in copyright
./website/content/en/docs/cli/operator-sdk_init.md:  # Initialize a new project defining a specific project version
./website/content/en/docs/building-operators/ansible/migration.md:The easy migration path is to initialize a new project, re-recreate APIs, then copy pre-v1.0.0 configuration files into the new project.
./website/content/en/docs/building-operators/ansible/migration.md:When we initialize a new project, we need to specify the domain that _all_ APIs in
./website/content/en/docs/building-operators/ansible/development-tips.md:this, initialize a new project:
./website/content/en/docs/building-operators/golang/migration.md:The easy migration path is to initialize a new project, re-recreate APIs, then copy pre-v1.0.0 configuration files into the new project.
./website/content/en/docs/building-operators/golang/migration.md:When we initialize a new project, we need to specify the domain that _all_ APIs in
./website/content/en/docs/building-operators/helm/migration.md:The easy migration path is to initialize a new project, re-recreate APIs, then copy pre-v1.0.0 configuration files into the new project.
./website/content/en/docs/building-operators/helm/migration.md:When we initialize a new project, we need to specify the domain that _all_ APIs in
denis@L560:~/huma/operator-sdk$ grep -ri "skip-go-version-check" ./
./website/content/en/docs/cli/operator-sdk_init.md:      --skip-go-version-check    if specified, skip checking the Go version
```

**Comment by everettraven** [comment]
@denist-huma Thanks for raising this issue! The problem that seems to be occurring here is that when initializing a new Go Operator project, it will attempt to run `go mod tidy` to ensure all the dependencies are up to date immediately after the project scaffolding has been completed. This particular logic is not prevented when the flag `--skip-go-version-check` is specified, but rather prevents a pre-scaffolding check that would error out early if the go version is incompatible.

The error:
```
go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
```
Is actually coming from the `go mod tidy` command that is being run to update the dependencies.

From what I can tell, the solution would be to either use an earlier version of Operator-SDK that scaffolds projects using go 1.18 (the latest Operator-SDK version that scaffolds using go 1.18 seems to be `v1.24.1`) or upgrade your local go installation to 1.19.



> One more question: where is CLI command "init" defined? Cannot find one in this repo, no "skip-go-version-check" substring.

So this is because the `init` command is actually defined by the Kubebuilder CLI package that we have as a dependency and build additional functionality on top of. The `--skip-go-version-check` flag is actually a part of the `go/v3` plugin's `init` command and can be found here: https://github.com/kubernetes-sigs/kubebuilder/blob/5098f759e28f42614e96a25ff01ffa8f38996237/pkg/plugins/golang/v3/init.go#L80

Here is the pre-scaffolding check that is not run when the flag is passed: https://github.com/kubernetes-sigs/kubebuilder/blob/5098f759e28f42614e96a25ff01ffa8f38996237/pkg/plugins/golang/v3/init.go#L112-L117

> And no overwrite of "go 1.18" already present in my "go.mod"

This seems like it would rather be an issue in the `go/v3` plugin as from what I can tell, it assumes that when it is used via the `init` subcommand that it is initializing a project from scratch (it doesn't expect a go.mod file to already exist so it overwrites it). For this problem in particular I would recommend raising an issue in [kubernetes-sigs/kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) where the `go/v3` plugin code is maintained.

I hope this helps!
