### ISSUE TITLE
Disable caching for Helm Operator when watching all namespaces to avoid OOMKilled in big clusters

### ISSUE THREAD

**Issue by haywoodsh** [operator-framework/operator-sdk#6255]
#### Describe the problem you need a feature to resolve.

When a Helm operator is installed in a cluster with a lot of namespaces and k8s objects deployed, the controller caches all the k8s objects, consumes a lot of memory and causes `OOMKilled` events. Watching one namespace only could potentially reduce memory usage, but our use case requires watching multiple namespaces. 

#### Describe the solution you'd like.

Disable caching for helm-operator when watching all namespaces.

/language helm

**Comment by jberkhahn** [comment]
So, we are aware of some memory issues in the Helm operator. We actually [just merged a pull request](https://github.com/operator-framework/operator-sdk/pull/6026) that might help with this problem. We should be cutting a release this week or so, could you try rebuilding your operator with the new version and see if that helps? If not we can trying adding something like this.

**Comment by madorn** [comment]
@jberkhahn @joelanford Thanks for the follow up. Will try the latest PR.

Any info on the possibility of disabling manager cache with helm-operator?

**Comment by joelanford** [comment]
Another thought: when we create dynamic watches for the operand objects, do we use a label selector to ensure we only watch and cache the subset of those objects that are actually managed by the operator? I'm guessing we don't and that if we did, it would be a significant improvement, especially on larger clusters.

**Comment by varshaprasad96** [comment]
@jberkhahn Adding some links here in case it helps during investigation:
Using of label selector while starting manager to selectively cache objects: https://github.com/kubernetes-sigs/controller-runtime/blob/main/designs/use-selectors-at-cache.md
Place where we set up the controller to watch the Helm CR: https://github.com/operator-framework/operator-sdk/blob/484013d1865c35df2bc5dfea0ab6ea6b434adefa/internal/helm/controller/reconcile.go#L48
Place where we set up reconciler for each API defined in watches.yaml: https://github.com/operator-framework/operator-sdk/blob/e859a564c81b2415a6e026b7d5a31be04448f235/internal/cmd/helm-operator/run/cmd.go#L209
This is where we add watches for resources in released Helm charts: https://github.com/operator-framework/operator-sdk/blob/e859a564c81b2415a6e026b7d5a31be04448f235/internal/helm/controller/controller.go#L127. Since we use the upstream Helm logic to install/uninstall/upgrade the release, I _think_ adding label selectors to cache objects would be in "watchDependentResources".

**Comment by jberkhahn** [comment]
so, it looks like you can make a predicate  based on a label selector and apply it in WatchDependentResources(), but how would you make all the dependent resources have the same label if they're created by just chunking the default helm chart?

**Comment by joelanford** [comment]
I've been taking a look at this. There are two things to do:
1. For the cache configuration, we need to configure a custom `NewCache` function on the manager options prior to calling `manager.New`.  This is actually not possible right now due to a bug in controller runtime. I've got a PR up that fixes an issue that helm-operator runs into since the primary CR is unstructured.Unstructured. https://github.com/kubernetes-sigs/controller-runtime/pull/2246

2. As @jberkhahn says, we need some label to key off of. My suggestion would be for us to add a _new_ label, something along the lines of `helm.sdk.operatorframework.io/chart: <chartName>-<chartVersion>`. The easiest spot to add that is in the ownerRefInjectingClient, but it feels a bit dirty to inject a label via a client that says it injects owner refs. Perhaps we rename that client to something a bit more generic that makes us feel better about injecting a few different things.

I'll try to get a PR up here, that uses my controller-runtime fork so that folks can test it.

**Comment by joelanford** [comment]
WIP PR here: https://github.com/operator-framework/operator-sdk/pull/6377

@haywoodsh This does not completely eliminate caching, but I expect it to significantly improve the situation. Its the best of both worlds. You still get caching which reduces load on the apiserver and enables near-immediate reconciliation when operand resources are changed or deleted, but now the cache contains _just_ the objects that are actually being managed by the operator. So now, the memory usage scales according to the number of CRs, not the size of the cluster.

 If possible, please try out a build of the helm-operator from my branch and let me know if this will solve your problem.

**Comment by vhosakot** [comment]
I referred https://sdk.operatorframework.io/docs/building-operators/helm/quickstart/ and installed `nginx-operator` and saw it OOM continuously on OpenShift 4.11.

per suggestion from @madorn, increasing memory limit of `nginx-operator-controller-manager` deployment to `4Gi` fixed the OOM crash of `nginx-operator-controller-manager` pod, thanks @madorn:
```
% kubectl get deploy nginx-operator-controller-manager -o yaml
...
        image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
        resources:
          limits:
            memory: 4Gi <====
...
        image: vhosakot/nginx-operator:v0.0.1
        resources:
          limits:
            memory: 4Gi <====

$ kubectl get pods
...
nginx-operator-controller-manager-56fff5db64-q9rrg    2/2     Running     0          15m
...
```

btw, I noticed steps in https://sdk.operatorframework.io/docs/building-operators/helm/quickstart/ are incorrect, let me know if I can submit a PR to correct them.

**Comment by acornett21** [comment]
@joelanford we have a partner asking about this as a mutual customer is still facing issues, is your WIP PR in a polished enough state to take to main?

**Comment by joelanford** [comment]
Just rebased it. I was looking for feedback (that I don't think I ever got) to make sure it solved the problem.
