### ISSUE TITLE
Notes on Go tutorial

### ISSUE THREAD

**Issue by dharmit** [operator-framework/operator-sdk#6314]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/

### Which section(s) is the issue in?

1. [Define the api](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#define-the-api) section asks to add `// +kubebuilder:validation:Maximum=3` marker. This, in turn, causes the [`kubectl patch` command](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#update-the-size) to fail with:
    ```sh
    $ kubectl patch memcached memcached-sample -p '{"spec":{"size": 5}}' --type=merge
    The Memcached "memcached-sample" is invalid: spec.size: Invalid value: 5: spec.size in body should be less than or equal to 3
    ```
2. The default `main.go` generated using `operator-sdk` command doesn't have `MemcachedReconciler.Recorder` initialized like [here](https://github.com/operator-framework/operator-sdk/blob/latest/testdata/go/v3/memcached-operator/main.go#L95). It causes the controller to panic in the `Reconcile` method.
3. The CR mentioned in [Create a Memcached CR](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#create-a-memcached-cr) section fails to get created due to missing value for `containerPort`. Adding `containerPort: 11211` to the spec helps fix it.

### What needs fixing?

1. Correcting the `kubectl patch` command or, adding a note in the doc would be helpful.
2. Mentioning it somewhere in the doc would be helpful, IMO, and save a lot of time for someone trying to get started with Operators for the first time.
3. Adding `containerPort: 11211` to the spec helps fix it.

#### Additional context

I'm trying the operator-sdk tutorial for the first time, so let me know if I'm making a mistake instead of something being amiss in the docs.

**Comment by dharmit** [comment]
I can open a PR to address these points I have raised. But I'd like to know from the team if I'm looking at this right or misunderstanding something myself. :)

**Comment by jberkhahn** [comment]
Sure, we'd love for you to submit a PR to fix these.

1. Probably just change the max to 5 in the kubebuilder tag.
2. this probably shouldn't be happening. will have to chat about this and figure out where it needs to be fixed. we'll talk about this at the next triage meeting.
3. Yeah, add the containerPort: 11211 to the example spec

**Comment by dharmit** [comment]
I've opened a PR for 1 & 3.

**Comment by varshaprasad96** [comment]
For (2), I see what the issue is: The operator-idk init command does not initialize the [recorder](https://github.com/operator-framework/operator-sdk/blob/5cbdad9209332043b7c730856b6302edc8996faf/testdata/go/v3/memcached-operator/main.go#L95) used for recording events from EventSource. Whereas in the reconciler code, we [record](https://github.com/operator-framework/operator-sdk/blob/5cbdad9209332043b7c730856b6302edc8996faf/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L300) a delete event, which when directly copied by users into the project scaffolded by `operator-sdk` init command fails. The two options for solving this (imo) could be:

1. Add a TODO section in the [sample](https://github.com/operator-framework/operator-sdk/blob/5cbdad9209332043b7c730856b6302edc8996faf/testdata/go/v4-alpha/memcached-operator/main.go#L95) - `main.go`, explaining that the user needs to initialize the recorder as it is one of the best practices for recording events. Add documentation regarding the same in tutorial.
2. Use [deploy-image](https://book.kubebuilder.io/plugins/deploy-image-plugin-v1-alpha.html) plugin by default to scaffold out operator-sdk. We are having the [testdata](https://github.com/operator-framework/operator-sdk/blob/5cbdad9209332043b7c730856b6302edc8996faf/hack/generate/samples/internal/go/memcached-with-customization/memcached_with_customization.go#L99) scaffolded out using deploy-image plugin to help users follow the best practices but the sdk init command by default doesn't use it in [tutorial](https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#create-a-new-api-and-controller).

I would vote for (1), given:
- we would not want a first-time user of Operator SDK to use a complicated command explaining all the flags while getting started. 
- It is simpler than making deploy-image plugin default, especially since the plugin is in alpha stage - not yet stable.

**Comment by dharmit** [comment]
> Add a TODO section in the [sample](https://github.com/operator-framework/operator-sdk/blob/5cbdad9209332043b7c730856b6302edc8996faf/testdata/go/v4-alpha/memcached-operator/main.go#L95) - `main.go`, explaining that the user needs to initialize the recorder as it is one of the best practices for recording events.

When/where is this sample `main.go` used/referenced? I'm asking because I didn't come across it while going through the Go tutorial. Which makes me wonder as to how the user will notice this TODO. 

Or, would adding it to this place automatically ensure such a TODO shows up in the `main.go` generated by `operator-sdk init`? I don't think so, but then I don't know how `operator-sdk init` works.

> Add documentation regarding the same in tutorial.

+1. That would surely help.
