### ISSUE TITLE
Pods keeps on restarting  using helm operator when we try running operator with make install run 

### ISSUE THREAD

**Issue by annu-mishraa** [operator-framework/operator-sdk#6345]
#### What did you do?

I have deployed helm charts using helm operator, pods keeps on restarting although there are no error logs.

#### What did you expect to see?

Pods to be in consistent running state instead of restarting multiple times

#### Environment

**Operator type:**

 helm Operator

**Kubernetes cluster type:**

`$ operator-sdk version`

`$ go version` (if language is Go)

`$ kubectl version`

**Comment by varshaprasad96** [comment]
@annu-mishraa Could you please share the logs of the operator for us to check if there is anything suspicious happening. Also, could you also share your project (in case it is open source). It is very difficult to find the cause of multiple restarts without having more information on what is happening.

**Comment by varshaprasad96** [comment]
@annu-mishraa A few questions more to try debugging this:
1. Is there anything else which is updating your object created by helm chart?
2. Does the operator eventually settle after multiple restarts? If so, then it can be considered as an benign error as mentioned [here](https://github.com/operator-framework/operator-sdk/issues/5555#issuecomment-1047136821).

**Comment by annu-mishraa** [comment]
@varshaprasad96 
1. Is there anything else which is updating your object created by helm chart? -> I don't see that there is any other thing which is updating the object.
2. Does the operator eventually settle after multiple restarts? No it keeps on restarting , and it is going into loop. Its not being consistent.

**Comment by varshaprasad96** [comment]
@annu-mishraa could you provide a link to the helm operator which is using the [chart](https://github.com/ODIM-Project/ODIM/tree/main/odim-controller/helmcharts/aggregation) mentioned here.

**Comment by annu-mishraa** [comment]
@varshaprasad96  : Operator-sdk version
operator-sdk version: "v1.27.0-2-g912231bd", commit: "912231bdb6f1976fea1041a9a0e939fa05d257f3", kubernetes version: "v1.25.0", go version: "go1.20.1", GOOS: "linux", GOARCH: "amd64"
The url for your refernce :https://sdk.operatorframework.io/docs/installation/

**Comment by varshaprasad96** [comment]
@annu-mishraa I would like to access your operator built using the helm chart specified [here](https://github.com/ODIM-Project/ODIM/tree/main/odim-controller/helmcharts/aggregation). Without having the operator project which you have scaffolded, it would be difficult to replicate the steps (since I don't have a sample CR or any configuration details in `watches.yaml` to try it locally). 

If your project is not open source, I would suggest the following code locations to look into to try debugging:
This (https://github.com/operator-framework/operator-sdk/blob/484013d1865c35df2bc5dfea0ab6ea6b434adefa/internal/helm/controller/reconcile.go#L74) is the logic where helm reconciler is implemented. To be specific we install a helm release [here](https://github.com/operator-framework/operator-sdk/blob/484013d1865c35df2bc5dfea0ab6ea6b434adefa/internal/helm/controller/reconcile.go#L237). What would possibly be happening, is between the time we fetch the CR from the [cluster](https://github.com/operator-framework/operator-sdk/blob/484013d1865c35df2bc5dfea0ab6ea6b434adefa/internal/helm/controller/reconcile.go#L87) (here) and the release is reconciled by creating a manager (https://github.com/operator-framework/operator-sdk/blob/484013d1865c35df2bc5dfea0ab6ea6b434adefa/internal/helm/controller/reconcile.go#L96), the resource is getting modified, which is possibly the reason when the resource is [reconciled](https://github.com/operator-framework/operator-sdk/blob/484013d1865c35df2bc5dfea0ab6ea6b434adefa/internal/helm/release/manager.go#L239) it results in this error. You could build the Operator SDK locally and probably find where the error is occurring.
