### ISSUE TITLE
How does controller test handles requeue from the reconcile function?

### ISSUE THREAD

**Issue by hellt** [operator-framework/operator-sdk#6356]
## Type of question

Best Practices

## Question

Hi all, in the [provided example](https://github.com/operator-framework/operator-sdk/blob/9d2f672c8e5bb0af8d0b5955cfa673aad21f1281/testdata/go/v3/memcached-operator/controllers/memcached_controller_test.go#L107) for testing controllers the Reconcile function is only executed once, with the ctrl.Result being ignored.

At the same time, the controller reconciliation loop assumes an early return when we create the deployment:

https://github.com/operator-framework/operator-sdk/blob/9d2f672c8e5bb0af8d0b5955cfa673aad21f1281/testdata/go/v3/memcached-operator/controllers/memcached_controller.go#L224-L227

When we create a deployment and return, how do we make the test suite to proceed? Shouldn't we reinvoke the reconciliation loop again?

**Comment by varshaprasad96** [comment]
@hellt This is a great question, explaining the test in below:

We could consider the example in "*_controller.go" to be more like a unit test wherein we test a particular reconcile action given the current state of CR in the cluster. As you said, we run the reconciler only once here: https://github.com/operator-framework/operator-sdk/blob/9d2f672c8e5bb0af8d0b5955cfa673aad21f1281/testdata/go/v3/memcached-operator/controllers/memcached_controller_test.go#L107 and we test the scenario wherein when we have a memcached custom resource in the cluster https://github.com/operator-framework/operator-sdk/blob/9d2f672c8e5bb0af8d0b5955cfa673aad21f1281/testdata/go/v3/memcached-operator/controllers/memcached_controller_test.go#L74-L105 does the controller reconcile to make the necessary changes. In this particular suite, as you mentioned the reconciler does not run continuously and queue in the events, but we instead verify whether the current state of CR is as expected after running one cycle of reconcile.  

If you would like to run the reconciler continuously, you would have to start the manager in a separate go routine since it is blocking. The manager would in turn run the reconciler and queue in the events from the objects which are being watched as it happens in a real scenario. Here is an example on how to do same: https://github.com/kubernetes-sigs/kubebuilder/blob/master/docs/book/src/cronjob-tutorial/testdata/project/internal/controller/suite_test.go#L146. An extensive documentation on writing e2e tests is here: https://book.kubebuilder.io/cronjob-tutorial/writing-tests.html

**Comment by varshaprasad96** [comment]
@hellt Your question was how to continue running the "reconciler", by which I mean you want to run a controller continuously such that an events are continuously getting processed. To be able to do so, you would have to run the "manager", as we do in `[main.go`](https://github.com/operator-framework/operator-sdk/blob/e859a564c81b2415a6e026b7d5a31be04448f235/testdata/go/v4-alpha/memcached-operator/cmd/main.go#L116).

If that was not your question, and instead you would like to wait for the result of just the first reconcile result then you could use `eventually`.
