### ISSUE TITLE
Add command line option to upgrade k8s dependencies when bumping SDK version

### ISSUE THREAD

**Issue by aravindhp** [operator-framework/operator-sdk#638]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Today if an operator author has to bump the SDK version in their operator project there is no way to automatically update the k8s dependencies in `Gopkg.toml`. Instead we have to manually copy the `Gopkg.toml` from the SDK [source code](https://github.com/operator-framework/operator-sdk/blob/8f0fe6975128d3670e92e0509c645d80657a6d68/Gopkg.toml#L9-L23).  

**Describe the solution you'd like**
Add a command line option like `operator-sdk update <version>` or something to that effect to help the operator author update their Gopkg.toml. 

/cc @hasbro17

**Comment by hasbro17** [comment]
It would be hard to support updating to any desired version(plus not sure that's useful since you wouldn't want to update to `v0.0.6` if say you're using the binary for `v0.0.7`).

Like you suggested the simplest thing to do is to regenerate the existing Gopkg.toml file from the binary(like we do in `operator-sdk new`) and run dep ensure.
The only issue with overwriting the existing Gopkg.toml file is the user might have added other constraints that would be removed by overwriting the file.
For e.g https://github.com/operator-framework/operator-marketplace/blob/master/Gopkg.toml#L63-L70

I don't think the `dep` CLI supports modifying constraints in Gopkg.toml to a specific version/branch/revision. You have to do it manually. So we might have to parse and update only what's needed.

**Comment by shawn-hurley** [comment]
I was thinking about this, and I don't see a good way of doing this that will not be a constant source of bugs and frustration. We also have to keep in mind that [modules](https://github.com/golang/go/wiki/Modules) will eventually be here and we probably want to support them. 

I think the best solution here might be better documentation. A table that says X version of the SDK expects  Y version of controller-runtime and so on. This would allow for 2 things. 
1. Not having to manage this file after creation, which I think would be painful.
2. If I as user X believe I can use Z version of controller-runtime and would like to and I manage my dependencies my self, the SDK won't overwrite this or stop me. Any issues that arise from this are on the user as it is not what we were expecting. 

Thoughts, am I over thinking this?

**Comment by shawn-hurley** [comment]
I really like the idea of print-deps. Following on what do you think of having it be pretty print first somthing like:
```bash
Name								Version
sigs.k8s.io/controller-runtime		v0.1.4
```

and then a flag that will ouput it in gopkg.toml format? 
```
[[constraint]]
  name = "sigs.k8s.io/controller-runtime
  version = "v0.1.4"
```
