### ISSUE TITLE
does leader for life require cluster role permissions ?

### ISSUE THREAD

**Issue by kaushiksrinivas** [operator-framework/operator-sdk#6431]
Hi,
We are trying to enable leader election in the operator sdk framework with mode "leader for life".
But we observe this path requires access to "nodes" in the k8s cluster. This internally asks for cluster role permissions for the operator deployment.

See here, 
https://github.com/operator-framework/operator-lib/blob/main/leader/leader.go

line 189 is looking for the "nodes" status. 
In our case, the operator is run "without clusterRole" access. And in non leader pods, this func isNotReadyNode at line 189 is logging failure to "get nodes" due to lack of privileges. But the pods are not crashing.

Do we need cluster role access to run the deployment of operator with "leader for life" mode enabled ?
Also, does "leader with lease" also require cluster role permissions ?

**Comment by kaushiksrinivas** [comment]
@camilamacedo86 
Can you support us  please ?

**Comment by varshaprasad96** [comment]
By looking at the codebase for leader-for-life, it seems like we are checking the status of the node on which the pod is scheduled before declaring the leader election to be complete. The controller in this case, needs to have the necessary cluster level permissions to be able to "get" the node on which the pod is running.

In case of leader-for-lease, afaik cluster level permissions are not required. The controller-runtime leader election codebase is based out of client-go wherein we use [Lease](https://github.com/kubernetes/client-go/blob/2a5f18df73b70cb85c26a3785b06162f3d513cf5/examples/leader-election/main.go#L110) object to determine the leader.  "Leases" are namespace scoped. The controller would require necessary permissions scoped to particular namespaces for being able to fetch ("get"/"list") and watch the resource locks. 

Also to note, it is suggested to use leader for lease rather than leader for life approach, since the former is accepted upstream (k8s and controller-runtime) and Operator SDK by default does not support the same.
