### ISSUE TITLE
How many controllers can an operator support at most?

### ISSUE THREAD

**Issue by AllenZMC** [operator-framework/operator-sdk#6445]
How many controllers can an operator support at most?

**Comment by varshaprasad96** [comment]
@AllenZMC There is no hard and fast rule. The number of controllers in an operator is a variable that depends on many factors. It greatly depends on the computational resources available for the Operator to run on K8s cluster and also on how efficiently the reconciler logic is implemented. To note, the k8s clusters can also be scaled horizontally by adding more worker nodes to distribute the workload, and this can be one of ways to support more number of controllers.

There is no definitive answer for this question. To find the optimal number for your environment, I'd suggest running performance tests and monitoring the consumption of CPU and memory resources.

In order to refer to best practices on when to have separate operators for controllers for an application, you could take a look at this [documentation](https://sdk.operatorframework.io/docs/best-practices/best-practices/).

**Comment by AllenZMC** [comment]
Thanks  @varshaprasad96
