### ISSUE TITLE
operator-sdk by default introduces a "vulenrable" version of `golang.org/x/net`

### ISSUE THREAD

**Issue by RiRa12621** [operator-framework/operator-sdk#6543]
a default installation, that follows the quickstart, will use a vulnerable version of golang.org/x/net and (if set up) dependabot will complain about it.

To Replicate

```
$ operator-sdk version
operator-sdk version: "v1.31.0", commit: "e67da35ef4fff3e471a208904b2a142b27ae32b1", kubernetes version: "v1.26.0", go version: "go1.20.6", GOOS: "darwin", GOARCH: "arm64"

$ operator-sdk init --domain some.io --repo github.com/rira12621/someOperator
$ git add .
$ git commit -m 'some commit'
$ git push
```

Result:

![Screenshot 2023-08-14 at 10 34 20](https://github.com/operator-framework/operator-sdk/assets/14996407/b7f3d436-4846-43a6-9f39-8dcc8dabb331)

**Comment by varshaprasad96** [comment]
Since this is an indirect dependency, a quick look results in:
```
➜  memcached-operator git: go mod why -m golang.org/x/net
# golang.org/x/net
github.com/example/memcached-operator/api/v1alpha1
github.com/example/memcached-operator/api/v1alpha1.test
k8s.io/client-go/rest
golang.org/x/net/http2
```

And looks like k8s.io/client-go is using an older version of this module: https://github.com/kubernetes/client-go/blob/e7cd4ba474b5efc2882e377362c9aa8b407428d9/go.mod#L22

This gets fixed if we bump the k8s dependencies to the latest minor release, probably 0.26.7: https://github.com/kubernetes/client-go/blob/30088cdd7e8d70b3000586d4e9e42e50684359ca/go.mod#L22

However, the scaffolding version of these deps in go plugins, needs to be fixed upstream in Kubebuilder. This issue relates to: https://github.com/operator-framework/operator-sdk/issues/6540

**Comment by theishshah** [comment]
Closing as this is duplicated in #6450
