### ISSUE TITLE
Helm operator multiple versions handling

### ISSUE THREAD

**Issue by juldrixx** [operator-framework/operator-sdk#6555]
## Type of question

How to implement a specific feature 

## Question

I want to implement an Helm operator that manages multiple version of a same chart but I'm facing an issue when creating a new version of api.

I'm initializing my project with:
```sh
operator-sdk init --plugins helm --domain test.com
```

then I add the first version of the chart:
```sh
operator-sdk create api --helm-chart chart-v1.tgz --group chart --version v1
```

But when I the second version of the chart:
```sh
operator-sdk create api --helm-chart chart-v2.tgz --group chart --version v2
```

I get an error because the crd already exists:
```sh
failed to create API: unable to scaffold with "base.helm.sdk.operatorframework.io/v1": error scaffolding APIs: failed to create config/crd/bases/chart.test.com_chart.yaml: file already exists
```

How I'm suppose to do it?

**Comment by varshaprasad96** [comment]
Since the question relates to multiple versions of the same chart, I'm assuming that you would like to create multiple-version project. In a multi group scenario, you need not use the create command again, but can add the new directory for the next version directly. Here is an in-depth tutorial to do so: https://book.kubebuilder.io/multiversion-tutorial/tutorial.html?highlight=multi#tutorial-multi-version-api. You may have to accordingly change the CRD generators, and mark one of them as stored version as mentioned in the documentation.

In case you are looking for multi-group support, wherein using creating multiple GVKs is possible by running `create api` command again, you can follow the tutorial here: https://book.kubebuilder.io/migration/multi-group.html?highlight=multi#single-group-to-multi-group

**Comment by varshaprasad96** [comment]
@juldrixx we are closing this issue. Please feel free to reopen if you think that the solution does not address your concerns. Thank you!
