### ISSUE TITLE
SA generated by operator-sdk does not contain the automountServiceAccountToken required for CNF cert

### ISSUE THREAD

**Issue by tkrishtop** [operator-framework/operator-sdk#6563]
## Bug Report

Some RH Telco partners utilize operator-sdk to create operators for later [CNF certification](https://github.com/test-network-function/cnf-certification-test/). CNF certification requires that operator service accounts **explicitly** [disable API credential automounting as a recommended practice](https://github.com/test-network-function/cnf-certification-test/blob/459b6a40074d7355e501c0f12d4d171038df50c0/cnf-certification-test/accesscontrol/rbac/automount.go#L46). The problem is that service accounts created by operator-sdk lack the `automountServiceAccountToken: false` setting, causing them to fail this requirement. 

```
{"ObjectType":"Pod","ObjectFieldsKeys":
["Reason For Non Compliance","Namespace","Pod Name"],
"ObjectFieldsValues":
["serviceaccount XXX-YYY-agents:XXX-lYYY-agents-controller-manager is not configured 
with automountServiceAccountToken set to false, 
impacting pod XXX-YYY-agents-controller-manager-86d746fbdd-fkg7b",
"XXX-YYY-agents","XXX-YYY-agents-controller-manager-86d746fbdd-fkg7b"]}
```

In simple terms, operator-sdk doesn't generate CNF-compliant operators.

#### What did you do?

I initiated the helm-operator and verified that the Service Account does not contain `automountServiceAccountToken: false` as follows:

```
$ cd nginx-operator/
$ operator-sdk init --plugins helm --domain example.com --group demo --version v1alpha1 --kind Nginx

$ cat config/rbac/service_account.yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nginx-operator
    app.kubernetes.io/part-of: nginx-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
```

#### What did you expect to see?

I expected the `automountServiceAccountToken: false` line to be automatically added during the generation of the operator's SA by operator-sdk, like this:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
automountServiceAccountToken: false
...
```

#### What did you see instead? Under which circumstances?

Instead, we have an SA without the `automountServiceAccountToken: false` line, and our partners must manually add this line to all operators generated with operator-sdk, in order to pass the CNF certification.

#### Environment

**Operator type:**

/language go
/language ansible
/language helm

**Kubernetes cluster type:**

`$ operator-sdk version`

1.31.0

#### Possible Solution

Adding this line to the [SA template](https://github.com/search?q=repo%3Aoperator-framework%2Foperator-sdk+%22kind%3A+ServiceAccount%22&type=code) should be a straightforward solution:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
automountServiceAccountToken: false
...
```

**Comment by acornett21** [comment]
@tkrishtop If this is added to `config/rbac/service_account.yaml` does the bundled SA look correct and get applied correctly when the operator is installed in a cluster? I would think there is more work then just updating the SA.

**Comment by acornett21** [comment]
To shed a little more light on this, the SA that is in the `config/rbac` directory is never created in the bundle folder, the below code excludes it:

https://github.com/operator-framework/operator-sdk/blob/master/internal/generate/collector/clusterserviceversion.go#L126

If the above code was changed to include all ServiceAccounts in the bundle and the operator developer added kustomize to update the service account properly, `operator-framework-api` would then throw an error saying this SA is not allowed in the bundle, see below:

https://github.com/operator-framework/api/blob/master/pkg/validation/internal/bundle.go#L63-L70

I'm not sure why this SA is **not included** in the bundle, probably because OLM is creating this SA based on the info in the CSV this is just speculation on my part. This means that operator developers can't customize the SA for their controller. Unless there is some other approach that they are supposed to follow, if so we should document the proper approach, as all we have now is `--extra-service-account` flag, but that is for another use case entirely.
