### ISSUE TITLE
Add annotations to CSV required for community operator acceptance

### ISSUE THREAD

**Issue by chipzoller** [operator-framework/operator-sdk#6576]
#### Describe the problem you need a feature to resolve.
When using operator SDK (v1.31 used) to build a community operator for submission to redhat-openshift-ecosystem/community-operators-prod, it is missing the following [required (or recommend) annotations](https://github.com/operator-framework/community-operators/blob/master/docs/packaging-required-fields.md#required-fields-for-operatorhub).

* categories
* containerImage
* support
* repository
* description

And `spec.icon` is empty by default which is also a requirement.

If an operator built with operator SDK by performing an `init` is submitted to the community operator repo, it will fail for required CI checks due to these omissions.

#### Describe the solution you'd like.

It would be extremely nice if operator SDK would either include these fields by default (first preference), or when performing `make bundle` they are prompts added to the current list of prompts asked of a user with a note specifying that in some cases they may be required.

**Comment by varshaprasad96** [comment]
The requirements could differ in different situations. Which is why we are skeptical on adding these annotations by default to the SDK scaffolding. We would recommend using kustomize patches to add these annotations, or adding them to the scaffolded bases should also work. 

@chipzoller closing this issue for now, please feel free to reopen if you feel otherwise. Thank you!

**Comment by chipzoller** [comment]
I respect the decision, however I think because this is such a common destination for operators you could at least build in something in the Makefile and allow users to opt in.

In any case, this issue should be closed as not planned rather than completed if you do not intend on implementing it.

**Comment by varshaprasad96** [comment]
@chipzoller These annotations are useful, but not a necessity, and eventually it would be difficult for us to cater to all the scenarios. The major reason for introducing Kustomize for building bundles was exactly this, to allow customizations in bundles, so that an operator author can extend it for different needs. Which is why we have the generic `kustomize build` command in place, and the users can inject any kind of kustomize generators/patches in their files.

**Comment by chipzoller** [comment]
According to the latest directions in the PR template, the annotations are required. I understand the Kustomize angle I'm just suggesting the user experience could be a bit better by at least informing users that the output of this SDK isn't sufficient for Red Hat's community needs.
