### ISSUE TITLE
Tutorial and install docs don't work well.

### ISSUE THREAD

**Issue by schichtnudelauflauf** [operator-framework/operator-sdk#6589]
### What is the URL of the document?

https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/
https://sdk.operatorframework.io/docs/installation/

### Which section(s) is the issue in?

Create new API
and install itself

### What needs fixing?

Create new API:
The thing requires "make" which is not in default install of many distros.
It fails in an annoying way because it already creates a resource in kubernetes but fails the go stuff.
If you call the command
'' $ operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller) ''
again it will fail because it exists.
--force will override that and its kinda obvious but its annoying.

Install itself:
There is also a prebuilt package for Archlinux.

#### Additional context

None

**Comment by varshaprasad96** [comment]
@schichtnudelauflauf Having GNU `make` installed is usually a common practice and is implied that any operator author would be having it which is why it is not explicitly mentioned. But if that's the case otherwise, please feel free to submit a PR that adds it to the documentation. 

```
'' $ operator-sdk create api --group cache --version v1alpha1 --kind Memcached --resource --controller) ''
again it will fail because it exists.
```
Regarding this, it is expected from SDK to fail when a user tries to create an API which already exists and is being tracked in the [PROJECT](https://sdk.operatorframework.io/docs/overview/project-layout/#common-base) file.
