### ISSUE TITLE
Ansible Operator Proxy Injects Owner Reference Across Namespaces

### ISSUE THREAD

**Issue by cpitman** [operator-framework/operator-sdk#659]
## Bug Report

**What did you do?**
Created an ansible operator that uses Cluster scoped CRDs and creates a namespace and resources in that namespace.

As an example, here is a custom resource. Note that it is not in a namespace:

```
apiVersion: cop.redhat.com/v1alpha1
kind: ProjectPipeline
metadata:
  clusterName: ""
  creationTimestamp: 2018-10-22T01:51:40Z
  finalizers:
  - project-pipeline-cleanup
  generation: 1
  name: example-projectpipeline
  namespace: ""
  resourceVersion: "416544"
  selfLink: /apis/cop.redhat.com/v1alpha1/projectpipelines/example-projectpipeline
  uid: 04c93942-d59d-11e8-9408-080027de4dc4
spec:
  friendlyName: An Example Project Pipeline
```

And here is a namespace RoleBinding, with a meaningless OwnerReference that kubernetes seems to ignore for now:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: 2018-10-23T17:59:55Z
  name: jenkins_edit
  namespace: example-projectpipeline-dev
  ownerReferences:
  - apiVersion: cop.redhat.com/v1alpha1
    kind: ProjectPipeline
    name: example-projectpipeline
    uid: df036778-d6eb-11e8-afe3-08002724fbb6
  resourceVersion: "102038"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/example-projectpipeline-dev/rolebindings/jenkins_edit
  uid: 726f5e69-d6ed-11e8-afe3-08002724fbb6
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: jenkins
```

**What did you expect to see?**
No owner reference, since owner references only work if both objects are in the same namespace.

**What did you see instead? Under which circumstances?**
An invalid ownerReference to a resource in another/no namespace

**Environment**
* operator-sdk version: f7a8fd3

* Kubernetes version information:
```
oc v3.9.0+191fece
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth

Server https://192.168.99.101:8443
openshift v3.10.0+456651d-57
kubernetes v1.10.0+b81c8f8
```

* Kubernetes cluster kind: minishift

* Are you writing your operator in ansible or go? Ansible

**Comment by mhrivnak** [comment]
Thanks for this report.

I suspect it will be sufficient to fix this by adding this logic to the proxy:

_"If the resource being created is not in the same namespace as the one specified in the owner reference, do not add an owner reference."_

Anyone have feedback on that?

**Comment by chancez** [comment]
@mhrivnak That would be correct, but it should probably be logging a warning in cases like that as it means that there could be bugs in the operator if it's relying on ownerRefs for deletion, but they cannot be applied.

**Comment by mhrivnak** [comment]
I would just hesitate to log a warning in case there's a chance that an operator author will deliberately want this behavior, which seems reasonably likely. End users don't like to see warnings in their logs that they can't do anything about, and eventually some of those users open support cases to figure out what's "broken".

**Comment by chancez** [comment]
This behavior being deliberate is a bug. There are really bad bugs OLM team has experienced from cross-namespace ownerReferences. It would be desirable for users to open support cases if it came up as it would indicate a serious bug.

**Comment by mhrivnak** [comment]
Maybe we're talking about different things. The reporter of this issue made an operator that creates resources in a different namespace from the CR (since in this case, the CR does not have a namespace at all). I'm saying in that case, our proxy should not try to auto-create an owner reference, and it should also not log a warning. It seems like a valid use case, and I'm not sure what would merit a warning or be a bug in that case. Do you see a problem with that use case?

**Comment by shawn-hurley** [comment]
Hey folks,

The first pr: #1148 and #1153 fixes and fixed this issue.

I am thinking that we should make a debug level 2 warning that this is happening and that a user needs to use a finalizer to clean up after itself. I also believe that we need to add an entire doc around this issue in the SDK. This is not just a problem with ansible operators but anyone writing an operator. 

@chancez @mhrivnak Does that make sense to you?

**Comment by mhrivnak** [comment]
If something gets created without an owner ref, and the CR doesn't have a finalizer, that would be good to communicate about to the developer. Perhaps the scorecard would be the best place for that.

As for logging, I like debug level better than warning since it's less likely to cause undue alarm. In a case where an operator really does have a use case for leaving a resource behind after the CR is deleted, asking them to have a finalizer to silence the debug message isn't a lot to ask.

**Comment by chancez** [comment]
I would expect it quite difficult to determine this behavior in the scorecard system, which is why I suggested logging it. Debug seems fine, but if the default log level omits it then new developers may not find this until later. 

I would expect that they would need to opt out of logging this rather than opt into making it visible. Putting it into debug and having a default level of info just means the user may not find out about their broken deletion handling until after it's been developed. I would expect it to be visible by default, and the developer would need to add code explicitly to silence such an error message, otherwise they may never even see it.

**Comment by shawn-hurley** [comment]
Just want to clarify the work that still needs to be done on this issue:

1. We need to add an info log, that mentions that resource XXX will not have an owner reference and therefore will need to be cleaned up.
2. We need to write a really good summary of the rules of this system in a user doc.
