### ISSUE TITLE
Please add v1.32.0 to Upgrade SDK Version guidance

### ISSUE THREAD

**Issue by DazWilkin** [operator-framework/operator-sdk#6597]
The Operator SDK is at release [v1.32.0](https://github.com/operator-framework/operator-sdk/releases/tag/v1.32.0) but the documentation trails [Upgrade SDK Version](https://v1-30-x.sdk.operatorframework.io/docs/upgrading-sdk-version/) has [v1.30.0](https://v1-30-x.sdk.operatorframework.io/docs/upgrading-sdk-version/v1.30.0/) as the latest.

I appreciate the assurance implicit in the upgrade guidance (even if only "There are no migrations for this release! 🎉").

Please add v1.32.0 to Upgrade SDK Version guidance

**Comment by everettraven** [comment]
@DazWilkin thanks for raising this issue! Looking at the link you shared for the "Upgrade SDK Version" that points to the documentation subdomain specifically for the v1.30.z releases: https://v1-30-x.sdk.operatorframework.io/docs/upgrading-sdk-version/

The v1.32.0 and v1.31.0 migration guides should be present at: https://sdk.operatorframework.io/docs/upgrading-sdk-version/

I'm going to close this issue since it seems to be a link mix-up, but if you feel this has been closed in error please feel free to reopen this issue
