### ISSUE TITLE
SDK not compatible with controller-runtime v0.16.2

### ISSUE THREAD

**Issue by bodji** [operator-framework/operator-sdk#6608]
## Bug Report

The SDK init generates code that is not working with controller-runtime v0.16.2

```
# command-line-arguments
cmd/main.go:71:3: unknown field MetricsBindAddress in struct literal of type manager.Options
cmd/main.go:72:3: unknown field Port in struct literal of type manager.Options
```

This commit removed MetricsBindAddress in manager.Options : 
https://github.com/kubernetes-sigs/controller-runtime/commit/e59161ee8f41b2f24953419533dca84d30262c21

#### What did you do?
```
$ operator-sdk init --domain xxx.tld --repo xxx --plugins go/v4-alpha .
```

Then, I added an external CRD from Prometheus operator.

The prometheus operator has a dependency on controller-runtime v0.16.2  : 
https://github.com/prometheus-operator/prometheus-operator/blob/main/go.mod#L44

#### Environment

- Operator SDK version : `operator-sdk version: "v1.32.0", commit: "4dcbbe343b29d325fd8a14cc60366335298b40a3", kubernetes version: "1.26.0", go version: "go1.19.13", GOOS: "darwin", GOARCH: "arm64"
`
- Platform : Mac OS
- Architecture : darwin-arm64

**Comment by everettraven** [comment]
Hi @bodji - thanks for raising this issue! This is likely because we haven't yet upgraded the Operator-SDK to work with the kubernetes 1.28 libraries that controller-runtime v0.16.z looks to be based on. The work to enable Kubernetes 1.28 support is tracked in #6554 

The appropriate workaround for now would be to manually update your dependencies and resolve any necessary conflicts.

**Comment by bodji** [comment]
I see :)

Ok, I can remove MetricsBindAddress and Port from the generated code then :)

Thank you very much for your quick answer !

**Comment by varshaprasad96** [comment]
Closing this issue, since #6554 is tracking the required changes.
