### ISSUE TITLE
Operator SDK + Kubebuilder compatibility matrix

### ISSUE THREAD

**Issue by przemolb** [operator-framework/operator-sdk#6776]
Hello,

in the company I work for there is a strict process required to approve a new software (including Open Source).
The process also applies if we want to use a new version of already approved software. And you can imagine it takes time and effort so you do that if it is absolutely necessary.
We got specific versions of Operator SDK and Kubebuilder approved. But since then there are a few new releases of both.
I would like to start the internal process again for the latest Operator SDK but I am not sure which Kubebuilder is supported in this release.
Is there any compatibility matrix showing which version of Kubebuilder is supported by particular Operator SDK release ?

**Comment by acornett21** [comment]
Hi @przemolb This information can be found in the `mod` file for any given `tag` which corresponds to any given released. For example `1.35.0` can be found [here](https://github.com/operator-framework/operator-sdk/blob/v1.35.0/go.mod#L46). Hope this helps!

**Comment by przemolb** [comment]
Thanks @acornett21 .
I guess it is an exact version and not the highest or lowest version supported ?

**Comment by acornett21** [comment]
Correct, each version of Operator SDK points to one version of Kubebuilder, since Kubebuilder is being used as a library. 

Though I'm not sure why your organization would need to know this level of dependencies, since you'd have to look at every library that is used but Operator SDK (or any Open Source software for that matter) and also get those approved, if that is truly the case.
