### ISSUE TITLE
Ansible operator-sdk up local --kubeconfig flag does not work

### ISSUE THREAD

**Issue by yanirq** [operator-framework/operator-sdk#700]
## Bug Report

**What did you do?**
Trying to run the Ansible operator sdk in local mode with a custom config file in some variations:
```
operator-sdk up local --kubeconfig "/home/user/myconfigfolder" (folder)
operator-sdk up local --kubeconfig "/home/user/myconfigfolder/config"  (file)
operator-sdk up local --kubeconfig /home/user/myconfigfolder/config 
operator-sdk up local --kubeconfig="/home/user/myconfigfolder/config"
operator-sdk up local --kubeconfig=/home/user/myconfigfolder/config
```

**What did you expect to see?**
Running the ansible operator in local mode should have detected the file and start.

**What did you see instead? Under which circumstances?**
The default path is always used ( ~/.kube/) with no message indicating why 

**Environment**
* operator-sdk version:

ee6eee63682b881fa899a4da74715fb2ec4039f3

* Kubernetes version information:

kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://127.0.0.1:8443
openshift v3.10.0+456651d-57
kubernetes v1.10.0+b81c8f8

* Are you writing your operator in ansible or go?
ansible

**Additional context**
WA for this problem was to copy the custom config and replace it in the default folder  ~/.kube/

**Comment by hasbro17** [comment]
@shawn-hurley So that would mean:
```sh
$ operator-sdk up local --operator-flags="--kubeconfig=<path-to-kubeconfig>"
```

Isn't that more verbose than if we just keep:
```sh
$ operator-sdk up local --kubeconfig=<path-to-kubeconfig>
```
and set the  `KUBECONFIG` env var like we do for the Go type.
https://github.com/operator-framework/operator-sdk/blob/master/commands/operator-sdk/cmd/up/local.go#L121

`--kubeconfig` is an implicit flag in the runtime. I think `--operator-flags` is probably better suited for flags explicitly defined by the user for their operator.

**Comment by estroz** [comment]
#705 fixes this issue.
