### ISSUE TITLE
The entire object metadata should be passed to the reconcile loop handler

### ISSUE THREAD

**Issue by pharwalk** [operator-framework/operator-sdk#709]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I have an issue when handling delete events. I need some metadata that is present in the Custom Resource but since we get the name and namespace information only , there is no way to access it as the object is already deleted.

**Describe the solution you'd like**

Send the complete Object as you used to in version 0.0.7 of the sdk.

**Comment by hasbro17** [comment]
@pharwalk If you need to do some cleanup that relies on your CR's metadata then the correct way to do that would be Finalizers.
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers

You can set a Finalizer for your CR when you create it so that the CR object won't be deleted but will only have the deletion timestamp field set. 
With the CR object still around you can inspect it, get the metadata and do any necessary cleanup before clearing the CR's `metadata.finalizers` field which will cause it to get garbage collected.

**Comment by pharwalk** [comment]
> @pharwalk If you need to do some cleanup that relies on your CR's metadata then the correct way to do that would be Finalizers.
> https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#finalizers
> 
> You can set a Finalizer for your CR when you create it so that the CR object won't be deleted but will only have the deletion timestamp field set.
> With the CR object still around you can inspect it, get the metadata and do any necessary cleanup before clearing the CR's `metadata.finalizers` field which will cause it to get garbage collected.

I see. Let me explore that.Thank you!
