### ISSUE TITLE
Build command could support updating operator.yaml

### ISSUE THREAD

**Issue by gtseres** [operator-framework/operator-sdk#769]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Following the instructions displayed [here](https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#1-run-as-a-deployment-inside-the-cluster), I saw that there are two separate steps
1. `operator-sdk build <image>`
2. Update `operator.yaml` with the image from step 1

**Describe the solution you'd like**
The `operator-sdk` build could take a flag for automatically updating the image name from step 1 to the `operator.yaml`, so that step 2 will not be needed. If it makes sense, this could be the default behaviour as well.

**Comment by hasbro17** [comment]
Originally we were overwriting the entire operator.yaml file. https://github.com/operator-framework/operator-sdk/issues/84
We obviously don't want to go back to that.
And adding a more sophisticated templating solution for updating the operator.yaml file doesn't seem worth the complication vs letting users just manage that file themselves.

However we could add an optional flag e.g `--update-deployment` to only update the deployment image field for `deploy/operator.yaml`.
And if `deploy/operator.yaml` is using multiple images fields then the cmd should just fail.

**Comment by hasbro17** [comment]
Recently in issues like #890 we've agreed not to add more flags to the CLI commands just to make one time updates to the deployment manifests.
It's much simpler for users to do that, rather than the SDK trying to cover every case and risk ballooning the number of CLI commands and options.

The exception being the CRD manifests which are generated from their Go types and comment tags.
