### ISSUE TITLE
Operator-sdk new action does not support "kind" flag

### ISSUE THREAD

**Issue by aaronmcohen** [operator-framework/operator-sdk#856]
The Operator new action help indicates that we can specify the `kind` flag during project creation

operator-sdk  new --help
> The operator-sdk new command creates a new operator application and 
> generates a default directory layout based on the input <project-name>. 
> 
> <project-name> is the project name of the new operator. (e.g app-operator)
> 
> For example:
> 	$ mkdir $GOPATH/src/github.com/example.com/
> 	$ cd $GOPATH/src/github.com/example.com/
> 	$ operator-sdk new app-operator
> generates a skeletal app-operator application in $GOPATH/src/github.com/example.com/app-operator.
> 
> Usage:
>   operator-sdk new <project-name> [flags]
> 
> Flags:
>       --api-version string   Kubernetes apiVersion and has a format of $GROUP_NAME/$VERSION (e.g app.example.com/v1alpha1)
>       --cluster-scoped       Generate cluster-scoped resources instead of namespace-scoped
>       --generate-playbook    Generate a playbook skeleton. (Only used for --type ansible)
>   -h, --help                 help for new
>       **--kind string          Kubernetes CustomResourceDefintion kind. (e.g AppService)**
>       --skip-git-init        Do not init the directory as a git repository
>       --type string          Type of operator to initialize (e.g "ansible") (default "go")
> 

However when the `kind` flag is used I get the following error
> FATA[0000] go type operator does not use --api-version or --kind. Please see "operator-sdk add" command after running new.

**Comment by hasbro17** [comment]
@aaronmcohen The `--api-version` and `--kind` flags are only supported for the ansible and helm type projects.
https://github.com/operator-framework/operator-sdk/blob/master/doc/ansible/user-guide.md#create-a-new-project
https://github.com/operator-framework/operator-sdk/blob/master/doc/helm/user-guide.md#create-a-new-project

I purposefully didn't support it for the default Go type operator project because I wanted new users to explicitly go through the step of `add api --kind=<kind> --version=<version>` to understand what gets scaffolded for defining a new API.
https://github.com/operator-framework/operator-sdk/blob/master/doc/user-guide.md#add-a-new-custom-resource-definition

@shawn-hurley I know you've mentioned unifying the experience before for all 3 cmds and support it for the Go operator as well. Or we could clarify that those two flags are only for the non-go project type.

**Comment by aaronmcohen** [comment]
Thank you for the quick response. My vote is to simply clarify that those two flags are only for the non-go project type.
