### ISSUE TITLE
Scaffolding cluster scoped CRDs

### ISSUE THREAD

**Issue by sslavic** [operator-framework/operator-sdk#890]
## Feature Request
operator-sdk currently (v0.3.0) supports scaffolding namespaced CRDs only. Please support scaffolding cluster scoped CRDs too. Btw kubebuilder supports it and rationale is somewhat documented on http://kubebuilder.netlify.com/basics/what_is_a_resource.html#namespaces

For consistency with already supported scaffolding of cluster wide watching operators (via `--cluster-scoped` switch in `operator-sdk new` command), scaffolding of cluster scoped CRDs should probably also be supported with similar `--cluster-scoped` switch for `operator-sdk add api` command.

**Comment by joelanford** [comment]
Thanks for the feature request. This should be do-able and pretty straightforward for Go operators. As you mentioned, we can likely add a `--cluster-scoped` flag for `operator-sdk add api` and `operator-sdk add crd`.

If I understand correctly, a cluster-scoped CRD only makes sense in the context of a cluster-scoped operator, so we'll need to add an extra check when creating cluster-scoped CRDs to make sure that's the case.

There's a catch with the Ansible and Helm operator scaffolding though. Since they require that `--api-version` and `--kind` be passed to `operator-sdk new`, there's an ambiguity in the meaning of the `--cluster-scoped` flag in those cases. Right now, it would be semantically equivalent to `--cluster-scoped-operator`.

So we have a few options:
1. Split the flags out. We would:
  a. Change the `operator-sdk new` `--cluster-scoped` flag to `--cluster-scoped-operator` for all operator types.
  b. Add `--cluster-scoped-crd` to `operator-sdk add api` and `operator-sdk add crd`
  c. Add `--cluster-scoped-crd` to `operator-sdk new`, but error out unless `--type` is `ansible` or `helm`
2. Allow `--api-version` and `--kind` for Go operators (and do 1a and 1b)
3. Remove `--api-version` and `--kind` for Ansible and Helm operators for `operator-sdk new`, thus removing the ambiguity of `--cluster-scoped`

@shawn-hurley I know you've said in the past that 3) is not a great option for Ansible operators because having the one-shot command is important to the Ansible operator workflow. Is that still the case?

Thoughts on this @hasbro17?

**Comment by joelanford** [comment]
There's also potentially changes to be made in the Helm and Ansible operator code, as they likely have built-in assumptions about namespace-scoped CRDs.

**Comment by shawn-hurley** [comment]
Assuming that the `WATCH_NAMESPACE` env var is set correctly, I don't believe there should be any issues from the ansible side.

**Comment by matihost** [comment]
ansible-operator  seems handling v0.4.0 `Cluster` wide CR
However 
`operator-sdk new foo-operator --cluster-scoped --api-version=foo.bar.com/v1alpha1 --kind=FooBar --type=ansible --skip-git-init --generate-playbook`
still creates CRD object sample with 'Namespaced` scope.

**Comment by xcoulon** [comment]
> ansible-operator seems handling v0.4.0 `Cluster` wide CR
> However
> `operator-sdk new foo-operator --cluster-scoped --api-version=foo.bar.com/v1alpha1 --kind=FooBar --type=ansible --skip-git-init --generate-playbook`
> still creates CRD object sample with 'Namespaced` scope.

I believe there is the same issue with the `go` generator when using the SDK v0.5.0:
```
$ operator-sdk new podset-cluster-operator --cluster-scoped
$ operator-sdk add crd --api-version=app.example.com/v1alpha1 --kind=AppService
$ cat deploy/crds/app_v1alpha1_appservice_crd.yaml | grep scope 
  scope: Namespaced
```
The scope of the CRD is `Namespaced`.

**Comment by hasbro17** [comment]
Just going to sum up some offline discussion on the plan for supporting cluster scoped crds and how it impacts the CLI so everyone's on the same page and we can discuss any drawbacks/assumptions to the proposed approach.

We can have two flags instead of one as @joelanford suggested above in option 1
- `--cluster-scoped-operator`: 
    - scaffolds an operator to watch all namespaces(`WATCH_NAMESPACE =""`) 
    - scaffolds ClusterRole in `deploy/role.yaml` and ClusterRoleBinding in `deploy/rolebinding.yaml`
- `--cluster-scoped-crd`:
    - only sets `scope: Cluster` for the generated CRD manifest.

Because a `--cluster-scoped-crd` implies that an operator needs a ClusterRole/ClusterRoleBinding there's a few different ways these flags can be used with `operator-sdk new` `operator-sdk add api` and `operator-sdk add crd`.

### Go operator
```bash
# Allowed
$ operator-sdk new <operator-name>

# Allowed
$ operator-sdk new <operator-name> --cluster-scoped-operator

# Not allowed/Error out
$ operator-sdk new <operator-name> --cluster-scoped-crd

# Allowed, print a warning if a ClusterRole is not found in deploy/role.yaml
$ operator-sdk add api --cluster-scoped-crd --api-version=<api-version> --kind=<kind>

# Allowed, print a warning if a ClusterRole is not found in in deploy/role.yaml
$ operator-sdk add crd --cluster-scoped-crd --api-version=<api-version> --kind=<kind>
```

### Helm/Ansible operator
```bash
# Allowed
$ operator-sdk new <operator-name> --type=<ansible/helm> --cluster-scoped-operator --api-version=<api-version> --kind=<kind>

# Not allowed/Error out. Without scaffolding a ClusterRole the operator can't use the cluster scoped crd
$ operator-sdk new <operator-name> --type=<ansible/helm> --cluster-scoped-crd --api-version=<api-version> --kind=<kind>

# Allowed, --cluster-scoped-crd requires --cluster-scoped-operator
$ operator-sdk new <operator-name> --type=<ansible/helm> --cluster-scoped-crd --cluster-scoped-operator --api-version=<api-version> --kind=<kind>

# Allowed, print a warning if a ClusterRole is not found in in deploy/role.yaml
$ operator-sdk add crd --cluster-scoped-crd --api-version=<api-version> --kind=<kind>
```

@xcoulon @joelanford @shawn-hurley
Thoughts on if we're in agreement on how to handle some of these cases where a `cluster-scoped-crd` requires the correct RBAC to be scaffolded. And if the combination of these two flags across the CLI isn't too confusing/verbose in practice?

**Comment by joelanford** [comment]
@shawn-hurley @hasbro17 What's your opinion on the `--cluster-scoped-operator` flag. IMO, it's somewhat confusing, especially with the addition of `--cluster-scoped-crd`, and it's a bit limiting.

`--cluster-scoped-operator` basically says "set things up to watch all namespaces" and "give the operator permission to read/write CRs and child resource types in all namespaces". When we add support for watching multiple namespaces, how will that impact this aspect of the CLI?

Stepping back, I think what we're actually trying to do is:
1. To steal a term from CSVs, configure which install modes the operator should support (i.e. Own, Single, Multi, All)
2. Configure RBAC to give the operator appropriate permissions, given its install mode(s).
3. Add CRDs with either Cluster or Namespace scope.
4. Configure RBAC to give the operator appropriate permissions, given its owned CRDs.

Right now, I think we're conflating 1,2 with 3,4 because we're stuffing everything into the same roles and role bindings. Does it make more sense to separate these out, such that CRD permissions are managed separately from child resource permissions? And maybe even that each CRD has it's own set of RBAC files tying it to the operator's service account?

On a totally separate subject, we either need to hold off on implementing support for cluster-scoped CRDs for the Helm operator or rethink #1102.

In #1102, we assume that we'll store the release state in a secret in the same namespace as the CR, so there is a built-in assumption that the CRD is namespace-scoped. There's no such thing as a ClusterSecret, so we need to think about where to put release state for cluster-scoped CRDs (or decide not to support cluster-scoped CRDs for helm).

**Comment by hasbro17** [comment]
We've dropped off this issue but we should try to reach a consensus before `v1.0.0`.

Having some time to think about it, just having the two flags `--cluster-scoped-operator` and `--cluster-scoped-crd` as defined above is still an incomplete solution since there are cases where despite the use of both flags users would still need to tweak their RBAC manifests, or the namespaces that they need to watch. 
E.g `--cluster-scoped-operator` but only trying to give permissions for a set of namespaces that the operator needs to watch.

> Stepping back, I think what we're actually trying to do is:
> 1. To steal a term from CSVs, configure which install modes the operator should support (i.e. Own, Single, Multi, All)
> 2. Configure RBAC to give the operator appropriate permissions, given its install mode(s).
> 3. Add CRDs with either Cluster or Namespace scope.
> 4. Configure RBAC to give the operator appropriate permissions, given its owned CRDs.

@joelanford That's pretty much it. However as you pointed out trying to handle 1,2 separately from 3,4 would most likely result in significant changes to the number and layout of our manifests.

Taking a further step back we should consider if we're not overcomplicating the CLI and scaffolding by trying to cover every possible namespace/permission-scope case. And most likely even then have some cases where it doesn't work.
As opposed to covering the common case: single namespace watch with namespace scoped RBAC.

Any other case of multi/all namespaces and namespaced/cluster-scoped CRD operator would just require a few line changes to the default scaffolded manifests:
- CRD manifest: cluster or namespaced
- role.yaml: ClusterRole vs Role
- deployment.yaml: env var `WATCHED_NAMESPACES`

One more reason why I don't think the extra flags would be of much utility is that most users figure out all of these scenarios after the fact when they have scaffolded their first operator project. At which point they have to make these changes manually anyway. 
E.g It's easier for me to change `WATCHED_NAMESPACES` and `role.yaml` then to scaffold a new project with `operator-sdk new --cluster-scoped-operator ...` once I want to switch my operator to a cluster wide mode.

So with that in mind I would actually want to remove even the current flag for `--cluster-scoped` to simplify the CLI and instead document all the changes you can make to run your operator in the different install modes and permission models.

**Comment by joelanford** [comment]
> So with that in mind I would actually want to remove even the current flag for --cluster-scoped to simplify the CLI and instead document all the changes you can make to run your operator in the different install modes and permission models.

I agree. 

The one minor gotcha that I know of is that Helm projects now automatically generate RBAC rules from the chart's default manifest, and we require `--cluster-scoped` if cluster-scoped resources exist. If we eliminate that flag, we'll have to think about how we would want that to work. 

We could keep the `IsClusterScoped` scaffolding option, and start with `IsClusterScoped = false`. And if cluster-scoped resources are detected in the default chart manifest, we could then set `IsClusterScoped = true` and log a message to the user about how/why we're creating a cluster-scoped operator.
