### ISSUE TITLE
How can I use the SDK on Windows, is there some trick?

### ISSUE THREAD

**Issue by robinbraemer** [operator-framework/operator-sdk#982]
I need to make operators with this SDK but, because Windows is currently not supported, is there any way around to use the SDK on a Windows PC? Could I generate the project in a VM with linux or so and import the files back to my Windows to develop on it?

**Comment by joelanford** [comment]
@robinbraemer I believe I've heard of other users successfully using the SDK on Windows, though there may be some unknown pitfalls since we don't test on Windows.

To answer your question, I think you have a couple of options:
1. You can certainly generate the project in a VM with Linux and use an IDE or text editor on Windows to develop. However, without an `operator-sdk` binary, you won't be able to use other parts of the CLI that are pretty useful (e.g. running generators, adding APIs and controllers, and building your operator image).
2. We don't publish a Windows binary, but as far as I know, you should be able to build it from source and run it natively on your Windows machine.

If you're up for trying out the native Windows option, we'd welcome any feedback and new issues you find.

**Comment by robinbraemer** [comment]
> [...]you should be able to build it from source and run it natively on your Windows machine.
I wasn't able to build it from source because of unknown syscalls in the ansible package etc. which are not available on Windows.

Now I have created me a VM with a desktop (VirtualBox) for developing operators.
The issue can be closed, thanks!

**Comment by robinbraemer** [comment]
>
